### ISSUE TITLE
Video's height is slightly rescaled.

### ISSUE THREAD

**Issue by jtran2795** [moonlight-stream/moonlight-chrome#101]
The video displayed from the Gamestream seems to be shrunken vertically leaving a black space at the bottom  of the screen.

This occurs with both 720p and 1080p resolutions on a 1080p display. Unsure about 4k.

**Comment by ShadowBullet** [comment]
I believe that it is because you are playing on a 16:10 aspect ratio screen, Moonlight/NVIDIA Gamestream Protocol only streams at 16:9. This is why you have black bars at the top and bottom. I believe that is what you are referring to, however I could be wrong.

**Comment by jtran2795** [comment]
I'm on a 16:9 display at 1920x1080. I attached an image of what I'm seeing. There is only a black bar on the bottom. The vertical dimension of the stream is shrunken. It's nothing damaging to the playability of games, but the scaling is very noticeable in games using small text as the text becomes slightly distorted.

![display](https://cloud.githubusercontent.com/assets/9217784/18226703/44e838a2-71d5-11e6-8f50-8ddde54411fe.png)

**Comment by ShadowBullet** [comment]
I know that for me, text itself is small (like the desktop on Windows) but that could be because I play on a 720P screen and streaming at 1080P. I will admit it is odd.

**Comment by Ryrin50** [comment]
Same issue here. There's a small black bar at the bottom of the screen as if the video is being rescaled slightly. I have a 16:9 screen. And the black bar is only at the bottom.
