### ISSUE TITLE
Game Posters Are Stretched

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#104]
Just encountered a wired issue, when selecting a host, the game posters are now appearing as though they are stretched. Have restarted, both Chrome and my PC. I also unpaired from the host. Has not happened with this current build until just today which is very odd. I have attached a screenshot of it below. 
![screen shot 2016-09-06 at 11 05 02 am](https://cloud.githubusercontent.com/assets/6118102/18281358/3e70f8c0-7422-11e6-905b-9d47b3043d37.png)
![screen shot 2016-09-06 at 11 08 36 am](https://cloud.githubusercontent.com/assets/6118102/18281378/4a7c6a5a-7422-11e6-9c83-c938594166de.png)

@raidancampbell Any ideas?

**Comment by ShadowBullet** [comment]
@raidancampbell Any possible correlation with any testing you have conducted?

**Comment by raidancampbell** [comment]
No, I've been unable to replicate this issue.  I'll look into it later, as I've been quite swamped lately

**Comment by ShadowBullet** [comment]
@raidancampbell Just compiled a new build with the latest commits from @cgutman and game posters are still stretched.

**Comment by dead** [comment]
Removing [this line](https://github.com/moonlight-stream/moonlight-chrome/blob/master/static/css/style.css#L160) fix this issue

**Comment by ShadowBullet** [comment]
@dead Excellent, I shall wait until @raidancampbell can commit this and then I will compile a new build

**Comment by raidancampbell** [comment]
Thanks for looking into this.  I've been terribly busy with final-semester work starting up, hopefully I'll find time later.
