### ISSUE TITLE
New GFE 

### ISSUE THREAD

**Issue by rampage47** [moonlight-stream/moonlight-chrome#105]
I can connect (use 0.5) to my server, but i dont see video (sound works fine)

**Comment by raidancampbell** [comment]
I just tested and confirmed it as working.  Are your ports forwarded, have you rebooted recently, have you tried reinstalling GFE?

**Comment by rampage47** [comment]
I use moonlight client during 5-6 months on few servers. I have not blocked ports. 
I try to connect to few servers (gtx 950 and gtx 970
1) reboot servers
2) reboot moonlight client
3)  reboot host pc
4) try to change resoluton and bitrate
I have not antivirus on my host pc

Black screen with sounds (keyboard and mouse dont work) Only sound

**Comment by rampage47** [comment]
> uninstall GFE
> reboot
> install GFE
> reboot
> enable GameStream in GFE
> reboot
> pair with moonlight

still doesnt work. (black screen with sound)

**Comment by rampage47** [comment]
Use java vers. 0.6.7 Works fine
Chome version still broken

**Comment by cgutman** [comment]
@rampage47 What OS is your client running on?

**Comment by rampage47** [comment]
i will  test again (some users can connect to my server with chrome version). I will try reinstall chrome and moonlight 0.5

**Comment by rampage47** [comment]
Os linux mint 18
reinstall chrome moonlight 0.5
black screen ( works fine before gfe update)
http://s017.radikal.ru/i444/1609/6f/800ae8bceed7.png

**Comment by cgutman** [comment]
@rampage47 please try going to chrome://flags and enable the "Override software rendering list" option. Restart Chrome and try streaming again.

**Comment by rampage47** [comment]
i have 2 same pc with windows 10. 
pc№1 Install chrome => install chome monlight 0.5 = works fine

pc №2 install chrome => cant install moonlight (webgl supporting)  webgl enable in settings
remove chrome and isnatall moonlight = black screen with sounds
I have promblem with chrome
Sorry guyz. Thx a lot for help. Close this topic
 ps video quality (chome version) much better then in java vers (0.6.7) with same bitrate.
