### ISSUE TITLE
Cant connect to host

### ISSUE THREAD

**Issue by SchoolboyQ33** [moonlight-stream/moonlight-chrome#108]
I cant connect to my host pc. App worked about a month ago but now i cant connect. Ive already port forwarded. People on reddit say that Nvidia stream service has to be running for moonlight to work but it doesnt seem to be running on my pc. If i try to run it manually i get a bunch of missing .dll files. Anyone know whats going on?

**Comment by raidancampbell** [comment]
try reinstalling GFE manually, then turn on GameStream in the settings

**Comment by SchoolboyQ33** [comment]
Already have but still doesnt work.

**Comment by raidancampbell** [comment]
For it to work, I did the following:

 - uninstall GFE
 - reboot
 - install GFE
 - reboot
 - enable GameStream in GFE
 - reboot
 - pair with moonlight

**Comment by SchoolboyQ33** [comment]
Ive gotten my iphone to pair with my host pc but now when i try to pair with my chromebook i keep getting this error "failure reason unknown" and cant fix it.
