### ISSUE TITLE
Black screen after first stream

### ISSUE THREAD

**Issue by aaronson2012** [moonlight-stream/moonlight-chrome#109]
I'm having an issue with the extension on Ubuntu 16.04 LTS x64. When I first run the stream after pairing my computer, it works fine, however, every subsequent stream yields a black screen, but I can hear audio.

Im running the xfce desktop environment if that matters.

If you need any other system info, please let me know. However, I do not have sudo access.

**Comment by rampage47** [comment]
duplicate #105
