### ISSUE TITLE
Starting RTSP handshake failed

### ISSUE THREAD

**Issue by dead** [moonlight-stream/moonlight-chrome#11]
> index.js:106 message received: Starting connection to 192.168.1.223 to play game ID game_id_1
> index.js:106 message received: Starting platform initialization...
> index.js:106 message received: Starting name resolution...
> index.js:106 message received: Starting RTSP handshake...
> index.js:106 message received: Starting RTSP handshakefailed
> index.js:106 message received: Starting connection failed

Any ideia what could be causing this?

**Comment by cgutman** [comment]
Moonlight Chrome needs a special bootstrapping client to connect. I've updated the readme with instructions.

**Comment by dead** [comment]
Thank you :+1:
