### ISSUE TITLE
PIN Window not showing up on host PC

### ISSUE THREAD

**Issue by kingcailan** [moonlight-stream/moonlight-chrome#111]
I'm able to connect, but as of GeForce Experience 3.0, the PIN window no longer shows.

**Comment by darkphoenixfox** [comment]
This is not a moonlight issue but a Geforce Experience/Drivers issue.

If you are suffering from this problem, before you try to pair go to your Nvidia Control Panel (*not* Geforce Experience) and in the top menu enable Desktop > Show notification tray icon.

Make sure that the green Nvidia icon is showing in your system tray.

Then try pairing again.

**Comment by prolitaaron** [comment]
I am seeing this same issue, and have verified the Show Notification Tray Icon is turned on.
