### ISSUE TITLE
Port to Samsung TV's

### ISSUE THREAD

**Issue by dead** [moonlight-stream/moonlight-chrome#112]
When I first meet this project, my main goal was to port it to work with Samsung TV, but unfortunately I don't own a 2015/2016 model.  I'm posting this to see if somebody else has interest in this, I'm currently without time to implement this stuff but I'd be really happy to see it working.

2015 TV's models uses [pepper_37](https://www.samsungdforum.com/pepper_37/cpp/), but it doesn't support the VideoDecoder, so it is not a straightforward port. I found a way to overcome this problem. Using the [MediaPlayer_Samsung](https://www.samsungdforum.com/pepper_37/cpp/classpp_1_1_media_player___samsung.html) with a custom data source ([ESDataSource_Samsung](https://www.samsungdforum.com/pepper_37/cpp/classpp_1_1_e_s_data_source___samsung.html)).

From the ESDataSource_Samsung documentation:
1. Create ESDataSource_Samsung object.

Audio:
2. Add audio stream using AddStream<T> with argument being callback accepting AudioElementryStream_Samsung.
3. Configure audio stream, by setting codec, sampling rate, channels and other necessary information.
4. Call ElementaryStream_Samsung.InitializeDone to confirm the configuration

Video:
5. Add video stream using AddStream<T> with argument being callback accepting VideoElementryStream_Samsung.
6. Configure video stream, by setting codec, frame rate, resolution and other necessary information.
7. Call ElementaryStream_Samsung.InitializeDone to confirm the configuration.

Other stuff:
8. Attach data source to the player by calling MediaPlayer_Samsung.AttachMediaSource.
9. Download and append Elementary Stream audio and video packets by calling ElementaryStream.AppendPacket

The packet must be in the [ESPacket](https://www.samsungdforum.com/pepper_37/c/struct_p_p___e_s_packet.html) structure, I'm not sure if the pts, dts and duration are required, if they are, it can be a problem. But it should be easy to implement this stuff and test it.

2016 TVs models uses [pepper_42](https://www.samsungdforum.com/pepper_42/cpp/) and it support the VideoDecoder api. So the only thing we need to adapt is to the remote control work.

Those TV's supports bluetooth controllers (ds4) and I think they work with the current implementation of moonlight-chrome (using the pepper inputs).

**Comment by Jnacosta** [comment]
Hey would it work on Samsung F8000 series I believe its 2014/15 model?

**Comment by dead** [comment]
No, you need a Tizen OS in TV to get pepper/nacl running :cry: 
You can look [here ](https://www.samsungdforum.com/Tizen/Spec#TVModelLineup)to check what is your TV os.

**Comment by Jnacosta** [comment]
I'm running out of ideas to stream pc games to my Samsung TV (Orsay OS) :(

**Comment by dead** [comment]
Using a raspberry pi is the easier way...

**Comment by cwook** [comment]
I have a Tizen OS TV, but I'm not sure how to start on this port.

**Comment by evilsephiroth** [comment]
Any news on this issue?
