### ISSUE TITLE
Moonlight chrome not installing under OS X

### ISSUE THREAD

**Issue by jaydeelive01** [moonlight-stream/moonlight-chrome#113]
Hi,

I have Chrome installed under OS X. When I try to install Moonlight, I get an error than WebGL is not compatible. I have configured all experimental and WebGL 2.0 options to activated under chrome://flags.

Any ideas ?
Thanks

**Comment by melgu** [comment]
Did you try reinstalling Chrome? I had problems at first, but now it just works.

**Comment by raidancampbell** [comment]
What model is the computer you're installing it on?  It's possible that your computer is too old to properly support the necessary libraries.

**Comment by melgu** [comment]
GeForce Experience is running on a machine with 2 GTX 1080s. Moonlight is running on a 2012 iMac with a GTX 680MX.

I'all try non-4K later. It has worked once for several games (in 4K with 100Mbit), and then it stopped working for some reason. I also get no error message. The Moonlight Streaming window just disappears.

**Comment by raidancampbell** [comment]
Closed due to inactivity
