### ISSUE TITLE
Latency rising sometimes

### ISSUE THREAD

**Issue by Dalizzi** [moonlight-stream/moonlight-chrome#116]
Hello, I've started using this new client and it's multiple times faster than older java based client. However, sometimes there's been some problems with latency in communication between host and client. Sometimes in 1-2min usage, latency goes to 2-3 seconds, sometimes nothing. Can I trace this somehow what is the rootcause for the problem ? Using Macbook(2016), 970gtx and 64bit win10 on server side.
Eventually I have to create anew session to server to get rid of 3sec latency. Then it goes ok for 1-2min. Sometimes this goes without problems for many hours.

**Comment by rampage47** [comment]
i have same problem (with same gtx970). Try to install new drivers

**Comment by Dalizzi** [comment]
Updated driver + gfx experience. Now the effect is significantly unfrequent and is eventually fixed in couple of minutes. There seems to be some kind of lag in video stream and the latency is gone. It feels like input is out of sync and then synchronized when lag is too great.

**Comment by Dalizzi** [comment]
Disabled mouse 'Enhanced pointer precision' on both client and server and the issue was gone.
