### ISSUE TITLE
Chrome apps being deprecated by google

### ISSUE THREAD

**Issue by timde9** [moonlight-stream/moonlight-chrome#117]
Google has announced that it will be removing support for chrome apps http://www.androidpolice.com/2016/08/19/google-phasing-chrome-apps-will-no-longer-work-2018/

is there any plan to work around this or will you just abandon the chrome port?

**Comment by megapro17** [comment]
I want to see better Java app

**Comment by megapro17** [comment]
https://github.com/moonlight-stream/moonlight-chrome/issues/89 duplicate
