### ISSUE TITLE
unable to create opengl context

### ISSUE THREAD

**Issue by rampage47** [moonlight-stream/moonlight-chrome#121]
my system
windows 10
google chrome  53.0.2785.143 m (64-bit)
moonlight chrome v 0.6
1) connect to my server
2) pick game
3) "unable to create opengl context"

**Comment by rampage47** [comment]
chrome://flags/
enable "rendering list"

**Comment by Recee23** [comment]
@rampage47 i am having same problem and i did enable rendering list in chrome://flags/ and it is still doing same unable to create opengl context problem
