### ISSUE TITLE
Add H.265 support

### ISSUE THREAD

**Issue by pecord** [moonlight-stream/moonlight-chrome#123]
I know the android version supports H.265 and its great, wish I could do the same on PC.  I saw there is a way to compile Chromium with H.265 support, curious if it would be possible to implement that.

chromium - win64 w/ h.265
https://github.com/henrypp/chromium/releases

**Comment by cgutman** [comment]
Unfortunately there's no PP_VideoProfile define to specify H.265 video.

https://developer.chrome.com/native-client/pepper_dev/c/group___enums.html#ga4d50d27186f68b2de578e82162206fea
