### ISSUE TITLE
Can't see the cursor

### ISSUE THREAD

**Issue by 8thmouse** [moonlight-stream/moonlight-chrome#124]
Mouse works OK but I just cant see the cursor when I play WOW.
Thanks for this great software ,btw :)

system: macOS 10.12(16A323)
chrome: 53.0.2785.143 (64-bit)
moonlight-chrome: 0.6

**Comment by Astelith** [comment]
Just plug in a mouse in the server and you'll see the cursor on WoW, I had the same problem and this worked for me :)

**Comment by raidancampbell** [comment]
I can confirm the above suggestion was the solution for me when I tried it.
