### ISSUE TITLE
Streaming over the Internet issues.

### ISSUE THREAD

**Issue by Tannerboo** [moonlight-stream/moonlight-chrome#125]
Hello,

Attempting to stream over the internet using Google Chrome Alpha Moonlight extension.

To start off, I have applied the extension and been about to stream the app through my laptop to my desktop while on my local network and the application ran as intended. I am now AFK from the target desktop, and on my laptop and attempting to run the application on a different network and after a period of time it states something along the lines of "Failed pairing to host." from the pairing I created originally on my local network. I have also attempted to add host with the target computers 192 IP address as well as the address given by Whatsmyip.com. None of these address's have brought forth results to allow Moonlight progress forward to show my listing of games.

As far as troubleshooting has gone, I have done many of the suggestions given. On the target computer, I have uninstalled and reinstalled the GeForce Experience, rebooted the target computer, and re-enabled Gamestream. I have also rebooted both this client computer and the target computer to make sure everything is as it should be. I have applied Moonlight to both computers Google Chrome. I have disabled Windows Firewall, AVG firewall, and my routers firewall to insure those weren't hindering the issue. I have inputted port forwarding for TCP: 47984, 47989 and UDP: 47998, 47999, 48000, 48010 as both TCP&UDP. I will state, since someone is bound to ask, I do have certain applications like AVG and Teamviewer(which is what I'm using to remote into my target computer) installed and have been able to work around them on the local network. I have made sure all services seem to be started and running. Currently still troubleshooting so more to come. Thank you for any and all assistance. I appreciate the help!

Update: Attempted to use a site like noip.com and still no luck to getting Moonlight to function properly. Will be attempting some adjustments to Chrome Native Client SDK and the like.

Edit: Moving to moonlight-stream/moonlight-chrome as the PC version is not technically being used in my specific situation.

**Comment by kuzhao** [comment]
@Tannerboo It's a good idea to set up a secured VPN tunnel between your client machine and server's network. I did this and could get on to my gamestream server without a problem.
Thing is, traversal through internet is usually not stable and QoS cannot be guaranteed. I got stuck quite often during tryout and suspect if UDP should be used for RTSP stream here. Do we currently implement UDP for RTSP?
