### ISSUE TITLE
Unable to create OpenGL context

### ISSUE THREAD

**Issue by Laink** [moonlight-stream/moonlight-chrome#126]
I get this error in Moonlight Chrome 0.6 when I try to launch steam or a game on distant computer : "Unable to create OpenGL context"
What can I do to fix it ?

Thanks!

**Comment by Laink** [comment]
Nevermind, Hardware acceleration was disabled in chrome settings.

**Comment by paymok** [comment]
For people who have the program and struggling which option you should enable in chrome.

Override software rendering list 

1. chrome://flags/
2. enable this option 

Override software rendering list Mac, Windows, Linux, Chrome OS, Android
Overrides the built-in software rendering list and enables GPU-acceleration on unsupported system configurations. #ignore-gpu-blacklist
