### ISSUE TITLE
Streaming over 4G very laggy

### ISSUE THREAD

**Issue by Jadinette456** [moonlight-stream/moonlight-chrome#128]
Hi, I don't understand what's happening : I can play all my games remotely over the Internet with the moonlight chrome app but if I use my 4G connection there are frame drops and freezes all the time, even if I stream at 2 Mbps ! (I usually get 70+ Mbps with my 4G). However everything is perfectly fine on a 5 Mbps shitty ADSL connection. So why is streaming stuttering with 4G 70 Mbps connection (30ms ping) and not with ADSL ?

**Comment by raidancampbell** [comment]
Moonlight is more sensitive to latency and jitter.  Wired connections provide much more deterministic throughput than a wireless connection: less packets are lost, making the connection more reliable and less stuttery.
