### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by ihmcjacky** [moonlight-stream/moonlight-chrome#129]
Encountered the following error when initialize the moonlight chrome 0.6.1

> common.js:436 Uncaught TypeError: Cannot read property 'split' of undefined

And I am unable to add the host after that (not sure whether this is related to the above error)

System
Ubuntu 14.04 64 bit
Chrome  52.0.2743.116 (64-bit)

**Comment by zenzizenzicube** [comment]
I am getting this on Debian Stretch and Chrome 53.0.2785.143

**Comment by DaStivi** [comment]
i'm on a qnap (hybridstation with chrome on HDMI output), i couldn't load the extension within chrome... i had to manually extract and load via the developer tools the extension... but it i got the same error about common.js ...   

maybe something with chrome on Linux distributions?
