### ISSUE TITLE
Imput lag on 5K screen (iMac Retina)

### ISSUE THREAD

**Issue by Astelith** [moonlight-stream/moonlight-chrome#130]
Hi All, 

If I'm using Moonlight windowed in an area of approx. 4K I have a great experience on my iMac retina, 0 input lag, like in local, but once i step out the 4K resolution, or when I go fullscreen, I have a terrible input lag and it became unusable.

Any thought ?

**Comment by Unitixcat** [comment]
stop it with the tread i got 175 emails just from two days and i cant get any other emails

**Comment by Jorys-Paulin** [comment]
@Unitixcat Sorry for that, we didn't know the not would send emails each time. Trust me, it was anoying for us too.
