### ISSUE TITLE
Failed to connect. are you sure the host is on?

### ISSUE THREAD

**Issue by Xnome** [moonlight-stream/moonlight-chrome#131]
So, i am at a loss here. i use the android version without any hiccups, thought would try this out as well, to play it on my chromebook.

When i click on add host. i am confused as to what to exactly type. i tried my Router Ip address. tried the Host name it shows on my android, tried the current IP address as well. none of them works. can anybody tell me how exactly to pair? am i doing something wrong?

**Comment by cgutman** [comment]
You should type the IP address of your PC running GeForce Experience

**Comment by binniebin** [comment]
I have same problem, chrome extension doesnt work with this ip adress, older java version show same ip and auto-detection work great
