### ISSUE TITLE
constant loading in version 0.6.1

### ISSUE THREAD

**Issue by giliammc** [moonlight-stream/moonlight-chrome#133]
when I install anything newer than 0.5.0 it never stops loading

**Comment by cgutman** [comment]
What version of Chrome/Chromium are you running and what OS are you using?

**Comment by giliammc** [comment]
i am running chrome os on a chromebook

**Comment by raidancampbell** [comment]
Have you tried uninstalling and reinstalling moonlight?  This will unpair you from any paired servers.

**Comment by giliammc** [comment]
yes multiple times

**Comment by HarryLovesCode** [comment]
Same issue. Stuck on the "Loading Moonlight Plugin" screen on recent versions. Tried everything from Chrome release channel, beta, to Canary builds. Same result.

**Comment by giliammc** [comment]
are you running it on a Chromebook?

**Comment by HarryLovesCode** [comment]
@giliammc No, I'm running

- MacOS Sierra 10.12.1 (16B2657)
- Google Chrome 54.0.2840.87 (64-bit) (Release branch)

**Comment by HarryLovesCode** [comment]
Update: Oddly enough this only happens at Uni. The only thing I can think of is blocked ports it might get stuck checking for?

**Comment by jimb0616** [comment]
I had a similar issue and for some odd reason, I reinstalled Java on both client and server and it worked fine.
