### ISSUE TITLE
Starting RTSP handshake...

### ISSUE THREAD

**Issue by melgu** [moonlight-stream/moonlight-chrome#134]
Pairing works.

Whenever I start any game, the game opens on the host and Moonlight says "Starting RTSP handshake...". After a couple of seconds, Moonlight goes back to the game selection without any message.

I tried the Java version. It works, but doesn't go fullscreen (4K).

**Comment by chrmica** [comment]
Having same issues worked once only, now cannot connect anymore and no error messages to help diagnose

**Comment by raidancampbell** [comment]
Does moonlight-chrome stream at non-4K resolutions?

**Comment by melgu** [comment]
GeForce Experience is running on a machine with 2 GTX 1080s. Moonlight is running on a 2012 iMac with a GTX 680MX.

I'all try non-4K later. It has worked once for several games (in 4K with 100Mbit), and then it stopped working for some reason. I also get no error message. The Moonlight Streaming window just disappears.

**Comment by ragnarok762** [comment]
I am having this same issue. 1080p 60 fps works fine, but 4k goes straight back to the desktop. When trying on my android device I get the error RTSP Handshake Failed: 403 

On most current GFE and a GTX 1070 and the moonlight pc is on the same version but with a GTX 1050 ti

**Comment by ragnarok762** [comment]
One of the developers were able to resolve my issue. Make sure that "Allow experimental Features" is checked in GFE settings. That resolved it for me.
