### ISSUE TITLE
Failed to connect! Are you sure host is on?

### ISSUE THREAD

**Issue by nex77qoz** [moonlight-stream/moonlight-chrome#135]
Java version of moonlight works jsut fine, but we can't connect via Chrome version. Our chrome, windows, GFE and moonlight versions are identical.
Windows 10
Chrome 54.0.2840.71
GFE 3.1.0.52
Moonlight 0.6.1

**Comment by pigeon-man** [comment]
Need help with this issue too. I tried the Java version and it doesn't work either, it doesn't even see the host PC. I can ping and RDP to the host PC. How do I know if gamestream is active within GFE? I have:

Windows 10 on both machines on a LAN
GTX 960 in the host PC
Chrome v. 55.0.2883.75 
GFE v. 3.1.2.31 w/ latest drivers
Moonlight v. 0.6.1
