### ISSUE TITLE
Falling back to CPU acceleration in Chrome on Linux

### ISSUE THREAD

**Issue by duneheishman** [moonlight-stream/moonlight-chrome#137]
Hardware video decoding is not working for me in Chrome on Arch.

I've enabled the #ignore-gpu-blacklist flag, and chrome://gpu is [now showing](https://i.imgur.com/zjM5bUM.png) that video decoding is hardware accelerated, but when starting a streaming session I still receive the message that hardware decoding is unavailable. Enabling #enable-gpu-rasterization did not make a difference.

Could this be an issue with Moonlight or my system? Thanks :)

**Comment by fnorbenden** [comment]
I am having the same problem. Everything was working fine on the previous version of moonlight and previous version of GFE. GFE update required update to 0.6.1, and now hardware acceleration is "unavailable." Updated to latest chrome-stable (55.0.2883.75) does nothing. Similar settings to the OP but with the addition of #enable-zero-copy. Nothing on the latest chrome-unstable either (56.0.2924.18).

Moonlight console output:
http://pastebin.com/8ji60Sbn

My guess is something going wrong at line 614. Not very familiar with the project so I'm not much help, sorry.

**Comment by MrBeatReed** [comment]
Same here!

**Comment by iilichf0** [comment]
and here... lets see if somebody can tweak it

**Comment by fnorbenden** [comment]
I took another look at the issue; at first I thought HW acceleration was being disabled because the NaCl API couldn't connect to the webserver created by GFE. I whitelisted the hostname for GFE's server and it still didn't work, however.

It seems pretty clear that the issue is the "profile" being used, which to the best of my understanding is chrome-speak for codec. Why this is now an issue when before, with the same gpu and chrome, it wasn't, I have no idea. But at least I've narrowed down the problem.

Would appreciate some insight from one of the devs. My gpu is a gtx 460.

**Comment by roobre** [comment]
I'm having the same problem too. I attach the outputs of `vainfo` and `vdpauinfo`.

Also I have Intel Corporation HD Graphics 520, with `xf86-video-intel 1:2.99.917+747+g028c946d-1`, kernel `4.8.13-1-ARCH`.

[vdpauinfo.txt](https://github.com/moonlight-stream/moonlight-chrome/files/733621/vdpauinfo.txt)
[vainfo.txt](https://github.com/moonlight-stream/moonlight-chrome/files/733620/vainfo.txt)

**Comment by DocMAX** [comment]
any updates?

**Comment by cgutman** [comment]
I think this particular issue is due to Chrome not accelerating H.264 decoding on Linux (other than ChromeOS). AFAIK, there are some distros that carry out-of-tree patches against Chromium to enable this functionality.

https://bugs.chromium.org/p/chromium/issues/detail?id=463440

**Comment by DocMAX** [comment]
never mind, switched to moonlight-embedded. working perfectly with va-api.

**Comment by Zemnexx** [comment]
So this leaves Linux users out of luck, unless you are using moonlight-embedded which requires an arm device from what I see. Linux users can only enable NaCl in Chrome, not Chromium, and the only way to have hardware accelerated h.264 is using a build of Chromium, which you cannot enable NaCl on to be able to click Add Host or see the host machine at all.

**Comment by ted23p** [comment]
I have hardware acceleration working in Moonlight Stream on ArchLinux. If you take the time to build chromium-dev from AUR, you can get NaCl support.

I'll list some of the config issues that came up for those interested in trying. The chromium-dev pulls in a dependency that requires a gpg key from debian to be imported - See AUR comments of the ncurses5-compat-libs package. You need to enable 3 flags in chromium for  hardware acceleration and specify the libva driver by environment variable - See the Arch Wiki. The bottom of the chrome://gpu page should show h264 profile info. If you still fallback to CPU, you should see errors at the bottom of that page appear.
