### ISSUE TITLE
Stuck on 'Loading Moonlight plugin...'

### ISSUE THREAD

**Issue by acernine** [moonlight-stream/moonlight-chrome#138]
I've downloaded moonlight-chrome.crx (v0.6.1) from [this page](https://github.com/moonlight-stream/moonlight-chrome/releases) to my laptop (Windows 10), installed the extension to chrome as instructed, but when I run the application it goes straight to the "Loading Moonlight plugin" screen and stays there (30 minutes have passed so far!).

I have GeForce Experience 3.0.7.34 open and running on the host machine (which is running a GTX1060), with gamestream enabled. Is it just that my laptop is incredibly slow, or have I done something wrong?

EDIT: I see #133 has a very similar issue; I have reinstalled multiple times and no fix!

**Comment by kykylkan** [comment]
Hello. I have this problom too at the PC in office(Win7 x64/latest Google Chrome)? but at home good works!

**Comment by lewisohn** [comment]
I'm having the same problem. Chrome OS 56.0.2924.28 beta (64-bit) on a Toshiba Chromebook 2. Stuck on "Loading Moonlight plugin..." with v0.6.2.

v0.6.1 worked and connected to my main PC but didn't display video, presumably due to GeForce Experience 3.2. I'm going to try rolling back to 3.1.

**Comment by roemhildtg** [comment]
I'm having the problem on Ubuntu 16.10 x64 with Chrome  56.0.2924.87 (64-bit). After launching the moonlight chrome app, it is stuck "Loading Moonlight Plugin". 

Using Moonlight 0.6.3.

**Comment by hansIanda** [comment]
Yeah. Uh. We need someone to address this. Common problem with this release. Did no one seriously respond yet lol?

**Comment by hansIanda** [comment]
Initially i added the unpacked version as a chrome extension. This gave me the above problem/result. After adding the CRX extension directly to chrome, it spent maybe 30 seconds at that screen and it worked. Someone with this same issue please try this to confirm.

**Comment by Jorys-Paulin** [comment]
Hey everyone, I had the same problem : I fixed it by building first, as described in the README.md

**Comment by roemhildtg** [comment]
This issue actually resolved itself after a little while. I didn't change anything.

**Comment by mzernetsch** [comment]
Had the same problem. Resolved it by manually enabling "Native Client" setting in Chrome (chrome://flags/#enable-nacl).

**Comment by phoenix3dfx225** [comment]
@mzernetsch solution worked for me!
