### ISSUE TITLE
Gamestream (Chrome) works perfectly on the same network, but never makes the RTSP handshake on different networks.

### ISSUE THREAD

**Issue by Opirr** [moonlight-stream/moonlight-chrome#140]
Exactly what's in the title. I'll run Chrome on my macbook pro 2011. It runs perfectly when I'm in my home but when I went to a friend's apartment, the handshake would fail every time. I would connect and see all my games/apps, and I can even close them out due to RTSP failure- but I can't ever actually jump into a game to play.

Am I using this incorrectly?

Sierra OS, GeForce Experience, and Moonlight are all on the latest version.

**Comment by raidancampbell** [comment]
Have you properly followed [the wiki's instructions on streaming over the internet?](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet)

**Comment by Opirr** [comment]
Yes, I have- the issue has been resolved (seems it didn't save that I had a static IP configured.

Griffith M. Davis, M.S. Medical Science
University of North Texas - Cardiovascular Toxicology
Department of Biological Sciences
Doctoral Candidate


On Nov 10, 2016, at 12:10 PM, R. Aidan Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you properly followed the wiki's instructions on streaming over the internet?<https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet>

-
