### ISSUE TITLE
Streaming not woking on Chrome app, but works on Android phone 

### ISSUE THREAD

**Issue by ronlaniado** [moonlight-stream/moonlight-chrome#142]
I keep getting an empty list when connecting to my PC on the Chrome app, but on my Android phone, all my games are shown, and streaming is flawless. Any clues?

 I've reinstalled GFE once, drivers are fully updated, reinstalled Moonlight to its most recent release, any clues?

**Comment by ianperez** [comment]
I am seeing the same issue.  My best guess is that one of the latest GFE updates broke it.

**Comment by ianperez** [comment]
I just noticed that this is resolved in the latest release (v0.6.1).  Did you make sure to uninstall the previous version before installing the new update?

**Comment by fletom** [comment]
I had this issue too when I first installed it today, and uninstalling Moonlight and reinstalling worked for me. Apps just started showing up.
