### ISSUE TITLE
Unable to get constant 60 FPS

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#145]
As it says, I am unable to get 60 fps. I get very sporadic increases and decreases hovering from around 40-55 all on a wired ethernet network. Any ideas? @raidancampbell

**Comment by jimb0616** [comment]
What type of GPU do you have on the server?  

It has to be good enough to transcode your gameplay on-the-fly while running the game locally. 

When you play  locally on that computer the GPU only uses resources to run the game. When you're streaming it, the GPU has to use some of its resources to transcode and stream at the same time. 

Also, make sure both the server and client have the latest versions of Chrome. And just for the heck of it make sure you have the latest version of Java.

**Comment by ShadowBullet** [comment]
Closing, I found that forcing it to use the GPU for rendering yielded much better performance (not perfect, still drops a bit, probably packet loss) and also mouse lag is much less. I thought it would default to the GPU but now it is because I am forcing it.
