### ISSUE TITLE
UWHD support?

### ISSUE THREAD

**Issue by TheExplorographer** [moonlight-stream/moonlight-chrome#146]
Any chance we can get UWHD resolution support?  2560x1080 and 3440x1440?  That will be killer!

**Comment by evildog1** [comment]
GameStream only support 720p 1080p and 4k resolution i guess

**Comment by TheExplorographer** [comment]
Nah, It's supports UWHD, I stream it all the time to twitch and YouTube.  Resolution is card/monitor dependent.
