### ISSUE TITLE
Cannot see mouse cursor while streaming

### ISSUE THREAD

**Issue by bunchjesse** [moonlight-stream/moonlight-chrome#148]
Streaming Windows 10 to macOS Sierra
Chrome 54
Latest GEForce drivers

What do you need to debug?

**Comment by jimb0616** [comment]
Do you have a mouse plugged into the host?

**Comment by bunchjesse** [comment]
Yes and the mouse works correctly.

**Comment by my1es** [comment]
GeForce Expirience 3.2.0.96, MoonLight 0.6.2, Windows 10 x64 - Cannot see mouse cursor ;(
