### ISSUE TITLE
Cannot launch game more than once without a reboot

### ISSUE THREAD

**Issue by bunchjesse** [moonlight-stream/moonlight-chrome#149]
Streaming Windows 10 to macOS Sierra
Chrome 54
Latest GEForce drivers

1. Launch a game (in this case ARK: Survival Evolved)
2. Quit the game with the GFE key chord (on Mac, CTRL+OPT+Q)
3. Click "Quit Current Game"
4. Launch the game again

The handshake fails and I"m returned back to the game chooser OR I hang on a black screen. The only thing that seems to fix this is rebooting the Windows machine.

What else do you need to debug?

**Comment by jimb0616** [comment]
When you close the stream be sure to click quit within the moonlight window. This works for me.

**Comment by bunchjesse** [comment]
@jimb0616 I updated my issue. I forgot to mention that I was already doing that.
