### ISSUE TITLE
"ADD HOST" button does nothing

### ISSUE THREAD

**Issue by t184256** [moonlight-stream/moonlight-chrome#150]
"ADD HOST" button does nothing except for showing the ripple animation.
I don't know how to debug it further.

Moonlight Chrome v0.6.1
Chromium Version 53.0.2785.143 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

**Comment by t184256** [comment]
It works in Chrome 55. Wuth Chromium it seems to entirely skip NaCl initialization. Please fix that.

**Comment by dmnc-net** [comment]
Yes, it is caused by missing NaCl. I suggest to include NaCl detection and display user warning.
