### ISSUE TITLE
Black Screen on Application Launch

### ISSUE THREAD

**Issue by Bokagha** [moonlight-stream/moonlight-chrome#152]
When I go to launch a game or Steam via Moonlight I get connected to my PC and can hear sound, but the screen is black and controls don't work.

Here is my setup:

Host PC
- Windows 10
- GeForce Experience version 3.2.0.96 with drive version 376.19

Client PC
- macOS 10.12.1
- Using Google chrome version of the app (0.6.1)

I have tried several troubleshooting steps such as:
- uninstalling/reinstalling GFE
- uninstalling/reinstalling Google Chrome and Moonlight
- chrome://flags and enabled the "Override software rendering list" option

Everything was working fine last night. This morning with the new GFE update is when the issue started occurring.

**Comment by jimb0616** [comment]
Same here

**Comment by cgutman** [comment]
I think they've changed the size of the video packet header again. I'll take a look later today.

**Comment by cgutman** [comment]
I've released Moonlight Chrome v0.6.2 which includes a fix for this
