### ISSUE TITLE
Controllers not mapped properly?

### ISSUE THREAD

**Issue by Gershy13** [moonlight-stream/moonlight-chrome#153]
Im having trouble getting rocket league to stream from my rig to my htpc.
I have 2 official ps4 controllers, 1 official ps3 controller, and 2 fake ps3 controllers (giotek vx-2 and another wireless controller)
I want to get atleast 3 controllers working (KB+M would have to work too), but 4 would be nice. 
Anyone know how i would get them working?

Gaming Rig:
4670k @3.8ghz
750 ti
8gb ram

HTPC:
Pentium e5800 dual core 3.2ghz
gt 610
4gb ram

**Comment by Gershy13** [comment]
bump

**Comment by towfiqi** [comment]
My xbox 360 controller is not mapped correctly. How do map the controller input?
