### ISSUE TITLE
Performance issues on Intel NUC

### ISSUE THREAD

**Issue by mandrichenko** [moonlight-stream/moonlight-chrome#154]
Is there another way to raise the performance of the streaming? Primarily video decoding settings. 
I saw that PPAPI can provide H264 High and Base profiles with/without HW decoding.
Understand that it depends on hardware performance, but I think my client machine (Intel NUC) is not so outdated:
Celeron N2820
HD Graphics
DDR3 4GB

I try to use 1080p 60fps with 20m bitstream, but I experience significant latency. My optimal performance settings for Moonlight is 720p 60fps 10m.

Steam In-Home streaming works good on this hardware on 1080p settings, using "better quality" option and hardware decoding.

**Comment by mandrichenko** [comment]
I really like moonlight. It provides more better image quality and controller support than Steam streaming. From now it's my favorite game streaming app on MacBook.

**Comment by adriancuzman** [comment]
I have this issue too on J1900, 1080/720 works at 30fps, but lags a lot 60fps, network is gigabit wired. CPU is ~50% on 30fps, ~70-80% on 60fps. Any ideas on what could be wrong? Also tested with my laptop and 60fps works perfectly even on wifi, so the issue is with J1900...
