### ISSUE TITLE
Black screen issue, Chrome Only

### ISSUE THREAD

**Issue by TheNferno** [moonlight-stream/moonlight-chrome#157]
When using the chrome client, I successfully connect to the host PC but when the stream starts, I get a black screen but I do have audio  from the host. No mouse input is registered by the widow. I am able to stream perfectly to my phone but not to the PC. It was working fine with V 0.6.1, and pre 12/15 update of GFE. Is it an issue with the 0.6.2 update? Because it seems that people were having this issue with previous version of the client.

**Comment by jimb0616** [comment]
Dumb question, did you update to the latest Moonlight-Chrome plugin released recently?

**Comment by TheNferno** [comment]
I am using version 0.6.2. Sorry for the lack of clarity in the OP. I had no issues with it in 0.6.1, but after the update to 6.2 and nvidia update to 376.33, it has stopped working

**Comment by TheNferno** [comment]
Somehow it got fixed, I have no idea what it was, but I just tried it today and it worked.
