### ISSUE TITLE
Multiple clients ?

### ISSUE THREAD

**Issue by Perdouille** [moonlight-stream/moonlight-chrome#159]
Hello !

I wondered if it was possible to use Moonlight to stream to 3 other players. For exemple, my PC is the server, and 2 friends connect to it with Moonlight and play with their controllers

We tried, but every time someone connect it kicks the other one :/

Any idea ? 

Thanks !

**Comment by cgutman** [comment]
GameStream doesn't support this. It's theoretically possible with some special software on the PC but so far nobody has written it.
