### ISSUE TITLE
Black Screen is killing me

### ISSUE THREAD

**Issue by fboulegue** [moonlight-stream/moonlight-chrome#160]
Here is my setup:
Win7
Nvidia gtx 750 ti
Nvidia Driver 376.19
GFE V. 3.2.0.96

Problem:

Every time I start the stream I hear sound (steam) but can't see any picture it is simply black.
Did try in 720p 30fps /60fps same for 1080p all same result.
Anyone a idea what could be wrong?

**Comment by cgutman** [comment]
Did you update to the Moonlight Chrome v0.6.2?

**Comment by fboulegue** [comment]
@cgutman doh -.- no I did not checking thanks a lot

**Comment by fboulegue** [comment]
solved
