### ISSUE TITLE
Black Screen with sound

### ISSUE THREAD

**Issue by blackecos** [moonlight-stream/moonlight-chrome#161]
Hi Moonlight Team,

yesterday I got an update for geforce experience. (3.2.0.96)
After that my friend can connect to me but she have black screen with sound from my game.

I reinstall geforce experience + she install the newest moonlight version. But it doesn't help. (She use chrome plugin)

With an older version of geforce experience all works perfect.

Is there any solution for this?

Greetings and merry christmas

**Comment by cgutman** [comment]
Please definitely make sure she's running Moonlight Chrome v0.6.2. Uninstall Moonlight and reinstall fresh just to make sure. If that doesn't work, try the Moonlight Java client - https://github.com/moonlight-stream/moonlight-pc/releases/tag/v0.6.7-r1

The most current Moonlight PC version won't work but the version I linked above will.

**Comment by xiaodoudou** [comment]
Hi,

I have the same issue on my side.
The Java client run just fine but chrome side is black.

I have test with the version 0.6.3 and still same issue.

Cheers
