### ISSUE TITLE
Remote 'Local co-op' gamepad on client and host

### ISSUE THREAD

**Issue by StratusHunter** [moonlight-stream/moonlight-chrome#163]
Sorry if this has already been asked but just wanted to check.

I have a host streaming successfully to a remote computer using the chrome app. We were hoping to play local co op. Me with either a Steam/Xbone/PS4 controller connected to the host and then the client with a PS4 controller using DS4Windows.

We currently are using mstsc.exe to stream everything but we were finding the client controller never worked (but the kb/m worked fine), is this remedied by loading a specific game rather than mstsc? Then from what I can find you can only ever get co op working at either the host or client side but not both? Is that correct? I'm guessing so due to the dll renaming trick?

Thanks for the great software and any help you can give me :)

**Comment by evildog1** [comment]
It is not possible on GameStream. Maybe Nvidia should add the feature on GameStream then Moonlight dev can add support.

**Comment by StratusHunter** [comment]
Thanks for the clarification :) we just got around it using controller on one side and just kb/m on the other. Hopefully NVIDIA will add it soon!
