### ISSUE TITLE
Mouse sampling too coarse when streaming 1080p to 1440p client

### ISSUE THREAD

**Issue by asmundg** [moonlight-stream/moonlight-chrome#166]
When streaming at 1920x1080 to a client with 2560x1440 resolution, I have to move the mouse a good distance before the movement registers in the streamed program. At that point, the cursor jumps several pixels.

This effect disappears when I change the receiving desktop resolution to 1920x1080.

**Comment by slyh** [comment]
I have a similar problem. When I'm using 1440p monitor with 125%/150%/175% DPI setting, the cursor doesn't move when I'm moving my mouse slowly. The problem disappeared as the DPI scaling are set to 100% or 200%.

I'm running Moonlight 0.6.1 with Chrome 55.0.2883.87 m (64-bit) on Windows 10 1607.

**Comment by asmundg** [comment]
Right, it does indeed work correctly at 100% scaling. 0.6.2 with chrome 55.0.2883.87, btw.

Your description is also more precise. There is a dead zone within which slow mouse movements do not register.
