### ISSUE TITLE
Keyboard and mouse not worked for fallout 4

### ISSUE THREAD

**Issue by VladimirButorin** [moonlight-stream/moonlight-chrome#167]
No input for fallout 4. As soon as the game started is is not possible to control the game from keyboard and no more mouse pointer on the screen (on the host the same issue). 

Seems the same problem as described here:
https://github.com/moonlight-stream/moonlight-android/issues/140

**Comment by Sawyer007** [comment]
turn controller off in the settings before starting the stream and they should work.

**Comment by VladimirButorin** [comment]
sorry, but there is no controller options in chrome version..

**Comment by Sawyer007** [comment]
in the game

**Comment by VladimirButorin** [comment]
Hi Sawyer007,

modifying  %userprofile%\Documents\my games\Fallout4\Fallout4Prefs.ini by setting bGamepadEnable=0 and also setting the file to Read Only solves this problem.

Thank you for help,
Vladimir
