### ISSUE TITLE
Cannot Run Moon Light on Chrome

### ISSUE THREAD

**Issue by Fenrir426** [moonlight-stream/moonlight-chrome#168]
Tried the newest version of Moonlight.  Chrome will not run Extension unless it's from their store.  Can it be uploaded to the store?

**Comment by xchannels** [comment]
Drasg and drop the download file on extension page. that worked for me

**Comment by Fenrir426** [comment]
Did that it comes up on the Extension screen but wouldn't allow me to enable it.  Says for my own protection they wouldn't enable it.  However, on the older versions, it was enabled but it would allow me to connect to my PC keeps saying it's unavailable and asks if I am sure it's on.  Which I know it's on due to Team Viewer.  That is why for the newest version I am asking if it can be uploaded to the Google Extension store.

**Comment by raidancampbell** [comment]
What OS are you using?  What version number and channel (stable/beta/canary) of Chrome are you on?

**Comment by yoongjun** [comment]
i'm also experiencing similar issues when i drag and drop the file into the extension page, it says that WEBGL is not supported.

**Comment by evildog1** [comment]
Latest version of Moonlight works fine on 55.0.2883.87 m (64-bit). It must be your problem
Try reset Chrome and reinstall to see if it solves the problem :)

**Comment by Fenrir426** [comment]
@raidancampbell This is the Chrome browser I have: Version 55.0.2883.87 m (64-bit) as for the channel I have no idea.  From the information I can put together it's the Stable channel.

@evildog1 So you're saying that Team Viewer might be messing with the Moonlight extension on Chrome?

**Comment by evildog1** [comment]
Yes it can, and it is also messing with GameStream in Geforce Experience.
I had Splashtop 2 before and i always got connection terminated when trying to connect to my PC. I uninstalled it and it solved the problem

Google Remote Desktop and Steam In-home streaming does not mess with Moonlight or GameStream. I  100% tested it

**Comment by Fenrir426** [comment]
@evildog1 So should I just unload the Team Viewer from the Google Chrome or completely from my computer and Google Chrome?

**Comment by evildog1** [comment]
You can try to disable it.

**Comment by Fenrir426** [comment]
I disabled it on Chrome and actually uninstalled it.  Tried the previous version of Moonlight and still, won't take the same message.  Tried moonlight again on my cell and iPad connects just fine.

**Comment by evildog1** [comment]
Uninstall and install Chrome. If your data are still there. Reset chrome, open your name next to minimize button -> Manage peoples and remove all profiles. This will delete your bookmarks and everything.
If you don't like resetting, use Chrome Portable version which allow you to use multiple Chrome you want to. I always use Portable version for Moonlight and other things on main Chrome to prevent issues

If still not working, reset all network settings on PC settings. If you are using Win7, use cmd to reset network. And disable the firewall. Google it :)

**Comment by Fenrir426** [comment]
I just noticed something while I was fiddling with it on my lunch break.  I have Moonlight working on both my cell and iPad and they work just fine with the connection.  However, I did disconnect my Moonlight on my cell and tried to re-establish the connection on my cell.  Just for s&*^s and giggles.  I couldn't re-establish the connection.  My only logical conclusion is that it's something to do with the internet at my workplace.  Since it's more secure it might not be letting the information through to do the initial connection.  Thoughts?

Can't fiddle with Chrome like that IT at my job has it locked up so that any uninstall of a program and installation/update of a program needs a password.  I am surprised I can even get this far using Google Chrome Extention to be honest.

**Comment by evildog1** [comment]
Ok that's the problem then. There is nothing much we can do if the computer at your job is restricted

**Comment by Fenrir426** [comment]
Ok, I found the solution or at least my coworker did.  Apparently, the IP Adress I used was that of my local IP Address.  I had to use a different IP Adress to get the application to work.  It is now working.  Sorry for the bother everyone.
@evildog1 @xchannels
