### ISSUE TITLE
Older Moonlight Extensions

### ISSUE THREAD

**Issue by Fenrir426** [moonlight-stream/moonlight-chrome#169]
Installed older versions of Moonlight extensions for Chrome.  Works up till the point of connecting.  Put in my IP Address comes back saying that are you sure that user is on.  Checked Team Viewer Application my comp is on.  Any suggestions.

**Comment by raidancampbell** [comment]
Older versions of the code will work properly with current GFE versions: this is the purpose of the updates.  An up-to-date GFE requires an up-to-date version of moonlight
