### ISSUE TITLE
Moonlight stream freezes with audio and sometimes controls active.

### ISSUE THREAD

**Issue by The-Song** [moonlight-stream/moonlight-chrome#170]
My friends and I have tried the newest Chrome plugin, some older chrome plugins, The newest PC version, version 0.6.7, as well as both the new GeForce Experience and Experience version 2.11.4.0

So far no matter the combination, my friend can pair, launch the game, then after just a few seconds his image freezes, but he can still hear what's going on. A few of the times, he could still input controls, but for the most part he had nothing but audio.

Not only is my computer (I'm the host) set as DMZ when we are doing this (all ports open), we also use a VLAN to alleviate the need for us to open ports in the first place.

I have no idea what is preventing us from a proper stream. I am fully able to stream to my own devices locally (my phone), which is essentially what VLAN is supposed to make streaming to him function as.

If it makes any difference we have been trying to launch the game Enter the Gungeon and Steam Big Picture Mode. Same problem either way.

**Comment by yoongjun** [comment]
Yes, I'm having similar issues where there screen freezes but everything else is working fine (audio/controls).

**Comment by evildog1** [comment]
You might read the troubleshooting
https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

**Comment by The-Song** [comment]
"You might read the troubleshooting
https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting"

That would be the first thing I did. Didn't help.

**Comment by The-Song** [comment]
bump.

**Comment by GreySer** [comment]
Me too that problem on chrome plugin!

**Comment by HorikawaOtane** [comment]
Yup same problem here!

**Comment by KammererTob** [comment]
Same problem here. 
Not enough testing done, but it seems to be related to maximizing windows or fullscreen. If we play in a small Window it seems to be working (as i said not tested enough to be 100% positive about that)
