### ISSUE TITLE
Audio from host with non-native steam games - not from client

### ISSUE THREAD

**Issue by bloodyvikings** [moonlight-stream/moonlight-chrome#171]
Hello,

I have the latest version of GeForce Experience, and when I run games that are not native to Steam the audio funnels out of my computer speakers instead of the client machine (a tv connected through HDMI to a Raspberry Pi). I just recently reinstalled the OS both on the Pi and the pc and it used to work perfectly fine before. Last time I ran Moonlight I had another GPU and my monitors were connected via DVI-D, but now I have them on HDMI. Could that be the problem? I've reinstalled the drivers and GeForce Experience. I've even tried with an older version but that changed nothing. I'm almost pulling my hair of right now out of frustration :-P Any ideas of where to start? 

By the way, if I alt+tab out of the stream and open playback devices on the host machine, the TV output that used to be there before I reinstalled the software isn't there anymore. Though, the audio works fine as long as the game is native to Steam.

Thanks in advance!

**Comment by raidancampbell** [comment]
Have you tried various output options in the audio settings of the server?  DVI-D can't carry audio, but HDMI can: it's possible that your computer is directly routing audio to the monitor.  Off the top of my head, I _think_ there's a GeForce device that you can route your audio to.

**Comment by bloodyvikings** [comment]
> Off the top of my head, I think there's a GeForce device that you can route your audio to.
Yeah, I remember there being a device that I could set as default but it's no longer there. I could always dig up my old monitors from the basement and plug them in again just to see what happens, but no matter what I want to keep it like I have it now. Hmm, there gotta be something I'm missing here :-/ Any other ideas or tips?

**Comment by bloodyvikings** [comment]
Oops, I just noticed I posted this in the wrong forum :-p My bad! Just close this one and I'll re-post it in the right section instead.
