### ISSUE TITLE
Swapping Controllers for Players 1 and 2

### ISSUE THREAD

**Issue by ShadowCX** [moonlight-stream/moonlight-chrome#175]
Hi,
is there any way to have the host's gamepad be registered as Player 2 and the guest's gamepad as Player 1? There actually do exist (sloppily programmed) games that don't let you assign controllers apprently, so that is an issue on rare occasions. I've already tried everything that came to mind, but to no avail..

**Comment by aznet218** [comment]
I second this, could not manage to get two controllers to work since, being the guest, when i join host, my controller override his on LAN matchmaking on the game Hive Jump.
