### ISSUE TITLE
How to stream in 1440p ?

### ISSUE THREAD

**Issue by wichtounet** [moonlight-stream/moonlight-chrome#176]
Hi, 

I'm trying to remotely play from one computer to another. Both of the these computers have 1400p resolutions. If I use 1080p streaminng the quality is really bad. 

Is there anyway to use the host resolution for streaming ? 

Thanks

**Comment by a2407** [comment]
Hi Moonlight-stream team,

Please include the 1440p streaming for moonlight chrome, as it would be great for users with 1440p displays.

Thanks,

**Comment by simongui** [comment]
I would like this resolution added: `3840 x 1600`.

**Comment by a2407** [comment]
Hi Simongui,

Can you please let me know the process of changing the resolution.

Thanks,

**Comment by simongui** [comment]
I think allowing us to add resolutions would be a better feature to satisfy people?
