### ISSUE TITLE
Gfe Update | We need Moonlight 0.6.3

### ISSUE THREAD

**Issue by rampage47** [moonlight-stream/moonlight-chrome#179]
Hi. After gfe update (today) we cant use current version of moonlight (0.6.2)

**Comment by ShadowBullet** [comment]
Same issue here as well

**Comment by ShadowBullet** [comment]
@raidancampbell @cgutman

**Comment by coreydwillis** [comment]
The issue was resolved when we both upgraded to Nvidia Experience 3.3.x last night.

**Comment by cgutman** [comment]
I know about the issue. GFE 3.3 seems to just 404 all box art requests. Other clients are okay with no box art, but Moonlight Chrome doesn't deal well with that right now.

**Comment by raidancampbell** [comment]
I'm updating now, I'll look into fixing the crash this afternoon

**Comment by cgutman** [comment]
I've release 0.6.3 with a workaround for this issue. It doesn't fix the broken box art, but it allows the UI to load without it.

**Comment by raidancampbell** [comment]
Closing, #181 encompasses the current issues
