### ISSUE TITLE
Game cards are not displayed (v0.6.3)

### ISSUE THREAD

**Issue by mandrichenko** [moonlight-stream/moonlight-chrome#181]
After updating to `GFE 3.3` and `Moonlight 0.6.3` some cards are not displayed.
I know about "incompatibility issue" introduced by `GFE 3.3`.

**Screenshot**
[http://imgur.com/a/pVZCU](http://imgur.com/a/pVZCU)
Where `XCOM 2` just installed game. Other games were installed prior GFE and Moonlight updates.
I think the older games should looks like `XCOM 2` default card.

**Comment by cgutman** [comment]
This is a bug in GFE 3.3. If they won't fix it, we'll need to find an alternate source of box art.

**Comment by dr00t** [comment]
I believe the best way is to get the cover arts from nvidia site directly. Two steps:
1) Base on the <ShortName> from applist XML fetch from  https://services.gfe.nvidia.com/GFE/v1.0/streaming-assets/<ShortName>  the list of game related files
2) fetch the cover art

**Comment by NightHammer1000** [comment]
Go to "%LOCALAPPDATA%\NVIDIA\NvBackend"
Right-click on "StreamingAssetsData" and click Properties.
Go to the Security tab.
Click "Advanced"
Change Owner to "Users" or "Everyone"
Set the Tick to Change underlaying Folder and Files.
Click Apply
Add "Users" or "Everyone" to the List with "Full Access"
Set the Tick to Change underlaying Folder and Files.
Click Apply again and close everything with OK.

Boxart should show up now.

**Comment by ShadowBullet** [comment]
I tried this but some things were not word for word, I can test again, but will need step by step exact as I might have messed something up because it did not change anything for me.
