### ISSUE TITLE
My games get reverted to LOW settings?

### ISSUE THREAD

**Issue by Sawyer007** [moonlight-stream/moonlight-chrome#182]
I just tried to play Assasin Syndicate. But the game always get reverted to the lowest possible settings when started through moonlight? Its fine when played locally. This on a i7 6700k, 32GB, 1080gtx

**Comment by cemarriott** [comment]
Having the same issue with Mass Effect: Andromeda. If I use VNC to launch the game, the settings are where I want them (Medium/High). Using the Moonlight streaming all of the settings are at Low. I believe this has to do with GeForce Experience using "optimal" settings when streaming to SHIELD. Usually in SHIELD devices there is a setting to turn off auto-optimization, but the Moonlight client does not seem to have this.
