### ISSUE TITLE
Stuck on Loading Moonlight plugin 

### ISSUE THREAD

**Issue by HewellP** [moonlight-stream/moonlight-chrome#184]
Hello, I came from java version and I had install the chrome extension in others computer but I can't run in a Surface Pro 4 - i5 4Gb 128GB. And I am saying all of this because even I had format and no way to pass that screen.
Apart of that I had installed Canary, Chromium, Beta, x64, x86, earlier version of chrome, of moonlight and what ever I had imagined.
Does anybody a clue?

**Comment by mejjem90** [comment]
Same problem om a Lenovo Yoga 2 pro. Tried version 0.6.2 and 0.6.3, both gets stuck on "Loading Moonlight plugin..." screen.

**Comment by CheeseSL** [comment]
Both versions works like a charm on my netbook v5-122p. I had this kind of issue before, the solution was to turn on the Native Client (NaCl) in chrome://plugins/.
Hope this helps you.

**Comment by HewellP** [comment]
For me, after 2 days, it repair itself... computer magic ... ¬¬'
