### ISSUE TITLE
Getting separate controller input per client

### ISSUE THREAD

**Issue by Tencao** [moonlight-stream/moonlight-chrome#185]
Now, I want to briefly explain my situation first of all. I host my game from my main pc, and have friends join from theirs, therefor I need the main pc to always be player 1. The problem is, every client that joins is classed as player 1 on the xbox 360 controller, which completely breaks any attempt at gaming together. I do know there's a wiki about renaming this and that dll but all that does is only make my controller work not everyone elses. If there was a way either their side of my side to assign what controller they are, that would solve all our problems.

**Comment by Tencao** [comment]
This is still something I eventually want fixed despite no attention being given for over a year

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so it will be a "don't fix" on that one, sorry!

**Comment by Jorys-Paulin** [comment]
If you still have questions, feel free to ask here :)
