### ISSUE TITLE
Unable to close stream host side

### ISSUE THREAD

**Issue by Tencao** [moonlight-stream/moonlight-chrome#186]
When hosting through moonlight, half the time closing the game does not end the stream, and the only way to fully close it is to turn the game share off in geforce, since the shortcut to end the stream does not work. Adding a ui button or a taskbar icon to end the stream would be a major help, especially if the hotkeys are fixed and later break again.

**Comment by teristam** [comment]
I also have this problem. It's quite irritating...any other method to close the stream from the client side?

**Comment by raidancampbell** [comment]
We do not control any of the server-side functionality, we cannot add any taskbar buttons to stop the stream.  Streams started through moonlight should be stopped through moonlight via the `Quit Current App` button in the upper right.  

Your solution of turning game share on and off is probably the best way to do it from the server.
