### ISSUE TITLE
DS4 controller works fine plugged in, just barely doesn't work wirelessly

### ISSUE THREAD

**Issue by cybersoldier8** [moonlight-stream/moonlight-chrome#188]
When I plug in My DS4 controller, everything works perfectly. However, if I try to run it wireless off of my bluetooth dongle, every thing works _except_ left and right on the left thumbstick. The controller works fine wireless when playing local games, it only shows this behavior in moonlight. It's clearly just a simple problem with mapping, but I don't see any way to modify control mappings from the client.

**Comment by juicypop** [comment]
I can confirm this issue runing latest chrome on windows 10

**Comment by slcc2c** [comment]
Same
