### ISSUE TITLE
Mouse delay and alternative solutions

### ISSUE THREAD

**Issue by Sawyer007** [moonlight-stream/moonlight-chrome#189]
I have just found out about a software which lets you share USB devices over the internet like they are locally attacked on the main streaming PC. It even shows the proper mouse or controller with its real name and installs its drivers under Windows 10. The software is called VirtualHere and I tested it with 3D shooter games. To my surprise it works way better then the moonlights mouse control's. It remains responsive all the time and even the precision in games seems way better. I can actually aim proper in 3D shooter games like Americas Army which is basically unplayable without using this software.

The software is free to use for just one input device, for 2 or more you have to pay.

This isn't meant to be a promotion or anything like that. But if it works way better then inbuilt controlling solutions it deserves to be recognized.

So the issue here is. Why don't the inbuilt mouse and controller solution use the same technology to work? Which is USB over IP?

**Comment by jimb0616** [comment]
Did you install the Server software to your gaming computer and the Client software on the computer or device you're streaming to? Or the other way around?

**Comment by Sawyer007** [comment]
Server software needs to be on your device you are streaming to.  Client has to be on your gaming PC.
I know it sounds unorthodox but its the correct way because you will share your mouse or gamepad from the weak computer to the strong one.

**Comment by jimb0616** [comment]
I figured that which is why I asked. I'll give it a try tonight. Thanks

**Comment by Sawyer007** [comment]
The developer claims it has zero latency on top of the network latency of course because it sends so little data that it doesn't matter.

For Honor, Ghost Wild Lands, Watch Dogs 2. All this games feature the EAC protection and the controller input from moonlight doesn't work for some reason nor does the game work with steam link or inhome streaming at all.  Moonlight can run this game and use mouse+keyboard but no controller input at all.

But with this software it works just fine. I just hope it wont be detected as a cheat of some kind.

**Comment by yaniv862** [comment]
i tried it i think it reduced the delay but the delay still exists

**Comment by Sawyer007** [comment]
Another thing which reduces mouse lag be it with virtualhere or default moonlight control is forcing Vsync off in driver settings. If you absolutely need to limit your fps due to gpu heating up which of course is a waste of power on a 60fps client if the game pushes double or triple that is to use something live MSI afterburner. It causes less input delay then Vsync.

**Comment by jerom007** [comment]
I have used advices to set same mouse speed on host and client with no success.

After some weeks, I realized that there was No Mouse Lag when using a laptop with Windows 10, same OS as on host !
(It was Windows 7 before on client...)

So try to use the SAME OS on your client and host machines (be it win7, 8 or 10) !!
Best of luck,
