### ISSUE TITLE
UI doesn't reset after quitting stream

### ISSUE THREAD

**Issue by raidancampbell** [moonlight-stream/moonlight-chrome#19]
Start stream, have NaCL capture mouse/keyboard, ctrl + alt + shift + q, screen goes black.

This needs to send the user back to a screen similar (or identical to) the `showAppsMode()` seen after retrieving the list of apps from a host.

**Comment by raidancampbell** [comment]
The current holdup is that I need to learn the new message passing system from CPP -> JS.  

I just need a message from [main.cpp's OnConnectionStopped](https://github.com/moonlight-stream/moonlight-chrome/blob/master/main.cpp#L45) into somewhere in index.js

**Comment by dead** [comment]
The new message system do not handle this case... (Since it isn't a callback, and more something like a event).
