### ISSUE TITLE
Host, and guest can't both use controller(s) at the same time.

### ISSUE THREAD

**Issue by jacobmix** [moonlight-stream/moonlight-chrome#193]
If someone joins me, and presses any buttons on their controller it seems to add a few new controllers
to the list (In game) and then i got two xinput 3s on there. None of my controllers work at this point.
The guest gotta join again, and not touch anything for me to get my controls back.
(I do not get them back after closing stream) if i change the DLLs it works fine,
but my guest can't use his controller. Another thing to note is that there's no sound for me when i host?
But there's sound for him? I'm using Windows 7 64bit. And i'm using PS3 controllers through
"SCP DS3 Tool 1.2.2.175" which emulates it as an Xbox 360 controller.
(Haven't switched to any of the newer versions yet.)
My guest was using a Logitech Xbox controller. Tho i did test with another guest,
and the same seemed to happen. This kept my controllers from working even when not streaming?
I'm not sure if there's any way to make sure moonlight is shut down completely.
Couldn't find it in Task Manager. Hope this get's fixed.
It'd be great if both host, and guest could use controllers without problems.
If any more info is required please just notify me.

**Comment by jacobmix** [comment]
Hmm... Seems my controllers stopped working when my guest left (With DDLs changed)
Says i got 4 controllers connected (In game) 1, 2, 3, 4. But i only got one controller connected.
Sound also still doesn't work in game. Can still get sound on YouTube with Chrome. (tested)
My keyboard still works in game btw.

**Comment by jacobmix** [comment]
Sound, and controller doesn't work in other games as well.

**Comment by jacobmix** [comment]
The game we were streaming was 1001 Spikes. Added in "Shield>GameStream>Games & Apps>Add"

**Comment by jacobmix** [comment]
Yeah when i edit the DLLs again (With the ".old") my controllers work. (Still no in game sound tho)

**Comment by jacobmix** [comment]
Closed "nvstream.exe" in Task Manager. (Admin), and now sound, and controllers work.

**Comment by jacobmix** [comment]
When stream is closed completly: http://prnt.sc/e94xo6
When streaming: http://prnt.sc/e9295h
(Just used a program called Antimicro to test if my controls worked in it, and stuff...
They didn't. Seemed to not work at all. It shows them, but the buttons do nothing.)

**Comment by jacobmix** [comment]
The "and then i got two xinput 3s on there." Might have been a one time thing or a glitch the first time we tried it out. But as far is i can tell. My controllers just don't work after his controller is active.

**Comment by jacobmix** [comment]
The DLLs i've tried to rename to fix the controls:
Program Files: "rxgamepadinput.dll" to "rxgamepadinput.dll.old"
Program Files (x86): "rxgamepadinput.dll" to "rxgamepadinput.dll.old"
Seem to make it so my guests's controls don't work. But fixes mine.
I've read somewhere that "rxinput.dll" is the one i should rename tho?
I'll keep testing, and see what happens.

**Comment by jacobmix** [comment]
Renaming "rxinput.dll" doesn't seem to do anything.
Sound seems to work on the hosting PC if i set "Remote audio ON (blue)" on the guest PC.
Still can't get guest controller to work when renaming "rxgamepadinput.dll"
And host controllers still lockup when use a controller on the guest PC.
Testing on my own PCs right now. (Guest being a laptop i have, and host being my main big PC.)

**Comment by jacobmix** [comment]
Been trying a few things, and nothing seems to work.
Gonna try to update to "ScpToolkit v1.7.277.16103-BETA"
From here: https://github.com/nefarius/ScpToolkit/releases
Might fix updating from the old version i got from here:
http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller
Gonna just run the "ScpDriver.exe" And uninstall. Then use the new version.
Hopefully i don't have to do any more before i begin the installation of the new one.

**Comment by jacobmix** [comment]
Nope. Updating that didn't fix it.
Even when i only have 1 controller connected to the Host PC, and 1 to the Guest PC. I get this: 
![Antimicro no DLL edits 1 host cont, 1 guest cont:](http://image.prntscr.com/image/66ad8681b38343c0a3e90cf1ff28b274.png)
This is without the DLLs being edited btw.

**Comment by jacobmix** [comment]
I guess there's just no support for both PCs to have control yet? Like with GeForce Share's "Play along side"
I just guessed that the "Controller Support" mentioned on http://moonlight-stream.com/ was for both PCs.
But i guess it's for the guest PC only. Not for both at the same time. (or multiple guests i suspect.)
Hope it can get added later. Would be way nicer to be both have guest, and host play with controllers.

**Comment by ZTylerDurden** [comment]
I second this.  The Shield streaming quality is so much better than what Nvidia offers in their Beta gamestream.  Please make a feature to support multiple controllers simultaneously on host and guest side.

**Comment by Jorys-Paulin** [comment]
Closing as per request from JacobMix on Discord

**Comment by Jorys-Paulin** [comment]
The issue is fixed in version 8.0
