### ISSUE TITLE
Stuck on "starting Control Stream Establishment"

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#194]
Newest drivers and GFE are installed, thought it was weird for a bit, restarted computer, still happens. Ideas? @raidancampbell @cgutman I feel like Moonlight chrome needs to be updated just a bit to also reflect the box art. I know many of us use moonlight chrome on our PC's and for me it is a essential part of my mobile experience. I don't want this project to just be forgotten and broken...

**Comment by ShadowBullet** [comment]
Okay, it only works on my local network, outside of my local network it is stuck on "starting control stream establishment" I have tried a VPN as well still a no go. My network has not changed at all since this app was even started (hence all ports are still forwarded), is it possible that GeForce Experience added a new port that we are not aware of?

**Comment by ShadowBullet** [comment]
Even more input, the issue seems to be across moonlight itself, I tested it on the iOS app and got the same result. I feel like this could be a GFE issue. @raidancampbell @cgutman Ideas?

**Comment by ShadowBullet** [comment]
Did some digging on NVIDIA forums, they were having an issue with gamestream connection, I thought this might be the issue. I installed the hotfix but still not luck at all. 

Link to the forum post: https://forums.geforce.com/default/topic/993297/gamestream/geforce-experience-hotfix-release-3-3-0-100-gamestream-connection-error-80330209/

**Comment by ShadowBullet** [comment]
Closed, restarting router fixed the issue. Port 47999 was not able to be opened as confirmed by the android app. However box art would still be a nice addition :)

**Comment by roxasofthedark** [comment]
I am now having the same issue you were with port 47999. restarting my router did not fix this issue for me. any ideas?
