### ISSUE TITLE
Stuck on "loading moonlight plugin" on ChromeOS

### ISSUE THREAD

**Issue by hiddenflames5462** [moonlight-stream/moonlight-chrome#197]
Okay so I tried booting it up yesterday and today but it was stuck trying to load the plugin and doesn't boot up no matter how long I wait. Is there something I've done wrong or does it have to do with moolight itself?
Don't know if you'd need this but I'm using a Toshiba Chromebook 2

**Comment by raidancampbell** [comment]
Can you take a look at the logs by following the guide [here](https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs)?

**Comment by vnascone** [comment]
I'm running into a similar issue after upgrading to Chrome 56. Unfortunately I don't see any log messages when following the linked guide.

**Comment by HigHurtenflurst** [comment]
I'm having the same problem -- the app stays at "Loading Moonlight plugin...".   Nothing shows in the console when opened via the given guide.  I've also reset the plugin via the guide, but the problem persists.

Trying on ChromeOS 56.0.2924.110 (64-bit) with plugin version 0.6.3.

**Comment by raidancampbell** [comment]
hmmm, this is troublesome.  I just double-checked and we're still using the latest stable SDK to compile.

Sounds like I'll need to learn how to install ChromeOS tonight...

**Comment by yu42hit** [comment]
I can confirm this happens to me as well on both Mac and Window. I Had to reinstall chrome and moonlight in order to fix. Sometimes it didn't work and I'd have to do it again.

**Comment by raidancampbell** [comment]
getting a ChromeOS environment is turning out to be more difficult than expected, all the guides seem to be for ChromiumOS.

I've made a couple of updates to the code to print out additional debugging info.  This new code is on the `master` branch, or can be found pre-built [here](https://dl.dropboxusercontent.com/u/9034340/moonlight-chrome-03-02-2017-verbose.crx).  This is simply the latest build of `master`, it will still show up as plugin version 0.6.3.  Please do not report issues with this build.

Anyone having issues with the "Loading Moonlight plugin...": could you try this code and see what's printed in the logs?

**Comment by vnascone** [comment]
This is what I get with the verbose build: 

```
common.js:370 Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLDocument.<anonymous> (common.js:370)
background.js:19 Chrome app runtime launched.
```

**Comment by vnascone** [comment]
Looking at the network logs it seems to hang trying to get 

chrome-extension://aeahmfndeacpdaimgdlalehfkeidcgpd/pnacl/Release/moonlight-chrome.pexe

**Comment by raidancampbell** [comment]
Okay, I changed the code to force a few options just to see what happens.  This code is NOT committed: it works on my computer, but I'm not sure how stable it is.

Same spiel as last time: it will still show up as plugin version 0.6.3. Please do not report issues with this build.

[here](https://dl.dropboxusercontent.com/u/9034340/moonlight-chrome-03-03-2017-force-nacl.crx) is the build.

**Comment by vnascone** [comment]
Unfortunately no change in behavior with this build: still stuck loading moonlight with no more information in the logs

**Comment by raidancampbell** [comment]
nothing different in the logs at all?  At the very least the following line should now longer appear:

     common.js:370 Uncaught TypeError: Cannot read property 'split' of undefined

Can you paste the logs somewhere for me to take a look?

**Comment by vnascone** [comment]
Ah you're right, the split error is gone, but now a different one on the background page.

Page Console
```
common.js:343 common.js: calling custom load function: common.domContentLoaded
common.js:310 common.js: Page loaded.
common.js:310 common.js: Browser supports NaCl (pnacl)
common.js:310 common.js: Creating embed: pnacl
common.js:70 common.js: creating nacl module
common.js:81 common.js: adding attrs to nacl module
index.js:744 Window loaded.
index.js:798 Loaded previously connected hosts.
```
Background Console
```
common.js: calling custom load function: common.domContentLoaded
common.js:378 Uncaught TypeError: Cannot read property 'replace' of undefined
    at HTMLDocument.<anonymous> (common.js:378)
2background.js:19 Chrome app runtime launched.
```

**Comment by raidancampbell** [comment]
Another day, another attempt.  This provides more debugging info, and is not expected to fix the issue.  The information worthwhile here is right below the line `common.js: body.dataset:` line in the logs.

Same spiel as last time: This code is NOT committed. It works on my computer, but I'm not sure how stable it is.  It will still show up as plugin version 0.6.3. Please do not report issues with this build.

The build can be found [here](https://dl.dropboxusercontent.com/u/9034340/moonlight-chrome-03-04-2017-force-nacl-verboser.crx)

**Comment by vnascone** [comment]
Console:
```
common.js: body: 
common.js:339 <body data-name=​"moonlight-chrome" data-tools=​"pnacl" data-configs=​"Debug Release" data-path=​"{tc}​/​{config}​">​<div class=​"mdl-layout__container">​…​</div>​<script defer src=​"static/​js/​jquery-2.2.0.min.js">​</script>​<script defer src=​"static/​js/​material.min.js">​</script>​<script type=​"text/​javascript" src=​"static/​js/​messages.js">​</script>​<script type=​"text/​javascript" src=​"static/​js/​common.js">​</script>​<script type=​"text/​javascript" src=​"static/​js/​index.js">​</script>​<script type=​"text/​javascript" src=​"static/​js/​utils.js">​</script>​<script type=​"text/​javascript" src=​"static/​js/​mdns-browser/​dns.js">​</script>​<script type=​"text/​javascript" src=​"static/​js/​mdns-browser/​main.js">​</script>​<dialog id=​"pairingDialog" class=​"mdl-dialog">​…​</dialog>​<dialog id=​"quitAppDialog" class=​"mdl-dialog">​…​</dialog>​<dialog id=​"deleteHostDialog" class=​"mdl-dialog">​…​</dialog>​<dialog id=​"addHostDialog" class=​"mdl-dialog">​…​</dialog>​<div id=​"snackbar" class=​"mdl-snackbar mdl-js-snackbar" data-upgraded=​",MaterialSnackbar">​…​</div>​</body>​
common.js:340 common.js: body.dataset: 
common.js:341 DOMStringMapconfigs: "Debug Release"name: "moonlight-chrome"path: "{tc}/{config}"tools: "pnacl"__proto__: DOMStringMap
common.js:347 common.js: calling default load function: common.domContentLoaded
common.js:310 common.js: Page loaded.
common.js:310 common.js: Browser supports NaCl (pnacl)
common.js:310 common.js: Creating embed: pnacl
common.js:70 common.js: creating nacl module
common.js:81 common.js: adding attrs to nacl module
index.js:744 Window loaded.
index.js:798 Loaded previously connected hosts.
```

Background Console:
```
common.js:338 common.js: body: 
common.js:339 <body>​<script src=​"static/​js/​jquery-2.2.0.min.js">​</script>​<script src=​"static/​js/​material.min.js">​</script>​<script src=​"static/​js/​common.js">​</script>​<script src=​"static/​js/​background.js">​</script>​</body>​
common.js:340 common.js: body.dataset: 
common.js:341 DOMStringMap__proto__: DOMStringMap
common.js:347 common.js: calling default load function: common.domContentLoaded
common.js:373 Uncaught TypeError: Cannot read property 'replace' of undefined
    at HTMLDocument.<anonymous> (common.js:373)
background.js:19 Chrome app runtime launched.
```

**Comment by hiddenflames5462** [comment]
I'm sorry as I am late but about 2 days ago it had fixed itself. I had been
busy with some other things lately and almost forgot I had posted
this.Still,thank you for trying to help.

**Comment by raidancampbell** [comment]
Unfortunately, I'm out of ideas for the time being.  I'm starting work tomorrow and I won't have much time to continue trying to replicate or fix this issue.  From what I've seen people with similar issues in Chrome NaCl plugins have been mysteriously solved over time.

My last-ditch-probably-won't-work suggestion is to verify that the `pnacl` module is up to date in `chrome://components/`, and that chrome itself is up to date in `chrome://chrome/`.

If someone comes up with the solution, please post it because I'm very curious.

**Comment by robinwassen** [comment]
I bumped into this on:
Chrome 57
macOS 10.12.3

Fresh install of both Chrome and macOS as of today.

Did some basic debugging and came to the following conclusions:
- The body element does not contain any data attributes
- The HTML does not contain any reference to the NaCL-module
- The application crashes when trying to read the non-existing data attributes

@raidancampbell What part of the code is supposed to set the data attributes on the body element? The NaCL module? Because I cannot find anything that is supposed to set the data attributes in any of the js-files.

**Comment by robinwassen** [comment]
Some further digging, this problem occurs before loading the module and is therefore not related to this.

I start to suspect that it is the HTML that is broken somehow.

**Comment by robinwassen** [comment]
The problem for this is that common.js is included in the background page that boots the application, the background page is basically an empty HTML page with references to some javascripts. 

This is why all data-attributes are missing and therefore the JS fails.

The script-tag to include common.js in index.html should of course not be removed.

*Solution to solve this problem:*
- Remove the common.js include from the manifest.json at: https://github.com/moonlight-stream/moonlight-chrome/blob/master/manifest.json#L17

I would guess that the all includes (both JS and CSS) except background.js is supposed to be removed from the manifest.json.

**Comment by raidancampbell** [comment]
Thanks for the investigation @robinwassen.  I've never been able to replicate the failure, and a build with your suggested change has no difference for me.

However, for the others who have been experiencing this issue, [I compiled the extension for you guys to give it a shot.](https://www.dropbox.com/s/mrqyvkez5jyo4uu/moonlight-chrome-03-26-2017-robinwassen.crx?dl=1)

**Comment by robinwassen** [comment]
@raidancampbell I have a theory on how you can reproduce this issue, the weird thing is that I cannot see how this works for you since this is a fatal error on startup. 

The only reasons that I can think of for avoiding this is if you run moonlight-chrome by directly opening index.html instead of loading it as an extension or if you have a different execution order for some reason.

**Steps to reproduce:**
- Remove background.js from app.background.scripts in manifest.json (but keep common.js)
- Pack and load the extension in Chrome
- Start the extension
- Open the background page inspector from chrome://extensions

Now you should be able to see that the error occurs in the background page for the application when it starts since common.js is executed on the background page which does not have all the required HTML-elements.

Worth mentioning is that i have moonlight-chrome running on my Mac now after unpacking the extension, removing common.js from the manifest.json and loading it unpacked.

**Comment by DaemonMonkey** [comment]
Hi, I've been having the same issue, getting stuck at "loading moonlight plugin."  The newest extension linked had the same issue.  Is there any info I can provide to help fix this?  I would very much like to play civ in bed!

**Comment by robinwassen** [comment]
@DaemonMonkey - Try downloading the version @raidancampbell linked to two comments before yours.

Add a comment here if it works or not so he knows if he should release that fix in the next version.

**Comment by CaptainMurasa** [comment]
The fix that @raidancampbell worked! I had a loading screen problem for a while and I was trying to figure out why I port forwarded wrong. The loading screen only compounded to my frustration to get Moonlight working properly and now I finally did it!

The only problem is so far is that the Desktop icon that showed up is not in the right frame, but I'm sure that can be easily fixed. I'll get a screenshot once I confirm that my connection with Moonlight works.

Thanks so much!

**Comment by DaemonMonkey** [comment]
@raidancampbell I tried that version and had the same issues.  Based on what @CaptainMurasa commented, do I need to mess with any ports before installing the plugin?

**Comment by CaptainMurasa** [comment]
@DaemonMonkey 

What I found was that if you can't get the right IP, the app might be stuck in a state of constantly looking for your desktop. Before this current change (and the result of me downloading this fix) I couldn't find my gaming desktop at all and the app correctly showed it as such. I had to go back and see if it was my ports/IP in my firewall/router and it was the issue.

What was really frustrating me back then was that I had no feedback and this problem made me frustrated. 

It won't hurt to try.

**Comment by raidancampbell** [comment]
Please note that the port forwarding and firewall exceptions are only relevant when you're streaming over the internet.  If you're streaming within the same network, there is no need to mess with ports

**Comment by kane3345678** [comment]
i had same problem but i figured it out.   

we need to follow the steps in [readme.md ](https://github.com/moonlight-stream/moonlight-chrome#building) to build nacl and then the browser can load it from source  
hope this can help ppl here
