### ISSUE TITLE
Black screen no sound issue...FIX

### ISSUE THREAD

**Issue by bkny65** [moonlight-stream/moonlight-chrome#200]
For those of you who are getting a black screen/no sound issue. I play a lot of games at my job when there is down time. So before I leave the house I have my PC on and my wife watches same TV that I have the PC on. When I get to work I open up Chrome and connect to Moonlight..EZPZ.. But, recently I've had some issues where I would get to work and I would get the same black screen/ no sound falling back to CPU issue BS. Well I think I solved that issue. When I left to go to work the TV was off and the graphics card did not detect a "monitor" plugged in rendering the GPU useless. As soon as I had my wife turn on the T.V I was able to connect to moonlight. So I did some digging, you can buy a dummy HDMI plug that you can connect into the GPU to make it think that it has a monitor/tv plugged into it. You can make one or you can buy one. I came across this guy on youtube who makes them it's called headless ghost, you may buy similar products on Ebay for $13. So I hope this helps some of you guys that are having this issue. I'm kind of having an issue of my own with one of my laptops stuck in the loading screen whenever I load Moonlight, so if anyone has a solution for that let me know.

**Comment by bkny65** [comment]
FYI I fixed the endless loading of Moonlight app on Chrome by installing the correct java application. I had the 32 bit one instead of the 64 bit one.

**Comment by Jorys-Paulin** [comment]
@bkny65 Then if your problem is fixed, you can close this issue, otherwise we can help!
