### ISSUE TITLE
Black Screen, no sound, no picture.

### ISSUE THREAD

**Issue by AramVex** [moonlight-stream/moonlight-chrome#201]
So my issue is when I start the moonlight, I get no picture or sound. I have opened ports, tried different versions, downgraded GE, amongst other things.

If I try to open an app via moonlight, this is when it happens. The app OPENS on the actual PC, but it's not feeding me any video. Is this an issue with moonlight or ge?

**Comment by raidancampbell** [comment]
Have you tried following the troubleshooting guide on the topic [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#no-video-displayed-on-device)?

If you have an android or ios device, you could try one of them to verify that it's not chrome-specific

**Comment by AramVex** [comment]
Yeah, I've done all of this.

I've tried it with driod, and it doesn't work still. Same issue.

**Comment by Calcyfer** [comment]
Old issue, but I might be able to help, having had a similar experience.
Make sure there is a screen connected to your host computer (or an hdmi dummy).
Otherwise, you'll get a black screen.
