### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by Fenrir426** [moonlight-stream/moonlight-chrome#203]
I have the following ports opened.
TCP: 35043, 47991, 47995, 47996, 47989, 47984, 48010
UDP: 7, 9, 47999, 47992, 47998, 47989, 48000
In accordance with GeForce and the following other ports as instructed.
TCP 47894, 47989
UDP 47998, 47999, 48000, 48010
However, I receive the following Connection Failed message.
Connection Failed
RTSP handshake failed with error -1

I have a HDMI headless port in one of my HDMI ports and a HDMI cord in another HDMI port that is going into a splitter into my T.V. and a regular cord going into my computer screen.

I tried them as individuals and still some error message.

I am completely baffled on what to do besides restarting everything from scratch.

**Comment by cgutman** [comment]
You forgot to open UDP 48010.
