### ISSUE TITLE
Fixing mouse lag and dead zones

### ISSUE THREAD

**Issue by yu42hit** [moonlight-stream/moonlight-chrome#205]
So I have two issues. One is the unbearable mouse lag and the other is the dead zone for mouse on the remote pc. whenever I move my mouse a little, it doesn't pick it up on the remote pc. whenever I use steam in-home streaming I never notice such a thing.

**Comment by air** [comment]
Running 0.6.3 on Dell Chromebook 13. I experience unusable mouse performance as above. I'm trying to play Hearthstone on a very powerful PC, nothing crazy.

Many touchpad movements just aren't reflected on the PC. Trying to draw a smooth circle motion is impossible.

I have tested:
- All combinations of 720p and frame rate
- Forcing off vsync for the game on the PC.

Neither help.

**Comment by air** [comment]
Interestingly if I start crouton (XUbuntu, trusty) and run the Chrome client, mouse performance is much better: 1. Tap-to-click continues to work (#231) and 2. Mouse responsiveness is good enough to draw a smooth circle.

I notice when I run in crouton, I get a message about HW decoding not available. I notice in the crouton log tab:

`Starting video stream...[29305:29305:0501/214446.209577:ERROR:gpu_video_decode_accelerator.cc(375)] HW video decode not available for profile h264 high`
