### ISSUE TITLE
Enhanced pointer precision turns randomly on

### ISSUE THREAD

**Issue by Discostoff** [moonlight-stream/moonlight-chrome#206]
Hello,
I use latest win chrome extension on win10.
Enhanced pointer precision turns sometimes on.

greetz

**Comment by raidancampbell** [comment]
Does the client (the computer running the Moonlight-Chrome app) have pointer precision turn on, or does the server (the computer running the game) have pointer precision turn on?

**Comment by AhornFPS** [comment]
Got the same issue, both pcs don't use mouse acceleration but sometimes when starting the moonlight stream, it activates it on the sending computer. I am not sure if this is coming from moonlight or gefore experience tho.

**Comment by airdjing** [comment]
Same issue here..
Very annoying problem

**Comment by Marctraider** [comment]
Same here from mac client to windows 7 server, no mouse drivers installed.

**Comment by Marctraider** [comment]
its not sometimes here, but always.

**Comment by sangdrax8** [comment]
Mine does this as well.  My clients are both ChromeOS and a Linux machine, using the chrome plugin.  This greatly increases the difficulty of using the mouse with any input lag.

I think my mouse sensitivity settings are also resetting.  Not 100% sure, just know that it doesn't feel right and I end up turning that down as well.

**Comment by owenwalker92** [comment]
I'm also getting something similar.

Either mouse precision will turn on, or my adjustments will not be saved. Everytime I connect to the GameStream it seems the settings revert.

This is with a win10 server, and OS X and/or Windows 10 client.

**Comment by owenwalker92** [comment]
I also have noticed that DPI settings on the mouse seem to be ignored and the maximum movement speed seemed to be locked directly to software sensitivity? 

Trying to adjust my DPI on the local mouse gives no difference in movement speed.

**Comment by cgutman** [comment]
GFE 3.13 now turns mouse acceleration off, so this should be resolved.

**Comment by Cloudore** [comment]
@owenwalker92 
Were you ever able to solve the issue with sensitivity settings being ignored? my minecraft left stick is locked at max sensitivity and nothing I have done has fixed it, host computer, game settings, or client computer side

**Comment by Discostoff** [comment]
ndi plugin

**Comment by Cloudore** [comment]
@discostoff
Huh, could you elaborate? Googled was unsuccessful when trying ndi plug in and moonlight

**Comment by Discostoff** [comment]
https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/

**Comment by cgutman** [comment]
This is fixed since a few GeForce Experience releases ago.

**Comment by stepc0re** [comment]
Two years later, same problem. Always when I connect through moonlight on my Gaming PC through my laptop, mouse acceleration is turned on. Very annoying. Am I missing something?
![grafik](https://user-images.githubusercontent.com/24844458/78276880-eb41ae00-7513-11ea-8fa4-112813bbea92.png)

**Comment by cgutman** [comment]
GFE is forcing mouse acceleration enabled when it starts streaming. This isn't something Moonlight controls.

**Comment by stepc0re** [comment]
So there is nothing i can do here? Sorry maybe its not an moonlight issue, but its not possible I am the only one having this problem. I cant find anything helpful on the internet...
