### ISSUE TITLE
Crash after RTSP Handshake

### ISSUE THREAD

**Issue by Dave247** [moonlight-stream/moonlight-chrome#207]
So I got a 1070, installed GeForce Experience, ticked to allow experiential features and then installed the plugin in chrome and tried to launch a game with it. However, for whatever reason no matter which game I choose it will crash during the part where it is establishing the RTSP handshake. There is no error message of any kind so I have no idea what could be causing it and what I should be looking into.

I uninstalled ESET and rebooted my PC but still no different, and as I have never had a Nvida card before or used the Geforce software I don;t think I should need to reinstall it either.

**Comment by pinas** [comment]
Not offering a solution I'm afraid, but wanted to mirror this experience with my GTX 970 and Dell Chromebook 13.  It shows my games but when I try to stream it just crashes while trying to establish the RTSP handshake.

**Comment by Dave247** [comment]
That's ok. Nice to know I'm not the only one who has this issue.

**Comment by michaelowens** [comment]
Same problem here. :(

PC: 980 Ti with latest geforce (updated ±1 hour ago)
Client: Chrome client (deleted & reinstalled just now) on a Macbook Late-2013

**Comment by Dave247** [comment]
Thanks to @mtichbon comment I was able to get it working... kinda. Trying to start the steam while the game is already running seems to sometimes work, but it still seems rather buggy and something still feels like it's misbehaving.
It's better then nothing though I guess. My next step is to try and actually stream/play with a friend.

**Comment by adilanchian** [comment]
Having the same issue over here. Running 1080 with all drivers up to date as of today. I can open and close the app, but I crash on the RTSP handshake. Will provide any information needed!

**Comment by Dave247** [comment]
So I'm kinda embarrassed to admit this but... the issue for me was that I was trying to run moonlight on my PC , which is what you **don't** do.
Moonlight is meant to be run on the other device that you want to stream to, either another PC or mobile device. So if you want to pay with a friend online you need to get **them** to download Moonlight and run it, and not you.
I've always suspected this was the case but wasn't fully sure as I was confused by the instructions.

**Comment by adilanchian** [comment]
hey, it happens to the best of us haha! 

Unfortunately, Im still running into the same issue with iOS and Chrome extension. On iOS I get the RTSP error -1 and on chrome extension I get a crash! No idea what it could be

**Comment by herpertutus** [comment]
just had the same issue, running ubuntu based disctro Kernel: 5.13.0-27-generic app displays RTSP handshake attempt then crashes, installed through flatpak but also tried snap. Any ideas gamers? :(
