### ISSUE TITLE
 Infinite loading

### ISSUE THREAD

**Issue by MaxKillermobs** [moonlight-stream/moonlight-chrome#208]
Background error:

Uncaught TypeError: Cannot read property 'split' of undefined
at HTMLDocument.<anonymous> (common.js:370)

common.js index error:

NativeClient: PnaclCoordinator: Compiler process could not be created.
common.js: ERROR [NaCl module load failed: PnaclCoordinator: Compiler process could not be created.]

**Comment by vnascone** [comment]
This sounds like #197

**Comment by MaxKillermobs** [comment]
I downloaded the latest SDK and source code, but it does not help

**Comment by Jorys-Paulin** [comment]
@MaxKillermobs Hey, does your problem still occurs?
