### ISSUE TITLE
Pairing doesn't work consistently

### ISSUE THREAD

**Issue by raidancampbell** [moonlight-stream/moonlight-chrome#21]
For some reason, pairing seems spotty: I can't get pairing to work on a first run, but after restarting, and another couple attempts, it seems to work.

To replicate this, it's necessary to clear the stored pairing by running the following line in the javascript console:

    chrome.storage.sync.clear()

**Comment by raidancampbell** [comment]
still no clue.  It's seemingly random. I got it to work on first run once.  There must be a race condition or something...

**Comment by raidancampbell** [comment]
I'm starting to suspect something's causing a timeout in pairing.c's gs_pair, but it still returns GS_OK.

If you wait long enough, the call will return with status 0 indicating the javascript message to "pair" was successful, but subsequent requests to list the apps will return unauthorized

**Comment by dead** [comment]
Try this:

    function moduleDidLoad() {
        if(!myUniqueid) {
            console.log("Failed to get uniqueId.  Generating new one");
            myUniqueid = uniqueid();
            storeData('uniqueid', myUniqueid, null);
        }
        
        if(!pairingCert) { // we couldn't load a cert. Make one.
            console.log("Failed to load local cert. Generating new one");   
            sendMessage('makeCert', []).then(function (cert) {
                storeData('cert', cert, null);
                pairingCert = cert;
                console.log("Generated new cert.");
            }).then(function (ret) {
                sendMessage('httpInit', [pairingCert.cert, pairingCert.privateKey, myUniqueid]);
            });
        }
        else {
            sendMessage('httpInit', [pairingCert.cert, pairingCert.privateKey, myUniqueid]).then(function (ret) {
                snackbarLog('Initialization complete.');
            });
        }
    }

**Comment by raidancampbell** [comment]
Did a pull, submodule update, added your change, a make clean, and cleared the data.  The following is output 

    index.js:35 Failed to get uniqueId.  Generating new one
    index.js:41 Failed to load local cert. Generating new one
    index.js:45 Generated new cert.
    index.js:21 Attempting pair to: XXXXXXXX
    index.js:95 sending pairing request to XXXXXXXX with random number 8183
    index.js:97 "pair" call returned.
    index.js:98 0
    index.js:21 Pairing successful
    index.js:149 entering show apps mode.
    index.js:121 pairing attempt returned: 0
    messages.js:22 https://XXXXXXXX:47984/serverinfo?uniqueid=a0c0d00a8bc7d230&uuid=d88d5375-a8f5-4363-a85e-b5864396f6e3
    utils.js:91 Requested app list
    messages.js:22 https://XXXXXXXX:47984/applist?uniqueid=a0c0d00a8bc7d230&uuid=3799a30c-bbed-4735-9baa-3e8fe2966aa4
utils.js:93 App list request returned with: <?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="applist" status_code="401" status_message="The client is     not authorized. Certificate verification failed." />
    utils.js:108 Returning app list:

There was a long wait in between the log in `index.js:95` and `index.js:97` which is what makes me suspicious of a timeout

**Comment by dead** [comment]
That's strange, I could not reproduce that here...

**Comment by raidancampbell** [comment]
Is everything working for you every time?  @cgutman can you give this a shot?

**Comment by dead** [comment]
Yep... Just to be sure, put a console.log(pairingCert) after the "Pairing successful" to see if the cert is really loaded.

**Comment by raidancampbell** [comment]
took a break, came back and it was 3/3 successful pairing attempts.  It's entirely possible I accidentally made other calls while trying to pair, which can apparently screw up the whole process.  Thanks for the code, @dead
