### ISSUE TITLE
Test Moonlight game streaming on Nintendo Switch via Switchboard

### ISSUE THREAD

**Issue by JonathanRowley** [moonlight-stream/moonlight-chrome#211]
SwitchBoard is a dashboard designed for the Nintendo Switch. It would be cool if you could get moonlight working on there. I'm not sure if the Switch has WebAssembly included as part of WebKit or not though... see http://SwitchBoard.cool or from a Switch goto Link Facebook to your account and search for the Facebook.com/SwitchBoardDash page. :)

**Comment by raidancampbell** [comment]
Moonlight-Chrome relies on Native Client code execution to run, and additionally has some Chrome-specific code in it.  If you want to have Moonlight run on the Switch, I would suggest making a new project, as it's out of the scope of Moonlight-Chrome.

**Comment by JonathanRowley** [comment]
Ok thanks for your comments. I thought it would be interesting to see but couldn't find any contacts for the moonlight project so posted here. Thanks again for taking the time to reply and good work with the project so far :)
