### ISSUE TITLE
[Feature Request] Open multiple windows/sessions at once

### ISSUE THREAD

**Issue by smcreamer** [moonlight-stream/moonlight-chrome#212]
When opening a Moonlight session, I can only create one window at a time.  Most of the time it isn't a big deal, but it can be tedious to open six or more windows for multiboxing.

Steps to Reproduce:
1. Install Moonlight.
2. Go to chrome://apps.
3. Click Moonlight.

Expected Result
Have a dropdown or slider to make more than 1 window at once.

Actual Result
No ability to create more than one window at once.

**Comment by Jorys-Paulin** [comment]
It works for me, but what would be the use case? Streaming from multiple computers at one time?
