### ISSUE TITLE
Video Stream not displayed correctly

### ISSUE THREAD

**Issue by ShadowCX** [moonlight-stream/moonlight-chrome#213]
Hello,
I have experienced a problem from time to time where the video stream would not be displayed correctly. Ever since the latest patch of GeForce Experience a few days ago the problem seems to have become permanent now unfortunately and no matter what I've tried, I can't seem to make it go away again.
What happens is that once my friend connects to my PC and we start up a game, the App Selection Menu will NOT disappear, but instead will remain with the video stream of the game being rendered right beneath the App Selection.

![17499809_1873506222890586_975022173_o](https://cloud.githubusercontent.com/assets/20975225/24361329/f415de58-1309-11e7-8e51-72a9f2007a6d.png)

As can be seen, he only appears to have a small preview-ish version of my Desktop being streamed and above that the App Selection menu is still displayed.
Is there ANYTHING we are missing? Is there some kind of key one can press to switch to full screen from this small preview-like video stream? 
Please, if anyone knows anything at all, I would be very grateful, as this issue is driving me into desperation already.

**Comment by ShadowCX** [comment]
Hi everyone,
some time has passed and I'll attempt to answer my own question now as it has resolved itself meanwhile and there just might be others having the same problem out there.
The glitch is actually triggered by quite the trivial mistake: my friend always tried to start up the games from the App Selector Menu by **DOUBLE CLICKING** on the icons. Apparently this behaviour triggers the glitch as shown in the above screenshot. By simply doing a single click the issue is completely resolved and everything works fine.
If I may make a **suggestion** to the Devs: maybe try and block the Moonlight App from being able to receive anything beyond the first click. I can only assume that would be relatively simple to fix and it would prevent inexperienced users from triggering that faulty behaviour of Moonlight.

**Comment by Jorys-Paulin** [comment]
Have you tried with the newest version ? (The one with the new UI)

**Comment by ShadowCX** [comment]
Hi,
since he now knows not to be double clicking, he's obviously avoiding doing so. Next time I'll tell him to try triggering the bug on purpose just for the sake of seeing whether or not the new UI is still prone to the same error and tell you here.
