### ISSUE TITLE
Command line options for Chrome Moonlight like PC Moonlight?

### ISSUE THREAD

**Issue by microchipmatt** [moonlight-stream/moonlight-chrome#216]
Hello, the advantage for me with the PC client for moonlight on Windows, MacOSx or Linux, is that I can automate the lunach, options and pairing from the command line.  I have a project that integrated moonlight into it (an open source one), and the command line options are very important to me, I can even launch right into steam from the command line.  Are there are similar automated options for the chrome extension, since the PC version, is soon to be discontinued?  Is there a way to lunch the moonlight chrome extension from:

1. Launch straight into a Gamestream server and a particular game and or steam?
2.  Pair automatically so that the user does not have to think about it
3.  Preset the quality and stream setting from a script, command line or any other method that automates the settings for a user?  

The main thing here is to automate as much for the user as I can like I can with the PC version.  Thanks in advance.

**Comment by Jorys-Paulin** [comment]
Maybe opening the extension via a custom URL would fit well, something like `chrome-extension://<moonlight>/index.html?host=192.0.0.X&game=1234&....`

**Comment by microchipmatt** [comment]
@Jorys-Paulin, can opening it from a custom URL, fulfill all of my requirements I laid out in 1, 2 and 3?  If so, can you point me to some documentation?

**Comment by Jorys-Paulin** [comment]
It would require an implementation of the extension, using `location.search` on the javascript in order to keep the `?host=192.0.0.X&game=1234&....` part and then parse it to get the arguments who could then be executed by the existing functions

**Comment by mtwomey** [comment]
+1 for wanting this capability (as I'm a mac user streaming from a PC).

**Comment by Jorys-Paulin** [comment]
@mtwomey It would be simple, but I find the code too messy to implement it properly...

**Comment by kishorv06** [comment]
@microchipmatt How do you automate the pairing process? I need it for a project, can you share details ?

**Comment by Jorys-Paulin** [comment]
@kishorv06 You'll need to implement an API on Moonlight that parses the query string. However, launching a game requires to have a host object which needs to be created, then paired, then you can query a game id, then you can launch it (of course with a lot of options to use)

**Comment by kishorv06** [comment]
I was asking about pairing. How could i automate the process of entering
pin on the server? Is there any API for that?

**Comment by Jorys-Paulin** [comment]
You shall execute in the command line `chrome "chrome-extension://<id-of-moonlight-extension>/index.html?host_id=x&pair=2546"`
But you'll have to implement URL routing, which is hard because of how messy and complicated the code is, and resolve the issue when chrome says this URL is invalid for some reason. I think as of now, it's impossible to implement this feature.
You could, however, use some kind of browser automation tool to run code inside the current app to make it work. Look at something like [Puppeteer](https://github.com/GoogleChrome/puppeteer).

**Comment by microchipmatt** [comment]
You have provided some great ideas.  Due to how the code base is currently implemented, I have asked Cam, if he is willing to provide us with some options. I was hoping to use this in my current open source software and project, but alas, I'm not sure from a time perspective if this is going to happen since it's been about a year now. I could attempt to implement it with the ideas above, but I think I would hit a wall at this point, "But you'll have to implement URL routing, which is hard because of how messy and complicated the code is"  I have some breakthrough moments sometimes, but I am doubtful if my coding knowledge would allow me to do this.  I am hoping Cam will save the day for me, even if at a later date.

**Comment by Jorys-Paulin** [comment]
@microchipmatt Using puppeteer to run custom javascript. However, you'll have to deal with visual dialogues. This is what happens when UI and logic are mismatched.

**Comment by microchipmatt** [comment]
Wow, looks like this would be quite the task...It might be easier if Cam provides the solution, so I don't hit the "Wall" I talked about earlier.  For the sake of exploring to the extent that I really realize I'm probably truly not up to the task with my knowledge, I will ask one more question. In this example here, "chrome-extension://<moonlight>/index.html?host=192.0.0.X&game=1234&"

Based on the current code, how does one determine what "id" the game was given for IE: "game=1234&".

**Comment by Jorys-Paulin** [comment]
Each game is given an ID by GFE, it should be unique to each game.

When you have selected an host, you have access to the host object named "api"
```javascript
api.getAppList()
return [
{title: "Assassin's Creed IV", id: 1966156111},
...
]
```

**Comment by microchipmatt** [comment]
I see. Thank-you. There is much work here. I pray Cam helps.  I will bash my head against the while in the meantime hoping something comes to be, based on our exploration here.

**Comment by Jorys-Paulin** [comment]
@microchipmatt If you want you can join the community Discord (https://discord.gg/dASxGZ) if you want us to talk more on that :)

**Comment by microchipmatt** [comment]
Wow, that would be really great...I think it would be a little intimidating for me, but as well, it would be good for me to get out of my comfort zone.  Thank-you so much for the invite :) I will find you there.

**Comment by kishorv06** [comment]
For your information, it's not a big task to implement url matching. I have
successfully another way in which I would provide the game code and host
address. If you people are still interested in creating a url based
solution, I could give it a try.

**Comment by Azelphur** [comment]
@kishorv06 any chance you'd put your modifications up on github for us to use?

**Comment by kishorv06** [comment]
Yeah. I would fork the repo to do the modifications. Will let you know when
it is done.

**Comment by kishorv06** [comment]
Looks like it is going to be a waste of time, as google is removing support for chrome apps on all platforms except chrome os.

![image](https://user-images.githubusercontent.com/11171849/42572574-554eaec0-8537-11e8-96af-b847cce299c1.png)

**Comment by cgutman** [comment]
The new Qt client for PC supports this
