### ISSUE TITLE
Microstutters on Chrome and iOS

### ISSUE THREAD

**Issue by jvdnguyen** [moonlight-stream/moonlight-chrome#217]
So I have my PC connected via ethernet, and am having some issues with streaming via Moonlight. When I'm on my laptop or on my iPad on wi-fi at the same location, whenever I stream using Moonlight I get stuttering no matter which settings I choose: 720p, 1080p, 30hz, 60hz, there's always stuttering. But, when I take my laptop or my iPad to a remote location 30 miles away, the stuttering is mostly gone and streaming works really well, even at 1080p60hz. 

That would suggest the wi-fi at the first location is poor, but that doesn't seem to be the issue. Running speed tests and such show pretty good DL/UL speed (42mbps download, 20mbps upload) at that first location.

**Comment by toothsaw** [comment]
It's no use testing the UL/DL speed: that's measured through the gateway, i.e. to/from the internet.
Your stuttering issue is on your local wi-fi network.
Maybe you're on a 2.4 GHz network and/or are getting some interference from other wireless devices (Bluetooth, consoles, cordless phones,...)
Be sure to connect your laptop/iPad to a 5 GHz WiFi network and try to shut everything else down.
