### ISSUE TITLE
Black screen, audio no video, gtx 1080 display port fix

### ISSUE THREAD

**Issue by jethozo** [moonlight-stream/moonlight-chrome#220]
I was having issues streaming using the above config. With monitor off, no video. Monitor on, video! Switching from display port to HDMI solved my issue. Hope this helps somebody else.

**Comment by boozecow** [comment]
Thanks, I experimented the same issue when I replaced my monitor.

**Comment by blackgold9** [comment]
So, I have a similar problem. I am trying to stream remotely, with the display plugged in to the hdmi port. If i try to stream, I get no video, but If I log in via chrome remote desktop, video works.

**Comment by Jorys-Paulin** [comment]
@blackgold9 Try re-installing completely Geforce Experience. Make sure you have the latest version of Geforce Experience as well as the latest drivers.

**Comment by blackgold9** [comment]
Installed (built the conputer) 2 days ago.

**Comment by Jorys-Paulin** [comment]
@blackgold9 
- Try enabling experimental features
- Try connecting from the Android client
