### ISSUE TITLE
No cursor when desktop streaming... is there a way?

### ISSUE THREAD

**Issue by Gaveroid** [moonlight-stream/moonlight-chrome#222]
I'm trying to do desktop streaming to a Chromebook so I can use programs like Autodesk Inventor when away from home, but for reasons I can't figure out I just don't have a cursor. I am desktop streaming via the method suggested in the wiki. I also tried just adding Inventor outright and streaming it, but the same thing happened. Is there a way for me to show the cursor? I read of some others having this issue, and yes a mouse is plugged in to my host PC.

**Comment by KayZey** [comment]
This started happening to me too and I haven't had this issue before the laste Nvidia Update. 

I use a headless Display and it has been working just great until I updated to the latest nvidia experience.

Any way of troubleshooting this?

**Comment by Sawyer007** [comment]
Do you have a mouse plugged in at all since its a headless setup? Because my mouse cursor also disappears as soon as I remove my mouse from the computer. I usually have 2-3 mices in my computer at any given time due to running virtual instances but this also seems to cause more wired mouse lag spikes. Works best If I have 2 out of 3 mices disabled when I use moonlight on the physical computer.

**Comment by Gaveroid** [comment]
I tried Chrome Remote Desktop but I couldn't even get it to connect. I have heard of other cases in the past where Gamestream just doesn't like other remote desktop stuff.

**Comment by GizmoTheGreen** [comment]
just installed moonlight for chrome, 0.8.2, latest GFE fom time of writing. and no cursor in a few games that don't render their own in game. so pretty useless sadly :(
no fix for this? drawing one client side so I know where I'm pointing?

**Comment by Jorys-Paulin** [comment]
@GizmoTheGreen This seems to be a bug on GFE's side. Sadly, we can't really implement your request, since there's no way for us to detect if the cursor is present only via a video
