### ISSUE TITLE
Escape Sequences do not work on Windows 10 Bootcamp

### ISSUE THREAD

**Issue by j4adam** [moonlight-stream/moonlight-chrome#224]
Vital Information:

Host Machine:
Windows 7 Ultimate
GeForce Experience 3.5.0.70
GeForce 970 on driver 381.65
Chrome Version: Version 57.0.2987.133 (64-bit)

Client Machine:
Bootcamped Windows 10 Enterprise
Chrome Version: Version 57.0.2987.133 (64-bit)

Issue:

When on the client machine, in any game/app I cannot escape or release mouse control using the following commands: Press Ctrl+Alt+Shift to unbind the mouse and Ctrl+Alt+Shift+Q to quit streaming.

I've tried all combinations of Control/Option(alt) and shift. I usually resort to control/option(alt)/Delete and force quit chrome and relaunch.

**Comment by cemarriott** [comment]
Have you tried holding the Fn (Function) key when you press Alt?

**Comment by j4adam** [comment]
That did it. Not a mac guy.
