### ISSUE TITLE
More Resolution options?

### ISSUE THREAD

**Issue by jinwk00** [moonlight-stream/moonlight-chrome#225]
Is there any way to make more resolution, since my client and stream only support up to 1366x768?
I want to see in true 768 quality, not 720.

Note: I tried creating a fork on http://github.com/jinwk00/moonlight-chrome/

**Comment by k7000i** [comment]
at line 31 in index.htm insert the desired option like `<option value="1366:768">1366x768</option>`

**Comment by jinwk00** [comment]
@k7000i Well I am suppose to add something to the code instead of the HTML, right?

**Comment by k7000i** [comment]
@jinwk00 Well if you look closely the LiInitializeStreamConfiguration function actually parse the option values from html, so you only need to edit that if you need this kind of modification.

**Comment by jinwk00** [comment]
@k7000i You are a true genius. Case closed.

**Comment by Junn-Sorran** [comment]
This might be a dumb question, but how can I recompile all of these files
in a .crx file with my own modifications?

2017-04-25 4:32 GMT+02:00 jinwk00 <notifications@github.com>:

**Comment by cemarriott** [comment]
You can edit the files in-place after you have added the extension to Chrome. I edited mine and added a new option, and it was available next time I opened Moonlight. For example, index.html is located here on macOS: 

/Users/<username>/Library/Application Support/Google/Chrome/Default/Extensions/kneneiigihpjinpiaoidjolckmeaogdh/0.6.3_0/

The resolution selections start at line 30.

On Windows, it is supposedly here (I have not verified this myself):

C:\Users\<Your_User_Name>\AppData\Local\Google\Chrome\User Data\Default\Extensions

**Comment by k7000i** [comment]
You dont have to recompile the project if you only modify the index.html otherwise you need to set up the build enviroment

**Comment by Junn-Sorran** [comment]
Neat, that was easy thanks!
On windows it was on C:\Users\[Username]\AppData\Local\Google\Chrome\User
Data\Profile 3\Extensions\kneneiigihpjinpiaoidjolckmeaogdh\0.6.3_0

2017-04-26 12:36 GMT+02:00 k7000i <notifications@github.com>:
