### ISSUE TITLE
What IDE is Moonlight-chrome made in and how do i load it

### ISSUE THREAD

**Issue by Darkyere** [moonlight-stream/moonlight-chrome#226]
Im sorry i write this here but i need a hand in understanding

I couldten find out on the net which ide is used and couldten find out how to get it into QT Creator both with git and cvs. It says there is no files to load after cloning the files

Is there anyone who could explain how which ide is used and how open Moonlight-chrome source code in it ?

**Comment by Calcyfer** [comment]
I use Jetbrains CLion. The source is C++.

**Comment by raidancampbell** [comment]
Last I checked, cgutman was using visual studio.  I use Sublime for any javascript code, and CLion for any C++
