### ISSUE TITLE
RTSP handshake issue

### ISSUE THREAD

**Issue by cordelljones** [moonlight-stream/moonlight-chrome#228]
Pairing works fine.

Whenever I start any game, the game opens on the host and Moonlight says "Starting RTSP handshake..." on the client. After a couple of seconds, Moonlight goes back to the game selection without any message of an error. Saw in an earlier post that checking for experimental features on the host fixed this issue, but this didn't work for me. 
I am running the Moonlight extension on a 2012 Macbook Pro and I am on a University wifi network, if that matters at all.

**Comment by Calcyfer** [comment]
Nothing in your console log?
Check [the wiki](https://github.com/moonlight-stream/moonlight-chrome/wiki) to see how to enable logging.

**Comment by cordelljones** [comment]
Not exactly sure if this is what you are asking for. But this is the message I see in the console log:
console.log(msg.data);
        if(msg.data === 'streamTerminated') {  // if it's a recognized event, notify the appropriate function
            $('#loadingSpinner').css('display', 'none'); // This is a fallback for RTSP handshake failing, which immediately terminates the stream.

**Comment by Calcyfer** [comment]
Follow this guide ;

> To enable debugging of packed apps (like the release .crx for Moonlight), head over to chrome://flags, and enable Debugging for packed apps
> 
> After restarting chrome, you should be able to right click -> inspect in the moonlight app. It may be helpful to take moonlight out of fullscreen by clicking somewhere on the app and hitting esc. The Javascript console will appear in the bottom pane, or as a tab along the top. Moonlight-Chrome writes all its log messages to this console.

It should look like this ;
![capture](https://cloud.githubusercontent.com/assets/1166874/25501679/e199c2f6-2b93-11e7-8278-225918131d22.PNG)

Copy the output from that right after the RTSP handshake fails, that should help pinpoint the issue.

Seeing how you're on university wifi though, I'm guessing a firewall or proxy might be the issue here, but we'll see.

**Comment by cordelljones** [comment]
Here you go, 

![screen shot 2017-04-27 at 9 46 21 pm](https://cloud.githubusercontent.com/assets/28089566/25511134/02e366e8-2b93-11e7-8c99-13aec0acb0a1.png)

**Comment by AgentT-mo** [comment]
I have the exact same Issue, but unlike other Issues that got resolved, I get this error on local Wifi
so I shouldn't have to open some ports in my router.

I also disabled both firewalls and reinstalled Geforce Experience, but I still get:
ProgressMsg: Starting RTSP handshake...
Starting RTSP handshakefailed

If someone could help I'd be grateful.

**Comment by Calcyfer** [comment]
@cordelljones I'm afraid this has indeed to do with the firewall on your university wifi, you could try setting up your own network within it, using your own router.
@AgentT-mo This could be to do with your router being too restrictive. Are you using some sort of provider-issues modem?

**Comment by AgentT-mo** [comment]
I'm using a AVM FritzBox 7560 as my router, 
I also tried creating a Hotspot on my Geforce PC and connecting with my second Device to it,
but I got the same Error :(

**Comment by Calcyfer** [comment]
@AgentT-mo Make sure you have updated to the latest version of GFE. If you have, try capturing what's happening on the network using Wireshark (create a pcap file).

That should point you in the direction of what's wrong, most likely a firewall issue.

**Comment by AgentT-mo** [comment]
hey i've captured my network with wireshark, but I have absolutly no clue what to look for. 
I've added both captures here 
The Client PC uses the IP: 192.168.178.20
and the Geforce PC uses: 192.168.178.23

I'd be nice if you could have a look :)

Thanks in advance

[Wireshark Files.zip](https://github.com/moonlight-stream/moonlight-chrome/files/976804/Wireshark.Files.zip)

**Comment by Calcyfer** [comment]
@AgentT-mo It seems your UDP port 57553 on your client is not reachable from your server.
You can use this display filter ; `ip.addr == 192.168.178.20 && ip.addr == 192.168.178.23`

Might be a firewall issue on your client or on your router.

**Comment by AgentT-mo** [comment]
Thanks Calcyfer 
i've looked for every thing that could possibly cause this behaviour and turn it off and/or reset most of my hardware. I have no clue what it was, but it works now.

Thanks :)

**Comment by Calcyfer** [comment]
Good to hear you got it working. Happy streaming!

**Comment by Cowpie321** [comment]
I know this topic is older, but my issue is close to the same, I cant seem to stream from outside my own house.. all the ports are opened and everything. Wondering if the office im in has a firewall of somesort on the internet. any way to check that on a chrome book?

**Comment by Jorys-Paulin** [comment]
Hey @AgentT-mo, if your issue is resolved then you can close it, otherwise we'll be here to help!

**Comment by AgentT-mo** [comment]
My issue got resolved, but this I didn't open this one , I just commented, so I can't close it

**Comment by Jorys-Paulin** [comment]
Ho, my mistake. Happy to see yours got solved! :)

**Comment by Jorys-Paulin** [comment]
@cordelljones Is your issue resolved? If so, you can close this issue, otherwise we'll be here to help!

**Comment by Goobstank** [comment]
I have this exact issue... I am using a win 8.1 laptop to connect to a win 7 pc, everything is forwarded correctly... Both on my router and firewall and on both computers jic.  GE version 3.12.0.84 I can see my games and launch them. I am using CRD to look at the remote pc. 
This is end of the console log right as it kicks back to the games screen. 
[messages.js, handleMessage] Message data:  ProgressMsg: Starting RTSP handshake...
messages.js:35 [messages.js, handleMessage] Message data:  Starting RTSP handshakefailed
messages.js:35 [messages.js, handleMessage] Message data:  streamTerminated

**Comment by Jorys-Paulin** [comment]
@Goobstank Try reinstalling everything, when it comes to theses errors we can't know exactly what happens because of the error handling :/

**Comment by Goobstank** [comment]
That worked thank you! now the only issue is its choppy AF... still better than CRD or TV though

**Comment by Jorys-Paulin** [comment]
@cordelljones Make sure you use high end WiFi or Ethernet between your computers.
