### ISSUE TITLE
Mouse scroll wheel not working

### ISSUE THREAD

**Issue by kagenokurei** [moonlight-stream/moonlight-chrome#229]
Using the Chrome extension on an MBP running macOS Sierra. My mouse is a Logitech G602. Host machine is running Windows 10 Creator's Update(not in any Insider ring). Host is using latest GeForce experience and GPU drivers at time of posting.

Mouse works fine in macOS. Also works fine when using MS Remote Desktop and TeamViewer 12. When streaming via Moonlight, I have tested at least the 3 primary mouse buttons(left, right, middle) to be working(haven't tested other buttons, as I don't use them much). Scrolling using the wheel, however, does not work. Scrolling via the MBP touchpad doesn't work either.

This seems to have started after the update to Win10 Creator's Update.

**Comment by mtsanderson** [comment]
I have the same issue as @kagenokurei. Attempting from an iMac running macOS Sierra -> Windows 10 host (no creator's update installed). Chrome version: 58.0.3029.81.

Things worked correctly yesterday, but now when using the Chrome extension, I don't have scroll wheel functionality on the host. Using Windows native RDP/Chrome remote desktop, scrolling works correctly.

Left/right/middle clicks still work, it is just scrolling that seems to be the issue. I'm wondering if perhaps Chrome updated on me and caused the issue (nothing else has changed).

I'd be happy to provide any extra info necessary.

**Comment by awakun** [comment]
Having the same issue going from Win10 remote machine to Win10 host running the latest chrome extension 0.63. Chrome version 58.0.3029.81.

**Comment by cemarriott** [comment]
Also having this issue now. Client is macOS Sierra, the host is Windows 10 (running the latest version, Creator's Update). Chrome build 58.0.3029.81.

**Comment by TheNferno** [comment]
Same issue is some games, The Division to name one

Windows 10 Moonlight 0.63 Chrome 58.0.3029.81

**Comment by slyh** [comment]
I think the problem has gone by updating Chrome to 58.0.3029.96.

https://chromium.googlesource.com/chromium/src/+/4c3e5bb200dfdf8c275de7b6d4a6dfc80cdb1ec3
