### ISSUE TITLE
More than one client gamestream

### ISSUE THREAD

**Issue by SpiderManMan** [moonlight-stream/moonlight-chrome#230]
Is it possible to stream to two devices or more at once? Or does someone have a work around to make this possible?

**Comment by Jorys-Paulin** [comment]
Currently, Geforce experience doesn't support multiple clients at once (at least I don't think so). Having multiple clients active at once (with separated games) would require either multiple instances of Geforce experience and two monitors or have a custom build that supports that feature.
In the meantime, it's not possible yet.

**Comment by jacobmix** [comment]
Think he means streaming one game to two other people. So you could play a game with three players.
Tho getting controller working for both host, and client at the same time would be best first i think.
(Host controllers don't work if client uses one. Workaround only takes away controller input from client.)
Something like this would be cool tho. I used to use moonlight to play OpenGL games.
So i don't use it much anymore now that it's officially supported.
The ability to stream to multiple people would be sweet, and i'd use moonlight a lot more tho.
(Playing online with multiple people in local only games)

**Comment by Jorys-Paulin** [comment]
So basically, Nvidia Share but integrated to moonlight? You could connect to the host via moonlight and then activate gameshare from the host itself. I might work, but I can't confirm that.
