### ISSUE TITLE
Any hope for password protection in the future?

### ISSUE THREAD

**Issue by minnux** [moonlight-stream/moonlight-chrome#233]
Just what the title says. I share a PC and wanted to have some kind of password protection before accessing the remote computer.

**Comment by Jorys-Paulin** [comment]
This feature would be a Geforce experience one. Expected the pairing code, no password is requested in the streaming process

**Comment by Alfagun74** [comment]
damn i cant get shit in detroit, anyone can play on my computer now

**Comment by Alfagun74** [comment]
nevermind it asks your for a 4 digit code before pairing your device
