### ISSUE TITLE
Extension won't install on ARM Chromebook

### ISSUE THREAD

**Issue by mrrcollins** [moonlight-stream/moonlight-chrome#234]
I have an Asus Chromebook Flip (C100) and when I drag the extension over to install it, nothing every happens. On my laptop I get the *Install App* dialog, so I'm assuming I'm doing the dragging right. :-)

Is the extension not compatible with ARM based Chromebooks?

**Comment by Jorys-Paulin** [comment]
After you clicked on the `Install App` dialog, moonlight should be in your Chrome apps. Try accessing it via `chrome://apps` or `chrome://extensions`
