### ISSUE TITLE
Bandwidth setting is not remembered

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#236]
As the issue states when a user changes the bandwidth to a desired number, that number resets to the default when the app is restarted. for example, streaming at 1080p 60 FPS the default bandwidth is 20 mbps, if a user were to change that number to 5 mbps because of their connection, they would have to do this each and every time the app is closed and it would reset back to 20 mbps. @raidancampbell @cgutman this has been happening for a bit now, (I have just neglected to report on it until now) any ideas?

**Comment by cgutman** [comment]
Fixed
