### ISSUE TITLE
Windows Explorer Crashes

### ISSUE THREAD

**Issue by Krazon** [moonlight-stream/moonlight-chrome#238]
Everytime I try to start a game my explorer crashes and I have to restart the PC. So Moonlight is completly broken for me.
Can anyone help me?

EDIT: Restarting the Explorer does not work.

**Comment by Jorys-Paulin** [comment]
Your windows explorer just quits out? Does it append on the host (the one with GeForce) or the client (the one with moonlight)? Does it also make the bottom bar disappear?

**Comment by Krazon** [comment]
It only happens on the host side. And as far as I remember the Taskbar does not disappear but if I clicked something nothing happened.
I always had to hold down the power button of my PC too shut it down.

Since one of the latest updates I dont have this problem anymore (totally forgot about my post here).

I use Moonlight to play with my cousin over the internet and now that the explorer crash problem got fixed somehow we got a new problem. My cousin can hear himself all the time while we play over the moonlight stream.
We use Discord to communicate and before that explorer crash problem he never heard himself and now he does which really annoys him.

**Comment by Jorys-Paulin** [comment]
Since GameStream captures host audio to send it to the client, the client might send it back to the host thanks to discord, making the sound loop

**Comment by Krazon** [comment]
Yeah, the thing is we use moonlight for about 1 and a half year now and my cousin never heard himself over my stream. (we always used discord while streaming).

What I also don't understand is if I got Spotify running before we launch the stream he can't hear anything of it but if start/restart spotify while we are streaming he can hear it...so why does moonlight not stream the host audio all the time? Why can't it just focus on the game sound or something?

**Comment by Krazon** [comment]
Of course he had the Host Audio enabled :D what I meant was why does it not stream all the host sound. Why do I have to restart Spotify so he can hear it aswell?

He has set the stream settings too 9MBit/s at 1080p 30fps (even tho I play in 1440p).
The way we stream might also be a problem (coming to it in a sec).

I remember that if I added my desktop as a game to the NVIDIA Shield Games list and he started the stream he also heard himself. We figuered a way out to get the stream to not change my resolution (1440p) and that he does not hear himself. 

The way we stream now is that I add a game ex. RimWorld to the list which he can start then without changing my resolution. Before the explorer crash problem we always used it this way and we never had a problem.
But now he hears himself even if we stream this way.

My Specs:
GTX1080
i7-4790K
Windows 10
16GB DDR3
All drivers are up-to-date

His Specs (not entirely sure):
GTX980
i7-6700K
Windows 10
32 GB DDR4
Probably not all drivers up-to-date (not sure why but he rarly updates his graphics driver and I guess some other drivers aswell)

**Comment by Jorys-Paulin** [comment]
- When launching games, Geforce could be forwarding only the game's sounds to the client, but if your friend can hear himself then Geforce must be picking the master audio, not only the one from the game in question
- Non-updated drivers are the cause of big issues. I suggest you ask your friend to update to the same version issue, in order to avoid compatibility issues

**Comment by Krazon** [comment]
He is on vactation at the moment so I'll report back if he has updated his drivers.

Another thing is since the latest GeForce Experience Update I always have to re-enable the Share Overlay after every restart of my PC but somehow even if I do not enable it I can see the Share Overlay's FPS Counter.
The Moonlight Stream seems to be not affected by that problem tho.

In the past months I had to completely uninstall my Graphics driver because somehow it got "destroyed" after I updated it. And GeForce Experience also has problems here and there. I always wonder what the heck is nvidia doing with their drivers and gfe.

**Comment by Jorys-Paulin** [comment]
Try completely uninstalling any graphical drivers, should fix it. Remains of programs can cause this sometimes

**Comment by Krazon** [comment]
I'll stay with my currently installed stuff since my system is running really stable now (besides GFE's Overlay)

**Comment by Jorys-Paulin** [comment]
#265 This might help regarding to discord use with moonlight
