### ISSUE TITLE
Very Loose Mouse Controls

### ISSUE THREAD

**Issue by pokeguru87** [moonlight-stream/moonlight-chrome#239]
I recently updated to 0.7.1 from 0.6.3 and the Mouse controls have become very loose, floaty even. Basically  I'll move my mouse and then stop, yet it will still continue to move for several seconds. It is also very sluggish, it doesn't match normal mouse movement and tempo like it used to. It seems almost like it is halving my polling rate and queuing up all movements and sending them like that. Makes it very difficult to play anything with a mouse.

**Comment by Neavend** [comment]
I seem to have the same issues, although when I plug out my external mouse and use the regular mouse pad I have absolutely no issue.

**Comment by cgutman** [comment]
Can you try this build to see if it fixes your mouse lag issues? https://drive.google.com/open?id=0B_5O1xNt8Q9lSVFXaDBwX3N5Q1E

**Comment by fupuchu** [comment]
Hi cgutman,

I too have the same issue, and the build you linked fixed it. 👍
