### ISSUE TITLE
Cache NvHTTP's appList

### ISSUE THREAD

**Issue by raidancampbell** [moonlight-stream/moonlight-chrome#24]
The `getAppById` and `getAppByName` functions both call `getAppList`.  I don't see how this is necessary: I think instead a cached copy of the appList should be kept around.

The change is straightforward: on each call to `getAppById` or `getAppByName`, it checks if the variable is populated, if it's not then the variable is filled by a call to `getAppList`.  Once we know the variable is filled, we continue with the logic of the function.

I think if the user really wants to add a new game, and see it appear in moonlight, without restarting moonlight, it's reasonable to expect them to hit the `Retrieve App List` button.  The `Retrieve App List` button should make an actual API call to `getAppList`.

**Comment by cgutman** [comment]
The way we do this on other clients is that we keep a cached copy of the app list XML which we load immediately when the user selects a PC. In the background, we fetch an updated app list, update the cache, then merge the results with the cached copy displayed in the UI. We fetch again in the background every 30 seconds.

**Comment by raidancampbell** [comment]
caching to disk (chrome storage) is apparently what should be done.

**Comment by dead** [comment]
It's really need to cache the application list in disk? It don't take that much time to load... A 30s refresh should be enough.

**Comment by raidancampbell** [comment]
The bits of this that @dead didn't do earlier are encompassed by #71
