### ISSUE TITLE
Unable to pair 0.7.1

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-chrome#240]
there seems to be se some issues with pairing the latest version.
The code prompt takes alot of time to show up on the PC and once I enter it...in moonlight it still shows pairing with please enter the code bla bla...doesn't seem to do anything.

**Comment by Jorys-Paulin** [comment]
Could you give us the app's logs? You can get them by going into `Examine views: index.html` in `chrome://extensions/`  then selecting the "Console" tab and giving us back what's shown.

**Comment by pokeguru87** [comment]
I am having this same exact issue. Also, something I noticed, after the first connection attempt I have to restart the Extension (close window and reopen it) to get the Code Prompt to show up again. I've attached my logs.
[kneneiigihpjinpiaoidjolckmeaogdh-1496368343583.zip](https://github.com/moonlight-stream/moonlight-chrome/files/1046475/kneneiigihpjinpiaoidjolckmeaogdh-1496368343583.zip)

**Comment by Jorys-Paulin** [comment]
Have you checked that you have the latest version of Geforce Experience and Moonlight. The logs don't show any errors at first glance. We might need to inspect the console to see if there's errors and track them down to the source

**Comment by pokeguru87** [comment]
Yes, I have the latest Geforce Experience, Nvidia Driver and I am using Moonlight 0.7.1. If it helps, I had originally paired to this machine with an older version before, but the other night when Nvidia's servers were having issues (before I realized that was the case), I tried removing and adding it back, and this is what I've gotten. Also, it isn't apparent by the log but these computers are not on the same network. It is connecting over the web. I have the appropriate ports forwarded to the machine and connect to a DDNS address. I changed it in the log for obvious reasons to the machine name of the computer instead (MALI-DEI). I wouldn't think this would be an issue since it worked before, but I figure I should mention it.

**Comment by pokeguru87** [comment]
So, I tried from another computer that was on the same LAN and I had the same issue. The pairing window takes a while to appear and then after putting in the code it eventually says it fails. I uninstalled 0.7.1 and went back to 0.7.0 and I am able to pair and stream just fine. I can also upgrade from 0.7.0 to 0.7.1 after it is paired, and I am still able to stream (although if I remove the pairing, I am still unable to pair with 0.7.1).

**Comment by Jorys-Paulin** [comment]
According to the commits, only the `moonlight common-c` was updated : https://github.com/moonlight-stream/moonlight-chrome/commit/c0d9ae87f233f3c74da0fb694a026da964decb2e
This might be because or that. Otherwise, I has to be a bug with the pairing cache

**Comment by pokeguru87** [comment]
Ya, I was looking at the commit and it didn't seem to be pairing related at all, which has me a bit baffled. Let me know if there is anything else you need from me. Otherwise I have a psudo-workaround, although it is a little bit of a pain.

**Comment by Jorys-Paulin** [comment]
So there's only one possible reason remaining : the paring system is making that bug. I won't be able to look at it know (tonight), being on mobile, but I'll look at it later. Something you can do to help me is to make steps to hopefully reproduce the error and track it down

**Comment by Jorys-Paulin** [comment]
Speaking of your workaround, what is it about ?

**Comment by pokeguru87** [comment]
The workaround is to pair with 0.7.0 and then upgrade to 0.7.1 after I've paired.

The steps to reproduce is very simple. All I do is try to pair with 0.7.1. Doesn't matter if it is an auto-detect computer or one that I add manually. I try to pair the window takes a while to pop up and then after putting in the code the pop up in Moonlight stays open for a while and eventually says that Pairing failed. I am on Windows 10 Pro x64 Creator's Update (On both Host and Guest systems) using Chrome 59.0.3071.82 (Official Build) beta (64-bit). All computers test on are running Geforce Experience 3.6.0.74 with the 382.33 Driver.

**Comment by Jorys-Paulin** [comment]
I honestly don't know why it does this, since the only difference between 0.7.0 and 0.7.1 is the commit we mentionned earlier. Weird ...

**Comment by Jorys-Paulin** [comment]
In the meantime, try to compile your own build, maybe it's just because the official build is corrupted or something

**Comment by pokeguru87** [comment]
I compiled at commit e4bec4133dd65f06c18c04a11c31891a2e006d7e and was able to pair and stream just fine, even over the web. I compiled using "pepper_49" of the NaCL SDK, if that makes a

**Comment by Jorys-Paulin** [comment]
So that would mean that the official build was not compiled properly? Did you installed the extension as an unpacked one or as a fully packed one?

**Comment by pokeguru87** [comment]
I just followed the instructions in the README, so Unpacked. I'm not even sure how to create the packed version could point me in the direction of instructions on how to do so, I'll test that as well. I tried to do the "Pack Extension" in the Extensions part of Chrome, but it gives me a Pack Extension Error "Failed to output private key."

**Comment by Jorys-Paulin** [comment]
For me, when I tried to output the extension folder, in `/www/moonlight-chrome`, Chrome created a `/www/moonlight-chrome.pem` file wich I used in the private key field. It asked to overwrite the unpacked extension and then gave me the path of the fully packed one, located for me at `/www/moonlight-chrome.crx`

**Comment by pokeguru87** [comment]
Well, funny, the problem was I had the repository in folder directly on my C: drive which is why it was failing to pack. Chrome couldn't write the Key directly C:. I put it into a sub folder and it worked just fine. I tried it out and I was able to pair just like normal. No issues.

**Comment by Jorys-Paulin** [comment]
Did you make sure that you are using your packed extension and not the unpacked one? If so, we cloud conclude that it was the official build that caused the problem, for whatever reason

**Comment by pokeguru87** [comment]
Yes, I made sure to remote the Unpacked Version from Chrome, and then I installed installed the Packed CRX that Chrome generated like I did with the official build (just dragging it into Chrome's Extensions screen).

**Comment by Jorys-Paulin** [comment]
So I think we can conclude that the issue came from the official build. We don't know why, but at least making our own build works.

**Comment by pokeguru87** [comment]
I just installed 0.7.2 and everything paired as it should. So something about the 0.7.1 build was just borked I guess.
