### ISSUE TITLE
Host Audio

### ISSUE THREAD

**Issue by StratusHunter** [moonlight-stream/moonlight-chrome#242]
From a bit of research I have a feeling this is an Nvidia issue but I wanted to see if this is a bug or if you guys know of a workaround or solution.

Our setup is a normal host/client using msdt.exe to stream the screen however the client has a Skype call open with the host so we can chat while playing. Until today whenever the client received the host audio all audio from the Skype call was filtered out so my friend could just hear me and the game audio. Now he can also hear the audio from his side of the Skype call creating a delayed echo. Is there any way to not send the Skype audio from the host to the client through moonlight? Thanks for your time.

Client: Moonlight Chrome 0.71
Host: Geforce Experience 3.6.0.74, GTX 970 Geforce 382.05

**Comment by Fire-Dragon-DoL** [comment]
Facing the same issue, for now I solved using another PC, but it's still terrible. My guess is that nvidia is streaming all the audio devices instead of just the "select as default" one

**Comment by ShadowCX** [comment]
I second this. As of now the current version of GeForce Experience has just become completely useless. It doesnt seem to be an issue of Moonlight though, as using the old version will produce the exact same problem. So fixing this issue will require work from Nvidia and not the Moonlight Devs, making this entire thread pointless I fear.

**Comment by StratusHunter** [comment]
It was more a long shot that they might know if you rename xyz.dll to xyz.dll.old that would fix it seeing as they have had their hands in the Geforce code.

I'll close it :)
