### ISSUE TITLE
Hardware decoding is unavailable. Falling back to default CPU decoding.

### ISSUE THREAD

**Issue by Frostguy361** [moonlight-stream/moonlight-chrome#243]
I get this message when I try to connect to my gaming pc using moonlight, "Hardware decoding is unavailable. Falling back to default CPU decoding." And, then it shows my gaming pc's screen and when I try to move the mouse around it is very laggy. The mouse will move slowly then shoot in the direction I am trying to go. I can provide any logs or information you need. My laptop has Windows Vista with Chrome Version 49.0.2623.112 m. My gaming PC has Windows 7 Professional and Chrome Version 58.0.3029.110 (64-bit) not that the chrome version of my gaming PC would matter I just thought I would include it. I would really love to use this program with my laptop, if you could assist me in troubleshooting this issue I would really appreciate it.
![moonlight_issue](https://cloud.githubusercontent.com/assets/10803230/26029634/d239bb92-3807-11e7-9591-c421c21bffdc.png)

**Comment by jacobmix** [comment]
Can you show what it says when you go to chrome://gpu/ ?

**Comment by Frostguy361** [comment]
![chromegpu1](https://cloud.githubusercontent.com/assets/10803230/26030226/9cc9dc18-381a-11e7-822e-94acc06a28ec.png)
![chromegpu2](https://cloud.githubusercontent.com/assets/10803230/26030228/a419a386-381a-11e7-8dbc-3353651b8325.png)
![chromegpu3](https://cloud.githubusercontent.com/assets/10803230/26030229/a7454b32-381a-11e7-8068-ccbecff07c9f.png)
![chromegpu4](https://cloud.githubusercontent.com/assets/10803230/26030231/aa45a444-381a-11e7-91a5-730c400093b5.png)
![chromegpu5](https://cloud.githubusercontent.com/assets/10803230/26030234/ad3adaa2-381a-11e7-9988-960d0ab26276.png)

**Comment by Frostguy361** [comment]
Could it be because I am on an older version of chrome? I can't update it because I am on Windows Vista.

**Comment by jacobmix** [comment]
Might be it. You could try to duel boot with Windows 7 if you can, and test it.
Probably too much trouble tho.

**Comment by cemarriott** [comment]
Is there some reason you are still on Vista? It does not receive updates anymore (security or otherwise). Is your graphics driver up to date? Vista may not receive the latest drivers for cards anymore either, not sure if Nvidia still supports it.

**Comment by Frostguy361** [comment]
Yes. I am still on Vista because I am a poor beaner and OS's cost money. My laptop is 10 years old. It is not worth putting any money into. When this one stops working I will get another one. Right now it is functional. It could run some pretty demanding games on low settings. It was a great laptop when I got it. My graphics driver is up to date.

**Comment by Frostguy361** [comment]
What are the requirements of the non-gaming computer?

**Comment by cgutman** [comment]
I seem to remember reading that Chrome won't use hardware-accelerated H.264 decoding on Vista or earlier.
