### ISSUE TITLE
Huge Mouse lag after updating to GeForce Experience 3.6.0.74

### ISSUE THREAD

**Issue by maximilianoe** [moonlight-stream/moonlight-chrome#244]
I was running Geforce Experience 2.11.4 and Moonlight Chrome 0.6.3 without any issues. 
After updating to the Win10 Creators Update & GeForce Experience (to 3.6.0.74) on the host machine there is now an immense mouse lag, almost 1 second.
Updating to Moonlight Chrome 0.7.1 and also disabling enhanced mouse precision on both machines didn't help.

Btw. 0.7.1 is resetting the Bandwidth setting after every restart.

**Comment by Cowpie321** [comment]
If you have razer synapse open, close it. Pretty much removed it fully.

**Comment by maximilianoe** [comment]
I had Razer Synapse running but unfortunately closing it didn't improve the lag at all.

**Comment by Pengen** [comment]
I have the same problem with huge mouse lag. When I tested with a generic mouse on the client computer the lag disappeared, so seems to have something to do with my Steelseries Rival 300 gaming mouse. Worked flawless before GFE 3.6.0.74

**Comment by airdjing** [comment]
I use razer mouse too.. I have same issue
Another mouse is correctly work well
Problem on only razer mouse

**Comment by maximilianoe** [comment]
I'm using a Lioncast mouse on the client computer so it seems like many mouse manufacturers are affected.

**Comment by cgutman** [comment]
Can you folks try this build to see if it fixes your mouse lag? https://drive.google.com/open?id=0B_5O1xNt8Q9lSVFXaDBwX3N5Q1E

**Comment by maximilianoe** [comment]
@cgutman The input lag is reduced to previous levels with this test build, so basically perfect. However with 2160p 60 FPS the mouse pointer is very choppy, looks like it gets refreshed only 15 times per second instead of 60. 2160p 30 FPS works fine though.

**Comment by Cowpie321** [comment]
@cgutman at 1080 60FPS it works perfectly! I was playing GTA V and it had some stutter but the mouse input lag was gone.

**Comment by maximilianoe** [comment]
Input lag reduced/fixed with 0.7.3.
