### ISSUE TITLE
Resolution issues and Input latency (PC -> mac)

### ISSUE THREAD

**Issue by Marctraider** [moonlight-stream/moonlight-chrome#249]
Hi there! First of all my appreciation for this wonderful piece of software. I have yet to find a better streaming service than this, also my thanks to Nvidia I guess, lol.

I have some issues though.

There is noticable input latency when streaming, if i'd had to guess it is almost 200/300ms give or take. Connection to my host PC Windows 7 is 1ms~ of latency when pinging, and 200+Mbit sustained with 5GHz AC.
It seems to be even worse with using an external mouse, especially ones that have high polling rates (1000hz). Dropping to 125hz fixes THAT particular issue, but it is still similar input latency to the trackpad. Its workable, but I dont think there should be as much latency.

With Geforce 2.x Experience, I am unable to use 2880x1800 natively, even when resolution is set to this at the host level. With Geforce Experience 3.x I am able to do so, however for some reason pixels are not aligned 1:1 and there is still scaling being applied for some awkward reason. If both host and client are set to 2880x1800 this shouldn't be happening right?
(I'm editing index.html to make this work)
I'm honestly not sure why there is no client option for manual resolution setting too, I mean.. Nobody wants to play scaled and/or with black bars. I know that you guys want to keep the interface clean, but there is more in the world than standard 16:9 aspect ratio monitors, not to mention people having 21:9 etc.

Other than that, everything seem to work flawlessly without hickups.
OH, one more thing. Apparently the host still plays though speakers, is there any way to only pass sound through connected client?

Thanks!

Edit: I'm not sure if this is normal, but CPU usage on the client (MacOS) is around 150/170% and is getting pretty hot. (I'm not sure how MacOS handles usage these days, i suppose 400% is all logical cores fully maxed)

Isn't the idea behind client side hardware decoding to alleviate the CPU and offload most to the GPU? Or is this cpu usage unavoidable?

**Comment by yu42hit** [comment]
Same here. I'm starting to give up on moonlight. There seems to be no way to fix this no matter what. Even on the mobile clients.

**Comment by cgutman** [comment]
OK, let's start:

> There is noticable input latency when streaming

Yes, we know that can be the case on some hardware.

Chrome's hardware video decoding has been more resource-intensive and higher latency than expected when we first started work. Sometime in the early Chrome 50s, they did some significant rework to reduce power usage but this seems to have caused increased latency and actually increased CPU usage on some platforms when accessing the video decoding stack from Chrome Apps.

We will probably need to bite the bullet and bring up separate native clients on Windows, Mac, and Linux (hopefully from a unified codebase, maybe with Qt or something). That's on my plate after I finish up some Moonlight Android work.

In the meantime, you can try streaming lower resolutions with the Java client if you find Chrome doesn't perform well on your hardware/OS/drivers/GPU/whatever.

> With Geforce 2.x Experience, I am unable to use 2880x1800 natively, even when resolution is set to this at the host level. With Geforce Experience 3.x I am able to do so, however for some reason pixels are not aligned 1:1 and there is still scaling being applied for some awkward reason. If both host and client are set to 2880x1800 this shouldn't be happening right?
> (I'm editing index.html to make this work)
> I'm honestly not sure why there is no client option for manual resolution setting too, I mean.. Nobody wants to play scaled and/or with black bars. I know that you guys want to keep the interface clean, but there is more in the world than standard 16:9 aspect ratio monitors, not to mention people having 21:9 etc.

You've just described the reason there's no option for manual resolution setting - it doesn't work correctly :)

GeForce Experience only supports certain 16:9 resolutions correctly, so that's all we expose.

> OH, one more thing. Apparently the host still plays though speakers, is there any way to only pass sound through connected client?

This is a bug in Moonlight Chrome. I have seen it myself but haven't tracked it down yet.

> Edit: I'm not sure if this is normal, but CPU usage on the client (MacOS) is around 150/170% and is getting pretty hot. (I'm not sure how MacOS handles usage these days, i suppose 400% is all logical cores fully maxed)
> 
> Isn't the idea behind client side hardware decoding to alleviate the CPU and offload most to the GPU? Or is this cpu usage unavoidable?

Covered this in the first point.

**Comment by Marctraider** [comment]
Thanks for the clarification, sorry If you felt this was some harsh critique, I just mainly wanted to know if everything was right on my end.

I must say even at 2880x1800 it is not actually noticable unless you move static Windows with fixed pixels. I dont mind some small borders I guess, as long as its 1:1 pixels. I'll try and discover the most favorable 16:9 res for 2880x1800 and report back.

As for the input latency, it was just a bit disappointing to see as the rest of the 'mechanism' of this type of streaming is as far as I know unheard of, and considering my PC is rather powerful (5Ghz Kaby + DDR4 3600 + 1070GTX). 

If someone can tell me a better alternative to high quality streaming on my Mac I'm all ears lol.

Can you suggest me some 'older' Chrome clients to experiment with which might possibly have lower latency at the expense of higher load?

I have not yet gotten the Java version to work, Think i simply got Connection refused errors.

**Comment by Sawyer007** [comment]
I can also confirm the mouse input delay on the chrome app. It starts all great responsive and after a minute or so the mouse starts to feel less and less responsive. I would guess about 100ms delay on top of what I started with.

The java app doesn't have this problem. It may be a bit less responsive to start with but its rock stable the whole gaming session.

**Comment by Marctraider** [comment]
Sounds like your issue is different. My chome/mac + pc combo is simply constant input lag without fluctuations.

**Comment by Sawyer007** [comment]
dunno how to describe this better. For example I move the mouse to left and it will react about 100-200ms later then it was supposed to.  Usually I would just put it down to streaming and trans-coding delay but then it wouldnt start as resposnive as you would actually sit in front of the host PC itself.

Or if you game infront of your TV which is set to gaming mode. All is great and responsive. Once you set it to movie mode to enhance the picture it adds about  200-300ms delay and the mouse isnt responsive anymore.

Unlocking the mouse from the screen may fix this for another 30 seconds. Then its back to the unresponsive movement.

Im hard wired but Im playing over the internet. A fiber optic connection with 5ms ping time.

**Comment by Marctraider** [comment]
Newest version 0.7.2 drastically reduces input latency, very good work! i have only tried with my built-in trackpad on my macbook which has inherent latency to begin with, but its a dramatic improvement.

Now just for custom res support (at least somehow manage 1:1 pixels without deformations) and this streaming software would be absolutely perfect. I'm afraid however it might be a limitation on Nvidia Shield side in which case it will be impossible?

My appreciations either way.

**Comment by Sawyer007** [comment]
How important is it to keep chrome up to date? I just noticed that I had it on 58 something version and when I clicked the about tab it started to update to 59.something.

**Comment by Marctraider** [comment]
I found out that while using Steam in-home streamer, the same pixel misalignment happens trying to stream 2880x1800 on host to MBP.

It appears it seems to be MacOS related as apparently the resolution runs on some weird semi 1680x1050 and scales the content up. Im not exactly sure how it works but eithet way MacOS makes both streaming solutions believe that the Mac is running on 1650x1050 rather than native. Meaning crap will still get up/downscaled accordingly.

After trying a random tool like SwitchResX and manually put res to native 2880, my pixels on steam in-home are exactly 1:1 aligned.

I'm almost 100% sure the same will apply to moonlight chrome. Perhaps the devs know more of this weird MBP behavior?

For the time being ill stick with steam, as sadly it is way less demanding for cpu/gpu and still significantly lower latency.

Moonlight still has a long way to go...

**Comment by cgutman** [comment]
Chrome video decoding performance on Mac is pretty poor for our video stream, so it's not surprising that the performance isn't great.

If Steam IHS works better, then use it instead. Moonlight for PCs has always been a lesser focus compared to the much better Android, iOS, and Embedded clients we have, because Steam IHS is already pretty good for streaming to a PC.

I have some more issues to take care of with Moonlight for Android, but I do plan to come back to PC and figure out how to get good decoding performance on all OSes. I suspect we'll probably have to write our own decoding backend like Steam IHS has.

**Comment by cgutman** [comment]
@Marctraider Can you try this build to see if it fixes your mouse lag issue with high polling rate mice?

https://drive.google.com/open?id=0B_5O1xNt8Q9lSVFXaDBwX3N5Q1E

**Comment by Sawyer007** [comment]
After playing the whole night with Parsec.tv I can now confirm that this is hands down the best software for windows as of now. It even beats Steam on all fronts.

I also didnt know that Windows 10 creators update gaming mode feature which is turned on by default forces triple buffering on all the games which increases the input delay as per there FAQ.

This doesn't mean I dont want a native Moonlight Windows APP. Maybe even with h265 support.

**Comment by Marctraider** [comment]
@cgutman If this is the same as version 0.7.3, I'm sorry to say the program refuses to connect to my host completely. I cant find a difference in config, same versions running, same IP's.

@Sawyer007 That is what's often said about new programs, until the flaws start to appear for users that require something other than the general features.

For one, it requires Windows 8+ for the host (Which basically means you're forced  to get your ass on the worst Windows of all time: 10) 

Secondly, do custom resolutions work in this program at all? Again a streaming service which claims it can do smooth streaming at 1080p@60 but they all refuse to support custom resolutions for some awkward reason, as it works fine with Steam In-home and Moonlight if you know how to do it.
