### ISSUE TITLE
GFE 3.6.0.74- troubles with games on opengl (DOOM 4; soma and etc)

### ISSUE THREAD

**Issue by rampage47** [moonlight-stream/moonlight-chrome#252]
Hi. I have some troubles after gfe update (Windows 10x64 (server); GFE 3.6.0.74)

1) troubles with opengl (vulcan) games (Doom 4; Soma) . if i use fullscreen mode, then i will see black screen. Games in window mode works fine

2) witcher 3 (steam version) Invisible cursor; Cant change any buttons (gog version works fine)

**Comment by airdjing** [comment]
Same problem here on chrome ver

**Comment by Jorys-Paulin** [comment]
Are you running the latest versions of all programs you use?
- [ ] Moonlight
- [ ] Geforce experience
- [ ] The latest drivers
- [ ] Your games

**Comment by rampage47** [comment]
yes. Do you try to stream opengl games?

**Comment by Jorys-Paulin** [comment]
Are they showing up in GeForce Experience?

**Comment by rampage47** [comment]
I can play in window mode (full screen mode - black screen with sounds)

**Comment by Jorys-Paulin** [comment]
No, what I meant was: Does the concerned games show up in the GeForce experience app?

**Comment by airdjing** [comment]
I have same problem
Doom 4 can't run on full screen mode (black screen) only can see windowed mode
opengl mode and vulcan mode are same problem.
I can see Doom 4 and Doom 4 VULCAN MODE game in GFE 

This is My system

- Server
Windows 10 x64
NVIDIA 384.76 Display Adapter Driver (980ti)
GFE 3.7.0

- Client
Windows 10 x64
Intel v20.19.15.4531 (HD 5300)
Moonlight v0.7.3

**Comment by Jorys-Paulin** [comment]
@airdjing And does Doom shows up in GFE? If not it might be because it's not supported.

**Comment by airdjing** [comment]
@Jorys-Paulin Yes I can see Doom 4 and Doom 4 VULCAN MODE game in GFE game menu and moonlight menu

**Comment by Jorys-Paulin** [comment]
@airdjing:
- Can you see in Settings/Shield menu for something?
- Can you make screenshots or screencasts to help us?
