### ISSUE TITLE
Moonlight downscale graphical settings/quality to minimum

### ISSUE THREAD

**Issue by jaydeelive01** [moonlight-stream/moonlight-chrome#253]
Hello !

I am using Moonlight on Chrome on my Macbook pro Late 2011 to stream my desktop PC with a GTX 960 4GB. 

 I have an issue that seem linked to "Game Optimization" setting in regular Shield devices. Whenever I start a game (either through MoonLight Interface or Steam) for streaming, it seems that it downscale graphical settings to the minimum (except for FPS and resolution). This issue occur in most game I play (Fallout 4, Witcher 3, Skyrim). 

I found that this can also occur on regular Shield devices when the setting "Optimize Game" is checked (it is optionnal, see here : https://forums.geforce.com/default/topic/971499/gamestream/gamestream-settings-game-optimization-problem-/)

However, I cannot find such setting in Moonlight... Any solutions, except than streaming my full desktop then launching the game ?

Thanks

**Comment by Jorys-Paulin** [comment]
If the option is done via the shield and not the GeForce app, then moonlight could do the same. This would just require an implementation. Until then, you can try to launch your games from desktop

**Comment by jaydeelive01** [comment]
Thanks.

However, is this problem known ? I mean, if this is a systematic implementaion of the procedure, I should not be the only one having this issue.

Thanks
Jd

Envoyé de mon iPhone

Le 14 juin 2017 à 15:08, Paulin Jorys <notifications@github.com<mailto:notifications@github.com>> a écrit :


If the option is done via the shield and not the GeForce app, then moonlight could do the same. This would just require an implementation. Until then, you can try to launch your games from desktop

**Comment by Jorys-Paulin** [comment]
The only way to have this feature is to mimic how the shield asks the host, just like the Java client apparently does #262. This feature could easily be implemented by the developers via the https://github.com/moonlight-stream/moonlight-common repository used in booth versions

**Comment by cgutman** [comment]
@jaydeelive01 The change in settings depends on your GPU (since GeForce Experience is doing optimizations to better stream with your GPU). But you can use the workaround of streaming your whole desktop then streaming the game from there - https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop

Launching games from Steam Big Picture may also work.
