### ISSUE TITLE
Microstutter/lag on client side only

### ISSUE THREAD

**Issue by jaydeelive01** [moonlight-stream/moonlight-chrome#254]
Hello,

When I'm streaming my GTX 960 4GB from a MacBook Pro Late 2011 (HD3000 GPU) using Chrome Moonlight, I'm encountering microstutter on the client side only when I'm trying to stream at 60 FPS or 1080p. When I'm at 720p/30FPS, things seem more smooth. I also notice the Mac getting hot (fans are at max) when this occur. Also, sometimes (not each time I run moonlight), I get the message that hardware acceleration is not available and that it will use CPU decoding.

Could it be an overheating issue ? 
Thanks

**Comment by Jorys-Paulin** [comment]
Maybe your host (from where you stream from) is not powerful enough to properly run, encode and send the stream to your client (the MacBook, right?). Encoding is a task generally given to the CPU, so you might be bottlenecked by it.

**Comment by jaydeelive01** [comment]
So I ended up cooling the Macbook and it got rid of the microstutter.

I guess the problem was client-side instead of serverside.

Thanks :)

Le 25 juin 2017 à 05:38, Paulin Jorys <notifications@github.com<mailto:notifications@github.com>> a écrit :


Maybe your host (from where you stream from) is not powerful enough to properly run, encode and send the stream to your client (the MacBook, right?). Encoding is a task generally given to the CPU, so you might be bottlenecked by it.

**Comment by Jorys-Paulin** [comment]
De rien :)

**Comment by Jorys-Paulin** [comment]
Hey @jaydeelive01, is everything okay? If so you can close this issue, otherwise I'll be here to help :)
