### ISSUE TITLE
[FEATURE REQUEST] Set a speed at 2M for cable users

### ISSUE THREAD

**Issue by ppeltriaux** [moonlight-stream/moonlight-chrome#256]
Please make a 2M and 2.5M speed available for AU cable users.

**Comment by Jorys-Paulin** [comment]
Do you mean `2.5Gb`? Because you can set it to 2.5Mb by putting the slider way down
![2017-06-14_21h02_54](https://user-images.githubusercontent.com/5084309/27149778-fa706e5c-5144-11e7-925a-de22ae22f372.png)

**Comment by ppeltriaux** [comment]
No I mean 2 not 2.5 if possible?

**Comment by Jorys-Paulin** [comment]
Same thing, it can be a bit tricky but you can set it to `2Mbps`
