### ISSUE TITLE
Can't choice 1440p resolution

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-chrome#257]
Hi, is there any way to run the stream at 1440p ? Currently there's only 720p, 1080p and 4K. Thank you

**Comment by Jorys-Paulin** [comment]
Resolutions in Moonlight are hard-coded (https://github.com/moonlight-stream/moonlight-chrome/blob/master/index.html#L32) however adding more resolutions could resolve the problem for the client side. However, I don't know if Geforce Experience supports it.

**Comment by Marctraider** [comment]
So far no effort in trying to get a pure 1:1 native pixel resolution failed. It works, but somehow pixels are never aligned. This is by the way no encoding artifact.

MacOS Sierra as client btw.

**Comment by Jorys-Paulin** [comment]
I think that Moonlight won't properly support 1440p resolution as long a Geforce Experiences supports it. After all, Moonlight is just a client, a client that needs a server to have someone to talk to. The GUI client-side can however scale to 1440p if the client permits it

**Comment by kellabyte** [comment]
@Jorys-Paulin `1440p` is supported. It's moonlight that doesn't allow it. I've done ultra-wide resolutions by modifying the javascript in moonlight and it works just fine. Moonlight should make adding custom resolutions an option.

**Comment by Jorys-Paulin** [comment]
You could do a pull request for that.

**Comment by mmolad** [comment]
@kellabyte Could you describe where you made this update? I would do a PR and make the update.

**Comment by cgutman** [comment]
I think at this point enough people have asked that I'd accept a PR adding this, as long as it clearly states in the dropdown that it's an experimental option.
