### ISSUE TITLE
Steam Big Screen issue

### ISSUE THREAD

**Issue by CheeseSL** [moonlight-stream/moonlight-chrome#258]
Version 0.7.2 i'm still experiencing an issue with loading steam's big screen, it seems to be start working then close after a wave animation. Also couldn't see some of my installed games like Tekken 7 which i should start manually by adding the laucher.exe in GFe,
PS: this issue happened earlier in ver. 0.7.1, not from the begging but suddenly.

**Comment by Jorys-Paulin** [comment]
- Are your games like Tekken 7 launched through Steam? Do they use custom launcher after you start them from Steam? (Like GTAV with the Rockstar Social Club thing)
- What closes after the wave animation? Steam big picture, steam itself and/or the stream? Does the moonlight client also close?

**Comment by CheeseSL** [comment]
1) I can't see the games like Tekken 7, Dead Space 2 (both license) in a moonlight main menu, the only way i could start this games is if i manually add them in a GFe or start from the Steam Big Picture. They doesn't use custom laucher.
2) I launch Steam in a moonlight menu, then i see a wave animation of a Big Picture like it normally happens, after 2 seconds it closes and i see my PC's (host) desktop for a while, then it brings me back to a moonlight menu. There is no Steam icon in system tray on my PC (host) or any Steam activity in processes which means that Steam client just closes itself. Moonlight doesn't close.

Here is a video i made https://streamable.com/al8jo with my issue.

**Comment by Jorys-Paulin** [comment]
Have you tried to delete the extension completely? Maybe something got corrupted and caused the problem. Also, do you have the latest drivers and versions for all programs?

**Comment by CheeseSL** [comment]
Yes i've reinstalled it completely (version 0.7.2). GFe ver.  3.7.0.68, Nvidia drivers ver. 382.53, latest Steam. Same happens from my Android device and Moonlight app, i asked the friend of mine and he also has the same issue with Steam Big Picture. Maybe it caused by a new Steam update, check it please.

**Comment by Jorys-Paulin** [comment]
Well Steam big picture is just buggy. I can't test it though...

**Comment by CheeseSL** [comment]
For no reason somehow it works today, a lil bit in a different way as usual (know there is no wave animation at all and it brings me right in a library, all games works fine), i didn't update anything till that moment. Pretty dissapointing when you can't see a logical rationale for some processes but i'll take it. Thanks for help.
