### ISSUE TITLE
Configurable Moonlight Connection Port Numbers?

### ISSUE THREAD

**Issue by MatthewFrench** [moonlight-stream/moonlight-chrome#259]
Is there currently a way of setting the ports that Moonlight uses to connect?
I have my desktop working beautifully with Moonlight with ports forwarded to allow a remote connection. I have a second PC that I would like to be able to moonlight into on the same external IP as well. 
At that point you run into port conflicts. My router allows forwarding ports to different ports for an internal IP. If Moonlight supports changing the ports it uses to connect, that would allow me to remotely use multiple computers on a single IP for game streaming.
Does Moonlight have this functionality?

**Comment by rampage47** [comment]
https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Comment by MatthewFrench** [comment]
I feel like you didn't even read the question.
Unless you're telling me that if it doesn't exist in that bit of documentation, it is not possible.

**Comment by Jorys-Paulin** [comment]
What he means is that the ports used for Moonlight (https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet) are the same as Geforce Experience, and that (as of today) they cannot be modified from the Geforce app itself, nor from moonlight itself

**Comment by cgutman** [comment]
Unfortunately, Moonlight doesn't have this functionality right now.

**Comment by Jorys-Paulin** [comment]
@MatthewFrench You could use something like [UPnP PortMapper](https://upnp-portmapper.sourceforge.io/) on your host PC that would redirect `some_ports` to the ports used by GFE, and you would have to change the ports used by Moonlight itself. It'll be fairly easy for the GUI/HTML part, however I don't know how hard it would be in the C++ part, where the actual video streaming takes place.

**Comment by MatthewFrench** [comment]
That sounds super awesome, thanks for the software tip!
If I were better at C++ libraries I'd take a look at moonlight's confiuration. I don't have those skills. :C

On Jul 22, 2017, at 2:55 PM, Paulin Jorys <notifications@github.com<mailto:notifications@github.com>> wrote:


@MatthewFrench<https://github.com/matthewfrench> You could use something like UPnP PortMapper<https://upnp-portmapper.sourceforge.io/> on your host PC that would redirect some_ports to the ports used by GFE, and you would have to change the ports used by Moonlight itself. It'll be fairly easy for the GUI/HTML part, however I don't know how hard it would be in the C++ part, where the actual video streaming takes place.

**Comment by Jorys-Paulin** [comment]
Hey @MatthewFrench, if your issue is solved, you can close this issue. Otherwise, I'll be here to help!

**Comment by MatthewFrench** [comment]
The idea isn't completed but we do have a direction.

On Jul 25, 2017, at 9:24 AM, Paulin Jorys <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @MatthewFrench<https://github.com/matthewfrench>, if your issue is solved, you can close this issue. Otherwise, I'll be here to help!

**Comment by Jorys-Paulin** [comment]
@MatthewFrench Well, as long as Geforce Experience doesn't have this feature, Moonlight can't have it since it's a client that requires a server, here GFE, that has the same features as the client.

**Comment by MatthewFrench** [comment]
I don't know enough about what libraries Moonlight uses and how it configures ports but Geforce Experience on the server side can be routed to different ports using the program suggested above and most routers also include port routing.
We'd just have to figure out how to change Moonlight's ports that it tries to connect to. For example if moonlight tries to connect to port 42,000, we could configure it to look at port 43,000 instead.

On Jul 25, 2017, at 9:48 AM, Paulin Jorys <notifications@github.com<mailto:notifications@github.com>> wrote:


@MatthewFrench<https://github.com/matthewfrench> Well, as long as Geforce Experience doesn't have this feature, Moonlight can't have it since it's a client that requires a server, here GFE, that has the same features as the client.

**Comment by eqwoot** [comment]
there is a stupid way to do it.  Set your client to connect to a local PC and on that PC redirect the GFE port to Port (i.e) 1000 of your home router and at the home router side set port 1000 to redirect to your desire GFE computer and correct GFE port.

**Comment by i9duya** [comment]
@MatthewFrench Did you try [this](https://stackoverflow.com/questions/11525703/port-forwarding-in-windows) in second host PC?
