### ISSUE TITLE
Prevent pairing and notify if GameStream is already in game

### ISSUE THREAD

**Issue by raidancampbell** [moonlight-stream/moonlight-chrome#26]
This will silently fail, which is a problem.

**Comment by raidancampbell** [comment]
Apparently this requires an HTTP implementation of NvHTTP, as the HTTP server will return the currently running GameID, even if you're not paired yet

**Comment by dead** [comment]
I think pairing should be done automatically when needed. (when connecting)

**Comment by raidancampbell** [comment]
As in the initial pairing, and eliminate the `pair` button?  I never thought of that, and don't see why it shouldn't work.  I like the idea.
