### ISSUE TITLE
Stream very laggy since update 0.7.2

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-chrome#260]
Hi, I played with version 0.7.1 and it's absolutely amazing : no drops on 4G but with the 0.7.2, the drops are back !

**Comment by Jorys-Paulin** [comment]
Have you tried to build your own extension? The last version caused some connection errors (https://github.com/moonlight-stream/moonlight-chrome/issues/240) that resulted in the official build being corrupted or something else, as the build we made worked for that user
