### ISSUE TITLE
Moonlight is showing my PC as off, but its on at my house

### ISSUE THREAD

**Issue by Cowpie321** [moonlight-stream/moonlight-chrome#263]
Im at my office trying to connect to my pc at home, it has the red box around it but when i connect to Steam from my phone my PC is on and downloading files. GFE is open.

Nvidia 1080
i7 7700k
GFE fully updated
Using a Chrome book as the one connecting to my client computer running 0.72

0.71 has worked before.

**Comment by Marctraider** [comment]
Pc locked by any chance?

**Comment by Cowpie321** [comment]
It does have a password to log into it, but before leaving for work i was sure to log in since i knew I would be needing it today. Seems strange. Maybe my office wont allow me to connect.... The other computers that have GFE installed here at the office pop up and i can connect to them fine.

**Comment by Cowpie321** [comment]
Still Not working, i have all my ports open, im going to assume that its my wifi at the office. If anyone else has some input please let me know!  Thank you!
