### ISSUE TITLE
Need help to figure out if configuration is wrong for streaming over internet

### ISSUE THREAD

**Issue by Cowpie321** [moonlight-stream/moonlight-chrome#264]
All my ports are correct, I followed exactly what to do on the guide, and i am really not sure what else to do. I tried to downgrade back to 0.7.1 since it did work ONCE, but there was no success there. Just need some advice or tips on how to get my chromebook to connect to my host PC at my house. Any information on servers that i can run my self or something. Im pretty new to streaming and im really not sure why something wouldn't be working. Any help would be great. Thank you in advance.

**Comment by Cowpie321** [comment]
UDP -> 7
UDP -> 9
UDP -> 47992
UDP -> 47989
TCP -> 47894
TCP -> 47984
TCP -> 47989
UDP -> 47998
UDP -> 47999
UDP -> 48000
UDP -> 48010
TCP -> 35043
TCP -> 47991
TCP -> 47995
TCP -> 47996



Thats all the ports ive opend

**Comment by Jorys-Paulin** [comment]
Are they opened on your router or ISP-box and did you have restarted it? Mine needs a reboot to make the ports properly open

**Comment by Cowpie321** [comment]
On my router. I reset it this morning, just got into work and it still cant find the computer..  Not sure where else to look.

**Comment by Cowpie321** [comment]
When I am home, I can stream within the network.

**Comment by Jorys-Paulin** [comment]
Surelly it's a bad configuration

**Comment by Cowpie321** [comment]
Any ideas on what I can do? Anyway to test if my office wifi isnt letting me connect? besides going somewhere else and testing

**Comment by Jorys-Paulin** [comment]
Not that I can think of...

**Comment by Cowpie321** [comment]
Damn, Okay. Thank you

**Comment by Cowpie321** [comment]
I just tried to add a new host using my IP address for the computer at home and it said to make sure it was on because it failed to connect... starting to think it might really be a configuration error somewhere.

**Comment by Jorys-Paulin** [comment]
Geforce has to be listening for it to work, meaning no screensavers

**Comment by Cowpie321** [comment]
I have no screensaver set, and I have it to turn off the monitor and only the monitor. shouldn't change GFE right?

**Comment by Jorys-Paulin** [comment]
I don't know, sorry

**Comment by Cowpie321** [comment]
Alrighty. Thanks.

**Comment by jacobmix** [comment]
So Host is not sleeping, and you can connect to host in the first place? (Like ping it?)
Else it might be a connection issue.
Another guy fixed it by portforwarding his ports to the right PC (Host)
https://github.com/moonlight-stream/moonlight-chrome/issues/255


Here's a quick Copy-Paste from another issue that has much of the same info:
Try getting 7.3 from [here](https://mega.nz/#F!fQ8kSAzL!b_QgzOeVxFFmhBleEZ4REg)
Right click `moonlight-chrome_Master_(v0.7.3)_Jun-25-2017.rar` and pick `Standard Download`
When it's done downloading unpack it to a location you will remember, and not move around.
Then go to `chrome://extensions/` Make sure `Developer Mode` is on,
and then click `Load unpacked extension...` Then select the folder you extracted.
Make sure it's enabled. Should be setup, and ready now.
Just click "Lunch" or use a shortcut to run it. (Make a shortcut by clicking `Details` Then `Create shortcuts...`)

You might also want `DevWarningPatchV1.0.10.rar` from the link.
It removed the Dev Warning popup that Chrome gives when it starts saying something like
"Some extensions aren't from the Chrome Store wanna disable them?"

You can also get `GameStreamFirewall.rar` which should open all the GameStream ports in your firewall.
You still need to portforward them through your router yourself tho.

If you can't/don't wanna portforward. You can try using `PortMapperSettings.rar`
Which explains how to download, and import settings into a program that should portforward for you.


You can also try Nvidia's: [Pftest tool](http://nvidia.custhelp.com/app/answers/detail/a_id/3488/~/gamestream-port-forward-and-log-collecting.) which should help you portforward, and troubleshoot.
(If download is down there's a backup on the mega link `pftest.rar`)

Is recommended that you just portforward through your router if you can tho.
Here's all the ports GameStream uses btw:
TCP: 35043,47984,47989,47991,47995-47996,48010
UDP: 7,9,,47989,47992,47998-48000,48010

Make sure GameStream is on: 
![GameStream1](https://user-images.githubusercontent.com/5995327/27591217-4ec77ab6-5b51-11e7-8c9a-f1dcf22ecfb9.png)

Not sure these settings are needed for Moonlight. But you can try turning them on too:
Allow experimental features, and have Share on:
![GameStream2](https://user-images.githubusercontent.com/5995327/27591189-40f851e4-5b51-11e7-8838-3a00b4a75c97.png)
Stream on (and add games) : 
![GameStream3](https://user-images.githubusercontent.com/5995327/27591387-c5de223a-5b51-11e7-9476-ae47d6b4a6cb.png)
Set how you share (In overlay "Alt+Z") : 
![GameStream4](https://user-images.githubusercontent.com/5995327/27591242-5c0196f8-5b51-11e7-97ad-b9d0b8738704.png)

**Comment by Cowpie321** [comment]
I have all the correct ports open and directly to my PC at home. Ill try the Gamestream Firewall thing as well when i get home. Thanks for the help. Ill let you guys know what works.

**Comment by Cowpie321** [comment]
I just tried to pair again after downloading the 7.3 update and it said pairing failed. Dont think its a problem with the ports

**Comment by jacobmix** [comment]
Try checking console/log, and `YourLocalIPHere:47989/serverinfo`?
https://github.com/moonlight-stream/moonlight-chrome/wiki
Maybe try "Deleting all stored pairings" with the command from the page above, and repair you device?
Try looking through #255 , and see if anything in there might help.

**Comment by Cowpie321** [comment]
Im really not that experienced with all this. Can you give me like step by step on trouble shooting? I really would love to get this working. I tried at work to connect to a different wifi, then connect to an office computer that has GFE, and it wont connect. But on the same Network it will.

**Comment by Cowpie321** [comment]
With the Port forwarding as well, the 47995-47996  What does the dash mean? Do i forward 47995 to port 47996? or Do i forward it to it self?

**Comment by jacobmix** [comment]
`47990-48000` just means it does those ports, and all in between them (if supported by your router)
So it'll do `47990,47991,47992,47993,47994,47995,47996,47997,47998,47999,48000`
And yeah you need to portforward for your host PC. (The PC connected to that router)

**Comment by Cowpie321** [comment]
Awesome thank you, Sadly none of these ended up working. Im able to connect fine inside in network, the moment I connect to another wifi on my chromebook to connect to my PC through moonlight the red box appears on my computer. Not sure whats goin on :/

**Comment by androbourne** [comment]
Check local windows firewall of the machine you are trying to stream from.

You need to allow the same ports through the router inside of the local windows firewall. I've seen times that even with the local firewall disable, it still didn't function properly until it was allowed through manually.

Also is your system on a static IP? do you have the ports forwarding to the static IP machine or is it simply "just opened" to all machines behind the modem/router? For it to work properly it should be going to a static source, not just generally open on the modem/firewall.
