### ISSUE TITLE
Moonlight CTD

### ISSUE THREAD

**Issue by blackecos** [moonlight-stream/moonlight-chrome#265]
Hi!

thanks for the hard work.

First of all there´s a new geforce experience update and it seems its not compatiblity anymore.

I tried an older version of geforce experience (3.6.0.74) and my friend can´t connect to me. If she starts a "app/game" the game does open on my pc, she get handshake then a grey screen and ctd on both pc´s. (Moonlight goes back to Useroverview and my game close)

Hope for helpfull answers + fix? ^^
Which versions of geforce experience works good with moonlight for chrome? (newest version)

Greetings Ecos

**Comment by cgutman** [comment]
GFE 3.7.0.81 works fine for me on v0.7.2. Can you describe what the exact issue you're having with the latest version is?

**Comment by blackecos** [comment]
I think the easiest way is to make a video. But she is offline now will post it tomorrow.

**Comment by cgutman** [comment]
Are you able to stream from another PC or mobile device within your network?

**Comment by blackecos** [comment]
I don´t know why but now it works fine. >-<

Thanks for the help

**Comment by blackecos** [comment]
We have only one little issue we use discord and moonlight since 1 year. And now she can hear her voice in moonlight.
Can I fix this?

**Comment by cgutman** [comment]
Nothing we can do on our side, but you can possibly try streaming your desktop (which uses a different audio capture implementation) and starting the game from there. https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop

**Comment by blackecos** [comment]
We tried it and it doesn´t help us. Tomorrow we try the new version of moonlight.

But the conection is far better then last year! Good work ;)

**Comment by thegreekjester** [comment]
hello, 
the problem I am experiencing happens when I launch my game(League of Legends). I can pair my two computers just fine using the moonlight chrome extension. But right when the game launches it closes and bring me back to the games overview again. I cant seem to launch the game at all.

**Comment by blackecos** [comment]
I think its a problem with LoL. Have you tried another game? Maybe LoL have a protect for this kind of streaming. (because of abusing it... "coop" stream for league of legends will be a bit cheating x))
Maybe you can try to play the game in window mode and stream your entire desktop?

**Comment by thegreekjester** [comment]
you are correct! I tried it with another game and everything worked fine, thank you so much. Another question is whether its possible to have the computer that the game is streaming from run it in the background so as to keep it freely available for other tasks. For example, having my gaming pc stream a game like starcraft but be able to also use another application like a browser or microsoft office at the same time.

**Comment by Jorys-Paulin** [comment]
Great idea @thegreekjester! however, it's Geforce Experience that it running your games and applications, not Moonlight. If they did, then it'll cause some problems: first, your entire screen is streamed, and second, making Windows/MacOS/Linux understand that we have two separate controllers (your client's gamepad or keyboard/mouse and the host's ones) is complicated, and even more for the programs.
