### ISSUE TITLE
Very bad latency on my Chromebook

### ISSUE THREAD

**Issue by LufyCZ** [moonlight-stream/moonlight-chrome#266]
Hi,
I tried the Moonligh Android app (root) on my Chromebook. but got very bad latencies 100-120ms. Same goes with the Chrome app (the latency doesnt show, but is really bad). When I try to connect from my iPad or Android phone (rooted), Im getting 20-25ms. It is a 2.4GHz network, but if it works on my phone, why wouldnt it on my CB ? I tried iperf, and the bandwith is 60-80Mbytes/s on both my phone and CB. Is there a way to fix it ? Thanks

**Comment by Lukyczk** [comment]
Update: Flashing another firmware on my router improved it, but it is still really choppy

**Comment by Jorys-Paulin** [comment]
Latency could be introduced by your networking infrastructure (wire is better than wifi), but also your hardware, either your client (from wich you stream to) or your host (the one wich runs the games)

**Comment by Lukyczk** [comment]
Is there a way to test it ? The host is ok (as it runs np on my phone). Im not sure about the CB tho

**Comment by Jorys-Paulin** [comment]
Is the phone running on the same network as the Chromebook? If so, we could conclude that the Chromebook is the issue

**Comment by Lukyczk** [comment]
It is running on the same network. Just tried it on my brothers CB. It wasnt choppy at all, but there was a noticeable lag

**Comment by Jorys-Paulin** [comment]
As always with Wi-Fi, you'll have at least some delay. But here your Chromebook seems to be the problem. Try completly reinstall Moonlight from stratch and come back here

**Comment by Lukyczk** [comment]
After reinstalling, the stream looks to be a lot more fluent, but I still have a pretty big delay (might be a placebo effect). Sometimes it would cut off completely (lagged video, and mouse). Im sitting 1 meter away from my router. The PC is connected to the router with a cable

**Comment by Jorys-Paulin** [comment]
How does it cut off exactly ?

**Comment by Lukyczk** [comment]
The video lags, just as if it was a picture, and the mouse acts as if I was still holding it. You can see the same effect as if you hold the primary click button and then pulled the USB out of your motherboard - it would still be clicked

**Comment by cgutman** [comment]
What resolution, frame rate, and bitrate is Moonlight set to?

**Comment by Lukyczk** [comment]
720p 30f/s 100Mbits

**Comment by Jorys-Paulin** [comment]
How about the host? What appends while your client lags ?

**Comment by cgutman** [comment]
100Mbps? That's probably way too much data for your decoder. Try streaming at 5 Mbps.

**Comment by Lukyczk** [comment]
cgutman: The latency went down, but the ocassional lag persist.
Jorys: When Im running, and it lags, I keep running. Just as if the client send "w", but the host then didnt receive "end of w"

**Comment by Jorys-Paulin** [comment]
Make sure you have everything updated on booth sides, sometimes it surprisingly works.

**Comment by Jorys-Paulin** [comment]
> I keep running

Your character on your host screen still runs, right ?

**Comment by Lukyczk** [comment]
Yup

**Comment by Jorys-Paulin** [comment]
But the client's screen is frozen

**Comment by Lukyczk** [comment]
Yup

**Comment by Jorys-Paulin** [comment]
Have you updated everything?

**Comment by Lukyczk** [comment]
Yes, got a Geforce Experience update today (it wasnt working before either)

**Comment by cgutman** [comment]
Are you using any Bluetooth devices with your Chromebook?

**Comment by Lukyczk** [comment]
No

**Comment by cgutman** [comment]
Can you download WiFi Analyzer on your phone and see if your network is overlapping another?

**Comment by Lukyczk** [comment]
I have checked that today. There are almost no other wifi networks nearby

**Comment by cgutman** [comment]
And you're using Moonlight v0.7.3 on your Chromebook?

**Comment by Jorys-Paulin** [comment]
Did you tried to connect to your modem via Ethernet ?

**Comment by Lukyczk** [comment]
cgutman: Yup
Jorys: Newer chromebooks dont have an ethernet port. Im planning on getting one tho (adapter)

**Comment by cgutman** [comment]
I don't know there's much else we can do. WiFi can be very finicky, especially 2.4 GHz. It could be something like a cordless phone, microwave, or other device causing periodic interference. Depending on the quality of the antennas and WiFi chip, devices may or may not be affected by it.

**Comment by Jorys-Paulin** [comment]
But apparently his brother's Chromebook works fine, why is that then?

**Comment by cgutman** [comment]
Different device = different WiFi chip and antennas

**Comment by Lukyczk** [comment]
Just tried again on my brothers CB - there was no stutter at all, but Ive had bad latency

**Comment by cgutman** [comment]
Were you running it at 720p 30 FPS 5 Mbps?

**Comment by Lukyczk** [comment]
Will try tomorrow. Thanks for your time tho

**Comment by Lukyczk** [comment]
k, just tested 720p 60f/s 10Mbps, no lags at all, but the latency is noticeable. I was testing it on BF1: I was watching the host screen - the clients screen is pretty delayed. I can use the keyboard on the client np. When I connected my mouse to the client, it was a bit more unplayable on the host. So the keyboard is flawless, but the mouse and video stream is delayed. (The mouse is a bit laggy - something like frame losses - I couldnt really aim.)

**Comment by Jorys-Paulin** [comment]
Weird. Honestly IBM running out of ideas...

**Comment by Jorys-Paulin** [comment]
Hey @LufyCZ, now that some time has passed, have you tried with the latest version of Moonlight (currently 0.8.2) and Geforce Experience?
