### ISSUE TITLE
Stock on Loading screen

### ISSUE THREAD

**Issue by Johnne25** [moonlight-stream/moonlight-chrome#267]
I have searched for a resolution to this issue and all of them say to enable Native Client.  I have done this, restarted everything, and still have the issue of being stock on the Loading Plugin screen.

I have tried v0.72 and v0.73.

I am running a MacBook Pro OSx 10.12.15 and with Chrome Version 59.0.3071.109 (Official Build) (64-bit)

**Comment by Jorys-Paulin** [comment]
> If you are stuck at the "Loading Moonlight" screen for more than a minute or so, you may have to manually enable NaCL in your Chrome settings. Type chrome://flags in the address bar and search for the option called "Native Client", click the Enable link for Native Client, and restart your browser.

Have you tried this?

**Comment by keralo** [comment]
I have the same problem. I also tried with 0.72 and 0.73
But I still have that problem even with the enabled NaCL
I even tried it on 2 computer

**Comment by Johnne25** [comment]
Yes.  I followed the steps to enable Native Client and restarted the browsers. I checked it gain to confirm it was enabled.

I tried again after a reboot as well.

I am still stuck at the Loading screen.


On Jun 25, 2017, at 7:08 PM, keralo <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same problem. I also tried with 0.72 and 0.73
But I still have that problem even with the enabled NaCL
I even tried it on 2 computer

**Comment by Johnne25** [comment]
I followed the instructions and also enable Native Client.

However, recently reinstalled OSX Sierra and this is when it all stopped working.

I have just installed the latest JAVA for MAC 64x and it is now getting past the Loading screen. 

You may want to add a message somewhere saying which version of JAVA is required.

**Comment by Jorys-Paulin** [comment]
Are you booth running the latest and official build of Moonlight ?

**Comment by keralo** [comment]
latest Chrome and latest build of moonlight yes

**Comment by Jorys-Paulin** [comment]
If you unsucessfully tried on a second client, then your host must be the issue

**Comment by Johnne25** [comment]
I solved my issue by installing the latest versions of JAVA on my computer.

Sent from my iPad

On Jun 26, 2017, at 10:20 AM, Paulin Jorys <notifications@github.com<mailto:notifications@github.com>> wrote:


If you unsucessfully tried on a second client, then your host must be the issue

**Comment by Jorys-Paulin** [comment]
I was speaking to @keralo, sorry!

**Comment by AgentCrowe** [comment]
I am having the same issue, but mine started today. Earlier, I was playing via Moonlight and one of my games were crashing (an issue that's unrelated to moonlight because the game crashes without streaming as well) so I updated to the newest version of drivers/Nvidia Experience and now non of my devices will connect to my desktop via moonlight, Not on my RP3 or MBP :( I will try updating Java and let you guys know.

**Comment by Jorys-Paulin** [comment]
@AgentCrowe If no Moonlight clients can connect to your host (with GFE), then the host is the problem

**Comment by AgentCrowe** [comment]
@Jorys-Paulin Right I get that, I am assuming its the Nvidia Geforce Experience that's the problem. The update seemed to be a pretty large update, is it possible that the current versions of Moonlight don't support the current version of GFE?

**Comment by Jorys-Paulin** [comment]
@AgentCrowe As long as they didn't changed the protocol used, it should still work. I'm not developer for that side of things, so I might be wrong

**Comment by AgentCrowe** [comment]
@Jorys-Paulin Thanks for the help, I'll keep plugging away and once it starts working I'll leave a detail description of my experience.

**Comment by Jorys-Paulin** [comment]
@AgentCrowe Hey, have you resolved your problem yet?
