### ISSUE TITLE
installation problems with asus chromebook c201

### ISSUE THREAD

**Issue by chugchug** [moonlight-stream/moonlight-chrome#269]
When I drag the downloaded file over the extensions page, it tries to redownload the file.  then it brings up a warning that it might be unsafe which when bypassed says "apps, extensions, and user scripts cannot be added from this website."  What am I doing wrong?  Is it my computer?

**Comment by Cowpie321** [comment]
Have developer mode on?

**Comment by jacobmix** [comment]
If you still have problem downloading it. Try getting 7.3 from [here](https://mega.nz/#F!fQ8kSAzL!b_QgzOeVxFFmhBleEZ4REg)
Then unpack it to a location you will remember, and not move around.
Then go to `chrome://extensions/` Make sure `Developer Mode` is on,
and then click `Load unpacked extension...` Then select the folder you extracted.
Make sure it's enabled. Should be setup, and ready now.
Just click "Lunch" or use a shortcut to run it. (Make a shortcut by clicking `Details` Then `Create shortcuts...`)

**Comment by chugchug** [comment]
yep.

**Comment by Jorys-Paulin** [comment]
@chugchug Hey chug, is everything running correctly? If so, you can close this issue, if not, just post here, I'll be happy to help you!

**Comment by chugchug** [comment]
I think I was downloading the wrong extension, but it works now.  Thanks.

**Comment by Tamesnake** [comment]
it still wont let me get on can u help me

**Comment by Jorys-Paulin** [comment]
@Tamesnake Describe what happens please
