### ISSUE TITLE
Cursor jumps about randomly when using non-standard client screen resolution

### ISSUE THREAD

**Issue by TheSnook** [moonlight-stream/moonlight-chrome#270]
This issue is with a Chromebook Pixel 2 client running 0.7.3 (0.7.2 had the same behaviour) on the latest Chrome beta 60.0.3112.41, and is triggered by setting the screen resolution to anything between the default (pixel-doubled) and native resolutions. I.e. 1280x850 or lower is fine, 2560x1700 is fine, anything between those is broken as described here.

When moving the mouse, the cursor will move normally for a little while, then warp backwards to a seemingly random point on the screen. The cursor is unable to traverse the full extent of the screen in either direction/axis without being affected. This doesn't depend how far or fast the mouse is moved on the client end (large sweeping movements or lots of small slow movements exhibit the same behaviour). The behaviour is still there whether Moonlight is running full scree, or in a window.

Enhanced precision is confirmed disabled on the server side.

**Comment by jango1985** [comment]
I also had this issue with non-standard client screen a resolution.  The cursor behavior resembles joystick behavior to me.
