### ISSUE TITLE
Xbox One S Bluetooth controller not mapped correctly

### ISSUE THREAD

**Issue by Mrono** [moonlight-stream/moonlight-chrome#271]
When using the controller through moonlight the inputs are not mapped correctly, it seems that microsoft moved the d-pad from buttons, to binary axis.  Picture doesn't show much but it does show what gets detected on each side, Right is chromebook, left is windows over moonlight
![screenshot 2017-06-27 at 7 39 40 pm](https://user-images.githubusercontent.com/1576789/27616960-8c76ce38-5b70-11e7-89f0-48958e30f3e5.png)

**Comment by cgutman** [comment]
You need to update the firmware on your gamepad using a Windows 10 PC or Xbox One for Chrome's mapping to work.

https://support.xbox.com/en-US/xbox-one/accessories/update-controller-for-stereo-headset-adapter

**Comment by cemarriott** [comment]
The XInput mappings have for the most part worked fine for me with this controller, a MacOS client and W10 host. IIRC the Select button does not get mapped, but everything else was fine.

**Comment by Mrono** [comment]
@cgutman That worked, thank you

@cemarriott it's a pity about the select button, I wonder why it doesn't get mapped on bluetooth, think it's an issue with chromeos or the controller not sending the data?

**Comment by Jorys-Paulin** [comment]
Does it also appends when connected over USB? Just wondering

**Comment by Mrono** [comment]
I tried that however when I plug in either of my Xbox one controllers over
USB into my Chromebook the Chromebook shuts off, Acer r13

**Comment by Jorys-Paulin** [comment]
More details? I don't understand quite well...

**Comment by Mrono** [comment]
@Jorys-Paulin Just as I said, when I plug in an xbox one controller to my chromebook with usb, the chromebook shuts off. Won't turn back on until the controller is removed. ¯\_(ツ)_/¯

**Comment by Jorys-Paulin** [comment]
So the whole operating system crashes? Maybe hardware incompatibility issues is the problem

**Comment by cgutman** [comment]
It's not a hardware problem. The Chromebook needs a newer kernel with this commit https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/input/joystick/xpad.c?id=c7f1429389ec1aa25e042bb13451385fbb596f8c

**Comment by Mrono** [comment]
@Jorys-Paulin Considering the issue is with bluetooth and not usb I don't think it's relevent, but you asked what happened when I plugged it in with USB so I told you.

@cgutman I've gotten it to work over bluetooth for all the inputs except 'select', my suspicion was that it wasn't mapped correctly in the chromebook kernel.  Looks like that may fix it, just gotta wait for it to come out now.  Pity I have to run developer mode to get it to work at all.
