### ISSUE TITLE
Game list in alphabetical order

### ISSUE THREAD

**Issue by nicholson101** [moonlight-stream/moonlight-chrome#272]
I think i'm probably not seeing/doing something obvious but my game list is in a completely random order. When using my shield portable or shield TV its fine so it lends me to believe the problem is in moonlight.

Any suggestions would be really handy

Cheers!

**Comment by cemarriott** [comment]
Same issue here. They show up in alphabetical order in GeForce Experience but Moonlight's list is apparently unordered. Additionally, Moonlight shows only a fraction of the games that GFE lists...

**Comment by Jorys-Paulin** [comment]
- @nicholson101 Order by letter is a fairly simple feature to implement, I'll take a look and see what I can do
- @cemarriott Moonlight lists all the games Geforce Experience give it, so if a game is not showing up then it's because Geforce don't send it to Moonlight, probably because it can't stream it to Shield devices : What games aren't showing up?

**Comment by cemarriott** [comment]
@Jorys-Paulin Ah, I didn't realize games supported by GFE, and those available to GameStream, were separate categories. I went through all the games listed in GFE and compared against the ones listed in Moonlight. Any that did not show up in Moonlight were indeed not in the list that can be used with GameStream. Thanks for clarifying.

I was in particular thinking of Civilization VI and the Sims games, both of which are not supported for GameStream but which work alright if added manually in the GFE GameStream settings.

If anyone else is curious, [the list supported for GameStream is here.](https://www.nvidia.com/en-us/shield/games/#library) (you have to scroll down to Library and pick the GameStream tab)

**Comment by Calcyfer** [comment]
@cemarriott You can still stream games not supported by Gamestream by adding them to your Steam library and starting Steam from Moonlight.

**Comment by Jorys-Paulin** [comment]
@Calcyfer You're right, however you can't guarantee that your game will run properly then.

**Comment by Calcyfer** [comment]
True - but it beats the alternative, I guess. :grin:

**Comment by Calcyfer** [comment]
@Jorys-Paulin Is the alphabetical sort something you're working on atm? 
_I've seen your console.log improvement PR, looking good btw._

**Comment by Jorys-Paulin** [comment]
@Calcyfer Well, the issue filled from the fact that the game-card only shows up when it's image is loaded. So the less time it takes to load the image, the sooner in the list you will appear, but you won't necessarily appear in the same order as the host gives it to Moonlight.

**Comment by Calcyfer** [comment]
@Jorys-Paulin Hmm I see. We could fix that with async loading or by sorting after all images have loaded. Not sure if that would make sense, though. 
Wouldn't want to make users wait on an image that may never load..
I'll have a look at it this weekend - doesn't seem like a very important feature, but it would be handy, I suppose.

**Comment by Jorys-Paulin** [comment]
Well there's two ways:
- Placing a placeholder image while the main image loads
- Using flexbox order to reorder each card as they load. This however triggers a layout and moves positions, Wich can be annoying for the user and also affects performance
- Reorder in JavaScript, but it has the same drawbacks as the last method
The response from the server is handled once it's complete, the images are loaded after that, asynchronously, meaning we can build the entire grid (including the game's name) and place the images after
