### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by crazy888** [moonlight-stream/moonlight-chrome#277]
Hello,

i get error message when trying to install moonlight:
UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL

Dunno how to slove this or to get it work......
![image2](https://user-images.githubusercontent.com/16318281/28077065-f0a8f08e-6660-11e7-9280-d2f313f31451.jpg)

My system:
Windows 10 x64
Chrome Version 59.0.3071.115
Moonlight v0.7.3

**Comment by Rocker545** [comment]
I'm having the same problem

**Comment by Jorys-Paulin** [comment]
Just to be sure, do you have the latest version for Chrome (or is it Chromium?), Moonlight and your operating system? What type is your device? (Is it a laptop, a Chromebook, a desktop?)

**Comment by crazy888** [comment]
Jep, it says Chrome "is up date" when i check for a update.

I want to install it on a Dell XPS15 9560.

**Comment by Jorys-Paulin** [comment]
Have you tried to enable NaCl, `chrome://flags/#enable-nacl`, just to see if it changes everything?

**Comment by crazy888** [comment]
No, it does also not install with nacl enabled.........

**Comment by Jorys-Paulin** [comment]
Could you try with another computer?

**Comment by crazy888** [comment]
I have tried it on another computer.

Win7 x64 .......... 

Also not working........

**Comment by Jorys-Paulin** [comment]
@crazy888 Then it's most likely that your computer host is the problem if multiple computers can't connect to it.
- To be sure, try running another version of moonlight, whether the mobile version or the Java one.
- Make sure that everything on both computers is updated, including Geforce Experience
- Make sure you enabled shield settings in that program. Maybe it deactivated itself, who knows

**Comment by crazy888** [comment]
@Jorys-Paulin  I´m not sure about what you are telling me. 
As moonlight is the client side and Nvidia is the server side, i dont have any problems with the server.
My server is streaming games over gamestream fine on my nvidia shield already.

My problem is that i can NOT INSTALL moonlight (client) on any PC.
And of course i can´t connect because i can not even install moonlight. 
But the problem is the INSTALLATION not the connection.

And on the client side is no Nvidia Experience because it is the client. How should i update this? Client side is using Intel graphics and AMD.

Did you mix something up here?

**Comment by jacobmix** [comment]
Try downloading *moonlight-chrome_Master_(v0.7.3)_Jun-25-2017.rar* From here:
https://mega.nz/#F!fQ8kSAzL!b_QgzOeVxFFmhBleEZ4REg
Then extract it to somewhere you will remember, and not move around.
Go to `chrome://extensions/` and turn on "Developer Mode" then click "Load unpacked extension..."
Pick the path to where you extracted the file you downloaded earlier, and it should show up.
Then make sure it's "Enabled" and you should see "Launch" in blue text under it. Click it.
Now Moonlight should run.

**Comment by Jorys-Paulin** [comment]
Maybe, but I can't help you with this error, which doesn't appear in the code, so that must mean that it is chrome-related, maybe chrome is not updated or is corrupted, or something else on your two computers is interfering, maybe the OS itself even. The help of someone else could be useful in order to fix that problem

**Comment by Jorys-Paulin** [comment]
@jacobmix What do you think is the problem?

**Comment by jacobmix** [comment]
@Jorys-Paulin That moonlight doesn't install/run? This should load it as an unpacked extension.
Which might help since installing it normally doesn't seems to be working,

**Comment by crazy888** [comment]
Yes, i can confirm it is working! Thanks a lot!

**Comment by Jorys-Paulin** [comment]
@jacobmix So the packed extension is corrupted?

**Comment by Jorys-Paulin** [comment]
Anyways, @crazy888 if you don't have anymore problems, you can close this issue :)

**Comment by jacobmix** [comment]
Not sure if this is how he was installing it. But i think chrome just didn't wanna install the extension .crx file when he dragged it into the extensions page. Google is strict on none chrome store extensions, and sometimes wont install them. Using Developer mode, and loading it as an unpacked extension goes around that tho. Or it might just have been something else with installing it that way. Not sure.

**Comment by crazy888** [comment]
@jacobmix yep i tried to install it by draging the crx file into my chrome extension page

**Comment by jacobmix** [comment]
Now Chrome might pup up every time you start it with an annoying warning like "You got one or more developor extensions installed. Don't install unsafe stuff kid. Wanna disable all dev extensions? *Disable* *Continue*" You can download "DevWarningPatchV1.0.10.rar" extract the bat file inside, and run it as admin while chrome is not running. Which should remove the popup. It will come back hen chrome updates tho. So you might wanna keep it around.
