### ISSUE TITLE
No Duel Monitor Support?

### ISSUE THREAD

**Issue by androbourne** [moonlight-stream/moonlight-chrome#278]
I searched everywhere online and do not see duel monitor support on this software. it would be nice as that is the mean reason I no longer use it for remote device access. I have web browsers stuck on the other screen that I can not bring over to a single window.

MSCST has built in duel monitor support already. The software just needs the options built into it to allow for control over the remote settings. I don't foresee this being a difficult request to complete.

**Comment by Jorys-Paulin** [comment]
Yes, you would be right. However, moonlight is just a client, meaning it connects to something else (GeForce experience), so if a feature is missing for it, then Moonlight can't implement it. :/
