### ISSUE TITLE
Can't play mortal kombat X steam edition

### ISSUE THREAD

**Issue by airdjing** [moonlight-stream/moonlight-chrome#279]
Not problem run Mortal kombat X steam edition game
But keyboard is not work
Another game is no problem

This is My system

    - Server
    Windows 10 x64
    NVIDIA 384.76 Display Adapter Driver (980ti)
    GFE 3.7.0

    - Client
    Windows 10 x64
    Intel v20.19.15.4531 (HD 5300)
    Moonlight v0.7.3

Only my problem?

**Comment by Jorys-Paulin** [comment]
- Does your game have keyboard support on your host?
- Does using a controller works?

**Comment by rampage47** [comment]
I have some problem. Mk x + moonlight = sad story

ps Jorys-Paulin , pls, stop it. U must test game, before write post

**Comment by Jorys-Paulin** [comment]
@rampage47 I would, but I don't own the game. I'm just trying to help you...
