### ISSUE TITLE
Adding controller mapping to support many different controllers

### ISSUE THREAD

**Issue by jmitchell89** [moonlight-stream/moonlight-chrome#280]
I'm a front-end javascript developer and I want to take the initiative here, but I think I need some help with the backend portion of this extension. I can create a html interface for mapping gamepad inputs to their respective "buttons". In javascript it is possible to "detect" gamepad inputs using this 

**API:** 
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

**Example:** 
http://html5gamepad.com/

I see a couple of problems with using this though:

1.  How do we map gamepad inputs from javascript to something moonlight can interpret? 
- Currently the only way I know to map inputs is via command line the `moonlight-embedded` way. 
3. Persisting the gamepad settings when they close the app and reopen. 

Also I just would like to point out that the front end portion of this project is not very easy to maintain the way it is setup. I would suggest using ES6 with babel, webpack, etc. It would clean up the code quite a bit and make it easier for new people to help out with the project.

**Comment by Jorys-Paulin** [comment]
@jmitchell89 I'm a front-end developer too, but I see some problems:
- All the gamepad input is handled through the moonlight C++ module, never does the HTML part have any interaction with it. The HTML part can talk with the c++ via a `sendMessage`, which would be a way to handle gamepad mapping. However, this would require, of course, an implementation on the c++ side. I suggest you start experimenting with the HTML part and show us your work, I'll be with great pleasure!

**Comment by cgutman** [comment]
My intention was to pass a mapping blob from the HTML side which the C++ code would consume.

The C++ code needs a couple arrays. One of [JS Gamepad button -> Moonlight button] mapping and another of [JS gamepad -> Moonlight axis]. The one gotcha is that you may find your d-pad mapped as a hat if Chrome doesn't understand it. In that case, it will be mapped as either 1 or 2 axes, depending on the OS's abstraction of HID devices.

**Comment by Jorys-Paulin** [comment]
@jmitchell89 And please use the `window.localStorage` ([MDN link](https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage)) instead of the `chrome.storage` API, as it's the most likely to be supported & optimised in the future. Happy coding!

**Comment by jmitchell89** [comment]
@Jorys-Paulin I don't think anyone here will want me to touch the c++ code, but I can definitely whip up a working prototype this weekend. Using components is a great place to start at work here we use the "React/Airbnb stack" which is react, redux, rx.js, webpack, and typescript thrown in. I'm not sure all that is necessary for a relatively small application like this, but I think using ES6 with webpack would be a great starting place to getting the code to a place where it's not so messy.

**Comment by Jorys-Paulin** [comment]
@jmitchell89 

Personally, I don't use react or redux, nor do I know how to use them. For Moonlight, I think that "plain-old vanilla javascript" would do the trick, because loading fewer frameworks (like JQuery right now) can be a great thing when it comes to performance.
Again, this version is supposed to run on **low-end devices**, meaning it needs to be as light and optimised as possible: this is why I recommended the use of `localStorage`, which will have long term support over the `chrome.storage` reserved for extensions.

I think that Moonlight development would benefit from the use of a package manager like `npm`, even if it requires the installation of [node.js](http://nodejs.org/) in order to build/dev on the project because it would make importing dependencies (like material components) much simpler, not to mention, **updating them**.

**Comment by jmitchell89** [comment]
@Jorys-Paulin Since that's the case I would say using webpack + es6 would be a great fit, and since chrome supports es6 out of the box too that makes it way easier you wouldn't need to worry about using babel or another transpiler. npm is great for package management, but I would suggest using yarn in addition to npm. It has a lock file so you can insure version consistence across developer machines, it better handles package dependencies, and it is much faster.

https://yarnpkg.com/en/

**Comment by Jorys-Paulin** [comment]
@jmitchell89 

- I'm already confident about the chrome support, provided that the user is running the latest version. However, I'm thinking about other browsers that this version might have to support if it is ever ported to something like [WebAssembly](http://webassembly.org/), I know that some browsers [don't support ES6 fully yet](http://caniuse.com/#search=ES6), including chrome when it comes to modules, which might be a neat thing to fragment the app's code under several files, each with a clear and precise function.
- I'm not really inclined to use two packages managers at once. However, some experiments might help us in that way, to see if the advantages `yarn` has can overthrow the performance and "ease of dev-setup" caveats.

**Comment by jmitchell89** [comment]
@Jorys-Paulin 

- It's fairly easy to run babel on code that you want to be supported with other browsers. Do you have a list of target browsers? Last I checked most browsers support es6:
https://kangax.github.io/compat-table/es6/ For module support webpack is the way to go. I've also used browserify but it is not nearly as nice.
- Sorry for the confuse I meant to say "use yarn over npm". However yarn still uses the same packages that npm has it just is a better package manager than npm and not an entirely different eco system like say bower.

**Comment by Jorys-Paulin** [comment]
So I've downloaded yarn and tested it for this project by downloading the `material-components-web`, which is the package I plan to use to replace MDL and from a quick inspection of the files I didn't really saw what advantages yarn could provide at such low-level use. Let me know how and why you think we should use it anyway, I'm interested in your thinking!

**Comment by jmitchell89** [comment]
Weird issue I'm having with communicating to the naclModule. I get the following error: 
`Returned error was: TypeError: common.naclModule.c is not a function`

Also is there a discord or slack chat that you guys use to communicate more efficiently?

**Comment by Jorys-Paulin** [comment]
I have a Discord account, but I don't know if the owner(s) have one or something similar

**Comment by jmitchell89** [comment]
I created a discord server for us to chat on I think it'd be helpful. I've almost got a basic rewrite of most of the javascript code finished using es6 syntax. Some things need to be heavily refactored later on however.

Feel free to join here:
https://discord.gg/T9W4SS4
