### ISSUE TITLE
Mouse feels sluggish

### ISSUE THREAD

**Issue by Cowpie321** [moonlight-stream/moonlight-chrome#281]
When im using my mouse it feels like its just falling behind, key inputs seem to be slugging as well. Any ideas what this can be?

**Comment by cgutman** [comment]
What are the specs of your client PC? What resolution and frame rate are you trying to stream?

**Comment by warglieneu** [comment]
@cgutman I am also experiencing very intese mouse lag. I know this issue is quite old, but thought maybe your are still looking into this. I am using a macbook pro 13 inches as client with Moonlight Chrome 0.7.3 and GFE 3.9.0.61 on the Host PC.
I am using a Logitech MX hooked up directly to the Host PC. 
It's a pity because the rest is really working well, I'm very impressed by the streaming quality!
Happy to share more details if needed :)

**Comment by Jorys-Paulin** [comment]
@waumand Are you running Chrome v64 ?

**Comment by waumand** [comment]
@Jorys-Paulin yes, I'm using the mac app of Chrome : Version 64.0.3282.140 (Build officiel) (64 bits)

Un-contrary to Windows, there is no x86 version of Chrome in MacOS right ?

I also try VirtualHere with a USB mouse and still a little laggy but really better : no feeling of "spikes".
And with Steam home-streaming I have more the same feeling than VirtualHere, maybe better (but the stream quality est worst than the perfect picture I go with Moonlight ^^).

**Comment by Jorys-Paulin** [comment]
@warglieneu 
- There was a similar bug with mouse in Chrome 63 but it should have been fixed in Chrome 64
- I don't know about Macs, but I think there's no version of modern MacOS x86
- Try with another mouse, see if the trackpad isn't the problem

**Comment by waumand** [comment]
I don’t have trackpad on my iMac, but also I tried 6 differents mouse. The problem is on MacOS, 3 differents Mac and still this proble ^^
I’ll try on Windows when I can.

**Comment by waumand** [comment]
I've tried on a PC under Windows 8.1 with the last Chrome x64 and the result is the same (latency and spike mouse in FPS games), but it's cool that it's not only a Mac trouble hehe ;-)

**Comment by Jorys-Paulin** [comment]
@waumand I suggest you reinstall your GeForce Experience then.

**Comment by waumand** [comment]
@Jorys-Paulin I've bought an Nvidia SHIELD 2017 and I can confirm that it's not a moonlight bug, it's only on the server side with GeForce Experience installed (I reinstalled it many times without succes to resolved it). Maybe depend on config in server side, ping in LAN, installations, etc.

So... not a moonlight bug :)

**Comment by Jorys-Paulin** [comment]
@waumand But then what happens to your host? What is the problem?

**Comment by waumand** [comment]
@Jorys-Paulin when you speak to host it's the client (macbook, shield, etc) you want to say ?

The mouse is a bit laggy, like some spikes, in fps games like Counter Strike or Natural Selection 2 or Fortnite, when I turn my head with the mouse there is some "stuck" or "spikes" I don't know how to describe it, like drop fps or Vsync fail, but it's not that. But with VirtualHere this effect disappear (it stay only a very little lag stay, no problem if just play online for fun with friends, but not ok for competition).

**Comment by Jorys-Paulin** [comment]
@waumand What happens on the host's screen ? Does it also lags ?

**Comment by waumand** [comment]
I can say it didn't lag (like latency is quite better in host), but the "spike" felling when I move my head in fps games still exist.
With VirtualHere I don't have this felling, so I think it's just in GFE the way how mouse work, maybe.

**Comment by Jorys-Paulin** [comment]
@waumand Have you enabled experimental features in GFE (it's like the beta)
