### ISSUE TITLE
Alpha Chrome version

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-chrome#282]
I know that this is we are benefiting from your hard free work and don't want to sound ungrateful, but I want to ask if things are advancing behind the scene for the chrome version. It seems to be far away from the quality of the android version.
Further more some new version seem to work far worse than older versions. the Alpha state doesn't seem to be working progressive.

**Comment by cgutman** [comment]
Do you have specific issues that you can point out? I've played several 4+ hour sessions with Moonlight Chrome v0.7.3 over the last week and it's worked well for me each time.

**Comment by Jorys-Paulin** [comment]
@apoklyps3 Surely, at first it doesn't seem that this project is very active. However, [many people like me](https://github.com/moonlight-stream/moonlight-chrome/network) are experimenting and proposing new features when they're done. I reckon the app's not optimised right now, the menus are running at 20fps for me according to chrome, but that's something easy to fix.

**Comment by apoklyps3** [comment]
alot of stuttering and controller lag.
even the image quality seems worse...
