### ISSUE TITLE
stuttering on all settings

### ISSUE THREAD

**Issue by boostjunkie92** [moonlight-stream/moonlight-chrome#283]
I used to stream to my laptop with the chrome plug in and it worked just fine at 4k60fps with a 30mb rate.  I recently did some changes to my host computer to help streaming to my 4k tv (changed adapter from 1gb to 100mbps/full) now when streaming to the shield via gamestream or moonlight the streams are perfect but my laptop and phone now have severe stuttering even at 720 with 10mbps bitrate.

**Comment by Jorys-Paulin** [comment]
Excuse me, but how do you stream to your shield from Moonlight and Gamestream?

**Comment by boostjunkie92** [comment]
i stream with my pc to my shield...

**Comment by Jorys-Paulin** [comment]
Yes but you are streaming your game from your computer to your shield or to another computer running moonlight?

**Comment by boostjunkie92** [comment]
Both... Streaming to the shield works fine but in times when my GF wants to use the TV I stream to my laptop but now it stutters but it used to run smooth before

**Comment by Jorys-Paulin** [comment]
Ok, and your laptop is running on your wifi as well as your shield?

**Comment by boostjunkie92** [comment]
No shield is hardwired, laptop is wifi

**Comment by Jorys-Paulin** [comment]
Wifi has a big impact on bandwidth and so does it on image quality and stuttering. In order to be sure you would have to connect your laptop to your host PC via ethernet. And are both of your PCs updated and running the latest Softwares?

**Comment by boostjunkie92** [comment]
Both PC's are updated, I've never had laptop issues before and the WiFi is a 300 Mbps connection also I've set the bandwidth as low as 10 Mbps still stutters

**Comment by boostjunkie92** [comment]
I'll try a hardwire and double check updates

**Comment by Jorys-Paulin** [comment]
And there's no stuttering on your shield? Weird...

**Comment by boostjunkie92** [comment]
Shield streams perfectly at 4k60

**Comment by hifihedgehog** [comment]
I had the same problem but I found the cause and it was not packet loss as others have suggested, either. Because Moonlight is running within a Chrome session, other Chrome extensions are enabled and they can potentially interfere with the video streaming. It turns out if I have any of my ad-blocking and video downloading extensions enabled, Moonlight stutters incessantly. I simply disabled each extension one by one, and then the experience was buttery smooth. I strongly suggest to the developers to recommend that users disable other Chrome extensions when streaming or the streaming experience could likely suffer.

**Comment by hifihedgehog** [comment]
Another likely possibility I also forgot to mention: the latest Intel HD Graphics drivers have gotten especially buggy over the summer. The August release will start stuttering after about 3 minutes of video streaming. The latest October release, which is evidently trying to boost GPU more to be more competitive with the mobile Raven Ridge APUs, has gotten to point of being completely unstable and unusable. It causes system-wide stuttering every 5 to 10 seconds on many 15W ULV Core systems including my Surface Pro 4 i7. Version 4627 seems to be the only release that has no issues with stuttering at streaming or system-level.
