### ISSUE TITLE
WebGL is not supported

### ISSUE THREAD

**Issue by KanBiiru** [moonlight-stream/moonlight-chrome#284]
When I try to install the .crx I get the error on top of the extension page "WebGL is not supported"

Chrome Build 59.0.3071.115
Windows 10 64bit

**Comment by jacobmix** [comment]
What does it say when you go to `chrome://gpu`?

**Comment by KanBiiru** [comment]
I figured it out. For some reason my Hardware Acceleration was turned off in Settings. I thought I saw it enabled under flags but apparently not. 

Thanks for helping
