### ISSUE TITLE
Chromebook screen stretching like the android app

### ISSUE THREAD

**Issue by RiverCambria** [moonlight-stream/moonlight-chrome#285]
Not really a bug but an improvement:
The chromebook plus runs 3:2 aspect ration and when using the chrome extension there are black bars boxing in the image at 16:9 or 10. I primarily use the android app now because the chrome extension doesn't support display stretching. I tried custom resolutions on the host machine but no luck.

**Comment by Jorys-Paulin** [comment]
@RiverCambria This app wasn't really meant for custom resolutions and display ratios.
