### ISSUE TITLE
Connection not working from phone

### ISSUE THREAD

**Issue by Fiirewolvar** [moonlight-stream/moonlight-chrome#288]
Me and a friend are trying to play a game with splitscreen multiplayer together, so we've both installed Moonlight. I did everything specified in the setup instructions, but it's not even working from my phone.

My computer appears online but when I try to pair with it, it gives the error message "Fetching Server Info Failed - The connection to the PC was interrupted" and sometimes switches to offline, then switches back to online a short while later. It also isn't working when my friend tries to connect, even though I have port forwarded and done everything specified in the setup guide. This is using Moonlight chrome version 0.7.3. It successfully gave me a code to enter once, though the window to enter it on my desktop did not appear.

**Comment by Jorys-Paulin** [comment]
@Fiirewolvar Moonlight chrome is not meant to run on phones. Plus, connecting two Moonlight client to one GeForce Experience host will confuse it, if not crashes it completely.
