### ISSUE TITLE
Option to Disable Controller Support

### ISSUE THREAD

**Issue by NightHammer1000** [moonlight-stream/moonlight-chrome#289]
An Option to disable Controller Support Completly would be Awesome because Games like PLAYERUNKNOWNS shows Controller Buttons if you play it with Mouse and Keyboard.

**Comment by Jorys-Paulin** [comment]
@NightHammer1000 It might be because of GeForce Experience, so we can't do anything about it sadly...

**Comment by NightHammer1000** [comment]
https://github.com/moonlight-stream/moonlight-android/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device
