### ISSUE TITLE
Game starts, No stream

### ISSUE THREAD

**Issue by kingcailan** [moonlight-stream/moonlight-chrome#290]
I'm able to connect and open a game, but I will never get a stream. I've found where the error is happening, but am unable to solve the problem, as I don't know how. I have a full log attached, but the TLDR is:

> #4(I)[2017-07-31 08:21:52,372]=03:21:52={00001F3C}<AdapterContext>   Initialized CUDA for device 'GeForce GTX 1070' (SM 6.1) in compute mode 'CU_COMPUTEMODE_DEFAULT'.
#5(I)[2017-07-31 08:21:52,372]=03:21:52={00001F3C}<VideoFrameProvid> Initializing Fbc6FrameProvider.
#6(I)[2017-07-31 08:21:52,373]=03:21:52={00001F3C}<FbcUtil>          Loaded library from 'C:\WINDOWS\system32\NvFBC64.dll'
#7(E)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<Fbc6FrameProvide> Failed to create FBC. Another instance exists and concurrent capture is not supported.
#8(I)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<Fbc6FrameProvide> Unloading FBC library
#9(I)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<VideoFrameProvid> Initialization error.
#0(E)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<VideoPipeline>    Failed to start: Failed to initialize video frame provider: SERVER_TERMINATED_VFP_ANOTHER_INSTANCE_ACTIVE
#1(W)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<NvThread>         Failed to quit native thread: CaptureThread (thread id: 00000000)
#2(I)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<VideoFrameProvid> Stopping Fbc6FrameProvider.
#3(E)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<VideoFrameProvid> Provider already stopped.
#4(I)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<VideoFrameProvid> Deinitializing Fbc6FrameProvider.
#5(E)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<VideoFrameProvid> Provider already deinitialized.
#6(E)[2017-07-31 08:21:52,384]=03:21:52={00001F3C}<VideoEncoder>     Encoder already stopped.
#7(E)[2017-07-31 08:21:52,385]=03:21:52={00001F3C}<VideoEncoder>     Encoder already deinitialized.
#8(I)[2017-07-31 08:21:52,402]=03:21:52={00001F3C}<AdapterContext>   Deinitialized CUDA context for adapter 0.
#9(I)[2017-07-31 08:21:52,407]=03:21:52={00001F3C}<AdapterContext>   Deinitialized context for adapter 0
#0(E)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<VideoStreamer>    Failed to start video pipeline.
#1(E)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<VideoStreamer>    Failed to setup encode config.
#2(E)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<NvscStreamingSes> Failed to create video stream 0.
#3(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<SciThread>        Sent event StreamAttemptFailed: 
#4(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<NvscStreamingSes> Starting teardown
#5(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<NvscStreamingSes> Quit requested, waiting on child threads to quit
#6(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<NvscStreamingSes> Termination reasons:
#7(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<NvscStreamingSes> - Source 'VideoPipeline', reason 'Failed to start: Failed to initialize video frame provider.', code 0x9300 SERVER_TERMINATED_VFP_ANOTHER_INSTANCE_ACTIVE
#8(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<cryptoutils>      SHA-256 input in hex: 64306230343335342D626436372D343637632D623136372D356334653931663032333433 [72]
#9(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<cryptoutils>      SHA-256 Hash in hex: A2198573096840BA83A4D4BB23C26098B14D0EC8C88E2E5672E951C8F484ED72 [64]
#0(I)[2017-07-31 08:21:52,408]=03:21:52={00001F3C}<ClientControl>    Client control thread terminating
#1(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<ClientControl>    Notified the client that the server is terminating with reason 0x9300
#2(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<ClientControlNew> Trying to release connection
#3(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<EnetMessageConne> Set message listener (channel ID: 0)
#4(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<ClientControlNew> Connection released
#6(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<VideoStreamer>    Destroying video streamer.
#5(I)[2017-07-31 08:21:52,411]=03:21:52={000019A8}<ClientControl>    Client control thread terminating
#7(W)[2017-07-31 08:21:52,411]=03:21:52={000019A8}<ClientControl>    Client control thread already terminated
#8(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<NvscStreamingSes> Termination reasons:
#9(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<NvscStreamingSes> - Source 'VideoPipeline', reason 'Failed to start: Failed to initialize video frame provider.', code 0x9300 SERVER_TERMINATED_VFP_ANOTHER_INSTANCE_ACTIVE
#0(W)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<NvscStreamingSes> Terminated unintentionally with reason 0x9300
#1(I)[2017-07-31 08:21:52,411]=03:21:52={00001F3C}<SciThread>        Sent event StreamDisconnectUnintentional: SERVER_TERMINATED_VFP_ANOTHER_INSTANCE_ACTIVE

It has something to do with the video frame provider, at least from my point of view.
[NvStreamerCurrent.txt](https://github.com/moonlight-stream/moonlight-pc/files/1186876/NvStreamerCurrent.txt)

**Comment by Jorys-Paulin** [comment]
> Failed to create FBC. Another instance exists and concurrent capture is not supported.

Is there another stream running at once? Seems like so.

**Comment by Xedox99** [comment]
The other instance running is ShadowPlay. You will need to turn off ShadowPlay or deactivate the whole "Share"-Interface. You could also try to reinstall GeforceExperience. Normally ShadowPlay should turn off, as soon as the stream starts
