### ISSUE TITLE
Can we turn off auto graphics settings

### ISSUE THREAD

**Issue by boostjunkie92** [moonlight-stream/moonlight-chrome#291]
Like the title says is there a way to turn off the Nvidia optimization within moonlight? I have mine disabled on Nvidia control panel and on my shield but there doesn't seem to be an option for moonlight.

**Comment by Jorys-Paulin** [comment]
@boostjunkie92 When moonlight is initializing a connexion, it passes an argument to enable or not game optimization. Unfortunately, it's barcodes and not accessible from the user UI.

**Comment by boostjunkie92** [comment]
i smell a feature request!! but ya its only because i run dsr at 4k instead of msaa and when streaming to a 1080p screen such as my laptop it sets my in game resolution to 1080p which looks like shit

**Comment by Jorys-Paulin** [comment]
@boostjunkie92 Well I don't see why it would run your `4K` game in `1080p`. Maybe your game can't be streamed in 4K, however that's at GeForce Experience's discretion.

**Comment by boostjunkie92** [comment]
On moonlight I set it to stream 1080p because the screen is only 1080p...I only stream 4k to my TV but I always leave in game setting at 4k whether I'm streaming 4k or 1080p because when I'm streaming 1080p the 4k setting acts as AA

**Comment by Jorys-Paulin** [comment]
@boostjunkie92 So basically your host is rendering a 4K image that is presumably downscaled to 1080p to be streamed to your client? It should work fine as long a GeForce knows it has to downscale...

**Comment by boostjunkie92** [comment]
Yes it works fine but when streaming at 1080p geforce optimization will set in game graphics to 1080p at every startup having to switch my graphics settings Everytime I stream via TV or laptop...being able to turn off optimization thru moonlight would solve this issue...streaming 4k thru moonlight isn't an option because I get heavy stuttering

**Comment by Jorys-Paulin** [comment]
@boostjunkie92 Optimisations gets enabled [around here](https://github.com/moonlight-stream/moonlight-chrome/blob/master/static/js/utils.js#L445). I don't remember Wich one of the options does it, but by default it is `true` and we need to change it to `false` to disable those optimisations.

**Comment by boostjunkie92** [comment]
The line is [here](https://github.com/moonlight-stream/moonlight-chrome/blob/master/static/js/index.js#L601). You would just need to change the 1 to a 0 but I'm talking about adding the option to gui settings

**Comment by Jorys-Paulin** [comment]
@boostjunkie92 Sure! It would be an easy add, just a switch or toggle button should do the trick. I'll see what I can do once I come back from my vacation, I promise!

**Comment by boostjunkie92** [comment]
Awesome! Have a beer for me!

**Comment by T0LL0** [comment]
It would be a really nice feature. Then I would't have to change resolution manually back to my default setting after using moonlight

Android app does have this switch.
"Optimize game settings
Allow GFE to modify game settings for optimal streaming"

**Comment by Jorys-Paulin** [comment]
Thing is,  adding stuff to the code is complicated,  since the code is a little messy. Even if it's just a check box and a variable.
