### ISSUE TITLE
"WebGl is not supported" error

### ISSUE THREAD

**Issue by kriekprinsloo** [moonlight-stream/moonlight-chrome#294]
When I try to install the .crx file in the [chrome://extensions/](chrome://extensions/) page, it tells me that "WebGl is not supported" and it doesn't install the file.  Does anyone know what is going on?
![screen shot 2017-08-06 at 11 17 44 am](https://user-images.githubusercontent.com/3825678/29005837-f50c9ef4-7a98-11e7-9b4a-3017e6dc6cb9.png)
I am using Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by dead** [comment]
Duplicate #284 ?

**Comment by kriekprinsloo** [comment]
Eh. That's why.  My mac is too old.  I am currently using a "Intel HD Graphics 3000 512 MB" graphics card.

**Comment by Jorys-Paulin** [comment]
@kriekprinsloo Well if your problem if solved, you can close this issue. Otherwise, we'll here to help!
