### ISSUE TITLE
input lag with emulated xinput(UCR)

### ISSUE THREAD

**Issue by jabujabu** [moonlight-stream/moonlight-chrome#295]
HI, my host spec is i7 6700/gtx 1070.
and guest spec is i7-4770HQ /iris pro 5200

I'm using bluetooth gamepad(joycon) as emulated x360 contoller generated in UCR(remapper program)

Steam in home Streaming working flawlessly with same setup, but moonlight has extreme input lag.(abt 2-3seconds delay)
everything is OK such as Screen streaming but only gamepad is laggy.

keyboard and mouse is completely working fine(both are wireless).

I guess it's only emulated xinput related thing??

Hopefully I'll appreciate this will be pushed to feature request, thank you

PS. I did some experiment with 'lighter' setup that hand made profile in UCR excluding all anlalog axis, result was much less input lag happens, but still slower than steam in home streaming(which is also with analog).

PS2. I just found my wifi(and router) is 2.4ghz. changing only router could be the solution?

**Comment by Jorys-Paulin** [comment]
Hey @jabujabu,
- Emulated controllers always have a performance impact, but it shouldn't be so important
- Changing your router's speed might be a solution only if the input lag happens between your two PC's rather than inside your guest, Wich might be the case.

**Comment by jabujabu** [comment]
Thx for the answer. I assume that this input lag could comes from ghosting input issue. Because my xinput device is emulated, it has dual ghosting (xinput(joycon driver(nintendo's orginal driver))). I assume that Moonlight's current gamepad mapping(using chrome built-in) doesn't love this(getting all ghosting input data together) .

Hopefully, if button mapping or gamepad device choosing tab menu is available on next version(I've seen some reply it's working on) and ghosting input data could be muted.

I was wondering if there is any workaround for now to manually map or select gamepad device?

**Comment by Jorys-Paulin** [comment]
@jabujabu Well I don't think so. It could be implemented by Moonlight, but on the `C++` side, Wich I don't know at all, but **it's still possible though.**
