### ISSUE TITLE
Unplayable FPS Drop During Active Gameplay (Combat). Possible Audio related?

### ISSUE THREAD

**Issue by Jayblez** [moonlight-stream/moonlight-chrome#296]
I was attempting to play Enter the Gungeon with two different friends of mine (one at a time). I was the host and they were client side. They had minimal input lag at the beginning of the game and while navigating menus, but when we entered the "gungeon" to begin fighting they would experience crippling FPS drops to the point their game would be unplayable from their (client side) end.

I tested this on an additional game, Hero Siege. Selecting characters and navigating menu's was fine but the moment they game started and they could move they experiencing massive FPS drops and could not play. The beginning of Hero Siege and Enter the Gungeon have no action/combat however I believe Enter the Gungeon has no ambient music and almost no moving sprites aside from the characters. While on the other hand, Hero Siege has quite a few active sprites and I believe also has music playing. 

Regrettably I don't know how to post any logs or anything but I would greatly appreciate help from the community. I have GTX 1080 and when I look through my performance tab nothing even spikes past 40% use while gaming and streaming. My internet doesn't dip or anything either while streaming so yeah, not too sure but this isn't quite my forte either.

**Comment by Jorys-Paulin** [comment]
Hey @Jayblez, indeed it is a very interesting problem. Do these games appear in the GeForce Experience tab as "Optimization available". I've seen some problems with games like that that weren't supported by GFE for streaming. How about these games?

**Comment by GeloRuse** [comment]
I can confirm such issue may be occuring with the games that are not available for optimization in GFE tab. 
I tested some games and huge FPS drop occur in following games:
1) Metal Gear Solid 2 (PC edition, not emulated) - during the intro and gameplay; menu had stable FPS.
2) Thimbleweed park - during whole game, especially during screen panning.
3) Berserk and the Band of the Hawk - during whole game.
BUT the issue didn't occur in LISA the Painful.
As host i tried lowering game resolution/graphics where it was possible - no effect.
Client tried lowering stream quality - no effect.
