### ISSUE TITLE
UI Controller Navigation

### ISSUE THREAD

**Issue by pokeguru87** [moonlight-stream/moonlight-chrome#298]
On the UI for selecting the computer and game it would be nice if this UI could be navigated via a controller. My thinking is that I want to run this on a HTPC, so I will be launching Moonlight from Kodi (I can do this already), but this system will not have a mouse or keyboard hooked up to it. I will only have access to a Remote (via a Flirc v2 + Logitech Harmony 650 and a Xbox One Controller).

If this is already possible please tell me how. I hooked up a Xbox One Controller and it didn't do anything when I tried.

**Comment by Jorys-Paulin** [comment]
Hey @pokeguru87, I actually made a [pull request](https://github.com/moonlight-stream/moonlight-chrome/pull/246) that added navigation in the menus, but using the `tab` key. Implementing this via a controller has some problems: what of some program is already using this controller? How should we handle user input?

**Comment by pokeguru87** [comment]
You should be able to use Controller support in HTML5. You'd need to keep track of where the "cursor" is or what has focus currently is and shift it appropriately in response to the controller input. I'm not sure of the specifics, as I haven't worked with HTML or JS very much. I have seen it done before. Here is a project where they've done Controller support in a HTML/JS based app: https://github.com/xan105/FFX-X2_LAUNCHER

I understand this might be a rather nice request, so I may give a shot as a learning experience. I've done something similar in C# before, so it would  only be figuring out the language specifics.

**Comment by Jorys-Paulin** [comment]
@pokeguru87 Of course. At first I thought it would be complicated since the fries are using flex and the number of items per row can game with the window's resolution, but implementing this should be as simple as:
```javascript
next(currentItem) // Triggered with "right direction" actions
{
 var nextItem = currentItem.afterElement() // Selects the next element after it
 nextItem.focus() // Makes the next element selected (:active)
}
```

**Comment by AnthraxLeprosyPi** [comment]
Hey guys,

were you able to get this to work?

**Comment by Jorys-Paulin** [comment]
@AnthraxLeprosyPi It would require an implementation, as stated. I'll be looking towards it.

**Comment by AnthraxLeprosyPi** [comment]
@Jorys-Paulin if you could point me into the right direction to give me a jump start I'd offer to have a got at it ;-)

**Comment by Jorys-Paulin** [comment]
@AnthraxLeprosyPi It is very complicated as the code is very messy, but the idea behind is to emulate the tab functionality I added using the controller. So you'll have something like a focus manager which knows every focusable element and has functions to scruple trough them. That's the idea.
