### ISSUE TITLE
Moonlight Chrome can't find/connect to my PC

### ISSUE THREAD

**Issue by evildog1** [moonlight-stream/moonlight-chrome#299]
Hello
I have a problem. Moonlight Chrome can't find my PC and it can't connect to the local IP I have given but all my Android and iOS devices can find and connect to my PC without any issues.
I tested it on Win7 laptop and Win10 laptop. All of my devices connected to the same router and my PC connected with ethernet cable
Anyone know what's the problem?

**Comment by Jorys-Paulin** [comment]
Hey @evildog1, sorry for being late.
- Did you make sure you were running everything in their most recent & stable versions?
- Can you [look into the console](https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs), see what logs out?
- Can you check in `chrome://flags/#enable-nacl` to see if it's turned on?
- Is "WebGL" under `chrome://gpu/` listed as "Hardware accelerated"?

**Comment by evildog1** [comment]
I have found out that AVG Internet Security (around June 2017 updates) started to block Moonlight and pings without any notice. I allowed other PC to ping to my main PC but still couldn't get Moonlight to connect. Since AVG affects emulation performance, I decided to uninstall AVG and now Moonlight works.
