### ISSUE TITLE
Chrome Alpha, Overwatch, blank screen but can hear audio

### ISSUE THREAD

**Issue by snappjay** [moonlight-stream/moonlight-chrome#303]
Hey all.

I have a Macbook Pro (2017) running the latest public beta of 10.13.  

Gaming rig is running 385.41.

Trying to start overwatch ends up with a blank screen from my Macbook, but I can still hear the audio.

**Comment by Jorys-Paulin** [comment]
Hey @snappjay, can you try to update to version `3.9.0.61` of Geforce Experience? Also, make sure Overwatch appears in the "Games" tab of GFE.
