### ISSUE TITLE
Failure to launch games/applications

### ISSUE THREAD

**Issue by drpeanut779** [moonlight-stream/moonlight-chrome#304]
Hello,
   First off want to say thank you to everyone who put their time and effort into this program. About 6 months ago I was able to run moonlight desktop version without issue. Recently I tried to go back and play some games via steam games list/emulator but no luck. Now I tried using moonlight for internet streaming as well as streaming to my laptop on the local network with no success. I will put below as much information as I can to help everyone who wishes to give me a hand.

**Host PC System Specs**

Windows 7 Ultimate SP1
Intel Core i7-3960x
32GB Ram 

GFE version: 3.9.1.61 BETA
[I have also tried the following versions of GFE: v2.11.2.55, v2.11.2.40]
Moonlight version[Chrome]: 0.7.3
GPU: nvidia geforce gtx 1060 6GB
GPU Graphics Drivers: 375.95 

--
I get stuck on this screen: http://i.imgur.com/0r2Pjja.png
Sometimes it doesn't even give me an error code but on occasion it does give me error code 521.

Lastly here is a snapshot of my Technicolor TC8715D port forwarding config. http://i.imgur.com/8vaJvfX.png

**Comment by Jorys-Paulin** [comment]
Hey @drpeanut779,

- Have you considered running the `3.9.1.61` (non-beta) version of Geforce Experience?
- Could you try and see what outputs into the console? `chrome://extensions/` > Moonlight > (While app is running) > Inspect views > `index.html` > "Console" tab.

**Comment by drpeanut779** [comment]
Hello, @Jorys-Paulin 
                     Thanks for taking the time out of your day to help me with this issue. I went ahead and grabbed the text that the index.html(Console Tab) was spitting when I had the app running. Now I collected the console data when I had 3.9.1.61 BETA & 3.9.0.61 version of Geforce Experience. I will attach the files below and the names indicate which version of Geforce Experience was installed. Thanks again for your time and help.

[Console 3.9.1.61 BETA.zip](https://github.com/moonlight-stream/moonlight-chrome/files/1268225/Console.3.9.1.61.BETA.zip)

[Console - 3.9.0.61.zip](https://github.com/moonlight-stream/moonlight-chrome/files/1268227/Console.-.3.9.0.61.zip)

**Comment by Jorys-Paulin** [comment]
@drpeanut779 Alright, from what I see there's nothing interesting to see:
```
messages.js:22 ProgressMsg: Starting RTSP handshake...
messages.js:22 Starting RTSP handshakefailed
messages.js:22 streamTerminated
```

Since the C++ part is not logging to that console it won't help us. I don't know what error exactly happen but you should try usign another flavor of Moonlight (like the java edition), to see if it's related to Moonlight Chrome only or because it is an error related to your host

**Comment by drpeanut779** [comment]
@Jorys-Paulin I have tried the java version of moonlight and it gives me the following error.

GFE error: Streamer could not be initialized. (Error code: 521)

**Comment by Jorys-Paulin** [comment]
So now at least we know that your host, and/or GFE is the problem. Does this happen with the two versions? Btw have-you the latest drivers for your GPU? Oh, and does your game appear in the games tab under GFE.

**Comment by drpeanut779** [comment]
Both versions of moonlight do not launch any game I ask it to. I am currently using outdated drivers at the moment and that is one option we could explore. The games I have installed and are asking it to launch do showup in GFE without any problems.

**Comment by Jorys-Paulin** [comment]
@drpeanut779 Try updating your drivers. More than enough it's the root of the problem

**Comment by drpeanut779** [comment]
@Jorys-Paulin Will do I will update this post once that is done and let you know what driver I updated to.

**Comment by wangzhazha100** [comment]
How to solve the problem "Streamer could not be initialized"
