### ISSUE TITLE
support pen pressure

### ISSUE THREAD

**Issue by cnkr3321** [moonlight-stream/moonlight-chrome#306]
hi
moonlight very useful for work
but I have galaxy book 12
The pressure dose not work
this model support wacom 4096 pen pressure

moonlight-android is maybe support
https://github.com/moonlight-stream/moonlight-android/issues/102

Chrome Is there a way?

**Comment by Jorys-Paulin** [comment]
Hey @cnkr3321, I don't think Chrome as yet any support for pressure or depth detection. If it would get implemented, what kind of software would you use it on?

**Comment by cnkr3321** [comment]
use software is zbrush,illustrator,photoshop
hope when day will support
