### ISSUE TITLE
disable sound option not working?

### ISSUE THREAD

**Issue by Andy2244** [moonlight-stream/moonlight-chrome#307]
I use a Win10<->Win10 connection and the custom "C:\windows\system32\mstsc.exe" application to share my desktop, but i'm not able to disable the sound transfer? The "remote audio" icon is not doing anything for this connection?

**Comment by Jorys-Paulin** [comment]
Hey @Andy2244, according to [the source code](https://github.com/moonlight-stream/moonlight-chrome/blob/master/static/js/index.js#L592), this icon should be functional. This option [is sent](https://github.com/moonlight-stream/moonlight-chrome/blob/master/static/js/index.js#L598) to Geforce experience, but we can't know whether or not is it actually used in any way

**Comment by Andy2244** [comment]
Oki, so maybe we can disable/turn off the incoming audio stream on the client side?

**Comment by Jorys-Paulin** [comment]
So you want to disable the audio streaming? Cause that option just disables your host's speakers.

**Comment by Andy2244** [comment]
I just realized that i can just turn off the audio for the moonlight app on the client side, via windows sound mixer, since i don't use chrome as my main browser. How about a option to disable audio on the client if moonlight app is minimized?

**Comment by Jorys-Paulin** [comment]
@Andy2244 Well, I don't think it's possible with browser code. It could be done with native code though (the NaCl module).

**Comment by Andy2244** [comment]
Ah oki, its just a minor inconvenience, since i don't want the sound on the client. I assume it works for directly started games, opposed to the "mstsc.exe" trick.

thx for the infos

**Comment by fragtion** [comment]
How can we disable audio on the client side entirely? I don't just want to mute it, I want to save bandwidth as well so that all traffic (on our constrained wan link) can be dedicated to the video stream. Any ideas ?

**Comment by cgutman** [comment]
It is not possible with GeForce Experience. It will actually fail to establish the connection if it is unable to establish an audio connection with the client.

**Comment by fragtion** [comment]
@cgutman Thanks for confirming that important distinction for the record as it may help others on the same quest... In which case I'll be happy to use Sunshine server instead. I still need some way to kill the audio stream on client while allowing it to continue as normal on host.  Just wondering, if I pick an interface that is "silent" will this consume less bandwidth?, ie is the audio stream VBR or CBR ? Thnx

**Comment by cgutman** [comment]
It depends on the server. Some versions of GeForce Experience will stop sending audio when it is entirely silent. I believe Sunshine will too (though this may vary depending on the platform).
