### ISSUE TITLE
360 Controller not recognised in Moonlight Chrome on MacOS

### ISSUE THREAD

**Issue by stretchneck** [moonlight-stream/moonlight-chrome#310]
Issues with wired 360 controller not being recognised in moonlight chrome running on MacOS on client PC (Macbook), tested so far:

- wired 360 controller works fine on Windows 10 host pc
- wired 360 controller works fine on macbook pro - all drivers installed and showing input
- wired 360 controller also works perfectly via steam in-home streaming.

Keyboard and mouse work fine via Moonlight, any ideas as to the issue?

**Comment by Jorys-Paulin** [comment]
Hey @stretchneck, could you try html5gamepad.com? That'll help us know if it's chrome related or not. Also try using the native client version.

**Comment by stretchneck** [comment]
Thanks for the tip - html5gamepad.com shows that the 360 controller is working correctly

**Comment by stretchneck** [comment]
Classical solution - rebooted the Mac.  Now everything works fine!
