### ISSUE TITLE
Ui Unresponsive

### ISSUE THREAD

**Issue by Tetrokun** [moonlight-stream/moonlight-chrome#312]
As title says, The UI is not responsive, I do not have a chance to connect to anyhting, as clicking on add new host does nothing, I've tried hitting enter, and clearing the cache for Chromium, I've attached a gif of the issue.
I am running Manjaro with 4.13 kernel. 
![peek 2017-09-12 00-02](https://user-images.githubusercontent.com/5799926/30314798-e17ece72-976f-11e7-94c8-0dfdb4d65294.gif)

**Comment by Jorys-Paulin** [comment]
Hey @Tetrokun, I also see that UIs that aren't supposed to be here are shown, like the "Quit current app". I think it's because Jquery or any of the scripts get loaded, or they aren't compatible with this version. Cloud you check the console for errors?

**Comment by Panderine** [comment]
I'm having the same issue with chromium on ubuntu  but I don't have the "top bar" only the add host button. I tried the same with chrome on windows without issues. Dunno what is going on with chromium.

**Comment by Jorys-Paulin** [comment]
Again, latest version of chrominium? What about the latest version?

**Comment by Panderine** [comment]
yes fresh install from repos today .How can I check the console for a chrome app?

**Comment by Jorys-Paulin** [comment]
Here: https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs. Make sure your JavaScript is enabled and working.

**Comment by Panderine** [comment]
Browser doesn't support native client or it's disabled.

I don't have a nothing in chrome://flags for native client in chromium, but
I do in my chrome install on windows.

**Comment by Panderine** [comment]
appears from http://code.google.com/p/chromium/issues/detail?id=109989 that NaCl works if you download the official google version and not the Ubuntu distributed package (lame).

**Comment by Panderine** [comment]
Fixed it, I had to install Google Chrome from their webpage. Chromium doesn't have NaCl support anymore. 

Also seems that this will be deprecated on 2018:
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1462647

**Comment by Jorys-Paulin** [comment]
@Panderine Hopefully WebAssembly will soon be supported widely enough and the `VideoDecoder` will also be ported, maybe enabling Moonlight to be an app that runs on a single webpage

**Comment by Tetrokun** [comment]
Thanks for the input guys, @Panderine IS correct about the NaCl bit, Actually I thought they removed support for NaCl plugins in the normal branch of chrome.
