### ISSUE TITLE
Mouse Delay

### ISSUE THREAD

**Issue by Pvehard** [moonlight-stream/moonlight-chrome#313]
I read that the Mouse Delay issue was resolved in 7.3 but I am using 7.4 and still have a 200-500MS delay on my mouse. I have tried everything that Google has provided as way of troubleshooting. 

1. I have set both the client and server to have the same mouse speed
2. I have removed Razer Synapse completely
3. I have enabled the option "Override software rendering list Mac, Windows, Linux, Chrome OS, Android Overrides the built-in software rendering list and enables GPU-acceleration on unsupported system configurations. #ignore-gpu-blacklist"
4. I have unplugged any gaming mice in on the server as well as left a plain jane Dell mouse plugged in
5. I have used both wired and wireless on the client
6. I have lowered the Mbps in Moonlight, (this just made the stream look like crap but didn't affect the mouse at all.
7. I have made sure the "Enhanced Pointer" option in the mouse settings was disabled on both client and server
8. I have removed TeamViewer completely 

I am using Moonlight to access my PC at home. I have 90 down 15 up at home and at work we have 500 Mbps down and 800 Mbps up. It's is not a connection problem because when I use TeamViewer I have no mouse delay at all. The only issue I have with Moonlight is the Mouse Delay. If we can resolve this, it will be the perfect solution to my situation.

**Comment by sjohnsox** [comment]
Similar issue as Pvehard. Running 7.4.

Adding to this, I tried the beta of Geforce Experience, currently running 3.9.1.61 BETA. Have no mouse software installed. When performing streaming through steam (local area only) this mouse delay issue does not exist. The host desktop just has a USB plugged in Logitech Mouse. My laptop just uses the touchpad or a wireless logitech mouse.

**Comment by cgutman** [comment]
Can you make sure it's really mouse delay and not general video delay? Try streaming locally while sitting next to the host computer and moving the mouse on the host directly.

**Comment by jerom007** [comment]
I have used all same advices to set mouse speed on host and client and other tips with no success.

After some weeks, I realized that there was No Mouse Lag when using a laptop with Windows 10, same OS as on host !
(It was Windows 7 before on client...)

So try to use the SAME OS on your client and host machines (be it win7, 8 or 10) !!
Best of luck,
