### ISSUE TITLE
Shield tab not appearing in GeForce Experience

### ISSUE THREAD

**Issue by ohayondotio** [moonlight-stream/moonlight-chrome#317]
I'm attempting to use moonlight-chrome and am not able to add my GeForce server to the application. 

I have tried to access myip:47989/serverinfo only to find that there is no geforce server running and that the page doesn't load. Googling lead me to find that I should enable the shield options in GeForce Experience, but I do not have the tab. I updated my graphics drivers to the latest version, tried the latest GeForce Experience as well as the beta and restarted multiple times throughout the process but I still do not have the tab and am not able to add my PC. I have also added firewall exceptions in windows firewall just in case it was causing issues. 

Has anyone been able to resolve this issue? I'm using a GTX 970.

**Comment by cgutman** [comment]
Check the compatibility issue list for known issues: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#known-application-compatibility-issues

Do you have any anti-virus software installed?

**Comment by lohayon5** [comment]
Hello, 

I do not have any 3rd party anti-virus and have tried disabling Windows Defender to see if it wasn't causing any issues. I went through the compatibility issues, uninstalled teamviewer, rebooted and tried again but I still do not see anything at 127.0.0.1:47989/serverinfo and no shield tab in the GeForce Experience settings. 

Thanks.

**Comment by Skitzzy** [comment]
Having the same problem

**Comment by Jorys-Paulin** [comment]
@Skitzzy Check for compatibility in the main settings panel (right where there is VR ready indicator) or reinstall completely GeForce Experience.

**Comment by chestarss** [comment]
Please check that your monitor is connected to the NVIDIA GPU output and not the integrated graphics output of the motherboard.
