### ISSUE TITLE
Question: Can you do multiple monitors?

### ISSUE THREAD

**Issue by j4adam** [moonlight-stream/moonlight-chrome#318]
I use the moonlight chrome plugin for many things, and a few of the uses are programs that I have the workspace stretched out across two monitors. I have two monitors at my remote location (laptop + TV usually) would like to be able to use both but I can't figure out how / if it's possible.

**Comment by Jorys-Paulin** [comment]
Hey, @j4adam!
Unfortunately, as **a client** we can't really implement new features that **aren't already implemented** on the other side, ie Geforce Experience.
If moonlight was also a server, then surely we should be able to implement it, by the main developers or even contributors like me.

**Comment by Papermanzero** [comment]
With sunshine it should be possible now
https://github.com/loki-47-6F-64/sunshine

**Comment by dada513** [comment]
Any update? Sunshine exists now

**Comment by Jorys-Paulin** [comment]
This could be implemented for setups using Sunshine, though it would probably be only for [Moonlight Qt](https://github.com/moonlight-stream/moonlight-qt). I've created a post on Moonlight's Feedback site, you can take a look here: https://ideas.moonlight-stream.org/posts/109/multiple-monitors
