### ISSUE TITLE
Chrome on Windows can't pair; Java, iOS, Android all work

### ISSUE THREAD

**Issue by Emstar** [moonlight-stream/moonlight-chrome#319]
I have a server which I am able to reach over the internet via iOS, Android, and Java clients, but my Windows machine is unable to connect with the Chrome client. When I try to "Add Host," in the Chrome app, the Moonlight client does nothing at all. The connect dialog vanishes when I click Continue, as expected, but then NOTHING happens... No error, nothing.

I can reach the server and stream successfully from iOS and Android, AND the legacy 64-bit Java client on Windows... all on the same wifi network, so there is something about the Windows Chrome client that is not working right.

The troublesome Chrome client DOES pair and stream over my LAN. 

I've tested with the client's Windows firewall completely off too--no change.

I hate to say it's a bug, but it kind of feels like a bug since I can prove that port forwarding is set up correctly via testing with Android, iOS, and Java. 

What should I try next? If this is a real bug, how do I gather useful data for the devs?

**Comment by Specthram** [comment]
hi,
I have the same issue. It work everywhere excepted on the chrome extension.

**Comment by cgutman** [comment]
Please go to about://flags and enable the option called `#debug-packed-apps` and restart Chrome. Then start Moonlight, right click on a blank area and click Inspect, open the console, reproduce the bug, then upload the console output here.

**Comment by Emstar** [comment]
Thanks for the instructions! I will do that in a day or two.

**Comment by Emstar** [comment]
So here I am at my favorite watering hole, ready to write a nice bug report with debug data... And it works now. Same wifi network, same everything as when I reported the issue. The computer had not even been restarted, having spent most of the time between then and now asleep. 

There was only one difference--I did turn on the debug flag before starting Moonlight. In case that somehow made a difference, I turned the flag off and tried again. Nope, same result, it's working correctly. 

Well, if it happens again, I'll I know what to do now. Perhaps it was an issue with the local internet connection that was not apparent during normal web browsing. 

I'll leave this issue open since a couple other people had the same problem, in case someone wants to post their logs.

**Comment by Specthram** [comment]
hi,
this is the log : 
```
common.js:320 common.js: Page loaded.
common.js:320 common.js: Browser supports NaCl (pnacl)
common.js:320 common.js: Creating embed: pnacl
Roboto-Light.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
Roboto-Medium.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
Roboto-Regular.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
index.js:800 Window loaded.
index.js:872 Loaded previously connected hosts.
common.js:320 common.js: RUNNING
index.js:502 entering show hosts and settings mode.
Roboto-Black.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.js:27 IPv6 address unsupported 2a01:cb1d:8275:dc00:d0e:f89f:88bd:e88
main.js:27 IPv6 address unsupported 2a01:cb1d:8275:dc00:f0a2:8e65:1472:9f8a
main.js:27 IPv6 address unsupported fe80::d0e:f89f:88bd:e88
main.js:30 Broadcasting to address 192.168.1.13
main.js:27 IPv6 address unsupported 2001:0:9d38:6abd:104f:15df:fdfb:dbf2
main.js:27 IPv6 address unsupported fe80::104f:15df:fdfb:dbf2
utils.js:35 NvHTTP {}
messages.js:22 https://x.x.x.x:47984/serverinfo?uniqueid=6d361f0533ddd558&uuid=d883272d-c8d9-41d9-8d81-18a80c392379
messages.js:22 https://x.x.x.x.local:47984/serverinfo?uniqueid=6d361f0533ddd558&uuid=b39c2c56-6684-421c-b52d-d601dd2fcbe2
messages.js:22 https://:47984/serverinfo?uniqueid=6d361f0533ddd558&uuid=e9f0c417-f4bb-498a-adf7-e490bc66b560
messages.js:22 https://x.x.x.x:47984/serverinfo?uniqueid=6d361f0533ddd558&uuid=4d6ef933-f224-4a2d-9f2c-497b233fd88a
utils.js:168 WARN! Failed to contact host: x.x.x.x
server address: x.x.x.x
server UID: 
is paired: false
current game: 0
server major version: 0
appversion: 
GFE version: 
gpu type: 
number of apps: 0
supported display modes: 

index.js:166 Failed to connect to x.x.x.x! Are you sure the host is on?
index.js:235 server address: x.x.x.x
server UID: 
is paired: false
current game: 0
server major version: 0
appversion: 
GFE version: 
gpu type: 
number of apps: 0
supported display modes: 

index.js:166 pairing to x.x.x.x failed!
```

**Comment by Specthram** [comment]
ok we found the reason : Kaspersky is blocking the connection because of certificate check
