### ISSUE TITLE
Can't run make file (Debian/SteamOS)

### ISSUE THREAD

**Issue by vjr2** [moonlight-stream/moonlight-chrome#320]
I just followed the instructions for installing the addon step by step and I can't do the last one

1) Install the Chrome Native Client SDK and download the current Pepper SDK = **DONE**

2) Set the NACL_SDK_ROOT environment variable to your Pepper SDK folder. If you need more detailed instructions, see here = **DONE**

3) Run git submodule update --init --recursive from within moonlight-chrome/ = **DONE**

4) Run make from within the moonlight-chrome/ repo = **FAIL**

The error I get is:

 `Makefile:15: /path/to/nacl_sdk/pepper_31/tools/common.mk: No existe el fichero o el directorio
make: *** No rule to make target '/path/to/nacl_sdk/pepper_31/tools/common.mk'.  Alto.`

(sorry I have a spanish interface ssh). 

What could be the mistake?

**Comment by cgutman** [comment]
Pepper 31 is ancient. You should be using at least Pepper 49.

**Comment by vjr2** [comment]
I'm using Pepper 49. But the error says I don't have the pepper_31

**Comment by cgutman** [comment]
What's your NACL_SDK_ROOT?

**Comment by vjr2** [comment]
My nacl_sdk is in my "downloads" folder, but I just typped just what the tutorial said: "export NACL_SDK_ROOT=/path/to/nacl_sdk/pepper_31"

Could be that the paths aren't the same? How do I fix this?

**Comment by vjr2** [comment]
Can't you just upload a made crx file for the extension? I've expended all the day in this with no results

**Comment by cgutman** [comment]
There are CRX files on the releases page - https://github.com/moonlight-stream/moonlight-chrome/releases

**Comment by vjr2** [comment]
Really?? Uuuugh and me trying to make the crx step-by-step. Wow I'm am insanely dumb. Thanks you very much

**Comment by Jorys-Paulin** [comment]
Hey, @vjr2! If your issue is fixed, please close this pull request. Otherwise, we'll be here to help!
