### ISSUE TITLE
Intergration with Visual Studio

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-chrome#321]
Lately, I've been trying out Visual Studio for general development, and then I came across `moonlight-chrome` and opened the `main.cpp` file, only to find out a lot of generated errors.

I've also seen that VS generated its own folder named `.vs`, which wasn't handled by the `.gitignore`.
So here's my question: if some of you are using Visual Studio, do you also have these errors? What config do you use?

**Comment by cgutman** [comment]
I don't use an IDE for Moonlight Chrome. I suspect VS wouldn't work properly due to how the makefiles are set up and I'm not sure whether the NaCl SDK has decent integration with modern versions of VS.

**Comment by Jorys-Paulin** [comment]
So you directly use the online github editor ?

**Comment by Jorys-Paulin** [comment]
@cgutman What IDE do you use for Moonlight?
