### ISSUE TITLE
Using Chromium Ubuntu test build cannot "click" on Add Host!

### ISSUE THREAD

**Issue by vonkoda** [moonlight-stream/moonlight-chrome#323]
Ok so Im using Chromium test as its the only way to get HW acceleration on Chrome in Linux. But I don't know if thats even working as when added as an extension and run, I can see the Add Host button, mousing over it highlights the button but clicking does nothing! So I can't progress past the initial screen.

Seems like an odd problem and has existed in the current version 0.7.4 and the previous.
Chromium is build 62.0.3202.18 and I've enabled the HW Video decode flag (which is disabled on linux Chrome entirely).
Ubuntu 17.04
nVidia driver (tried many no diff) 384.90

**Comment by vjr2** [comment]
I have the same issue, I just added the chromium app on my raspberry pi 3 and it wont work

**Comment by Jorys-Paulin** [comment]
Hey, @vonkoda and @vjr2, Could you give us some screenshots?

**Comment by vonkoda** [comment]
Hmm.. you really arent following if you are asking for a picture of the default mainscreen!  Like thats it, you cannot click Add Host therefore you cannot do anything.

See linked:
https://i.imgur.com/3iCKx8b.png

**Comment by vjr2** [comment]
Yeah, I have the same issue

**Comment by dead** [comment]
See https://github.com/moonlight-stream/moonlight-chrome/issues/312

**Comment by vonkoda** [comment]
Oh well, thats that then. Native Client isn't support in Chromium _and_ Hardware Decoding is not supported in Chrome.. leaving Linux users snookered without a workable solution. 
You may as well remove it from supported OS's till (/if) you move to WebAssembly!

**Comment by Jorys-Paulin** [comment]
@vonkoda That's what I meant by screenshots, like in #312 javascript didn't seem to be working. We've already discussed WebAssembly, but a required component isn't available yet.

**Comment by vonkoda** [comment]
@Jorys-Paulin   Fair enough, I take back my cheekiness!

**Comment by vjr2** [comment]
So there is no way to use moonlight chrome on rpi3?

**Comment by Jorys-Paulin** [comment]
@vjr2 There's the Java version

**Comment by cgutman** [comment]
@vjr2 @Jorys-Paulin No, if you're on a Pi, you should be using [Moonlight Embedded](https://github.com/irtimmer/moonlight-embedded).

The Java client won't run on ARM (and would run absolutely horribly even if it could).

**Comment by Jorys-Paulin** [comment]
Ho right, my fault.

**Comment by cgutman** [comment]
No worries!

**Comment by cgutman** [comment]
@vjr2 Which distro are you using? Chrome/Chromium definitely still supports NaCl, so your distro must not be enabling it during the build.

**Comment by vjr2** [comment]
Im using the last build of Chromium. And it doesn't support NaCl. And if it does I don't know how to enable it

**Comment by cgutman** [comment]
@vjr2 What distribution of Linux are you using? Google doesn't provide builds of Chromium, so you must be getting them from some other source, like your distro.

**Comment by vjr2** [comment]
I'm using Raspbian. And raspbian has Chrome with the OS-pack

**Comment by vjr2** [comment]
And moonlight chrome runs fine in raspbian... is just I can't add the host because the button doesn't work

**Comment by cgutman** [comment]
The package maintainer(s) for Chromium in Debian (on which Raspbian and Ubuntu is based) has not enabled NaCl in the official packages, so Moonlight Chrome and other NaCl-based plugins (like Chrome Remote Desktop) will not work.

See `enable_nacl=false` in their Chromium package source in https://anonscm.debian.org/cgit/pkg-chromium/pkg-chromium.git/tree/debian/rules?id=794aa1820460727711e534ea1042db7eebc1601d#n48

**Comment by vjr2** [comment]
and there is not way to enable it? I want to use chrome's version because I have problems with the embedded version (I can't pair no matter what)

So is there a way to enable NaCl in chromium?

**Comment by cgutman** [comment]
To be clear, Chromium proper (Google's upstream) does and will continue to include NaCl through at least Q1 2018. Your distribution's build of Chromium has purposefully removed NaCl for some reason. You can't enable NaCl if it's not included when the package was built.

I think a more fruitful use of your time would be determining why Moonlight Embedded won't pair, since Moonlight Chrome may just run into that same issue if you get a build with NaCl enabled. I'm also fairly certain Moonlight Chrome's rendering performance won't be as good as Moonlight Embedded's.

**Comment by Jorys-Paulin** [comment]
It could also be that JavaScript might not work, making the ui broken (you see My hosts and My games were you shouldnt), wich is why I asked for screenshots
