### ISSUE TITLE
Need more precision in bandwith cursor for lower uplinks

### ISSUE THREAD

**Issue by ppeltriaux** [moonlight-stream/moonlight-chrome#326]
Hi,

We need to be able to adjust more precisely the bandwith cursor at for lower uplink speed for chrome moonlight.
It goes from 1.5Mbps to 2.5Mbps and then 3.5Mbps, can you please make 2Mbps and 3Mbps available as well via the cursor?

Thanks

Pascal

**Comment by cgutman** [comment]
@Jorys-Paulin Hmm, do you have some thoughts here? It's declared with `step="0.5"` but when using it via the mouse it tends to most often act as if `step="1.0"`.

**Comment by ppeltriaux** [comment]
Hi, I tried many times, it goes from 3 to 2.5 and then 1.5, there s no way
to set it to 2

Le jeu. 5 oct. 2017 à 13:22, Cameron Gutman <notifications@github.com> a
écrit :

**Comment by Jorys-Paulin** [comment]
@cgutman The slider component in MDL is kinda weird. When you use big numbers, like from 0 to 200, you don't have much space to be precise with the mouse. However, you can **use the keyboard** to input more precise values, just make sure **the slider has focus**.

**Comment by ppeltriaux** [comment]
I tried using keyboard but i cannot have the slider move with any keys, i
tried with and without focus, every single key of the keyboard.
What key did you used to move it?

Pascal

**Comment by ppeltriaux** [comment]
my bad, i finally got it working with holding the mouse clicked and moving
with arrow  keys,

Thanks

**Comment by owenwalker92** [comment]
You can also press tab once and it'll select the slider bar, can then use arrow keys to adjust in 0.5 increments.

**Comment by Jorys-Paulin** [comment]
Good thing it worked. If you're done you can close this issue, otherwise I'll still be there.
