### ISSUE TITLE
Forever stuck on "Loading Moonlight Plugin..."

### ISSUE THREAD

**Issue by Adaman120** [moonlight-stream/moonlight-chrome#327]
Hello, I've been trying to get Moonlight working, but it continually hangs on "Loading Moonlight Plugin" indefinitely.

I've tried updating my NVIDIA drivers, Chrome, the Moonlight extension, and Java. I've tried disabling my anti-virus too. I've made sure that all my ports are forwarded properly and it still refuses to work.

I've tried various solutions posted in this forum, but none of them seem to apply to me.

As a last-ditch effort, I'm posting a new thread to see if someone more knowledgeable can lend a hand. Below is a debug log. I hope someone can make sense of it and point me towards a working solution.

`common.js:320 common.js: Page loaded.
common.js:320 common.js: Browser supports NaCl (pnacl)
common.js:320 common.js: Creating embed: pnacl
index.js:744 Window loaded.
index.js:798 Loaded previously connected hosts.
index.html:1 NativeClient: Data Execution Prevention is required but is not supported
common.js:320 common.js: ERROR [NaCl module load failed: Data Execution Prevention is required but is not supported]
index.html:1 NativeClient: PnaclCoordinator: Compile stream init failed: reply not received from PNaCl translator (it probably crashed)
common.js:320 common.js: ERROR [NaCl module load failed: PnaclCoordinator: Compile stream init failed: reply not received from PNaCl translator (it probably crashed)]`

Thanks for taking the time to look into my issue.

**Comment by Jorys-Paulin** [comment]
Hey @Adaman120, from what I can see your chrome version doesn't seem to support nacl very well: `Data Execution Prevention is required but is not supported `. Which system are you running moonlight on?

**Comment by Adaman120** [comment]
Hello @Jorys-Paulin. I am running a 64-bit Home version of Windows 7. It is a legit copy that has all updates, if that even matters. I should also mention that I have downloaded everything else Moonlight requires (Such as Micosoft Silverlight).

**Comment by Jorys-Paulin** [comment]
@Adaman120 Are you running an official release?

**Comment by Adaman120** [comment]
Not at the moment. I tried a tweaked version that someone else released, but the problem remains the same. I suppose I could re-download the official release and post a new debug log, if it would make a difference.

**Comment by Adaman120** [comment]
I redownloaded Moonlight Chrome v.0.7.4 and also took the time to enable Native Client in chrome://flags, but the problem still persists. Here is the new debug log.

`common.js: Page loaded.
common.js:320 common.js: Browser supports NaCl (pnacl)
common.js:320 common.js: Creating embed: pnacl
Roboto-Light.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
Roboto-Medium.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
Roboto-Regular.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
index.js:800 Window loaded.
index.js:872 Loaded previously connected hosts.
index.html:1 NativeClient: Data Execution Prevention is required but is not supported
common.js:320 common.js: ERROR [NaCl module load failed: Data Execution Prevention is required but is not supported]
index.html:1 NativeClient: PnaclCoordinator: Compile stream init failed: reply not received from PNaCl translator (it probably crashed)
common.js:320 common.js: ERROR [NaCl module load failed: PnaclCoordinator: Compile stream init failed: reply not received from PNaCl translator (it probably crashed)]`

It looks like part of the old plugin persists, but I'm unsure on how to reset it.

**Comment by Jorys-Paulin** [comment]
Try enabling NaCL here: `chrome://flags/#enable-nacl`

**Comment by Adaman120** [comment]
@Jorys-Paulin I already enabled it. No dice.

**Comment by alex9099** [comment]
same here, native client did not solve the problem

**Comment by raidancampbell** [comment]
@Adaman120 Can you look into the current status of Windows' Data Execution Prevention by using [this link](http://www.thewindowsclub.com/verify-status-data-dep), then possibly enabling it by following the instructions [here](http://www.thewindowsclub.com/disable-data-execution-prevention)?

It looks like a hardware/OS configuration issue from some quick googling

**Comment by cgutman** [comment]
@Adaman120 Hmm, no DEP? What CPU is in your client PC?

Can you also paste the contents of chrome://version/ here?

**Comment by Adaman120** [comment]
@raidancampbell My DEP is currently set to only protect Windows system components and services. DEP should be disabled for everything else. I could try disabling it completely, if you think it would help.

@cgutman I have an Intel Core i7 930. It's one of the earlier i7 models, if that makes any difference. Here's my contents of my chrome version, as you requested.

`

Google Chrome | 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 57c9d07b416b5a2ea23d28247300e4af36329bdc-refs/branch-heads/3163@{#1250}
OS | Windows
JavaScript | V8 6.1.534.41
Flash | 27.0.0.130 C:\Windows\system32\Macromed\Flash\pepflashplayer64_27_0_0_130.dll
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --debug-packed-apps --enable-nacl --flag-switches-end
Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path | C:\Users\Adaman\AppData\Local\Google\Chrome\User Data\Default
Variations | c68ab9a3-3f4a17df3095aa95-3f4a17df7c1bc906-f55a797447e5d3db-3d47f4f4d43bf3e5-bd7cd813ba3f87da-45bda65679616653-f23d1dea5ca89f9-3f4a17df9e201a2b-7e3ae0575b3ed0a1-3f4a17df68812885-4d2fac875e3a236d-4113a79ef347910c-3f4a17dfb791c1b8-3f4a17df9773d3bd-f23d1dea99144bc3-3cc2175e9e5c75f1-2ad3bd2ff79cb77b-3d47f4f427219e67-b204717823a898eb-aaaaf5b14ea303a6-ecbb250e447469ba-ca7d8d807aa46da5-54f5980dde03e059-e65e20f2fbe6bb40-ca7d8d801354da85-f34af386494d8760-91c810eff47ae82a-86f22ee53ac60855-486e2a9cf296190c-90ee16554442aae2-4ad60575ed1d377-e1cc0f1475f0f0a0-4ad60575e2b18481-6bdfffe7e7e71889-e1cc0f14644b8345-ca7d8d8094e68624-3f4a17df828a5926-ca7d8d80
Compiler | MSVC 2015 (PGO)

`
