### ISSUE TITLE
change resollution on connect?

### ISSUE THREAD

**Issue by marcspc** [moonlight-stream/moonlight-chrome#328]
Hi, I like using steamlink because when I connect from my TV, it changes to a lower resolution so everything looks bigger, can Moonlight do the same?

I'm trying to play on a squared monitor when my computer at home hast a widescreen monitor, problem will be worse when I get an ultrawidescreen monitor

thanks

**Comment by Jorys-Paulin** [comment]
Hey @marcscp. You should know that GeForce Experience already can lower your games resolution if it needs to. Moonlight can only accept 1080p and 720p resolutions, as they're the only ones supports by GeForce Experience.

**Comment by muffinmannameistaken** [comment]
GeForce Experience does have support other resolutions you no longer need beta GeForce Experience
