### ISSUE TITLE
[Feature request] Add option to block windows hotkeys.

### ISSUE THREAD

**Issue by oreyg** [moonlight-stream/moonlight-chrome#333]
It would be great if we had an option to disable some key combinations (or pass them to host).

**Comment by Jorys-Paulin** [comment]
Hey @oreyg, what key combinations are you thinking about exactly?

**Comment by oreyg** [comment]
windows key, alt+tab and so on. 
Offtopic: is there a hotkey to stop broadcast and quit?

**Comment by Jorys-Paulin** [comment]
But then how should be handle theses? How to guess if the user wanted to input `Alt+Tab` to the host computer or the client computer?

**Comment by Jorys-Paulin** [comment]
> To exit a stream, press Ctrl+Alt+Shift+Q. (Readme.md)
I never tested but it should work.

**Comment by oreyg** [comment]
The same way virtualization software does. By default all combinations are passed to target machine (or filtered in our case) until user presses ctrl+alt+space. After that all combinations apply to client machine. The filtering itself should be optional.

**Comment by Jorys-Paulin** [comment]
It would be a great idea. I won't go ahead and implement it right now because C++ is not my cup of tea at all. But people like @cgutman could do it.

**Comment by oreyg** [comment]
I'm closing this issue because this is non-priority and issues page is already full of much more relevant tasks.

**Comment by Jorys-Paulin** [comment]
@oreyg Not to mention he's working on a new version, maybe it will include this feature, though some keys like the Meta/Windows key and Alt+Tab seem o be disabled by Geforce experience.
