### ISSUE TITLE
Resolution/view on client is incorrect

### ISSUE THREAD

**Issue by GoldenCoins** [moonlight-stream/moonlight-chrome#334]
Currently with the moonlight chrome client, when streaming any resolution to my 1920x1080p laptop, the view is squished. There is a small area of black at the bottom of the screen (8 pixels exactly) and the image is squished upwards

You can see in this screenshot: http://goldiefoxx.com/69832810.jpg (Taken on the client / laptop) at the bottom, that the task bar on the streamed view is 8 pixels above the taskbar on the client PC

This occurs even when the stream is the exclusive window.

As a result the streamed image is never "crisp" or "clear" because the pixels are not properly aligned.

Is there any way to fix this?

**Comment by Moederbeer** [comment]
I'm having the same issue where I can see part of my taskbar below the "fullscreen" moonlight stream and also a black space all around the image. This makes the image always look aliased no matter which settings I pick in game. So in my case it doesn't look squished but more like it's zoomed out a little.
