### ISSUE TITLE
blackscreen over internet but not same network

### ISSUE THREAD

**Issue by GlennBrone** [moonlight-stream/moonlight-chrome#336]
So basically as the title says, my moonlight shows a blackscreen when I try over internet streaming, but it doesnt when i stream on the same network,

**Comment by cgutman** [comment]
The issue is probably that your port forwarding for UDP 47998 is incorrect or being blocked by some firewall along the way.

**Comment by Jorys-Paulin** [comment]
Hey @GlennBrone, is your issue resolved? If so, you can close this issue, otherwise, we'll be here to help!
