### ISSUE TITLE
New UI for PC and app selection

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#34]
The Moonlight Chrome UI should look and work similarly to Moonlight Android and iOS.

- PCs should be displayed in a grid with icons rather than a dropdown
- All mDNS discovered PCs should be added to the grid automatically
- There should be a separate page or advanced settings panel for adding a PC to the grid by IP address
- After a PC is clicked, if paired, the app grid should be displayed with box art and app titles. If not paired, pairing should begin.
- There should be a separate settings page rather than having the settings stuck at the top

**Comment by raidancampbell** [comment]
@abdallahsoliman I'm going to want some of your time to assist in this.  Hopefully within the next two weeks.
