### ISSUE TITLE
Add Host Error

### ISSUE THREAD

**Issue by Cameron4760** [moonlight-stream/moonlight-chrome#341]
Hi, I have a problem where when I go to connect manually to Nvidia shield through ios 11 I get an error saying 

                                                                        "Add Host
Could not connect to host. Ensure Gamestream is enabled in Geforce Experience on your PC."

Im running Windows 10 Pro and have all the latest and greatest drivers installed for the shield and made sure it was enabled. I recently port forwarded to see if it would resolve the problem but this did nothing. I have a i3 3220 and a gtx 650. Any ideas?

**Comment by Jorys-Paulin** [comment]
@Cameron4760 Make sure to reinstall everything, making sure Geforce experience isn't installed anymore after rebooting, and re-installing it and give it a final reboot, see if it works

**Comment by Jorys-Paulin** [comment]
Hey @Cameron4760, is your issue resolved? If so, you can close this issue, otherwise, we'll be here to help!
