### ISSUE TITLE
Controller mapping issue

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-chrome#342]
It's been bugging me for a while now.
But on some instances my dualshock 4's mappings are passed totally wrong through Moonlight.
Testing the mappings locally with html5 gamepad tester shows X button as button 0 locally.
While testing the same thing while passed through moonlight gives me button 4
except DPAD and left analog every other mapping is messed up.
what gives?

**Comment by apoklyps3** [comment]
any ideea on this?

**Comment by Jorys-Paulin** [comment]
@apoklyps3 What Moonlight does is forwarding your input to GFE, so I don't see why this would occur. Does it still happen as of today?
