### ISSUE TITLE
Extreme mouse desync

### ISSUE THREAD

**Issue by Cur** [moonlight-stream/moonlight-chrome#345]
This makes games unplayable.  It would be bearable if when i move my mouse to the corner of the screen that it kept going but it's blocked at the border so you cant continue moving the mouse that's lagging behind.  

Starting with my mouse from my home PC in the centre of the screen, and the mouse overlay from android in the centre,   i can move the android mouse all the way to the border and it's only moved 1CM from the center of the screen.  

Not using the Rooted.    There has to be a way to have the mouse sync better so it's at least somewhat usable??

Video showing how severe the issue is:  https://youtu.be/CJtmM8QB6m0

**Comment by cgutman** [comment]
It sounds like you're using the Android client. This bug tracker is for the Chrome client. For Android bugs, you should file them on https://github.com/moonlight-stream/moonlight-android/issues
