### ISSUE TITLE
Red Box around PC/port forwarding?

### ISSUE THREAD

**Issue by KiloFoxBravo** [moonlight-stream/moonlight-chrome#346]
Its 2am here so forgive me (posted initially to wrong forum.) I cant for the life of me get this to work.

I went and followed the guide to the number (I believe) but I still cant connect remotely. I forwarded the ports on my router but I have a feeling something isnt right. I am able to on my local network but when I attempt to use hotspot (so I can access PC remotely) I get the red box around pc. Not sure what I am doing wrong here but any help would be appreciated thanks!!

**Comment by Zibbibbo** [comment]
If you have Windows 10 Creator Fall (Build 1709) on your host pc try to disable Windows firewall, just the "private network firewall"

**Comment by cgutman** [comment]
You might need to click Add PC then type your host PC's external IP address for it to connect. You can find that address via whatsmyip.com on your host PC.

**Comment by Jorys-Paulin** [comment]
Hey @KiloFoxBravo, is your issue resolved? If so, you can close this issue, otherwise, we'll be here to help!
