### ISSUE TITLE
Hardware decoding is unavailable. Falling back to default CPU decoding - black screen

### ISSUE THREAD

**Issue by Manlibear** [moonlight-stream/moonlight-chrome#347]
Getting this as a toast at the bottom of the screen when I try to start a game. The screen remains black, but sometimes I have been able to get sound through. 

chrome://gpu

Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Disabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Panel Fitting: Hardware accelerated
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated

OS is a bit of a curve ball, I'm running Chrome OS by Neverware on an old MacBook (3,1), so I'd imagine this isn't going to be that easy to replicate!

**Comment by Jorys-Paulin** [comment]
@Manlibear Some updates came through since you opened this issue, Is your issue resolved?
