### ISSUE TITLE
Default playback device.

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-chrome#349]
Whenever I close moonlight (chrome) on the client it does not revert audio  on the host to the default before streaming. It gets stuck to Nvdia HDMi device thingy.

**Comment by cgutman** [comment]
Are you quitting the game using the Quit button in Moonlight, exiting the game within the streaming session, or just closing Moonlight without closing anything on the streaming PC?

Which app/game are you seeing this with?

**Comment by apoklyps3** [comment]
I'm quiting the using quit in game. Could the issue be that I am running the game from a desktop (mstsc.exe) env?

**Comment by cgutman** [comment]
Ah yep. For mstsc.exe, it will stay running until you manually quit it using Moonlight. When you exit the stream (which you can do via Ctrl+Alt+Shift+Q), you can press the Quit Current App button and that should end the streaming session on the host side.

**Comment by apoklyps3** [comment]
thanks. 
much apreciated

**Comment by Jorys-Paulin** [comment]
Hey @apoklyps3, is this issue resolved? If so, you can close this issue, otherwise we'll be here to help!
