### ISSUE TITLE
[Feature request] Add 2k resolution

### ISSUE THREAD

**Issue by hendrysadrak** [moonlight-stream/moonlight-chrome#350]
Awesome piece of software, keep on going 🚀

**Comment by Jorys-Paulin** [comment]
@hendrysadrak Just to be sure, we're talking `2560x1440` or `2048x1080`? More resolutions is a recurring request. However, we can't add them if Geforce Experience doesn't support it, just in case.

**Comment by Zibbibbo** [comment]
I vote for "2560x1440" :-)

**Comment by Jorys-Paulin** [comment]
Looking back at [all requests about 1440p support](https://github.com/moonlight-stream/moonlight-chrome/issues?utf8=✓&q=is%3Aissue%201440p%20) I think we should add it to Moonlight.

**Comment by muffinmannameistaken** [comment]
Geforce does now natively support most resolutions, previously you would need Geforce Beta to get them to work, keep in mind your monitor or graphics card must be able to support the targeted resolution e.g a monitor that does not support 4k then it will not stream at 4k and the same goes for gpus. 
 You can add other resolution yourself chrome extensions can be unpack using Winrar then repack using chrome it self. The chrome extension seems to be a bit buggy at the moment the stream is a bit off not sure if it just me.( the part of the video stream is missing or push off a little, the position)
to make the changes just search the repository for 1080 or 720

**Comment by hendrysadrak** [comment]
Yeah i meant 2560x1440. Didn't know about GeForce not supporting :)

**Comment by Jorys-Paulin** [comment]
I'll look towards a PR for that then :)

**Comment by Jorys-Paulin** [comment]
According to `http://<geforce-pc>:47989/serverinfo`, the following resolutions are supported:
- 3840x2160@60Hz
- 3840x2160@30Hz
- 1920x1080@60Hz
- 1920x1080@30Hz
- 1280x720@60Hz
- 1280x720@30Hz
And 2560x1400@60 or 30Hz is not present, that means it isn't supported, unfortunately. We could still try, but I'm not sure if it'll work or not.

Here's my `serverinfo`:
```xml
<SupportedDisplayMode>
    <DisplayMode>
      <Height>2160</Height>
      <RefreshRate>60</RefreshRate>
      <Width>3840</Width>
    </DisplayMode>
    <DisplayMode>
      <Height>2160</Height>
      <RefreshRate>30</RefreshRate>
      <Width>3840</Width>
    </DisplayMode>
    <DisplayMode>
      <Height>1080</Height>
      <RefreshRate>60</RefreshRate>
      <Width>1920</Width>
    </DisplayMode>
    <DisplayMode>
      <Height>1080</Height>
      <RefreshRate>30</RefreshRate>
      <Width>1920</Width>
    </DisplayMode>
    <DisplayMode>
      <Height>720</Height>
      <RefreshRate>60</RefreshRate>
      <Width>1280</Width>
    </DisplayMode>
    <DisplayMode>
      <Height>720</Height>
      <RefreshRate>30</RefreshRate>
      <Width>1280</Width>
    </DisplayMode>
  </SupportedDisplayMode>
```

**Comment by hendrysadrak** [comment]
But could available displaymodes taken from `http://<geforce-pc>:47989/serverinfo` automagically on connection?

**Comment by Jorys-Paulin** [comment]
Well if something like this appears then you could stream in 1440p.
```xml
<DisplayMode>
  <Height>2560</Height>
  <RefreshRate>30</RefreshRate>
  <Width>1440</Width>
</DisplayMode>
```

**Comment by muffinmannameistaken** [comment]
i got 1440p to work try it out 

[moonlight chrome.zip](https://github.com/moonlight-stream/moonlight-chrome/files/1443022/moonlight.chrome.zip)

**Comment by cgutman** [comment]
Are you guys actually getting GFE to set the display resolution to 1440p too or just the stream resolution? What games are you testing with?

I just tested with Borderlands 2 and GFE 3.10.0.95.

GFE _will_ give you back a 1440p stream (that was never the issue), but it will just be upscaled 720p until you go manually change the resolution in game to 1440p yourself. Worse still, the resolution doesn't even stick! Next time you start stream, it sets the in-game resolution back to 720p. That's a pretty bad experience if you ask me, and that's the reason we don't ship with non-standard resolutions supported.

**Comment by muffinmannameistaken** [comment]
I just stream my desktop and then just launch any of my games or apps from there, i tested this with my laptop and a friend pc over the internet he has a 1440p monitor and it work , well the resolution work but the performance wasn't good but it work.

**Comment by kikidark** [comment]
what happened to this request?

**Comment by simongui** [comment]
This is like the 3rd issue I've seen for resolutions. I commented to one in the past about adding these resolutions:

```
<li class="mdl-menu__item" data-value="2560:1080">2560:1080</li>
<li class="mdl-menu__item" data-value="3840:1600">3840:1600</li>
```

I confirm that they do in fact work, I have a fork. Perhaps the app should come with standard resolutions and allow us to add custom ones instead of having feature requests all the time?

**Comment by cgutman** [comment]
I'm not opposed to such a change, but someone must do the work to make that UI.

**Comment by Jorys-Paulin** [comment]
The best would really be to be able to change resolution and framerate once you connected to the PC and not before, as well as fetching supported resolutions and framerates and giving the user the possibility to add custom resolutions on a per-PC basis
