### ISSUE TITLE
High kernel times

### ISSUE THREAD

**Issue by beste-spellen** [moonlight-stream/moonlight-chrome#351]
When streaming a game, in Task Manager I see extremely high kernel times caused by Moonlight. This causes sometimes more than 50% CPU "usage". (CPU is j3455, which is not a fast processor by any means... but should be able to decode a stream fine).

However, this does not directly lead to huge lag spikes, 1080p/60fps runs smooth.

Maybe this is system related, don't know if other people also see this?

**Comment by Jorys-Paulin** [comment]
@beste-spellen I think it's mostly due to the chrome software itself and how it handles native modules. Let me know what you think!
