### ISSUE TITLE
The image can not be displayed in full window.

### ISSUE THREAD

**Issue by yxt945** [moonlight-stream/moonlight-chrome#352]
After i installed 388.13-desktop-win10-64bit-international-whql.exe,the image can not be displayed in full window.however it's shows correctly when i connected with vnc or anydesk.
<img width="960" alt="moonlight1" src="https://user-images.githubusercontent.com/26162678/32358559-0ad364ae-c015-11e7-9390-1e9c4dc96a19.png">

**Comment by cgutman** [comment]
What is the native resolution of your host and what is the resolution you're attempting to stream?

**Comment by yxt945** [comment]
my host : intel G4560, Nvidia 1050 2G, resolution 1366x768 ,Windows 10
moonlight : 720P 30FPS 5Mbps,Mac osx 10.12.6 moonlight chrome 0.7.4

**Comment by yxt945** [comment]
when i connected with anydesk or vnc,moonlight shows correctly.
<img width="960" alt="moonlight2" src="https://user-images.githubusercontent.com/26162678/32365455-f0b48f8e-c047-11e7-98f4-3f86c9250e29.png">

**Comment by yxt945** [comment]
I reinstall windows yesterday.it works fine.

**Comment by Jorys-Paulin** [comment]
Hey @yxt945, is your issue resolved? If so, you can close this issue, otherwise, we'll be here to help!
