### ISSUE TITLE
Chrome moonlight big video delay

### ISSUE THREAD

**Issue by IngBitKing** [moonlight-stream/moonlight-chrome#356]
Hi,
i spent some time on finding solution for my problem but i cant figure it out.
I try moonlight chrome extension and moonlight.jar.
When I try run moonlight.jar steam run but java crash.
Chrome extension run ok but I have big video delay, when I move cursor host pc react perfect but on pc where I run moonligh is about half second delay.
Run it on 100Mb wired network where nothing else running

GFE: 3.10.0.95

Moonlight Chrome v0.7.4

Host PC:
System: Win 7 64bit
CPU: i5-4460
GPU: GTX 970
RAM: 16GB

Moonlight PC:
System:  Win 7 64bit 
CPU: i5-2430M
GPU: Intel
RAM: 6GB

Hope my english is understandable.

**Comment by IngBitKing** [comment]
Finaly i run Moonlight.jar I trying to run it in greater resolution than my laptop have, but with same result like chrome extension
![moonlight_java](https://user-images.githubusercontent.com/33427606/32453974-199a18f0-c31e-11e7-8ffd-8b3663a89d58.png)

**Comment by ctbear** [comment]
I have a similar issue, except that my delay is about 10-15 seconds long. What it looks like is this:

1. Connect moonlight Chrome to my host PC (connects okay)
2. Select a game
3. Move the cursor in moonlight, notice on host PC that the cursor is moving correspondingly
4. Notice that the screen in moonlight doesn't change at all for 10 seconds, then suddenly refreshes and the cursor jumps to the new location

I have the latest GFE, and Moonlight Chrome 0.7.4 on a Pixelbook.

My host PC spec is:
* i5 6600K
* 16GB 2400 RAM
* GTX 1070
* Windows 10 with latest updates

My client (Moonlight Chrome) is installed on the new Google Pixelbook, running stable channel.

**Comment by Jorys-Paulin** [comment]
@IngBitKing @ctbear Have you tried to re-install Geforce Experience? Do your problem still occurs?
