### ISSUE TITLE
Mouse pointer reset to center position each time it hit edge of the screen

### ISSUE THREAD

**Issue by defcon1186** [moonlight-stream/moonlight-chrome#358]
Hello guys,
I'm wondering if I am only one with this issue. I'm using last version of Moonlight and GFE. When I play mouse based game I've noticed my mouse pointer reset his position on the center of the screen each time I "touch" an edge of the screen. This occur both in windowed and fullscreen mode, even if I got same resolution both on server and host. I've got any kind of issue if I play with controller. Any of you have some workaround for this ?

**Comment by SlayerUSA** [comment]
#335

**Comment by cgutman** [comment]
Duplicate of #353
