### ISSUE TITLE
Moonlight Rejecting connection instantly.

### ISSUE THREAD

**Issue by Jsarria** [moonlight-stream/moonlight-chrome#361]
When using either the mobile or chrome app of moonlight, moonlight instantly rejects with "Failed to connect to ... ? Are you sure the Host is on?" with a network or local connection. The gefore PC i used was on a bit of a hiatus for a month. (Motherboard failed -> switched from a z170a 6700k to z370 8700k) I tried reinstalling geforce experience but the issue persists.  How would i be able  to fix this?

**Comment by Jorys-Paulin** [comment]
You could try the following:
- Making sure both devices are on the same network (They should be able to ping each other)
- Making sure you have the latest drivers and the latest version of Moonlight
- De-installing **completely** GFE, rebooting between (check by going to `<host-ip>:47989/serverinfo`)

**Comment by Jorys-Paulin** [comment]
@Jsarria Is your issue resolved? If so, you can close this issue, otherwise we'll be here to help!
