### ISSUE TITLE
cant install in chrome 

### ISSUE THREAD

**Issue by cqwer** [moonlight-stream/moonlight-chrome#362]
it is impossible to install in chrome, it says "this website cant install any extensions..."
is there any workaround? even older versions of moonlight are impossible to install :(

**Comment by cgutman** [comment]
Download the extension to your PC first, then drag it to the extensions page from your file browser and that should work.

**Comment by Jorys-Paulin** [comment]
@cqwer Is your issue resolved? If so, you can close this issue, otherwise we'll be here to help!

**Comment by cqwer** [comment]
Solved, thanks
