### ISSUE TITLE
Option to allow disabling remote cursor and track local cursor position instead

### ISSUE THREAD

**Issue by kellabyte** [moonlight-stream/moonlight-chrome#363]
Some remote desktop software hide the remote cursor and show you your local cursor. There's several advantages to this.

1. Perceived performance looks extremely low latency. You don't feel a remote cursor lagging behind your hands movement. By the time you click something anyways the remote cursor is already where you want it to be so everything is perceived to be much lower latency. It feels extremely snappy.
1. If you're on a Mac connecting to a Windows PC, the mouse cursor acceleration algorithm is different on both OS's. It is very disorienting when it behaves differently. By tracking the local mouse cursor position instead, you get a much more natural feel.

**Comment by cgutman** [comment]
This would be nice to have but I don't think GameStream supports client-side cursor rendering (or at least I don't know how to activate it). It makes sense that it wouldn't since it's primarily designed for gaming and client cursor rendering requires absolute pointer locations which is unsuitable for gaming (since it's bounded by the screen).

**Comment by kellabyte** [comment]
Why would GameStream need to support that? It's local to the client computer. What you want to do is disable the display of the remote cursor and just send the local cursor position (relative to the remote window positions).

For example, try Jump Desktop.

**Comment by cgutman** [comment]
That's what I'm saying - GameStream does not support disabling display of the remote cursor or sending absolute cursor coordinates. Both of these are crucial to client-side cursor rendering.
