### ISSUE TITLE
Mouse cursor changes position when refocusing

### ISSUE THREAD

**Issue by realies** [moonlight-stream/moonlight-chrome#365]
When alt+tabbing for example I expect the cursor to continue from where my host OS cursor is, not where it last was on the target computer. That should be possible by sending new cursor coordinates based on the cursor position at the time refocusing happens.

**Comment by Jorys-Paulin** [comment]
@realies Does the cursor's position updates only when you move your own?

**Comment by realies** [comment]
It continues from where the target computer has left it.

**Comment by Jorys-Paulin** [comment]
@realies That's because mouse position updates aren't sent until chrome tells us it has, meaning you have to move a little your mouse in order for the whole system to acknowledge the fact that the cursor should be moved.

**Comment by realies** [comment]
Does chrome tell you where the host cursor position is on the time of refocusing?

**Comment by cgutman** [comment]
@realies Yes, we know the location of the client PCs cursor. The issue is that we don't know where the host PC's cursor is.

Our only input to the host is via X and Y cursor deltas. We don't send absolute coordinates, so we can't determine where the host's cursor will be due to mouse acceleration on the host, bounding by the host display, and mouse capture by applications on the host.

**Comment by Jorys-Paulin** [comment]
@realieshttps://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs

**Comment by realies** [comment]
Still wondering if an add-on daemon on the host could be a good idea used for sending extended keystrokes and more accurate mouse coordinates.

**Comment by cgutman** [comment]
It's definitely possible to have a little server on the host and opportunistically connect to it for extended features, but right now my highest priority work is getting the new PC client released.

**Comment by Jorys-Paulin** [comment]
@realies https://github.com/moonlight-stream/moonlight-qt ;)
