### ISSUE TITLE
Disable host OS mouse acceleration

### ISSUE THREAD

**Issue by realies** [moonlight-stream/moonlight-chrome#366]
When connecting from macOS to a Windows 10 machine it is painfully obvious that the host OS cursor moves with macOS acceleration prior to the Windows one. Would it be possible to send raw mouse/trackpad data and rely on the target os to deal with input acceleration?

**Comment by Jorys-Paulin** [comment]
@realies No, since your client's cursor dictates how the host's cursor moves.

**Comment by realies** [comment]
Many native applications are capable of taking the raw mouse input, it should be possible.

**Comment by cgutman** [comment]
Host mouse acceleration is disabled in GFE 3.13, so this is fixed on NVIDIA's side.

**Comment by cgutman** [comment]
Chrome can't provide us with raw input via NaCl, but the native PC client already has this feature.
