### ISSUE TITLE
#Suggestion - What about a Steam Link version ?

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-chrome#367]
Today I bought a steam link. I found out that Valve was [providing an sdk](https://github.com/ValveSoftware/steamlink-sdk) for developing applications.
Since moonlight is present on basically all platforms, why not investigate into **another version for the Steam Link**?
This would allow us to enable Gamestream to it and even discover how steam's streaming protocol works and implement it as **an alternative** to Gamestream!

**Comment by hrywlms** [comment]
Out of curiosity are there any examples of said SDK being utilized to actually create anything usable yet? I would love to clear the dust off my Link and use it for something.

I am in favour of supporting someone looking into this, though, as much as I love the Steam Controller and the Link's native support for it Steam's in-home streaming has a few limits that make Moonlight a much better option IMO.

**Comment by Jorys-Paulin** [comment]
@hrywlms I'm not a C++ developer, but I've tried to compile the [Kodi example](https://github.com/ValveSoftware/steamlink-sdk/tree/master/examples/kodi) without any success on my Ubuntu Virtual machine. The main reason I wanted this new version is that it allows for **Geforce optimised streaming** as well as **compatibility with Uplay games**, and it would allow Moonlight to run on **dedicated devices** other than a Rasberry Pi

**Comment by Luarst** [comment]
[This](https://github.com/irtimmer/moonlight-embedded) repository may be a good start in doing so. I'd like for this to happen as well.

**Comment by Jorys-Paulin** [comment]
@hrywlms I known the steam link runs on some kind of BusyBox distribution, but I'm no expert on this

**Comment by cgutman** [comment]
Not relevant to this client. Moonlight Qt has some Steam Link support (currently incomplete)
