### ISSUE TITLE
WIN/CMD key not working

### ISSUE THREAD

**Issue by realies** [moonlight-stream/moonlight-chrome#368]
It seems that the CMD key on macOS is not mapped to the WIN key on Windows.

**Comment by Jorys-Paulin** [comment]
@realies Since Moonlight justs send the `CMD` key to Geforce Experience, GFE should just send that same key to your game. It should

**Comment by realies** [comment]
Could there be an add-on daemon that intercepts non-working keys and sends them to the host?

**Comment by Jorys-Paulin** [comment]
@realies No, unless we make our own GFE

**Comment by realies** [comment]
Assuming that patching would be breaching the software license.
