### ISSUE TITLE
Graphical feedback when connecting the stream

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#37]
Similar to Android, PC, and iOS, Moonlight Chrome should display connection progress messages as the connection is being established. This way the user is not left with a black screen while the app is starting.

**Comment by raidancampbell** [comment]
An [MDL Progress Bar with Indeterminate Progress](http://www.getmdl.io/components/index.html#loading-section) may be a good way to do this.  Alternatively, a spinner may work just fine.
