### ISSUE TITLE
Mouse Button 4 and 5 not being sent to host pc

### ISSUE THREAD

**Issue by Xalcon** [moonlight-stream/moonlight-chrome#370]
As the title says, mouse button 4 and 5 are not sent to the host PC (also known as the "back" and "forward" buttons)
Mouse Button 3 ( Scroll wheel click) is working fine.

**Comment by Jorys-Paulin** [comment]
@Xalcon We'll, maybe it is sent, but maybe GeForce Experience doesn't do anything with it.

**Comment by Klut** [comment]
With the latest Version of GeForce Experience 3.12.0.79 even a Mouse connected to the Shield Tablet doen‘t work with Button 4 and 5. So this is a limitation by Geforce Experience and not Moonlight.

**Comment by slrgt** [comment]
still not working
