### ISSUE TITLE
Chrome apps stop working Q1 2018

### ISSUE THREAD

**Issue by SESNut** [moonlight-stream/moonlight-chrome#371]
How will this affect moonlight?

**Comment by TesseractCat** [comment]
Would it be possible to convert the chrome app to a native desktop app?

**Comment by Jorys-Paulin** [comment]
For me, the better way would be to rewrite the whole application as a WebAssembly one, making this version potentially run on all devices !

**Comment by raidancampbell** [comment]
The chrome client will stop working after the cutoff date.  @Jorys-Paulin I'm interested in WebAssembly more than the alternatives: I'll spend a while to determine the feasibility of porting it.  If you have any insight into the matter I'd be glad to hear it

**Comment by cgutman** [comment]
At the moment, we have issues with sockets and decoding APIs being unavailable via non-PPAPI methods. Chrome Remote Desktop launched a web beta to replace their PPAPI extension - https://remotedesktop.google.com/ - which is definitely closer to our problem space and worth investigating. Hopefully the code is available in the Chromium repository like the old plugin was.

**Comment by Jorys-Paulin** [comment]
Switching to WebAssembly modules would also allow to make multiple modules for multiple stream services ;)

**Comment by TesseractCat** [comment]
Would switching to WebAssembly allow us to host the moonlight client as a website?

**Comment by Jorys-Paulin** [comment]
@TesseractCat And that's the big point, no more installs or updates ! (kinda)

**Comment by TesseractCat** [comment]
Would using WebAssembly mean we would need to use websockets? If so, wouldn't that require some large code rewrites?

**Comment by Jorys-Paulin** [comment]
@TesseractCat No need for that, WA should do that alone

**Comment by TesseractCat** [comment]
I believe webassembly emulates sockets with websockets, which might not work with Nvidia Gamestream.

**Comment by Jorys-Paulin** [comment]
@TesseractCat Or we could just create our own "Gamestream" from scratch. That would finally allow us for more headroom when it comes to new features, as well as better documentation on how the whole thing works.

**Comment by TesseractCat** [comment]
True, but that sounds like a separate project.

**Comment by Jorys-Paulin** [comment]
@TesseractCat I mean it would probably work, one day or another.

**Comment by thealex626** [comment]
Maybe make a separate standalone Windows app?

**Comment by Jorys-Paulin** [comment]
@thealex626 There's already the [Java version](https://github.com/moonlight-stream/moonlight-pc) for that ;)

**Comment by SESNut** [comment]
you mean abandoned like the java version too?

**Comment by Jorys-Paulin** [comment]
@SESNut No, just like it had no update since a year or more

**Comment by SESNut** [comment]
oh you mean 2 years ago like the windows version?

**Comment by Jorys-Paulin** [comment]
@SESNut The Java version is just deprecated in favor of the chrome version, but it's support still appears to be active

**Comment by thealex626** [comment]
Java version is deprecated. Also Java performance is worse than a C++ app.

**Comment by apoklyps3** [comment]
looks like chrome version is going to die in alpha state.
thanks google....

**Comment by Jorys-Paulin** [comment]
There's still Web assembly to hopefully save this version

**Comment by apoklyps3** [comment]
Well, I won't hold my breath.
Best bet would be for Nvidia to make a native PC client, but I won't hold my breath. They are milking that Nvidia Shield till the end.

**Comment by Jorys-Paulin** [comment]
Plus there's already us to make it. The native, Java edition works fine.

**Comment by apoklyps3** [comment]
yes and thanks for all your work and please don't take any offence, but a client from Nvidia would ensure better stability as they get money out of it, one way on another.
I'm on the latest moonlight version and I keep getting slowdowns with extreme stutters from time to time. only way to monitor it is trough task manager and what I have noticed is that moonlight network usage drops bellow the target biterate and there is no way that is because of my connection.
anyway to force moonlight to never go bellow a certain biterate? I have noticed it is dynamicaly lowering the networ usage (hence the biterate) when ingame menu. would be great if we could force for it to stay all the time at a certain value.

**Comment by Jorys-Paulin** [comment]
I won't be able to help you on that, unfortunately, I'm not expert when it comes to networking issues. Maybe open another issue and give us details, @cgutman may help you on that.
