### ISSUE TITLE
Unable to connect over Internet, LAN connection fine.

### ISSUE THREAD

**Issue by dlenoxx** [moonlight-stream/moonlight-chrome#372]
This has been attempted with the Java and Chrome version.

When attempting to access over the internet with the Chrome version it simply says "Failed to connect. Is the Host on?" and when trying to connect with the Java client I get "Unrecognized SSL message. plaintext connection?".

I've tested my ports with telnet and canyouseeme.org and both are able to hit every TCP and UDP port with no problem. I'm able to ping my IP as well.

I've tried putting my computer in the DMZ on my router and disabling Windows Firewall to see if that makes a difference and there was no change. I do have the DD-WRT platform on my router so there may be just some setting I'm not familiar with that is preventing this.

Connection over LAN works perfectly so I know the software is functioning fine, but I can't figure out what else to test from since any of the testing methods seem to be working.

**Comment by Jorys-Paulin** [comment]
@dlenoxx Have you redirected your router's ports to your host? Just making sure :)

**Comment by dlenoxx** [comment]
@Jorys-Paulin I did, but I also /think/ I found a solution.

I disabled the port forwarding settings I put in and turned on UPnP on the router. Almost immediately nvidia gamestream popped up. I tested on my local network and was able to find the host with the external IP, but I won't be able to test remotely till Monday.

**Comment by Jorys-Paulin** [comment]
@dlenoxx You can still reopen this issue if it's not, but I hope for you that you won't have to ;)
