### ISSUE TITLE
Question: Is there a way to add moonlight to windows firewall whitelist on the host pc? 

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-chrome#373]
So the only way for to me to get moonlight working is disable the firewall on my host pc, otherwise moonlight can not find the host pc. I don't want to just disable the firewall, is there a way to add moonlight to whitelist?

**Comment by Jorys-Paulin** [comment]
@robertshen1202 See [this guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#port-forwarding-recommended-for-most-users) on what ports to open in order to let Geforce Experience communicate with moonlight

**Comment by robertshen1202** [comment]
This guide is for streaming over the internet, I am on a local network. Does this guide also apply to local network?

**Comment by cgutman** [comment]
If your local firewall is blocking those ports, then yes, you will need to add those as exceptions on your PC's firewall software.

**Comment by robertshen1202** [comment]
I add these ports to the windows firewall inbound rule, it is still not working

**Comment by cgutman** [comment]
Does it work with the firewall disabled completely?

**Comment by robertshen1202** [comment]
yes it does

**Comment by cgutman** [comment]
hmm, can you screenshot the rules you created so I can double-check them?

**Comment by robertshen1202** [comment]
[Link to Imgur](https://imgur.com/JjAgfnu)
the rule is set to private network only, and I have double checked the network profile to make sure the connection is private.

**Comment by cgutman** [comment]
Looks good. What happens when you try to stream? Does your PC appear online?

**Comment by robertshen1202** [comment]
It doesn't show up in moonlight, and if I try to add the host pc through ip, it will tell me "failed to connect to (insert local ip address here), are you sure the host is on? " If I turn the firewall off on the host pc, host pc will immediately show up in moonlight. After I paired with host pc with firewall off, I turn the firewall on, there will be a red outline on the host pc.

**Comment by robertshen1202** [comment]
so i just saw this post with a similar issue #346. One person suggest turn off the private firewall if the host pc has windows build 1709, which is the build my host pc has. Should this be add to known issue section?

**Comment by Zibbibbo** [comment]
The one person was me, I've restored the previous windows build on the host pc and the firewall problem is gone, then i've reupdated again to build 1709 and the problem is back again, so, I think you should add this to the known issue. 
This is less critical than the mouse problem when 1709 is on the client pc btw.

**Comment by Jorys-Paulin** [comment]
Hey @robertshen1202, is your issue resolved? If so, you can close this issue, otherwise, we'll be here to help!

**Comment by robertshen1202** [comment]
Well, the thing is that I turn off the firewall on the host computer to get it to work. This issue also seems to be consistent with host computer that has windows build 1709 (the problem exist on two windows computer I owned and it doesn't exit on my laptop with build 1607). I don't consider turning off firewall a solution. If someone can add this to the troubleshoot section in either this chrome extension wiki or the general moonlight wiki, I will gladly to close this issue.

**Comment by Jorys-Paulin** [comment]
@robertshen1202 I found this to open the ports of your firewall: https://technet.microsoft.com/en-us/library/ms345310(v=sql.100).aspx

**Comment by Jorys-Paulin** [comment]
@robertshen1202 What do you think?
