### ISSUE TITLE
Black Screen after Logo Animations but have sound

### ISSUE THREAD

**Issue by sincorecom** [moonlight-stream/moonlight-chrome#374]
Hi All,
I am new to Moonlight. Currently, I have an android pad and a PC both running moonlight and both having the same issue. After the Logo animations play I get a black screen. I can hear the music but nothing else has anyone else run into this? I am running the newest version of Drivers and Geforce Experience.
Thanks

**Comment by Jorys-Paulin** [comment]
@sincorecom Can you give us some screencasts or screenshots? Is your host (computer running your games) printing images?

**Comment by sincorecom** [comment]
So I may have figured it out. The moniter I'm using on the machine is very old. Like 10 years old so my guess is moonlight is trying stream a HD stream while the moniter isent doing hd. I'm planning to buy a new moniter this weekend. If this fixes it I will report back.

**Comment by Jorys-Paulin** [comment]
@sincorecom So, does your new monitor fixes the issue? I really want to find out what causes the issue :/

**Comment by sincorecom** [comment]
So no it did not but I got to the bottom of the issue! I was being dumb it was the game not moonlight. For some reason, I assumed the game was compatible. I did more research and it turns out unless you run the game in borderless window mode it won't stream. So Problem solved!
