### ISSUE TITLE
Mouse cursor keep reseting to center

### ISSUE THREAD

**Issue by KSodR** [moonlight-stream/moonlight-chrome#377]
Hi,

Using moonlights chrome app, when the cursor hits the edge it resets to middle of the screen. Thus making any kind of gaming using keyboard + mouse unplayable since you cant move the camera. Bug or fix available?

Thanks.

**Comment by Jorys-Paulin** [comment]
@KSodR See #376 for details. It will be fixed in the next version of chrome.

**Comment by KSodR** [comment]
@Jorys-Paulin Installed the fixed version on chrome beta just to be sure. Fixed it. Chrome or moonlight bug?

**Comment by Jorys-Paulin** [comment]
Chrome related bug

**Comment by Jorys-Paulin** [comment]
Hey @KSodR, I think you can close this issue now that you know what causes this :)
