### ISSUE TITLE
Can't find host

### ISSUE THREAD

**Issue by Xypod13** [moonlight-stream/moonlight-chrome#378]
My host has a gtx 1070
My device is a Lenovo yoga 910

Tried everything:
- turned off firewall
- rebooted everything
- checked if settings were on

Geforce expierence version is tha latest: 3.11.0.73

I've read that NVIDIA Streamer Network Service has to be active, but i cant find it in services, maybe that's it?

**Comment by Jorys-Paulin** [comment]
@Xypod13 Try the following:
- [] Checking if Shield is showing and enabled inside GeForce Experience's settings
- [] Reinstall completely GeForce Experience
- [] Try to ping your host from your client if possible

**Comment by Xypod13** [comment]
1. ![knipsel32](https://user-images.githubusercontent.com/34884671/34378820-43aeaffa-eaf8-11e7-8fd9-f9af3fd0c75f.PNG)
shield running fine

2. Ill try that

3. ping host to client? how?

**Comment by Jorys-Paulin** [comment]
1. That's good news. Make sure you reboot when you toggle that.
2. I reinstall GeForce Experience more times that I would like.
3. You can go to `<host-ip>:47989/serverinfo` and check for a response. It might give you an error.

**Comment by Xypod13** [comment]
Deleted Geforce Experience, reinstalled, rebooted pc, started moonlight chrome on client, nothing

Where do i put the <host-ip>:47989/serverinfo ? in the cmd? and on my client or host?

**Comment by Xypod13** [comment]
Nevermind! i manually put the ip numbe rof my pc in the client moonlighht chrome, and it works! so reinstalling geforce helped ^^ tnx!

**Comment by Jorys-Paulin** [comment]
In your browser, like chrome or Firefox. Make sure you insert the right local ip of your host before the `:`

**Comment by Jorys-Paulin** [comment]
Use this trick whenever it doesn't seem to work. When it happens, just reinstall GeForce Experience.

**Comment by Jorys-Paulin** [comment]
Now you can close this issue, hope I helped !

**Comment by Xypod13** [comment]
It works, but there is a massive lag spike sometimes. My pc just runs fine, but my laptop just stops moving and then continues. Is that my wifi, laptop, or else?

**Comment by Jorys-Paulin** [comment]
@Xypod13 Probably your WiFi, try connecting from a wired connection

**Comment by Xypod13** [comment]
Laptop doesnt have a ethernet port :/

**Comment by Jorys-Paulin** [comment]
@Xypod13 What kind of laptop do you have? This version of moonlight is made to run on low power PC's, so I don't see why your laptop maybe causing the problem.

**Comment by Xypod13** [comment]
Lenovo Yoga 910
i7-7500u
Intel HD 620 graphics

**Comment by Jorys-Paulin** [comment]
@Xypod13 It should be okay, I think your WiFi might be the bottleneck there, sorry :/

**Comment by Xypod13** [comment]
Ive got fiberglass 50mbit up/down. Is it my router then or my laptop wifichip?

**Comment by Jorys-Paulin** [comment]
It should be your WiFi card, I don't see any other reason why you would have issues with steaming, but maybe someone else like @cgutman can help, the developer of the actual steaming module. I'm very limited when it comes to the actual streaming over the network :/

**Comment by Xypod13** [comment]
Oh sorry

I guess ill be buying a usb to ethernet adapter :P 

Tnx for all the help!

**Comment by Jorys-Paulin** [comment]
@Xypod13 You can now close this issue or open a new one for the streaming problems, your choice!

**Comment by Xypod13** [comment]
I think ill buy a ethernet usb adapter, and if that doesnt work, ill open a new one.
