### ISSUE TITLE
Moonlight force constant biterate

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-chrome#379]
Is it possible to create a version where the biterate is not variable?
I would like that the biterate set in the main screen to be constant.
Way to many times find my moonlight(chrome) network activity to drop way below the targetef biterate. Of  course that's when stutters and stream freezes occur

**Comment by Jorys-Paulin** [comment]
@cgutman Maybe this is a great idea for a feature request

**Comment by cgutman** [comment]
The bitrate is locked to the specified value already. That said, depending on the complexity of the scene, the encoder may not fully utilize the bitrate allowed if it can encode the frame using less data at roughly equal quality.

If you're seeing a drop in network activity with stutters and freezes, that's probably your network dropping packets, not Moonlight. Make sure you're connected via 5 GHz WiFi or Ethernet (and preferably have at least one of the PCs wired to the router).

**Comment by apoklyps3** [comment]
So the issue is created by thre enconder(nvidia)?
If my network drops packets how come I have the same constant speed when downloading files or watching full hd stream eighter via kodi or emby?
