### ISSUE TITLE
Computer freezes when closing Moonlight with game still open

### ISSUE THREAD

**Issue by Stuke00** [moonlight-stream/moonlight-chrome#380]
If I close Moonlight on Chrome while the game on the remote PC is still open, the remote PC will freeze up and eventually reboot or I will have to hard power it down.  If I exit the game before closing Moonlight, no issues.

**Comment by Jorys-Paulin** [comment]
@Stuke00 Try reinstalling GeForce Experience. In the meantime I will try to reproduce the issue.

**Comment by Stuke00** [comment]
Yes I did do a complete uninstall and reinstall.  It did not always do this, been an issue for a couple months now.  I don't have an actual Shield to see if it does it there or not, but I have 2 other computers I use the Chrome extension on and they both do it.  Nothing in the windows event viewer either that I can see.

**Comment by Jorys-Paulin** [comment]
@Stuke00 So then the problem is happening on the GeForce Experience side of things, Wich might limit how we can fix this problem

**Comment by Stuke00** [comment]
Anything I can do to help troubleshoot it?

**Comment by Jorys-Paulin** [comment]
@Stuke00 See if the problem occurs:
- When closing the app normally
- When closing using task manager
- When reloading the app (see online on how to do that)

**Comment by cgutman** [comment]
Does your PC blue screen then reboot or just reboot with no BSOD?

It seems like this is probably a hardware or software issue on your PC. Make sure you're on the latest Nvidia drivers. Do you have a CPU or GPU overclock?

**Comment by Jorys-Paulin** [comment]
@Stuke00 I tried the following:
- [x] When closing the app normally
- [x] When closing using task manager
- [x] When reloading the app
At no point did my computer froze. The game just kept running like it was still streaming.
What game where you running while those append?

**Comment by Stuke00** [comment]
Must've been something with my PC, ended up reformatting and reinstalling windows and appears to be good now.  Thanks for the advice and help!
