### ISSUE TITLE
Support of client resolution\cbr\stats and the option to force h265 if supported

### ISSUE THREAD

**Issue by Numerok** [moonlight-stream/moonlight-chrome#381]
So the whole question is in the title.
Generally we need this option for saving the bandwidth for 1366x786 (on which are the most low-end or old laptops) clients or not standard aspect ratio (16x10, 21x9, 5x4, 4x3 and so on).
Also from the steam experience, i can tell that quality and delay would be better.
Also from the steam experience, it'll be nice to have the cbr option because it produces less delay. (is it possible with nv gamestream protocol?)

From testing in osu! via the 100mb\s internet with 8ms ping on moonlight and steam that runs via hamachi to make local network (so steam clients will connect to each other) and i can say that steam experience was much-much better, less delay, better quality because no interpolation takes place.
Also i tried to play pubg, and i can say that steam is way ahead. if i set the ingame resolution to my client resolution and in steam set the stream resolution to client based I get much-much better image then i would get with interpolation (especially from 1600x900(max res of my host pc in 16x9 aspect raito)->1920x1080->1366x768)

And also from the steam experience, it'll be nice to have statistics which show the current delay, the decoding type, and cpu\gpu load.
Also i want to ask for option to force h265 (like in android client) if it supported on client because it also produces less delay(as tested on my redmi 4 pro - 13ms with h.264 and 8 ms with h.265).

i tried it on java client but input lag was too big from the start.(also, why dont you create a standalone client written on c(any) with native fullscreen for decreasing the input lag?)  

forgot to mention: 
sorry for the errors in text if there's any, English isn't my main language. I will appreciate if you point out these errors.
(Text checked in google translator XD i love how it translates steam and moonlight <3)
as suggested - by @Jorys-Paulin i reference @cgutman

**Comment by Jorys-Paulin** [comment]
Hey @NuMeRoK, thanks for your feedback!
- Weird resolutions may not be supported by your host. They might get resized on the Moonlight side, tho I'm not sure.
- What do you mean by CBR? I'm not familiar with it...
- Stats might be a great addition to the software, something the C developers might have to make (I'm only a JavaScript developer)
- Forcing H.265 would be nice too, again, feature idea for the C devs.
- Bad English is not important as long as we can understand you ;)

**Comment by NuMeRoK** [comment]
CBR - constant bitrate.

> Weird resolutions may not be supported by your host. They might get resized on the Moonlight side, tho I'm not sure.
moonlight resizes resolution by itself(but i don't know, on host pc, or on client pc but it does not batter cuz at the end it is all scaled to the client resolution). If i set the res on host pc to it max res then it would be (1680x1050(16x10)->1920x1080(16x9)->1366x768(16x9)). but if you add client resolution then it would be direct 1680x1050(16x10)->1366x768(16x9) so there is no difference in that but we skip one resize which relieves us from one interpolation that reduces the image quality(and also reveals us from some unnecessary information that client pc don't need.).

**Comment by Jorys-Paulin** [comment]
@NuMeRoK Constant bitrate is already discussed in #379, but it's apparently already a thing. When it comes to the actual streaming I suggest you ask @cgutman, the main developer of Moonlight.

**Comment by NuMeRoK** [comment]
yea, i saw that, but here i consider cbr not from stability side but from latency side, it's kind of different.

**Comment by Jorys-Paulin** [comment]
@Numerok You host PC can only stream the following resolutions which are described at `<host-ip>:47989/serverinfo`.

Here's the section you're looking for, use something like an [html formater](https://www.freeformatter.com/html-formatter.html) to see it:
```xml
<SupportedDisplayMode>
      <DisplayMode>
         <Height>2160</Height>
         <RefreshRate>60</RefreshRate>
         <Width>3840</Width>
      </DisplayMode>
      <DisplayMode>
         <Height>2160</Height>
         <RefreshRate>30</RefreshRate>
         <Width>3840</Width>
      </DisplayMode>
      <DisplayMode>
         <Height>1080</Height>
         <RefreshRate>60</RefreshRate>
         <Width>1920</Width>
      </DisplayMode>
      <DisplayMode>
         <Height>1080</Height>
         <RefreshRate>30</RefreshRate>
         <Width>1920</Width>
      </DisplayMode>
      <DisplayMode>
         <Height>720</Height>
         <RefreshRate>60</RefreshRate>
         <Width>1280</Width>
      </DisplayMode>
      <DisplayMode>
         <Height>720</Height>
         <RefreshRate>30</RefreshRate>
         <Width>1280</Width>
      </DisplayMode>
   </SupportedDisplayMode>
```

**Comment by Numerok** [comment]
@Jorys-Paulin strange, but i tried to force the resolution on java standalone version and it worked. Don't know why there are only these resolutions.

**Comment by Jorys-Paulin** [comment]
@Numerok Theses are the resolutions that are officially supported by your host, but apparently nothing prevents you from running other ones.
For building, if you find the guide too complicated, we've made another version [here](https://github.com/Jorys-Paulin/moonlight-chrome/wiki/Building)

**Comment by Jorys-Paulin** [comment]
@Numerok Have you tried building the app? Otherwise, each release has a `.crx` file that you can use otherwise.

**Comment by Jorys-Paulin** [comment]
Can you follow up? Give us more details, please? In the meantime, closing this issue.
