### ISSUE TITLE
Low end Chromebook

### ISSUE THREAD

**Issue by shnickelson** [moonlight-stream/moonlight-chrome#382]
I have a low end Chromebook that I am trying to get Moonlight working on.  The Android version streams flawlessly but has limited functionality (mostly lack of mouse support).  When i use the the Chrome version of Moonlight i experience considerably lower performance.  I have a 200mbps wifi signal (that my Chromebook gets at least 100mbps of) so the internet speed shouldn't be an issue.  I tried tinkering around with the fps and resolution setting but can't get it to perform as well as the Android version.  Any tips?

**Comment by Jorys-Paulin** [comment]
@shnickelson Make sure you run as little things as possible in the background. Otherwise, I'm not familiar with Chromebooks so I won't be able to help you :/

**Comment by Jorys-Paulin** [comment]
@shnickelson Did it helped?

**Comment by Jorys-Paulin** [comment]
Le me know how it goes. For now, closing this issue
