### ISSUE TITLE
Mouse input lag

### ISSUE THREAD

**Issue by jaydeelive01** [moonlight-stream/moonlight-chrome#383]
Hello !

I notice high input lag when i use my mouse in games that require it (stellaris, euiv, mostly strategy games).

I wonder if you could fix it somehow ? I don’t get it using geforce now.

Thanks,

**Comment by Jorys-Paulin** [comment]
@jaydeelive01 What type of connection are you using between the two computers. Ethernet is most ideal, as bad WiFi is very common in ISP-provided modems.

**Comment by Duglz** [comment]
I have the same issue when going over the internet.

**Comment by Jorys-Paulin** [comment]
@Duglz This is to be expected when steaming over the internet.

**Comment by jaydeelive01** [comment]
I see.
I indeed get this error while streaming over the Internet (on a 15 Mbits+ bandwith while asking 10 Mbit in Moonlight), but I also get it in local LAN over good quality 5 Ghz connection on a dual-band router (that I purchased, not my ISP ;-)).

Any clues or plans to solve this issue ?

**Comment by Jorys-Paulin** [comment]
@jaydeelive01 Try connecting the two computers directly via Ethernet, that's all I can see for now...

**Comment by Zibbibbo** [comment]
I noticed that the input lag it also affected by the VGA on client side.

I recently updated the vga on the pc I use at work and the input lag over internet is almost gone, now is much much better. (previously i was using cpu-integrated GPU, now a dedicated nvidia 1050)

**Comment by jaydeelive01** [comment]
Zibbibbo, 
I agree that it's a possibility, but it's still puzzling. I don't have the possibiliy to test a new GPU for the client, but the strange thing is that I don't seem to have any input lag while using a controller, even in 1080p.

**Comment by Jorys-Paulin** [comment]
Can you follow up? Give us more details, please? In the meantime, closing this issue.
