### ISSUE TITLE
No sound on main pc

### ISSUE THREAD

**Issue by Sunexider** [moonlight-stream/moonlight-chrome#384]
I tried to pair my pc and cellphone and was successful, but for some reason even after I stop the streaming I can no longer hear anything on the main pc, already tried the option where I can hear in both the pc and cellphone and I wasn't successful

**Comment by Jorys-Paulin** [comment]
@Sunexider Does your resolution also keeps being modified? Your 1080p screen gets resized to 720p for streaming but keeps at 720p even after streaming: is that your case?

**Comment by Jorys-Paulin** [comment]
Can you follow up? Give us more details, please? In the meantime, closing this issue.
