### ISSUE TITLE
Mouse recognising issues on ChromeOS

### ISSUE THREAD

**Issue by theTBC** [moonlight-stream/moonlight-chrome#385]
When using Moonlight on Chrome OS, the trackpad and the mouse do not register any movement UNLESS I am holding down left click and dragging to move the cursor. Is this a known bug and are there any solutions?
Thanks in advance.

**Comment by cgutman** [comment]
This sounds like you're using Moonlight Android on Chrome OS. Are you sure you're using this Chrome extension to stream?

**Comment by Jorys-Paulin** [comment]
@theTBC Please re-open an issue if you need it ;)
