### ISSUE TITLE
Help With Mac

### ISSUE THREAD

**Issue by FR0ST8ITE** [moonlight-stream/moonlight-chrome#387]
I need help setting this up with macOS (using chrome). It's kind of hard to set up, so deeper explanations would be better. And if you can't, the developers should take the mac portion off of their main menu thing.

**Comment by Jorys-Paulin** [comment]
@FR0ST8ITE I made another version of the guide: https://github.com/Jorys-Paulin/moonlight-chrome/wiki/Installing. Let me know if it helps!

**Comment by Jorys-Paulin** [comment]
@FR0ST8ITE
Le me know how it goes. For now, closing this issue
