### ISSUE TITLE
Can't connect to computer over school wifi.

### ISSUE THREAD

**Issue by Brad2345** [moonlight-stream/moonlight-chrome#389]
Hi I'm having a problem where i'm trying to connect to my computer from the school, just for the fun of it, and to see if I can play any games, and show my friends. Don't worry i'm not trying to play games in class or anything that would be crazy! At my house it connects just find, and I port forwarded the ports needed, and was able to connect from a different area with different wifi, but when I go to school, and try it it gives me a error, and can't find the PC. I typed this in the search bar with my ip  http://[your PC IPaddress]:47989/serverinfo, and it showed me  list about my PC. Is the School able to block moonlight or something, and if so is there a way to get in still?

**Comment by Jorys-Paulin** [comment]
Hey @Brad2345,
- Have you followed the official guide? If so, it needs an update:  `IMPORTANT: If you stream over the Internet, you must add a new port forwarding entry for TCP 48010`
- Maybe your school is blocking off unusual ports like the ones used by Moonlight / Geforce Experience
- Are you able to see the list of games?
- Can you give us some logs? (replace your IP in those)

**Comment by Brad2345** [comment]
Hmm it just started working randomly today, I don't know what changed, but thanks for the response anyways Jorys.

**Comment by Jorys-Paulin** [comment]
No problem, if everything works, you can close this pull request. :)

**Comment by Ilovegothchics** [comment]
> Hmm it just started working randomly today, I don't know what changed, but thanks for the response anyways Jorys.

ik this is like 6 years old, but if you dont mind, could you explain how you got it to work, im dealing with the exact same issue. Is it a specific port, and if so which one? Thank you in advance :)
