### ISSUE TITLE
Catch errors due to NaCl module not being loaded

### ISSUE THREAD

**Issue by raidancampbell** [moonlight-stream/moonlight-chrome#39]
The first time the NaCl module is loaded (such as after a `build clean`) loading takes longer.  Unfortunately, it takes long enough that the user can reasonably try to pair before the module is loaded.  Any calls into NaCl will fail until it's loaded, so we need some way to prevent these calls from being made until the module is initialized.

**Comment by raidancampbell** [comment]
useful API for doing this: https://developer.chrome.com/native-client/devguide/coding/progress-events

**Comment by cgutman** [comment]
Fixed by 27cdd06225bf3c8b629f2168336f0962bf9469c7
