### ISSUE TITLE
RTSP handshake failed

### ISSUE THREAD

**Issue by murgatt** [moonlight-stream/moonlight-chrome#391]
I have a strange issue trying to use Moonlight to stream over the internet (outside my house).
I followed the setup guide and I opened TCP and UDP ports. Everything works great when I use Moonlight Android application, I'm able to connect to my PC, to launch a game and to play. 
But as soon as I try to do the same with Moonlight chrome extension, I cannot launch any game, it fails after RTSP handshake and returns to Moonlight games listing. On the PC the game is started but Moonlight chrome extension doesn't display it.

I am running Moonlight chrome extension on a 2017 Macbook Pro on a wifi network (same network used with Moonlight Android application).

**Comment by Jorys-Paulin** [comment]
@murgatt Have you opened the `48010` TCP port?

**Comment by murgatt** [comment]
Thank you for your answer @Jorys-Paulin 
I checked again, but yes, I have opened all the ports mentioned in the setup guide including `48010` TCP port.

I tried again to start a game with Moonlight chrome extension, but this time on my house WIFI network. Never noticed because I was trying to stream over the internet, but it failed too.
It's weird because with my Android device it works like a charm no matter what network I use.
The problem seems to be really specific to the Moonlight chrome extension.

**Comment by cgutman** [comment]
What version of Moonlight Chrome is installed?

**Comment by murgatt** [comment]
My version of Moonlight chrome is 0.8.0 @cgutman

**Comment by Jorys-Paulin** [comment]
@murgatt You should update to `0.8.2` see if it helps.

**Comment by murgatt** [comment]
I updated to `0.8.2` and everything seems to be working now.
My bad, I should have done it before.
Thank you for your help @Jorys-Paulin & @cgutman !
