### ISSUE TITLE
Does Moonlight support HDR-Gamestream?

### ISSUE THREAD

**Issue by leeson865** [moonlight-stream/moonlight-chrome#392]
Looks like Nvidia shield can support HDR/4k gamestream without requiring the host PC to have a HDR monitor. Can moonlight do this? I can't find any HDR in the settings.

http://support-shield.nvidia.com/gamestream-user-guide/#t=Set_Gamestream_Resolution_1.htm

**Comment by cgutman** [comment]
Moonlight Chrome does not, because the Pepper APIs do not support decoding HEVC.

**Comment by leeson865** [comment]
Is there another option for getting HDR to work through Windows 10 PC?

**Comment by cgutman** [comment]
Nope, not at the moment

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, wich will support HDR eventually.

**Comment by nathankferguson** [comment]
Any update on this?

**Comment by cgutman** [comment]
No, the ChromeOS will never support HDR for the reasons mentioned above.

**Comment by nathankferguson** [comment]
Sorry, I was referring to HDR support in general, primarily for the desktop
client.
