### ISSUE TITLE
Issue streaming on different networks 

### ISSUE THREAD

**Issue by NowJoJo** [moonlight-stream/moonlight-chrome#395]
I have forwarded all my ports and stuff, I tried to go on my second home network and I open moonlight and my pc has a big red box around it, can anyone help me?

Thanks

**Comment by Jorys-Paulin** [comment]
@NowJoJo Have you manually added your PC as `<your-ip>`?

**Comment by NowJoJo** [comment]
That's how I added it the first time on my standard network, now it shows up as desktop-~~~ (letters and numbers) 

Should I try adding the IP again on the second network?

**Comment by Jorys-Paulin** [comment]
@NowJoJo IMPORTANT: If you stream over the Internet, you must add a new port forwarding entry for TCP 48010

**Comment by NowJoJo** [comment]
I have already added that one, I just set it up yesterday.

**Comment by Jorys-Paulin** [comment]
@NowJoJo And you restarted your router?

**Comment by NowJoJo** [comment]
I have yes.

**Comment by Jorys-Paulin** [comment]
Weird. Try opening the console to see what happens.

**Comment by NowJoJo** [comment]
How would I do that ?

**Comment by Jorys-Paulin** [comment]
https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs

**Comment by NowJoJo** [comment]
What should I be doing in there?

**Comment by NowJoJo** [comment]
It says this: just keeps repeating this over and over

utils.js:200 [utils.js, utils.js,  selectServerAddress] Failed to contact host DESKTOP-~~ NvHTTP {address: "<ip address>", paired: false, currentGame: 0, serverMajorVersion: 0, appVersion: "", …}
(anonymous) @ utils.js:200
Promise rejected (async)
(anonymous) @ utils.js:197
Promise rejected (async)
(anonymous) @ utils.js:194
Promise rejected (async)
(anonymous) @ utils.js:191
Promise rejected (async)
selectServerAddress @ utils.js:188
pollServer @ utils.js:151
(anonymous) @ index.js:147
messages.js:35 [messages.js, handleMessage] Message data:  https://<IP address>/serverinfo?uniqueid=bb43b6770163bfef&uuid=96b5d8da-6452-4551-8d84-e5d0e8558ba1
messages.js:35 [messages.js, handleMessage] Message data:  https://DESKTOP-~~.local:47984/serverinfo?uniqueid=bb43b6770163bfef&uuid=0b21d6bd-faf5-4a87-a094-d4624db95241
messages.js:35 [messages.js, handleMessage] Message data:  https://:47984/serverinfo?uniqueid=bb43b6770163bfef&uuid=f69e3c02-ed94-42b3-b6bb-0110004fc70a
messages.js:35 [messages.js, handleMessage] Message data:  https://<IP address>/serverinfo?uniqueid=bb43b6770163bfef&uuid=9cf85165-0a53-4011-a52f-f5f66b8fd2c8

**Comment by Jorys-Paulin** [comment]
@NowJoJo It should say something like `http://your-ip:47984/serverinfo?uniqueid=bb43b6770163bfef&uuid=f69e3c02-ed94-42b3-b6bb-0110004fc70a`. Have you correctly entered your ip inside the add host button dialog?

**Comment by NowJoJo** [comment]
Its using my PC's name, not IP.. Ill try again

**Comment by NowJoJo** [comment]
Doesn't work, says are you sure host is on

**Comment by NowJoJo** [comment]
Okay, it shows up like the way you sent ONLY when I am on the same network as the PC

**Comment by NowJoJo** [comment]
@Jorys-Paulin ^

**Comment by NowJoJo** [comment]
@Jorys-Paulin No, you said it should say "http://your-ip:47984/serverinfo?uniqueid=bb43b6770163bfef&uuid=f69e3c02-ed94-42b3-b6bb-0110004fc70a" 

I said when I am on my home/primary network it shows the IP, when I am not it just says my computers name, I tried adding the IP address again on a different network and it just says is the host on?

**Comment by Jorys-Paulin** [comment]
@NowJoJo That means you misconfigured your ports. Check if they're open and pointing to your computer and restart your ISP box after that. You should then be able to enter your ip address inside the add host dialog and it should connect and log what I wrote above.

**Comment by NowJoJo** [comment]
@Jorys-Paulin I opened all the ports that the guide says to, I ran you .bat script, restarted my router many times and computer. The only thing I haven't restarted is my ISP box/modem, I'll try to do that now and let you know the result

**Comment by NowJoJo** [comment]
@Jorys-Paulin That didn't work either...

**Comment by NowJoJo** [comment]
Still searching for help!

**Comment by NowJoJo** [comment]
When I am not at home do I use my home IP address or the PC IP address?

**Comment by cgutman** [comment]
Your home IP address. The PC IP address is only valid on your home network.

**Comment by Jorys-Paulin** [comment]
Le me know how it goes. For now, closing this issue
