### ISSUE TITLE
Can´t connect Moonlight to host PC via Chrome Alpha App

### ISSUE THREAD

**Issue by TALENTCRAZY** [moonlight-stream/moonlight-chrome#396]
Hi, Moonlight Java worked for me during months via Hamachi with no problems, but since christmast it stopped.

Now I have to use Chrome Version because Java Version
 was discontinued.

Host PC: Windows 10 Prof, Nvidia GTX 1070 OC Strix Asus, and Geforce Experience 390.65.

Client PC: Windows 7. Last version of Moonlight Chrome.

----------

If i try to use Moonlight Java it says to me that It needs UDP 48010 port.

https://i.imgur.com/fBTMDxH.png

If i try Chrome App it opens the program on host PC but doesnt stream anything in the Client, it report a gray windows (Sometimes its doesnt do anything) and nothing happens. No message, nothing.

https://youtu.be/boYPx8eo3VM

----------

Ports UDP/TCP 48010 are open on both PCs, Client and host.

Both PCs have 300 mb symmetrical 

--------

I need your help, my job depends on Moonlight power, i travel a lot and need to use my WorkStation via streaming without lag.

Thanks you.

**Comment by Jorys-Paulin** [comment]
@TALENTCRAZY Have you opened and configured all the ports mentioned [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet)?

**Comment by cgutman** [comment]
Are you sure you're using Moonlight Chrome v0.8.2? The failure at RTSP handshake stage is the symptom of trying to stream from GFE 3.12 with an older Moonlight client.

If so, I'd suggest a Wireshark packet capture on your host PC to make sure the TCP 48010 packets are making it to your machine.

**Comment by TALENTCRAZY** [comment]
Solved.

I configured all ports from Jorys link, and updated GeForce Game yesterday to 390.77, now it works pretty well.

Thanks you all.

**Comment by Jorys-Paulin** [comment]
@TALENTCRAZY Now you can close this issue :)
