### ISSUE TITLE
Unable to stream over internet

### ISSUE THREAD

**Issue by androbourne** [moonlight-stream/moonlight-chrome#397]
Hello,

Previously I was able to stream over the internet with no issues. I tried to update moonlight stream client to most current chrome release. Now I am unable to launch anything.

I followed the troubleshooting guide, and setup guides, reforwarded my ports in the router, made exceptions in local firewall and disabled it, disabled AV etc....

Static IP is correct as well and canyouseeme.org shows the ports are open.

I open Moonlight Streaming app and I am able to add my PC to it. When I click on a game and it appears to complete the handshake and it launches the game on the Host PC but does not stream it to the local machine over the internet. I can even "close open apps" inside of Moonlight and it will close the app properly on the host machine. It simply wont stream the image\display to the local machine.

It appears to perform the launch app process but fails at the very last second. No black screen, nothing. It just shows handshake process and closes the launched application right away.

I have tried updating Nvidia drivers on the host pc as well. Rebooted multiple times etc... No matter what I do, I simply can't get it to display an image anymore over the internet.

**Comment by Jorys-Paulin** [comment]
@androbourne Have you tried that?
> IMPORTANT: If you stream over the Internet, you must add a new port forwarding entry for TCP 48010

**Comment by androbourne** [comment]
Yes. That is the very first thing I did. I even deleted all my existing port forwards and redid them all from scratch, including that port which shows up on canyouseeme.org as open.

**Comment by Jorys-Paulin** [comment]
@androbourne No reboot of your ISP box since the ports are already opened. You have forwarded your ports directly to your computer?

**Comment by androbourne** [comment]
Yes. As I stated in my original post. Local firewall is disabled but just to be save I allowed the ports locally through firewall just incase. I also have a static IP on the PC and internet ports forwarded from my firewall to my local PC. That is on a bridged connection without any double NATs etc...

And as stated previously. canyouseeme.org on the host machine shows the ports are open.

I do not have an ISP modem/box. It is behind my firewall, my firewall is connected directly to the fiber line handling all traffic.

This worked previous to the recent update...

**Comment by Jorys-Paulin** [comment]
@androbourne I suggest you ask the devs, like @cgutman for technical details.I don't see why it wouldn't work.

**Comment by Jorys-Paulin** [comment]
@androbourne Have you followed this guide to setup everything? https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet

**Comment by androbourne** [comment]
Yes... I've followed that setup guide as well.

**Comment by Jorys-Paulin** [comment]
@androbourne Have you tried with the Java version?

**Comment by Ajguy** [comment]
I'm running into the exact same issue. Games launch and host PC adjusts resolution, but the Moonlight extension on the remote client just kicks out to the game list as soon as it connects. When I attempted to re-run a game, I can hear it for a just a second before betting kicked back to my library again.

**Comment by androbourne** [comment]
@Ajguy Yep, exactly same issue I'm having.
@Jorys-Paulin No I havn't tried it. Where is the java version? I don't see it for download on the main page.

**Comment by androbourne** [comment]
So today it appears to be working with no changes made...  not sure whats going on. Still using chrome version.

I suspect maybe it had to do with a firewall at the location I was at. However, the place I'm currently at has the same firewall as the one from the original site I was trying to stream too, it doesn't work from that one site but works at another.

Strange.

**Comment by Jorys-Paulin** [comment]
@androbourne Is your issue resolved? If so, you can close this issue. otherwise, we'll be here to help!

**Comment by noi4eg** [comment]
I have same issue

**Comment by Jorys-Paulin** [comment]
@noi4eg What's happening exactly? Give me the most details as possible to allow myself to help you.
