### ISSUE TITLE
USB over IP to support Steam Controller, racing wheels, flight sticks, even VR headsets?

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-chrome#399]
As of today it is possible to use the keyboard and mouse as well as an (Xbox style) controller. But peripherals like racing wheels and flight sticks are more common with PC gaming and Chrome runs on laptops where people are more likely want to use these (less on mobile devices). And this would also open the possibility to stream VR games on a VR headset which is connected to the client and not the host! VR gaming over the cloud will be the future. My prediction is that GeForce NOW will have VR support in 1-2 years for standalone devices like the Oculus Santa Cruz, making high-end VR gaming truly wireless! And USB over IP would also allow us to use the Steam Controller.

**Comment by Jorys-Paulin** [comment]
Hey @JasonS7notG5, It is a great idea, but if Geforce Experience doesn't support it, then we're out of luck, we won't be able to implement it into Moonlight :/
