### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by frax1988** [moonlight-stream/moonlight-chrome#401]
After connecting to my local PC where i run gamestream from and clicking on a game, i get sound for like 1-2 seconds and a black screen before i get sent back to the game selection screen. I can see the game has been opened on my PC and working but not on my chromebook where i run the Moonlight chrome extension. I have tried removing my pc from the list and adding it again to no succes. What am i doing wrong?

**Comment by Jorys-Paulin** [comment]
Hey @frax1988, what was the problem? Why did you close this issue?

**Comment by frax1988** [comment]
Sorry for not posting this, totally forgot. What solved my problem was a reboot on my computer. Then everything started working properly!
