### ISSUE TITLE
Try to build but make error "No rule to make target"

### ISSUE THREAD

**Issue by waumand** [moonlight-stream/moonlight-chrome#402]
Hello,

I'm trying to build myself the CRX because I need some special resolutions like 1440p at 16/9 for an iMac and 1600p at 16/10 for a macbook pro retina.
So I folk and modify the index.html.
I follow this tuto : https://github.com/Jorys-Paulin/moonlight-chrome/wiki/Building

But as you can see on the picture, I god a trouble at make.bat with a "No rule to make target" "needed by" ... 
![capture d ecran 2018-02-11 a 16 44 18](https://user-images.githubusercontent.com/6934787/36075679-a18cfcfc-0f52-11e8-89ac-eb98f8efb158.png)
So how can I avoid this error ?

**Comment by Jorys-Paulin** [comment]
You need to unit git submodules, I forgot to add this in my guide

**Comment by KayZey** [comment]
Cool, can you make a few 21:9 ratios or isn't that supported?

**Comment by waumand** [comment]
@KayZey Yes I can, please tell me precisely what resolutions do you want ?
I cannot test myself 21:9 with a native screen in server (I can "trick" by adding new resolutions in Nvidia panel) and client, but the quality won't be good to see (I could only testing bitrate), so I'll modify my fork, build it and send it to you for testing.
I'll try this toning or tomorrow.

Please reply to me directly into https://github.com/moonlight-stream/moonlight-chrome/pull/386 because the issue 402 is solved ;-)

**Comment by Jorys-Paulin** [comment]
Hey @waumand, you can close this issue now, I'll add this to my guide :)

**Comment by waumand** [comment]
@KayZey come on in https://github.com/moonlight-stream/moonlight-chrome/pull/386 because I close this Issue.
I've done what you need, it's build there, check it.

I don't have do something special in my Nvidia Machine, except I also create these resolutions on my Nvidia panel (because my TV didn't support more than FullHD 16:9) and check the support for resolutions that my TV didn't support.
What is your graphic card in your Nvidia Machine ? You are in RJ45 ?
What is the model of your Macbook ? And you already are in Wifi AC I suppose ? (needed, working not great in Wifi N)
