### ISSUE TITLE
about streaming with PS4 controller

### ISSUE THREAD

**Issue by leehom87** [moonlight-stream/moonlight-chrome#403]
The X axis of the left stick is not responding when I use my PS4 controller.

**Comment by Jorys-Paulin** [comment]
@leehom87 Try on htmlgamepad.com If your X axis is recognized and works

**Comment by leehom87** [comment]
@Jorys-Paulin My PS4 controller works fine in Moonlight JAVA version and steam game streaming. I don't know why the X axis of left stick is not recognized in chrome version. BTW, my computer is a MAC.

**Comment by Jorys-Paulin** [comment]
@leehom87 What I wanted to see was if the controller's X axis was recognised by your browser, usign http://html5gamepad.com/, checking for Axis 0 and 1
![html5gamepad com_ screen 720p](https://user-images.githubusercontent.com/5084309/36140166-8e01f314-10a0-11e8-882e-a048488668e3.png)

**Comment by leehom87** [comment]
@Jorys-Paulin My PS4 controller is ok with an USB cable.
But when I use bluetooth, Please see below.
![wechatimg34283](https://user-images.githubusercontent.com/36401861/36162094-77f19162-1120-11e8-9a97-111d0cdfaf27.jpeg)

**Comment by Jorys-Paulin** [comment]
@leehom87 Looks like it is recognized correctly. Where you pushing the X-axis while making this screenshot ?

**Comment by leehom87** [comment]
@Jorys-Paulin I'm pushing left stick right with an usb cable, it works fine.
![wechatimg35](https://user-images.githubusercontent.com/36401861/36164079-3d3e145e-1126-11e8-8962-c59a6c36ffc4.jpeg)

This is I am pushing left stick right in bluetooth condition. It seems the AXIS 0 is not responding.
![wechatimg36](https://user-images.githubusercontent.com/36401861/36164118-6064520e-1126-11e8-8568-2dcfb6ce9f96.jpeg)

**Comment by Jorys-Paulin** [comment]
@leehom87 Are the other axis working?

**Comment by leehom87** [comment]
@Jorys-Paulin Yes, all other axis working, only the X AXIS of left stick not responding

**Comment by Jorys-Paulin** [comment]
@leehom87 Weird. I don't know why it does that tough. I won't be able to help you on that :(

**Comment by leehom87** [comment]
@Jorys-Paulin it's ok, thanks!

**Comment by Jorys-Paulin** [comment]
@cgutman Any ideas?

**Comment by Rporter996** [comment]
Hello I'm having the same issue. Everything on the controller works except for left and Right on the left stick and it seems the chrome extension is the only option now as the java version is discontinued. Any ideas?

**Comment by Jorys-Paulin** [comment]
@Rporter996 Does it also happens on http://html5gamepad.com?

**Comment by bpmcl** [comment]
This is still an issue as of the 0.9.0 release. Inputs all fine on http://html5gamepad.com, and is otherwise working in all other Mac apps except Moonlight.
