### ISSUE TITLE
Window Mode works! FullScreen Lagging.

### ISSUE THREAD

**Issue by Floraly** [moonlight-stream/moonlight-chrome#404]
I use Moonlight in Window Mode on Chrome and everything works great. If I switch to FullScreen image laggs and mouse movements lags and everything feels fine shifted by 500 ms. In window Mode it feels not delayed.

Streamer and Client both uses 720p Resolution. 1388x720 with 60fps. Connected with LAN 1 GBit both Computers. Direct connection with only one switch.

Can someone give me an hint why FullScreen don't work very well?

**Comment by Jorys-Paulin** [comment]
@Floraly You are using a very weird resolution, maybe the scaling that (maybe) happens in fullscreen is at the heart of the problem
