### ISSUE TITLE
Mouse Sticking and Stuttering Chrome OS Moonlight

### ISSUE THREAD

**Issue by jrclinton** [moonlight-stream/moonlight-chrome#405]
Hi,

I recently was having the issue where my mouse would be stuck in the middle of my screen and snap back whenever it would leave a small range around the center. After upgrading to the latest release of chrome like the other posts suggest, and ensuring I have the latest installation of moonlight (chrome) installed The problem went away. However now I am experiencing a new error where my mouse will "stick" as I am moving the cursor downward.

I have tried to unplug my mouse on the host computer, change the mouse being used on the chromebook, turn off mouse acceleration on the host computer, play with sensitivity settings on both the host and chromebook. If there is any known fix, let me know.

Chrome Version: 64.0.3282.144 (Official Build) (64-bit)
Host OS: Windows 10
Geforce Experience Verson: 388.13

**Comment by Jorys-Paulin** [comment]
@jrclinton When you are playing a game, it is normal for the cursor to stay in the middle (if I'm not mistaken), and it shouldn't be displaying

**Comment by jrclinton** [comment]
@Jorys-Paulin Does moonlight only support controller games? I thought it supported keyboard and mouse games as well?

**Comment by Jorys-Paulin** [comment]
@jrclinton Yes it does support  mouse and keyboard. Try reinstalling and checking for updates to see if he problem still occurs.

**Comment by jrclinton** [comment]
After reinstalling, I am still seeing the issue. Chromebook is Acer C720p.

**Comment by Jorys-Paulin** [comment]
@jrclinton But does the host cursor gets moved ?

**Comment by Jorys-Paulin** [comment]
@jrclinton Have you tried re-installing Geforce Experience or try running the Android version on your Chromebook as well as another device?
