### ISSUE TITLE
No video in certain environments

### ISSUE THREAD

**Issue by tara9tara** [moonlight-stream/moonlight-chrome#406]
I have a VPN connection from my workplace to my home PC.
iOS works normally. Chrome has no video. (Rarely one frame is displayed)
Audio comes out.
Chrome does not have any problem on the local LAN.
I doubted the problem of VPN, but if I connect VPN via iPhone's LTE network, the picture will appear normally.
What is the problem?

Chrome Ver. 65.0.3325.73 on MacOS 10.13.3
Moonlight Chrome v 0.8.2

**Comment by Jorys-Paulin** [comment]
@tara9tara To stream over the internet you'll need to input your home's IP address and port-forward using the [official guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet), VPN is not supported :/

**Comment by tara9tara** [comment]
Thank you!
 I stopped VPN connection and connected with global IP, Chrome also worked.
