### ISSUE TITLE
No mouse cursor on client even with mouse plugged in in the host

### ISSUE THREAD

**Issue by CheessieStew** [moonlight-stream/moonlight-chrome#408]
Tried all the tricks I've read on the internet but it seems like this is a more serious case. Basically, I can see the cursor on the host's display, but it is invisible in the client's display.

The client runs on Acer Chromebook R 11

**Comment by Jorys-Paulin** [comment]
@CheessieStew How is that even possible? GeForce Experience captures all the screen, including the cursor...

**Comment by CheessieStew** [comment]
No idea, that's what's happening - the cursor is visible only on the host's screen.

**Comment by Jorys-Paulin** [comment]
@CheessieStew Maybe reinstalling GeForce Experience will fix the problem, this is the first time I see this issue...

**Comment by CheessieStew** [comment]
@Jorys-Paulin Did it, no luck :/

**Comment by Jorys-Paulin** [comment]
@CheessieStew Could you give us some screenshots?

**Comment by CheessieStew** [comment]
![screenshot 2018-02-18 at 15 52 11](https://user-images.githubusercontent.com/16167821/36353197-b813a45a-14c3-11e8-842a-3f2e2d662017.png) Here's what the client sees [incoming edit]

**Comment by CheessieStew** [comment]
![20180218_155717](https://user-images.githubusercontent.com/16167821/36353288-cb5e84f2-14c4-11e8-8d99-40dd11f9b606.jpg)
potato quality, but shows the problem

**Comment by Jorys-Paulin** [comment]
@CheessieStew Well, maybe something on your computer is preventing you from capturing your cursor. Does screen sharing also show your cursor?

**Comment by CheessieStew** [comment]
@Jorys-Paulin The cursor appears in both steam's in-home streaming and chrome remote desktop. What kind of screen sharing do you mean?

**Comment by Jorys-Paulin** [comment]
@CheessieStew Something like Discord or Skype, but I'm just trying to see what could cause the problem.

**Comment by CheessieStew** [comment]
@Jorys-Paulin just tested on discord and indeed it hides the cursor...

**Comment by Jorys-Paulin** [comment]
@CheessieStew So some software is hiding it.

**Comment by CheessieStew** [comment]
@Jorys-Paulin Apparently. Any guesses on how I might go about fixing it?

**Comment by Jorys-Paulin** [comment]
@CheessieStew Maybe your antivirus is doing it, but it's just a guess :/

**Comment by nathanvong** [comment]
Hi there, 

This issue still persists for me. 

The mouse cursor is invisible (but visible on host). It is also invisible with some mouse cursors in games such as Deus Ex Mankind divided's menus. The workaround in when on Windows is to enable mouse cursors, but there is no solution for an in game menu. 

Any advice would be greatly appreciated.

**Comment by Ir0nb1rd** [comment]
Hi,
I also had this problem.
Changing the mouse pointer color to black has fixed this for me for some reason.

**Comment by rtappmeyer** [comment]
I have this issue only in the Win 10 login screen. When I log in from iOS client (apple tv or iphone), ios14.0.1 i don't see the mouse pointer, which i need to click on the on-screen keyboard to enter the pin. Once i'm on the win 10 desktop, i'll see the mouse pointer , no problem.

**Comment by drthegirlfriend** [comment]
I am now having this issue infact....it's at any full screen windows 10 issue, and only since the latest update about 2 days ago....running moonlight v3 and windows 10....I've updated pretty mcuh everything I could think of, it doesn't seem to fix the problem.

**Comment by drthegirlfriend** [comment]
With help on the discord, a solution was found to use DDU from guru 3d to clean uninstall all current drivers, and downgrade to game drivers https://www.nvidia.com/en-us/drivers/results/159887/ 446.1 

This fixed the issue, But I have not attempted to reupgrade drivers. This symptom started appearing after installing windows 19042.

**Comment by drthegirlfriend** [comment]
This bug returned as soon as any driver was updated above version 446.1, After doing a roll back on windows to version 1909 build 18363.1440, and fully updating geforce experience, and studio driver 461.92. This bug completely dissappeared. To reiterate, any version of windows above 1909 had this mouse bug for me. 

As such, the conclusion is there is a problem somewhere with windows build 19042, Geforce experience 3.21.0.36 and any driver past version 446.1

Hope this helps

**Comment by oit63** [comment]
no luck

**Comment by wangshuai-007** [comment]
I  try use bluetooth mouse in ipad, and run moonlight paly game.
But the cursor is not visiable(sometimes)

When I run mstsc for  my PC,It works well

Besides,moonlight not support mouse down event and mouse up event

**Comment by Andrew1431** [comment]
> Hi, I also had this problem. Changing the mouse pointer color to black has fixed this for me for some reason.

Bless you @Ir0nb1rd this fixed my issue on Windows 11. The exact same issue as described in this thread. Didn't happen on my desktop, but trying gamestream from my laptop and I was having this issue.

**Comment by ashish7adlakha** [comment]
Mouse is only not visible when it is in text selection icon mode. i changed mouse color to black it started showing
