### ISSUE TITLE
Windows 10 version

### ISSUE THREAD

**Issue by vsnst** [moonlight-stream/moonlight-chrome#409]
Hello, Thank you for providing such a good application.
I wonder will there be a Windows 10 App or a version without using chrome, maybe support Microsoft Edge. Thank you

**Comment by Jorys-Paulin** [comment]
@vsnst For now, it's impossible since we're relying on UDP and TCP sockets available only on chrome extensions.

**Comment by vsnst** [comment]
Thank you for replying. I'd glad to help for beta test if possible. :)

**Comment by Jorys-Paulin** [comment]
@vsnst A Windows 10 version will be only possible if we find a way to make the application as like a simple web site

**Comment by Insidious611** [comment]
I'm sorry, what? That's the most bizarre reason to not release a native app I've ever heard. "We're using UDP and TCP sockets only available to chrome"? That's... that's not how sockets work.

**Comment by Jorys-Paulin** [comment]
@Insidious611 
- On the web, only WebSockets are allowed (for "security reasons"), raw upd/tcp sockets are limited to extensions in chrome only
- "Making it act like a webpage": use WebSockets as a replacement for UDP/tcp sockets, provided we can make the conversion to UDP/tcp on the host computer before it arrives at GFE, which doesn't support WebSockets as far as I know
- Using electron could be a solution, something using the HTTP or net package, because calls to the GFE API needs a custom certificate

**Comment by Insidious611** [comment]
"On the web, only WebSockets are allowed" I guess my Discord client, IRC client, spotify, etc are communicating over thin air then?

**Comment by Jorys-Paulin** [comment]
@Insidious611 Nope, they are using WebSockets, because they can. We, we can't because GFE doesn't support it. We'd like to, but we can't :(

**Comment by Insidious611** [comment]
That's... I really suggest you get a refresher course in the TCP/IP stack. Desktop applications can communicate over raw TCP/UDP (or even other raw network protocols, such as ICMP!) just fine. If this weren't the case, things like the "ftp" command running in cli, "ping", etc wouldn't work. The concept of "WebSockets" didn't even exist before 2011.

**Comment by Jorys-Paulin** [comment]
@Insidious611 Yes, but it's in the case we port the current app. We could remake it in native code and use your sockets.
When it comes to web apps, we are usign websockets, example with spotify: (wss stands for web socket secure)
![unitlted](https://user-images.githubusercontent.com/5084309/40872408-086fc0b0-664e-11e8-9398-a4e74c7493af.png)

**Comment by Jorys-Paulin** [comment]
@Insidious611 Here's with Discord:
![image](https://user-images.githubusercontent.com/5084309/40872433-688750da-664e-11e8-9b3c-262f6cdf8b3a.png)

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so I guess it's the version you asked. In the meantime, closing this issue.
