### ISSUE TITLE
RTSP Handshake failed with error 35

### ISSUE THREAD

**Issue by ParanoidEye3** [moonlight-stream/moonlight-chrome#410]
Hey everyone, I'm trying to get Moonlight to allow streaming to my iOS tablet, and I can get it to function just fine while at home on my own Wi-Fi network. When trying to use a different network however, I receive the error "RTSP handshake failed with error 35"

I have opened up ports 47984, 47989, and 48010 on my router and firewalls as TCP. Verified that they are open as well from canyouseeme.org. I have opened ports 47998, 47999, 48000, 48002, and 48010 as UDP as well to make sure I receive audio.

Originally I tried streaming over IPv4 and received this error, so since both my home network and my tablet get 10/10 for IPv6, I decided to install the GameStream IPv6 Forwarder, however receive the same error message.

I tried disabling my firewall all together on my PC to make sure I didn't miss something there, I have uninstalled GeForce Experience on my computer and performed a fresh install, I have deleted the computer from moonlight and manually added with my IPv6 address and still receive the same errors.

I'm at a complete loss at this point, and any help would be most welcome!

**Comment by ParanoidEye3** [comment]
I'm sorry, I believe I have this in the wrong section. I have moved it to the iOS thread.

**Comment by Jorys-Paulin** [comment]
@ParanoidEye3 Hope you can get an awnser there, otherwise you can still post here!
