### ISSUE TITLE
4k black screen

### ISSUE THREAD

**Issue by devonak** [moonlight-stream/moonlight-chrome#411]
Running through LAN, client is an old p5n-d Core 2 Quad, 8 gigs ram gtx 970 windows 7 64 bit.  The game machine is a i7 4790k,16 gigs ram gtx 1080ti windows 10.  Using my galaxy s8 I can select 4k and it runs without a hitch.  Both monitor for game machine and client are 4k.  Not sure why phone android app can do the 4k but the chrome moonlight version can't?  When I load into my desktop via the mstsc.exe app all I see is a black screen.  It looks like the mouse won't activate into the window either.  Like I'm only still using my local mouse, even after clicking into the black screen.

**Comment by devonak** [comment]
Tried turning off some flags to see what would happen.  When I turn off "Hardware Accelerated video decode" 4K will work (slowly).  The black screen no longer appears though.  When I do this I see the message at the bottom of the screen saying that hardware accelerated video decode didn't work so it's falling back to CPU decode.  I presume this is no desired.  Why would HAVD fail on 4k but not at 1080 (I Tried on the other resolutions).

**Comment by Jorys-Paulin** [comment]
@devonak Maybe, since you said it's an old client. Try with another if you can.

**Comment by devonak** [comment]
@Jorys-Paulin only other one I have.  I don't know much about h.264 but I wondering why the chrome://gpu readout said my baseline, main, and high were 1920x1088 for h.264. It's there any way to modify this or is it just a limit of the gtx 970?  also does anyone know if the Nvidia shield has this limitation for game streaming?  I really want to stream 4k from my upstairs to down.

**Comment by Jorys-Paulin** [comment]
@devonak Your 970 should be able to decode a 4K stream, just make sure drivers are up to date. Streaming in 4K is possible, at least it should.

**Comment by Jorys-Paulin** [comment]
@devonak Have you enabled hardware acceleration btw? It's under `chrome://settings` at the very end under advanced settings.

**Comment by Jorys-Paulin** [comment]
Can you follow up? Give us more details, please? In the meantime, closing this issue.
