### ISSUE TITLE
Game only runnable in windowed mode

### ISSUE THREAD

**Issue by Amoulila** [moonlight-stream/moonlight-chrome#412]
Hello,

A few weeks ago, me and my friend were trying to play Tales of Zestiria through GFE and the moonlight chrome plugin. We ran a single test, and it was working 100% fine.

We then were busy with our respective lives, and we tried today to play it, but it was not working properly anymore. This issue only applies to the streaming process, since the game works 100% fine solo (QHD, full/windowed mode etc).

To sum up, the game crashes instantly in fullscreen mode, and can only be played in windowed mode (that I first have to change in "solo" in the graphic settings of the game). If I try to revert it back to fullscreen (when paired with my friend), the game crashes in the same fashion.

This is an issue because we both have QHD screens, and the game is nearly unplayable in windowed mode, plus the resolution is smaller than QHD.

So naturally, we tried several things: 

- I downranked both GFE and Nvidia drivers several times: nothing changed
- My friend downranked Moonlight: nothing changed
- I formated my computer: nothing changed
- I tried to start the game in 1980x1080 instead (both desktop reso, and IG reso): no success
- I tried other games (as Magicka 2), but they were working fine

I also need to mention that I encounter the same exact issue with the Moonlight Android app on my smartphone device (to  rule out to my friend was the issue OR the chrome plugin).

Totally unsure of what that might be. Could be related to Steam, could be related to this game specifically (but it worked fine 3 weeks ago), could be that I'm missing something  obvious.

I'd appreciate any kind of help, thanks.

Regards.

**Comment by Amoulila** [comment]
Sorry, problem solved. My game wasn't fully updated for some reason. It works fine now. 

Still, thank you for this amazing app. Playing with my far away friend "locally" is like a dream coming true.

Regards.

**Comment by Jorys-Paulin** [comment]
@Amoulila Happy to see your problem got resolved with an update, I didn't have an idea of what was happening otherwise, good thing it got solved with an update :)
