### ISSUE TITLE
Mouse Scroll Not Working

### ISSUE THREAD

**Issue by AttChatuba** [moonlight-stream/moonlight-chrome#413]
I'm on the latest version of moonlight, and using Chrome beta (because it was the only way to fix another mouse related bug) Also in the latest version. 

Until a couple of weeks ago, I could stream to my windows 10 laptop over the internet from my home computer without many problems, but now every time I try to use the scroll wheel, it does nothing.

The only way I managed to get it working was by alt tabing in and out of moonlight, but doing that makes the keyboard stop responding inside moonlight

**Comment by Jorys-Paulin** [comment]
@AttChatuba 
- The mouse bug you are mentioning is fixed in Chrome v64 (at least it should)
- I tried with my laptop and got no problems
- To make the keyboard interact again, you have to click once to make your cursor being captured as well as your keyboard

**Comment by AttChatuba** [comment]
@Jorys-Paulin 

The Chrome version is: Version 65.0.3325.88 (Official Version) beta 64 bits
I do click to make the mouse and keyboard work, but only the mouse responds.

**Comment by Jorys-Paulin** [comment]
@AttChatuba Chrome Beta should be fine, maybe try to run the official release to see if that's the problem. So, both the keyboard and the mouse scroll doesn't work? I don't see why they wouldn't, since it works for me (I run beta GeForce and official release for chrome)

**Comment by AttChatuba** [comment]
@Jorys-Paulin Sorry if I didn't make myself clear, english isn't my first language.
I meant, keyboard works normally, and mouse moves and clicks with all 3 buttons, but the scroll wheel doesn't move up or down.
When I alt+tab and click back into moonlight, the mouse works as normal, but the keyboard stops working inside moonlight.

I'll try using it with the normal build

**Comment by Jorys-Paulin** [comment]
@AttChatuba I'm just intrigued by this issue, first time I see it.

**Comment by Jorys-Paulin** [comment]
@AttChatuba Are you running the latest version of Geforce Experience? Are you running experimental features?

**Comment by AttChatuba** [comment]
@Jorys-Paulin yes, I am using the latest version (I check it almost everyday) and no, I'm not using any experimental features.

**Comment by AttChatuba** [comment]
@Jorys-Paulin I couldn't find a solution anywhere.

**Comment by Jorys-Paulin** [comment]
@AttChatuba Maybe enabling experimental features may help... I honestly don't know how to resolve this issue...

**Comment by AttChatuba** [comment]
@Jorys-Paulin well, thanks for trying, I'll wait and see if anyone else has any idea of what could be happening

**Comment by AttChatuba** [comment]
Switching from the beta version of chrome seems to have fixed the scrolling issue, I just hope the mouse stutter bug has been fixed on that version as well

**Comment by Jorys-Paulin** [comment]
@AttChatuba Glad you cloud find your answer :)
