### ISSUE TITLE
Starting control stream establishmentfailed when trying to connect over ipv6

### ISSUE THREAD

**Issue by WegFetZ** [moonlight-stream/moonlight-chrome#415]
Hi

I'm having trouble getting streaming to work over ipv6 with moonlight-chrome.

I am trying to stream from my desktop with a GTX 1070 and the latest version of Geforce Experience to my notebook over the internet. Everything works well within my local network over ipv4, but since I do not get a public ipv4 address from my isp, but only an ipv6 address (with ds-lite), I need to use ipv6 when I'm elsewhere.

I followed the instructions on https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet and made sure that no (windows) firewall is blocking any ports. In fact the connection doesn't seem to be the problem here, because I can reproduce the error locally on the desktop itself, trying to connect to its own link-local ipv6 address (which again works well using the local ipv4 address).

Everything goes well up to the "Starting control stream establishment..." stage. The game is launching on my desktop, the RTSP handshake succeeds, but then the window just returns to the game overview.

This is the relevant section of the Moonlight log (ip removed):
> messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting input stream initialization...
> messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting control stream establishment...
> messages.js:35 [messages.js, handleMessage] Message data:  Starting control stream establishmentfailed
> messages.js:35 [messages.js, handleMessage] Message data:  streamTerminated
> messages.js:35 [messages.js, handleMessage] Message data:  https://XXXIPV6XXX:47984/serverinfo?uniqueid=6dd43e002570e69f&uuid=8a3cd3d9-0b32-402d-9c4e-dea979f43b86
> utils.js:243 [utils.js, _parseServerInfo] Parsing server info: n.fn.init [root, prevObject: n.fn.init(1), context: document, selector: "root"]
> utils.js:348 [utils.js, utils.js] Returning memory-cached apps list

Full log: https://pastebin.com/9P1s3KZS
Note that the control stream establishment fails without error code.

The NVStreamer log has a lot of 

> Timeout of 500 ms for: connection creation

messages in it, before the stream gets terminated.
Full log: https://pastebin.com/5sKEpTi0

Since everything works well with ipv4 I was thinking that maybe the GS-IPv6-Forwarder doesn't work as expected, so I cloned and recompiled it, after adding a few additional ports, listed here: https://forums.geforce.com/default/topic/764816/gamestream/remote-gamestream-router-port-forwarding-and-tegra-zone-update-/
Unsurprisingly, this didn't help at all.

I'm out of ideas. If I had the time I would clone the repo and try to debug, but maybe you guys have any idea or I'm missing anything?

**Comment by cgutman** [comment]
Hmm, I thought I had tested Moonlight Chrome successfully with IPv6 but maybe not. I have the same issue, though my iOS and Android clients connect fine via IPv6.

**Comment by WegFetZ** [comment]
I cannot test it for Android, since my phone doesn't seem to have any IPv6 connectivity at all and I don't own any iOS device to test it. I had some free time today, which I used to write a little python program to act as a relay between ipv6 and v4, just like your GS-IPv6-Forwarder and it worked well with that, so I really think there is an issue with the IPv6-Forwarder.
I would have tried to debug, but I'm not really knowledgeable in C++. Might be a good opportunity to get into it.
