### ISSUE TITLE
Keyboard layout incorrect and always EN/US

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-chrome#416]
It always uses EN/US layout not the Windows 10 layout selected.

**Comment by Jorys-Paulin** [comment]
@makedir See #393

**Comment by Jorys-Paulin** [comment]
@makedir I'm still waiting on the developer @cgutman for advice, I don't know how to resolve this error for now :/

**Comment by Jorys-Paulin** [comment]
@makedir I just tested and it still does that. I'm running Geforce Experience Beta.

**Comment by makedir** [comment]
@Jorys-Paulin Hm ok. Yes, I am running beta too of GFE. So that doesnt resolve it. I dont see it because of game is in the forground. Does GFE change the Windows keylayout to EN or what? Maybe send a keybind to Windows to change it to default when game starts.

**Comment by Jorys-Paulin** [comment]
@makedir I just tested, and the indicator in the bottom right stays at "FRA"

**Comment by makedir** [comment]
@Jorys-Paulin Did you open a bug ticket about it on the Nvidia GFE forum? They wont read it anyway or do anything about it as I know Nvidia.

**Comment by Jorys-Paulin** [comment]
@makedir No I didn't

**Comment by felixcousseau** [comment]
Hi, Is there any update ?

**Comment by Jorys-Paulin** [comment]
@makedir I just tested with my azerty keyboard and it printed qwerty... So no it's not fixed yet.
