### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by realies** [moonlight-stream/moonlight-chrome#419]
Latest Moonlight is stuck on loading animation. Tried 2 versions back, same result. Tried enabling the aforementioned flag in Chrome and restarting, same result. Any ideas what's causing this? Latest Windows 10 x64.

**Comment by Jorys-Paulin** [comment]
@realies Have you tried the android version? Maybe Geforce Experience is the problem.

**Comment by realies** [comment]
@Jorys-Paulin, the app does not load at all. This is prior a connection attempt.

**Comment by Jorys-Paulin** [comment]
@realies Both the android version and the chrome version? Can you give us screenshots?

**Comment by realies** [comment]
Unfortunately currently can't. It opens up the Moonlight app on Chrome and stays at the loading bar (not stuck, playing the loading animation forever). Chrome on macOS and Android clients work.

**Comment by Jorys-Paulin** [comment]
@realies Try inspecting by opening the console: https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs

**Comment by Sojborg** [comment]
I have the same issue as OP

**Comment by Jorys-Paulin** [comment]
@Sojborg PNacl is probably disabled. That's the only thing I see from the logs.

**Comment by Sojborg** [comment]
@Jorys-Paulin you should add that to the install guide if that is an requirement.

I tried it and it got me further according to the logs but i'm still stuck on the "Loading moonlight" screen:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLDocument.<anonymous> (common.js:381)
background.js:19 Chrome app runtime launched.
```

**Comment by Jorys-Paulin** [comment]
@Sojborg Are you sure your Chrome is updated? Because something breaks the split method.

**Comment by Sojborg** [comment]
My chrome version: 
Version 64.0.3282.186 (Officiel version) (64-bit)

It says that there are no updates available.

**Comment by Jorys-Paulin** [comment]
@Sojborg Weird. I don't know what does that then :/

**Comment by Sojborg** [comment]
i just tried on another machine where it works fine :-/. But i need it to work on the machine where it doesn't work.

I tried to disable all other chrome extension and reinstall chrome but no luck. Any other suggentions?

**Comment by Jorys-Paulin** [comment]
@Sojborg Maybe something is blocking access to sockets.

**Comment by Sojborg** [comment]
I have symantec firewall. Have you heard about issues with this concerning moonlight?

**Comment by Jorys-Paulin** [comment]
@Sojborg No but I know moonlight relies on chrome sockets to communicate with your network

**Comment by Sojborg** [comment]
Is it using websocket secure (wss) or none secure (ws)? https://stackoverflow.com/questions/45737635/socket-connection-from-chrome-extension-being-blocked-by-proxy-firewall

websockets works on in general on my machine:
https://www.websocket.org/echo.html

**Comment by Jorys-Paulin** [comment]
@Sojborg Sadly it doesn't, it's actually raw TCP UDP sockets provided by chrome.

**Comment by Jorys-Paulin** [comment]
@Sojborg Each extension can use it, but your firewall may be blocking it.

**Comment by seppeel** [comment]
Hi,
i am having the same issue on a linux machine running chrome 67 on ubuntu 18.04. Im stuck at "Loading moonlight" screen. And im getting the "Cannot read property 'split'" error, too.

Any new ideas on this? Thanks! :)

**Comment by Jorys-Paulin** [comment]
@seppeel are you running the packages from Chrome?

**Comment by seppeel** [comment]
@Jorys-Paulin As Chrome does not allow me to install the crx directly, i downloaded the 0.9.0 zip (tried master too) with unpacked it and installed it with "Load extracted extension" (translated from german :D ). NativeClient is enabled.
I tried to start moonlight via chrome://apps and via the newly created shortcut in ubuntu.

does that help? :D

**Comment by Jorys-Paulin** [comment]
@seppeel I'm not familiar with the Linux version, but make sure you have everything listed in the [requirements](https://github.com/moonlight-stream/moonlight-chrome#requirements)

**Comment by seppeel** [comment]
Yes, looks like something with pnacl support goes wrong ... :(

```
[updateStatus, common.js] Page loaded.
common.js:56 [browserSupportsNaCl, common.js] is NOT host toolchain for tool: pnacl
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:58 [browserSupportsNaCl, common.js] mimetypes: application/x-pnacl
common.js:331 [updateStatus, common.js] Browser supports NaCl (pnacl)
common.js:331 [updateStatus, common.js] Creating embed: pnacl
common.js:74 [createNaClModule, common.js] name: moonlight-chrome, tool: pnacl, path: pnacl/Release, width: 200, height: 200, attrs: {}
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:94 [createNaClModule, common.js] moduleEl: {}
index.js:905 [index.js] Moonlight's main window loaded
2pnacl/Release/moonlight-chrome.nmf:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:1 NativeClient: could not load manifest url.
common.js:150 [handleError, common.js] ProgressEvent
common.js:331 [updateStatus, common.js] ERROR [NaCl module load failed: could not load manifest url.]
```

**Comment by Jorys-Paulin** [comment]
> common.js:56 [browserSupportsNaCl, common.js] is NOT host toolchain for tool: pnacl

Definitely. I would ask @cgutman for this, he knows better how to deal with this. I wasn't able to make it work on my Ubuntu WM

**Comment by Jorys-Paulin** [comment]
@seppeel BTW, have you enabled native client under `chrome://flags`?

**Comment by seppeel** [comment]
Yes, its enabled.

**Comment by Jorys-Paulin** [comment]
@seppeel As I said, I don't really know the Linux version, so we'll be asking @cgutman for this, for I don't know.

**Comment by cgutman** [comment]
No longer relevant since support for the affected platforms is discontinued. The native PC client is not affected by this issue.
