### ISSUE TITLE
Test and enable 4K streaming

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#42]
We need to add the GUI options for 4K and find any other places where resolutions might be hardcoded. We should also make sure it works on the various platforms.

**Comment by raidancampbell** [comment]
Where are we getting a 4K panel to test this?  I don't know anyone with one

**Comment by raidancampbell** [comment]
Also, what do we call "4K"?  There seems to be two major conventions, and "4K" doesn't fit well with either:

720p, 1080p, 2160p

HD, FullHD, UltraHD

I'm opting for continuing with the standard and calling it "2160p".  We could possibly label it to the user as "2160p (4K)"

**Comment by cgutman** [comment]
On Android, we use 720p, 1080p, and 4K. Although the terms are technically different categories, they are the terms that users recognize. Not as many people recognize 2160p or UltraHD as 4K.

**Comment by Flowwwie** [comment]
I have a 5k panel, which I can run at 4k to test.
Also a java/node + css/html/javascript dev

**Comment by raidancampbell** [comment]
The current build of master should be capable of streaming 4K.  We tried it, and received video.  You're welcome to build and verify on your end

**Comment by Flowwwie** [comment]
Yeah It works no issues for game streaming.
For streaming remote desktop from windows through mstsc.exe it either black screens or insta-freezes.
Doesn't bother me and I'm not sure whether it's an issue on your side or a limitation or rdp as I haven't gone any further than simply trying to do it

**Comment by raidancampbell** [comment]
I saw identical behavior, good to know

**Comment by Flowwwie** [comment]
Actually after some more manual testing it appears to freeze after 10-15 seconds on anything. Not using wired ethernet so that could be the problem, but am using 5ghz ac . Will get on a wired connection and have another look

**Comment by raidancampbell** [comment]
Does it freeze and kick you back to the UI?

Could you open the Javascript console (right click>inspect>console) and see if anything is logged when you see the freeze?

**Comment by raidancampbell** [comment]
@Flowwwie do you have any updates on this?

**Comment by Flowwwie** [comment]
Sorry been rammed with work and will be this weekend too.
Status : Streaming at 4k starts fine and the video freezes after ~4 seconds.
Audio carrys on.
No errors in Javascript console

This is over 5ghz wifi A/C, I do not have an ethernet port on this macbook to test a wired connection.
When I have time I will get it going on another pc with an ethernet port to test

**Comment by jeid64** [comment]
Moonlight-chrome probably should also have the check that Moonlight-common does here (https://github.com/moonlight-stream/moonlight-common/blob/1848665dc5254f3b983ba6258326409bd815fbb4/src/com/limelight/nvstream/http/NvHTTP.java#L381)

If you don't have a 980 card, the server won't return 4k in the list of supported resolutions from /serverinfo. If you then try to select 4k, it will fail to setup RTSP stream as your card can't support it.

I can try and make a commit tonight to check if 4k is supported and if not, remove it from the dropdown list of possible resolutions.

**Comment by Flowwwie** [comment]
I have a 980 in my desktop so compatibility on that end is fine

**Comment by raidancampbell** [comment]
This was released a while ago, and have heard no issues if it breaking so far.

If something breaks down the road, I may implement a check for support, the data already exists on the backend.
