### ISSUE TITLE
Moonlight keep asking for pairing every launch

### ISSUE THREAD

**Issue by evildog1** [moonlight-stream/moonlight-chrome#420]
Its so frustrating that it kept asking me to pair every launch and have to go back to my pc to type the damn code. Luckily, other remote desktop apps exists. I used Chrome remote desktop to enter the code but still frustrating.

I cleared profile, reinstalled Chrome, and moonlight and it remembered my paring for 2 days until this bug come back again. It does not happen on other platforms iOS and Android. They remember pairing for 6 months and still remember even no use than 2 weeks.

**Comment by Jorys-Paulin** [comment]
@evildog1 Sadly I don't know why it does that but I'll be curious to know what causes this error. I know the app use Chrome's local storage, so maybe it is flushed by some other program on your system, or even by chrome itself

**Comment by evildog1** [comment]
Possibly but i don't have programs that flush this. Do you know the location of logs to diagnose the error?

**Comment by Jorys-Paulin** [comment]
@evildog1 https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs

**Comment by lkaczmarski** [comment]
Hello, 
I'm having the same issue. I've attached some screenshots from the Inspect console. Sometimes it will ask for pairing and sometimes the host icon shows a yellow frame when clicked on and nothing else happens. Any ideas what could be causing this? 

![capture](https://user-images.githubusercontent.com/34713255/37020131-ab3802ac-2112-11e8-81cd-7d4356430aa7.PNG)
![capture2](https://user-images.githubusercontent.com/34713255/37020136-b0c4fb30-2112-11e8-9b98-580643081b3b.PNG)

**Comment by Jorys-Paulin** [comment]
@lkaczmarski Nothing shows up in the console, it seems like it's pairing but refuses to set the `pair`property to `true`. I don't know what causes this.

**Comment by evildog1** [comment]
It seems to be fixed after chrome update

**Comment by evildog1** [comment]
It happens again after a week but my phone still remember.

**Comment by Jorys-Paulin** [comment]
@evildog1 What do you mean by "my phone still remember"

**Comment by lkaczmarski** [comment]
So it looks like my issues with losing pairing completely disappeared once I removed adblocker from chrome.

**Comment by Jorys-Paulin** [comment]
@lkaczmarski Maybe it was the program that cleaned the app localstorage, thinking it was tracking data

**Comment by cgutman** [comment]
I think I fixed the culprit - https://github.com/moonlight-stream/moonlight-chrome/commit/ddd7310e384349331ce82260e13e3b7a79f31f0b

**Comment by cgutman** [comment]
Fix released in v0.9.0
