### ISSUE TITLE
Mouse Cursor Stuck on Spinner during Diablo 3 on Macbook Pro - SO CLOSE to working!

### ISSUE THREAD

**Issue by timzyk** [moonlight-stream/moonlight-chrome#421]
First, immense thank you for Moonlight! I'm blown away at how well it works. 

The issue i'm having:
- Installed Chrome extension on 17" Early 2011 MacBook Pro Chrome browser (after troubleshooting all the WebGL errors/stuff)
- Load moonlight via Chrome App Launcher, pick Diablo 3
- Game loads but the mouse cursor changes to the spinner as it loads Battle.net
- Once Battle.net loads Diablo 3 loads great but the cursor is stuck on the blue spinner
- I can fiddle with the Diablo control settings and manage to get the spinner mouse pointer to change to the regular mouse pointer BUT the "click location" (or whatever it's called) is NOT the tip of the mouse pointer, it's the bottom of the mouse pointer which is super confusing (unplayable)

Any ideas on a workaround???

I did try clicking Steam instead of Diablo 3 directly, then picking Diablo 3 from within Steam but no luck. I'm using a super cheap USB connected mouse (no DPI settings or anything). 

Again, major thanks for what you do!

-Tim

---

Data exported | 3/2/2018, 1:17:13 PM
-- | --
Chrome version | Chrome/64.0.3282.186
Operating system | Mac OS X 10.13.3
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/9611116ee79c63602f452e4fae2242a61cf0672d/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/9611116ee79c63602f452e4fae2242a61cf0672d/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 2987f0fde973
2D graphics backend | Skia/64 713571f9afcf4b673812cd3b52bb5b17c107038b-
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --enable-nacl --enable-webgl-draft-extensions --ignore-gpu-blacklist --flag-switches-end

**Comment by Jorys-Paulin** [comment]
@timzyk Weird, Diablo III is supposed to be fully supported by GeForce Experience... Is it the only games it does that to? Can you try the Android version, see if that's moonlight-chrome related.

**Comment by timzyk** [comment]
Diablo 3 works via my Shield TV with mouse support (albeit laggy but sep issue) so I'd think it's a Chrome/Macbook Pro issue??

**Comment by Jorys-Paulin** [comment]
@timzyk Maybe, it's the first time I see this issue (had a lot of these lately) so I don't really know what's happening...

**Comment by Jorys-Paulin** [comment]
Can you follow up? Give us more details, please? In the meantime, closing this issue.
