### ISSUE TITLE
black screen, no sound after fixing the issue with timeout of "Starting Control Stream Establishment"

### ISSUE THREAD

**Issue by pyrow14** [moonlight-stream/moonlight-chrome#423]
I'm having an issue with Black screen, no sound. It first was failing to even pull up a black screen and would stop doing anything at "Starting Control Stream Establishment" as if it would time out and go back to the game list.

Now it gets past the stream establishment but just shows a black screen

![image](https://user-images.githubusercontent.com/37121222/37053835-172c00de-2132-11e8-8b68-285b900e6b64.png)

Everything tried so far
Ports Forwarded:
48010
47989
47984
47999
47998

-I forwarded all of these ports in both UDP and TCP

other things tried:
-I have tried making the host machine start Rise of the Tomb Raider first and then use moonlight to connect
-I tried to make the resolution of the game in 1920 by 1080 windowed mode, read someone else got it to work on this forum by making the game run in window mode. 
-I made sure the moonlight client side was ready by putting it on the 1080 resolution thinking I need to have both sides understanding that the res is 1080

Host computer
Win 10 
i7
16gb ram
gtx 1070

Client machine
win 10 pro
i3
8gb ram
no graphics card

Hopefully you guys can give me some more ideas to test. I also have no access to the router on the Client side because I'm trying to play video games on slow days in the office :p #superproductive haha. Thanks for any and all help. 

PS Client machine I use, uses tons of RDP connections to other VM's and what not, which I have heard causes issue. I don't know what these issues are exactly and I tested by closing all RDP instances even the splashtop app I use to connect to the host machine. but same as if I left everything open.
Again thanks for any and all help here.

**Comment by Jorys-Paulin** [comment]
@pyrow14 Sadly the module used for streaming doesn't log its activity, so asking you for logs won't probably help. Still, you can give them to us if you want (blur the external ips)

**Comment by pyrow14** [comment]
@Jorys-Paulin I actually was able to get it to work! Thanks anyway. Turns out it was more darn ports I didn't find until I read another  article. 

The only issue now is that there is a fair amount of latency on the client machine when using my xbox one controller. Any good ideas on decreasing latency?

**Comment by Jorys-Paulin** [comment]
@pyrow14 What ports were missing? Use wire wherever you can.

**Comment by Jorys-Paulin** [comment]
Hey @pyrow14, do you still have latency issues? If not, you can close this issue, otherwise, we'll be here to help!

**Comment by thespyman13** [comment]
I am having this same exact issue. Moonlight was working for me last month, but all of a sudden it's not. I think I have every port forwarded, but my android device is stuck at "Control stream establishment". Any fix on that?

**Comment by Jorys-Paulin** [comment]
@thespyman13 Maybe you updated to a new version of GFE and didn't added the 48010 port.
