### ISSUE TITLE
extention crashes while trying to load icons

### ISSUE THREAD

**Issue by nk33** [moonlight-stream/moonlight-chrome#427]
Lately my extension crashes after loading about 5 icons. 

If I completely remove the extension,  then re-add it,  it works the first time only, after that it will crash every time. Not sure whether the timeout has to be increased or its something else.

**Comment by Jorys-Paulin** [comment]
@nk33 That's because all the icons are loading at once, I think.

**Comment by Jorys-Paulin** [comment]
@nk33 Or is it since you updated to chrome 65?

**Comment by SirHamlin** [comment]
This is happening to me as well.  I have to open the app multiple times for it to finally load everything.

**Comment by nk33** [comment]
@Jorys-Paulin i am honestly not sure as I dont use it on this pc that often -  but it has only been in last few weeks. 

should i revert to a previous version of chrome? what is the best known version for this extension?

**Comment by nk33** [comment]
why cant we just have a tick box at the begining so it doesnt load the icons. i know it looks good like this but honestly...who cares? LOL

**Comment by nk33** [comment]
update - when i restart the pc it works for the first time. If i close it then try and reopen it it crashes every time.

so basically to use this extension at the moment i have to reboot my pc first every time loool

**Comment by Jorys-Paulin** [comment]
@nk33 Could you [read the logs](https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs), see if there's anything weird going on, because it shouldn't do this unless your PC can't handle loading multiple images at once.

**Comment by Jorys-Paulin** [comment]
https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs

**Comment by nk33** [comment]
ok - i have enabled this, relaunched chrome then relaunched the app...clicked on the pc...and it crashed.

I went to inspect and it gives me a whole bunch of stuff on the right - what should i send?

**Comment by Jorys-Paulin** [comment]
@nk33 Everything, make sure you blank IPS before

**Comment by nk33** [comment]
sorry...blank ips?

**Comment by Jorys-Paulin** [comment]
@nk33 Yes, if you want you can blank them out

**Comment by nk33** [comment]
i mean whats ips?

**Comment by Jorys-Paulin** [comment]
@nk33 Some things like 192.268.0.10, but since you stream overpriced your local network you don't really need it

**Comment by nk33** [comment]
theres so much stuff here i have no idea what to send you...everything under elements?

**Comment by Jorys-Paulin** [comment]
@nk33 The console tab logs many things

**Comment by nk33** [comment]
i have probably done this really crap

![image](https://user-images.githubusercontent.com/25930267/37361030-c91d1de8-26e9-11e8-9f0b-3a48c4a2dd04.png)

**Comment by Jorys-Paulin** [comment]
@nk33 Next to "Elements" you have "Console". Click in and you'll see lines of logs Wich basically shows what the program is doing and what can happen wrong. I can already see and error on your screenshot (that's the red Cross labeled 1 on the top right)

**Comment by nk33** [comment]
when i click on console, there is nothing there. The error was from something else i tried to do 

so when i click on console i just get a cursor  - like you get when it wants you to type a command

**Comment by Jorys-Paulin** [comment]
@nk33 I noticed you are running Chrome 65. Maybe this is (another) bug that was introduced with the update.
I also noticed you aren't inspecting the right window, you need to inspect the moonlight window, not the extensions tab

**Comment by nk33** [comment]
so in the extensions tab, i right click on the moonlight icon, then click inspect. thats what it brings up

**Comment by Jorys-Paulin** [comment]
>  You need to inspect the moonlight window, not the extensions tab
Inspecting the extensions tab won't show up info about moonlight

**Comment by nk33** [comment]
when i open moonlight, i cannot right click on its window - there is no menu

**Comment by Jorys-Paulin** [comment]
Have you followed the guide I gave you? You should be able to open the console then.

**Comment by nk33** [comment]
ok - i see now - i was being an idiot.

ok - so i got the console working - the problem is that when the app crashes so does the console so i cannot copy and paste the error

**Comment by nk33** [comment]
it crashes while loading each game...u can see it loadiung the games one by one - then it just crashes

**Comment by nk33** [comment]
![image](https://user-images.githubusercontent.com/25930267/37365396-48fab358-26f5-11e8-9dfc-39bb13c13fbc.png)

**Comment by nk33** [comment]
![image](https://user-images.githubusercontent.com/25930267/37365456-7e2e49b8-26f5-11e8-8cae-afd083281498.png)

**Comment by Jorys-Paulin** [comment]
@nk33 Weird, it loads the images from the cache, so it shouldn't be a problem

**Comment by nk33** [comment]
it crashes at a random image every time

can i clear this cache so they can come down fresh?

**Comment by nk33** [comment]
tell me - do you know how to remove the games that GFE picks up automatically and puts into Gamestream - all i want to appear are the ones i create shortcuts for myself and add manually. they dont contain images and that would be perfect

**Comment by Jorys-Paulin** [comment]
@nk33 It's not a feature yet. All your games in GFE are shown, even if you hide them :/ And even tho they don't have a proper image, technically they have (the controller image IS an actual image, not the default one by moonlight)

**Comment by nk33** [comment]
? ok - but my computer is decent spec - i have worse pc's that dont have this problem, Any ideas why mine is crashing on icon load?

**Comment by Jorys-Paulin** [comment]
@nk33 Chrome is beautiful but terrible at the same time. I don't know why it does that for you :(

**Comment by nk33** [comment]
i have another idea - maybe the dev can increase the timeout before it registers as a crash - i am sure if we made it another 30 seconds it wouldnt crash

**Comment by Jorys-Paulin** [comment]
@nk33 I think chrome is to blame here. Try to find an read chrome's logs or even better, chrome's crash logs.

**Comment by nk33** [comment]
its happening on my work pc as well now - wasnt before

**Comment by Jorys-Paulin** [comment]
@nk33 If your work of recently updated to chrome 65, it is definitely to blame

**Comment by nk33** [comment]
@Jorys-Paulin i have reverted back to various old versions and still get the same error.

i honestly think there is something new in GFE preventing machines with weaker processors from finishing the icon load.

I suspect this because further evidence is that i have tried it from my Razer Edge Pro and it works fine, closed moonlight and re-opened it over 5 times- works a treat (i7 3517U)

**Comment by nk33** [comment]
ridiculous now - it is crashing on my high end devices as well....what is going on????

**Comment by cgutman** [comment]
Should be fixed by https://github.com/moonlight-stream/moonlight-chrome/commit/6c457fe56def88c06d5d83942df281641723b4ac

**Comment by cgutman** [comment]
Fix released in v0.9.0

**Comment by nk33** [comment]
WOW - the icons load instantly now!!

thanks v. much to the devs!!!!
