### ISSUE TITLE
Input delay using Moonlight Chrome

### ISSUE THREAD

**Issue by Lariax** [moonlight-stream/moonlight-chrome#428]
Hi. I have a problem. Big problem for me. Before this, I always play game on my phone (Xperia Z2). No lag at all (15ms). Today, I wanna try at my laptop. But the delay is about 100ms or 200ms.
Here is my Host specs:
CPU: i5-6600K @ 4.5GHz
RAM: 8GB
GPU: GTX 1070.
Connection: 100Mbps Full Duplex
Geforce Experience: 3.12.0.84 (Latest Version)

This is my client PC:
CPU: i5-3210M @ 3.1Ghz
RAM: 8GB
GPU: Intel HD 4000/GT 650m
Connection: 2.4Ghz 300N wifi
Moonlight Chrome: 0.8.2

Then, I tried to stream game from my host to client using steam home streaming. No delay at all. I expected there was video encoding problem here.

**Comment by makedir** [comment]
I have the same issue. I think it is just a very very very very very very very very very very bad idea, to solve a programmable problem like this, via a Chrome Addon. There should be some kind of w32 standalone client written in C.

**Comment by Lariax** [comment]
@makedir Are you using windows 7 or windows 10?

**Comment by makedir** [comment]
Windows 10 64bit.

**Comment by FelixKratz** [comment]
@makedir  A native port seems like a nice community project, i recently did a native implementation of moonlight for macOS with HEVC support. Maybe someone will start a native windows port at some point.

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so it will be a "don't fix" on that one, sorry!
