### ISSUE TITLE
Xbox360 controller not working on any PC client (Mac or PC

### ISSUE THREAD

**Issue by dthomson39** [moonlight-stream/moonlight-chrome#429]
I an new to this so sorry if I have assumed something works in a particular way and it doesn't!

I have NVEx installed on my host machine and can open and run games very well via Steam with Moonlight on my Mac and on my PC clients - but- I cannot get my Afterglow XBox 360 controller to work on either client. I am running the machines on the same LAN.
The game I'm trying this with is Elite Dangerous.
Any advice or things to test etc I would welcome.

**Comment by Jorys-Paulin** [comment]
@dthomson39 Try going to http://html5gamepad.com on your laptop, see if your gamepad is recognized

**Comment by dthomson39** [comment]
Hi
Thanks for replying. To be sure I’ve done the correct check :

I opened the link you sent using the browser in Steam that was available after running moonlight  - the test indicated that no gamepad was connected even after pressing    all buttons - I do have the Xbox control software running on the Mac and that shows the pad is working fine.

Cheers

Dave

**Comment by dthomson39** [comment]
Hi

Please ignore my last message - I can confirm that the html5 tester does
pick up the controller on both the mac and the pc and shows changing data
as buttons and sticks are moved. So there is something going on (or not)
between my client machine using Moonlight/chrome and the host running
GEForce/ Steam as I re-ran the game and the controller is not seen by the
game.

Are there router issues that I should look at or something else re software
configs on the host?

Regards

Dave

**Comment by Jorys-Paulin** [comment]
@dthomson39 Maybe the Xbox control software is the issue.Disable it if you can to see if that's the problem (I'm not familiar with that program).

**Comment by dthomson39** [comment]
HI again,

I removed the controller drivers on the Mac and restarted - no difference -
still the same on the PC as well.
On the client game menu there are only options for keyboard and mouse
copntrol and these do work within the game - there are no gamepad options
the game menu on the host machine but if I plug one into the host those
menu options appear - those dont appear on the client machine.

Any further throughts? I'll stick to the PC client for now as that might be
easier to fathom.

Regards

Dave


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Jorys-Paulin** [comment]
@dthomson39 There was an issue like that with L4D2, but got premusably resolved by the commit [fdcd3d4](https://github.com/moonlight-stream/moonlight-chrome/commit/fdcd3d4747b70ca6e1c906956c62b44d7778c5da). Maybe your game isn't fully compatible with Gamestream.

**Comment by Jorys-Paulin** [comment]
@dthomson39 `Elite Dangerous` is listed as supported under Geforce's [list of optimised games](https://www.nvidia.com/en-us/geforce/geforce-experience/games/), but that doesn't mean it has full controller support, even for gamestream

**Comment by dthomson39** [comment]
Who would know?

Shall I email them or would it be someone in the Moonlight dev team (unless
you are one of those anyway) - I don't mind chasing Frontier if that's
required.

Cheers

Dave

**Comment by Jorys-Paulin** [comment]
@dthomson39 I'm a contributor, but I don't exactly knows how the streaming part works (it's written in C++, and I'm a JavaScript developer), but the dev @cgutman might know how to fix this issue.

**Comment by dthomson39** [comment]
Great thanks - I’ve popped a note into the frontier forums - I’ll contact @cgutman and see where it takes me

Thanks for being so helpful.

Dave

**Comment by dthomson39** [comment]
One final thing - how to I reach @cgutman? I can’t see a way of opening an issue with him as the recipient

**Comment by Jorys-Paulin** [comment]
Sometimes he checks for issues updates where I ask him for help, by mentioning him he should be notified.

**Comment by dthomson39** [comment]
Great thanks
D

**Comment by dthomson39** [comment]
Hi just thought I’d let you know my problem is almost fixed - turns out there was a setting in my router that needed flipping and the controller jumped into life!

Only issue now is that one button is not detected by the html5 tester on the client but is on the host - right trigger button. I have tried to create a map using the tool but have no idea where to add the line that was generated or at which end of the comms channel (host or client)!

Thanks 
Dave

**Comment by Phaethon1** [comment]
> Hi just thought I’d let you know my problem is almost fixed - turns out there was a setting in my router that needed flipping and the controller jumped into life! Only issue now is that one button is not detected by the html5 tester on the client but is on the host - right trigger button. I have tried to create a map using the tool but have no idea where to add the line that was generated or at which end of the comms channel (host or client)! Thanks Dave
> […](#)
> Sent from my iPhone
> On 16 Mar 2018, at 08:33, Jorys Paulin ***@***.***> wrote: Sometimes he checks for issues updates where I ask him for help, by mentioning him he should be notified. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Hi dthomson39, I got the same issue. which router setting was it?
