### ISSUE TITLE
"Add Host" button not working on Linux running Chromium

### ISSUE THREAD

**Issue by clay53** [moonlight-stream/moonlight-chrome#430]
The button just doesn't do anything.

**Comment by Jorys-Paulin** [comment]
@clay53 Can you open the console (https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs) and give us the logs?

**Comment by Jorys-Paulin** [comment]
@clay53 I tested on Chromium 64 on Ubuntu 17.10 with the official release and I got the following inside the console:
```
common.js:331 [updateStatus, common.js] Page loaded.
common.js:56 [browserSupportsNaCl, common.js] is NOT host toolchain for tool: pnacl
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:58 [browserSupportsNaCl, common.js] mimetypes: application/x-pnacl
common.js:331 [updateStatus, common.js] Browser does not support NaCl (pnacl), or NaCl is disabled
index.js:820 [index.js] Moonlight's main window loaded
index.js:903 [index.js] Loaded previously connected hosts
```

The main  takeaway here is: `common.js:331 [updateStatus, common.js] Browser does not support NaCl (pnacl), or NaCl is disabled`
@clay53, Is it the same for you?

**Comment by bottleneckblaster** [comment]
I ran into this same issue on Arch with the most recent mainline Chromium release. I've solved the problem by building/compiling the most recent Chromium-dev branch (available via AUR). The GPU/HW accel options in the dev branch's chrome://flags and chrome://gpu pages give you a large degree of freedom (and a huge performance boost if you're using the Nvidia VDPAU drivers as it allows you to use GPU h264 decoding in Moonlight).

**Comment by Jorys-Paulin** [comment]
@bottleneckblaster Si Maybe it is because pnacl isn't supported in the official build but is in the custom build. I'll try compiling and give you my results, since I've never compiled chrome before.

**Comment by clay53** [comment]
Here (sorry it took me so long):
[updateStatus, common.js] Page loaded.
common.js:56 [browserSupportsNaCl, common.js] is NOT host toolchain for tool: pnacl
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:58 [browserSupportsNaCl, common.js] mimetypes: application/x-pnacl
common.js:331 [updateStatus, common.js] Browser does not support NaCl (pnacl), or NaCl is disabled
index.js:820 [index.js] Moonlight's main window loaded
index.js:903 [index.js] Loaded previously connected hosts

**Comment by Brike70** [comment]
Hi Guys,

Just wanted to bump this as I'm having the same issue.

There is a PPA for Chromium dev, which has the video codec but not the native client here:

https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev
https://github.com/saiarcot895/chromium-ubuntu-build

Wonder if it would be worth raising it with them to get native client included?

Cheers,

Brike.

**Comment by cgutman** [comment]
No longer relevant since the affected platforms are now unsupported. This bug does not affect the native PC client
