### ISSUE TITLE
Single buuton on Xbox360 controller on client not detected

### ISSUE THREAD

**Issue by dthomson39** [moonlight-stream/moonlight-chrome#432]
I have tested an Afterglow Xbox 360 controller using the html5 tester and all buttons respond on the host and one the client machine (MAC Book Pro).  When I connect via moonlight chrome the right trigger button is not detected (again using html5 tester via the browser in Steam).
Not sure where to go from here as its a key button for many games.

**Comment by Jorys-Paulin** [comment]
Can you follow up? Give us more details, please? In the meantime, closing this issue.
