### ISSUE TITLE
Wake on Lan (WOL)? Feature request.

### ISSUE THREAD

**Issue by gbdrbob** [moonlight-stream/moonlight-chrome#434]
Hi, I see no option in moonlight-chrome to wake a host PC. 

I think many users would find this feature useful, even if we had to manually enter the host MAC address. 

I believe the MAC address/the arp table is not accessible to chrome apps so unless geforce experience on the host PC reports the MAC to moonlight it would have to be entered manually.

In the meantime there already exists a separate [chrome app for Wake-on-LAN](https://chrome.google.com/webstore/detail/wake-on-lan-wol/apfabhfippohjkndobkbeoiplilgojei)

**Comment by Jorys-Paulin** [comment]
@gbdrbob Is it possible, since when you go to `<geforce-pc>:47989/serverinfo`, you get the following line:
```xml
<mac>D8:CB:8A:C0:B1:56</mac>
```

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so it will be a "don't add" on that one, sorry!
