### ISSUE TITLE
Workaround for keyboard keys

### ISSUE THREAD

**Issue by realies** [moonlight-stream/moonlight-chrome#436]
Is there a way to send the Windows key to the remote machine or Alt+Tab? Noticed that sending Ctrl+Shift+T to the remote Chrome doesn't work as well.

**Comment by Jorys-Paulin** [comment]
@realies Indeed it doesn't work at all for me. Don't know why.

**Comment by realies** [comment]
@Jorys-Paulin, it is most likely a limitation by GameStream. I wonder if there could be an adequate workaround.

**Comment by Jorys-Paulin** [comment]
Via javascript, it is possible to detect the meta key (also known as the windows or mac equivalent). However, when asking to block default action (open the windows menu) it is completely ignored and still opens the windows menu.
I tested here, on the very bottom, with "key down" and "suppress default action" enabled: https://www.quirksmode.org/js/keys.html

**Comment by realies** [comment]
@Jorys-Paulin don't think capturing the keys is the issue but rather them coming out on the other end via GameSteam. An ugly solution would be an agent on the remote machine that executes the keystrokes for you, but I would go that way only as a last resort.

**Comment by Jorys-Paulin** [comment]
@realies It still opens the client's menu btw

**Comment by realies** [comment]
Testing with a macOS client here. Do you mean that pressing the meta key on a windows client shows the client's start menu?

**Comment by Jorys-Paulin** [comment]
@realies Yes, sorry if you misunderstood

**Comment by realies** [comment]
I see. Not sure how `moonlight-streaming` works and if Chrome apps are capable of capturing the meta key input. Should be fairly easy to determine with something like [this](https://www.autoitscript.com/autoit3/docs/functions/Send.htm) by sending `{LWIN}` to the Moonlight window. Might be able to test later on with a Windows client.

**Comment by realies** [comment]
Meanwhile, noticed that Ctrl+N also does not get sent, but Ctrl+O and others do...

**Comment by Jorys-Paulin** [comment]
@realies Maybe it's all client side reserved shortcuts

**Comment by tagcode** [comment]
Depending on your setup, you could use mouse without borders or synergy as workaround.

**Comment by cgutman** [comment]
Some keys are blocked by the Nvidia server. You can use AutoHotKey as a workaround.

**Comment by shalak** [comment]
> Some keys are blocked

@cgutman can we find a complete list of all the blocked keys somewhere? Is it available?
