### ISSUE TITLE
Choppy gameplay for about 5 seconds.

### ISSUE THREAD

**Issue by stromseng** [moonlight-stream/moonlight-chrome#437]
I am having issues where both, audio and video will become choppy/laggy for 5-10 seconds at a time. This makes monlinght unplayable. I have tried exiting Razer Synapse, using a different mouse, changing resolution, fps and bandwith.
I have seen other people havingthe same issues with an Intel Integrated GPU.  I am using HD Graphics 4000 on my laptop. My CPU is a i5-3320M @ 2 Ghz, 4 cores.
There should be no issues with my desktop as i am using a 7700K and a 1080ti. They do not have thermal issues and its running on a 300 Mbit up/down network.

**Comment by Thrywyn** [comment]
Well, the chopping is now gone but my mouse will randomly teleport... If i barely move it 2cm it will suddenly flip me around 3 times in game. Starting to wonder if its a mouse issue, or razer synapse being wierd.

**Comment by Jorys-Paulin** [comment]
@Thrywyn Only way to know is to use another mouse...

**Comment by Jorys-Paulin** [comment]
Hey @Thrywyn, have you tried using another mouse?
