### ISSUE TITLE
unable to find pc on any device 

### ISSUE THREAD

**Issue by nadaso8** [moonlight-stream/moonlight-chrome#439]
moonlight has ceased to show my pc online even when i'm running geforce experience and the pc is on After a some problems with power delivery to the video card (the cable was being flakey, I replaced it).
 I'm on driver version 391.35, Geforce version 3.13.1.30, running on a geforce gtx 1060. 
Also i've updated to the latest moonlight chrome version to see if that was the problem and it doesn't appear to be the case. Is this version of geforce experience not supported yet?

**Comment by Jorys-Paulin** [comment]
@nadaso8 Even the android version doesn't detect it? Have you tried to manually add your PC?

**Comment by Jorys-Paulin** [comment]
@nadaso8 You should try hitting `http://<your-pc-ip>:47989/serverinfo` first

**Comment by nadaso8** [comment]
i'm able to hit the server out of safari but the page is blank, also if i enter ping <pc ip> into the terminal i get a response without issue and Streaming through steam works fine. 
The fact that steam wasn't having problems was what made me think it was a problem in moonlight in the first place. As for android version i'm not sure, I only own an iPhone but that and my raspberry pi have also been unable to connect. 
 
I'm going to see if a full re install of geforce experience helps any thing so I'll be back with news on that later.

**Comment by Jorys-Paulin** [comment]
@nadaso8 That means you probably didn't restart, I think it is necessary for it to restart; And oh, re-enable the shield option in the settings of course.

**Comment by nadaso8** [comment]
Thanks for the help I got things running again, the full reinstall and restart did the trick.
