### ISSUE TITLE
Unplayable input latency with Streaming over IP

### ISSUE THREAD

**Issue by SnekSnak** [moonlight-stream/moonlight-chrome#440]
I know this might not technically be an issue but I'm not sure where else to post.

I only have access to 12mbps upload speeds thanks to Comcast still limiting most home lines unless you have gigabit connection which raises the upload cap to 40mbps.

Moonlight recommends 10mbps for 720p60, but the input latency feels like it's somewhere between 100-200ms. Just to clarify this is when playing over the internet not in-home. It's **slightly** more playable with singleplayer shooters like KF2, but games like Binding of Isaac Rebirth are a nightmare. You essentially have to train your brain to react ahead of time.

Does this latency go away at higher upload rates? Would playing 720p60 at 40mbps reduce latency? I thought I remembered reading that increased bandwidth meant better visuals but worse latency. 

I was hoping for some first hand experience. If it's simply a limitation of Chrome then I'm confused why development time was put into the Chrome app while the Windows Java client was discontinued.

**Comment by Jorys-Paulin** [comment]
@SnekSnak Is it best with the java version? The chrome version was only made for Chromebooks but seemed to became the main version.

**Comment by SnekSnak** [comment]
@Jorys-Paulin I can't confirm whether or not the Java version worked much better as I used it probably close to 3 years ago and the project was in a much different place. Also my internet and hardware were different.

**Comment by Zibbibbo** [comment]
What gpu have your client pc ? if it's the integrated one (like Intel HD or something similar) you can have lot of input latency. 
I've resolved this issue upgrading the client pc with a nvidia 1030, the input lag is reduced about 95% now and everything is playable without problem.

**Comment by Jorys-Paulin** [comment]
@SnekSnak Moonlight was meant to use for in-home streaming, not over the internet in the first place; if it works, great for your, otherwise, too bad.

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so it will be a "don't fix" on that one, sorry!
