### ISSUE TITLE
Failed to connect to <IP>! Are you sure the host is on?

### ISSUE THREAD

**Issue by Discodude16** [moonlight-stream/moonlight-chrome#441]
Hello. I have an issue attempting to reconnect to my PC with moonlight on chrome. I have just reinstalled moonlight, my graphic card drivers, and restarted my PC. Shield is enabled, and I'm able to connect to my PC with apps such as Teamviewer.

Specs:
GTX 750 TI
Nividia GeForce 3.13.1.30
Moonlight 0.9.0

Thanks in advanced!

**Comment by Jorys-Paulin** [comment]
@Discodude16 Could you give us the logs ?
