### ISSUE TITLE
RTSP Handshake Failed Error -1 ?

### ISSUE THREAD

**Issue by AlexS2412** [moonlight-stream/moonlight-chrome#442]
when attempting to connect over the chrome client i get this...

**Comment by mandogy** [comment]
For me when I got this, I tried a few times and then I actually checked my PC and turned out the application was updating.

**Comment by mrsylerpowers** [comment]
Everything was working for the longest and now all of the sudden I am getting this error also

**Comment by Jorys-Paulin** [comment]
@AlexS2412 Plase can you give us the logs? See [here](https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs). Please blank out your public IP if you're connecting over the internet.

**Comment by Jorys-Paulin** [comment]
@mrsylerpowers @AlexS2412 Hey, is it still not working? Have you tried reading the logs?

**Comment by cgutman** [comment]
No response from reporter.
