### ISSUE TITLE
Wrong aspect ratio of covers

### ISSUE THREAD

**Issue by icstyle** [moonlight-stream/moonlight-chrome#444]
Hi

I noticed that the game covers are slightly stretched. I think original size is 600x850 pixels, but it the app it looks more like 600x800 pixels.

Thanks

**Comment by Jorys-Paulin** [comment]
@icstyle
Using chrome dev tools, the natural image size is of `300x400px`, while the display size is of `150x200px`, which looks to me as the same aspect ratio. Maybe yours look different because your window isn't `960x540px`

**Comment by icstyle** [comment]
Yes you are right. But on my Shield TV I'm getting correct aspect ratio on covers. Maybe they could be streched a bit to the "correct" aspect ratio in Moonlight?

**Comment by Jorys-Paulin** [comment]
@icstyle They can't be stretched since they're already at the right size and aspect ratio...

**Comment by icstyle** [comment]
Like I wrote in my first post, they're not in the correct aspect ratio:

![image](https://user-images.githubusercontent.com/37982725/39053746-0983b034-44b0-11e8-9c27-4b6f56e6f7a8.png)

Just compare this covers with my previous screenshot.

**Comment by Jorys-Paulin** [comment]
@icstyle That's because they have their own aspect ratio, these covers aren't the same as the ones in GFE and maybe your Sheild. They're not the same aspect ration because they are different. We can't stretch them without making then look funny (just look at how they look when you hover them) and we can't get other ones because of how Gamestream gives theses images.

**Comment by icstyle** [comment]
I must admit, you're right, they're not the same covers. At least this is true for the games which GFE detects itself. For all custom added games (and IMHO including the Steam-cover), it's streaming the "wrong" covers, and that's why they get strechted. Since we can only specify one type of cover in GFE, I also don't see a solution for that... Interesting tho, how Shield TV can get the other type of covers.

**Comment by Jorys-Paulin** [comment]
@icstyle If you want you can close this issue if you don't have any other suggestions.
