### ISSUE TITLE
Make sure host pc is on.

### ISSUE THREAD

**Issue by Munkeywaxx** [moonlight-stream/moonlight-chrome#445]
Evening all!

So, i'm gandering leaving my PC On overnight allowing for some silly SHMUP's to be played when in bed.

Currently, Geforce Experience is OPEN And Streaming is turned ON Yet, when I attempt to connect to the host PC VIA WiFi I get the re-occurring message:

"Failed to connect to (IP). Are you sure the host is on."

At the time of writing, I am on the host PC.
The GameStream Settings in GFE are ON/OPEN.
Both Client and Host are on the same network.
I've tried With a Direct Bridge between the two devices and nothing has changed.

As far as I am aware, I have the ENTIRE Port-range open on the host pc, but am still unable to connect from the client.

Any ideas/Suggestions? 

Thanks,
~Munkeywaxx

**Comment by Jorys-Paulin** [comment]
@Munkeywaxx Open the console and tell us more there. See the wiki on how to do that

**Comment by Munkeywaxx** [comment]
@Jorys-Paulin 
Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLDocument.<anonymous> (common.js:381)

Is all i'm getting from the console.

Is this a "Me" thing?

**Comment by Jorys-Paulin** [comment]
@Munkeywaxx Is there anything else ? Just reload the app to get the full log and give it to us

**Comment by Munkeywaxx** [comment]
@Jorys-Paulin 

At the time of posting the original Error, that was all I could see from the console.

I've just retried having got back from work and stumbled upon:
https://gist.github.com/Munkeywaxx/b646cf70c8d89d7bb121a303e05ad1ab

**Comment by Munkeywaxx** [comment]
Even connecting to "Localhost" From the PC That GFE Streaming is turned on, still won't connect.

**Comment by Jorys-Paulin** [comment]
@Munkeywaxx Go to `<geforce-pc-ip>:47989/serverinfo` and see what it gives to you. It should be XML code

**Comment by Munkeywaxx** [comment]
https://gyazo.com/d01af80234551456f020cabf5d450446

Sorry for being a bit of a tit.

**Comment by Jorys-Paulin** [comment]
@Munkeywaxx When I get this error, I have no choice but to remove Geforce Experience, reboot, install it and reboot the page to work again :/

**Comment by Munkeywaxx** [comment]
Reboot GFE Or BOTH GFE And Drivers?

**Comment by Jorys-Paulin** [comment]
@Munkeywaxx Uninstalling only GFE should do the trick, should have said that in the first place.

**Comment by Munkeywaxx** [comment]
No worries, will get back to you within the next 10-15 minutes.

**Comment by Munkeywaxx** [comment]
Well @Jorys-Paulin 

It's working now.

Thanks for the assistance, Greatly Appreciated!

Any ideas on why it sometimes refuses to work?

**Comment by Jorys-Paulin** [comment]
@Munkeywaxx I don't know, but it's pretty anoying. Now you can close this issue if you're done with it.
