### ISSUE TITLE
What about a WebAssembly port?

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-chrome#446]
As you may know, Moonlight uses [Native Client](https://developer.chrome.com/native-client) mainly to decode the video stream, as well as network requests.
Thing is, NaCl is apparently ready to be removed from future Chrome Versions, with the main replacement being [WebAssembly](http://webassembly.org/), which is standard to all browsers, not only Chrome.

A WebAssembly version will have many advantages:
- Make Moonlight run in all browsers and devices (even smartphones)
- Get the optimisation for each of them
- And most of all, make Moonlight runs as a single website (do you imagine how cool it is?)

I have seen that some core components required for video decoding where missing, but is it still the case?
I'd very like a WebAssembly version as the main and only one to replace all the other versions, as it would be simpler to manage only one version instead of four separate ones.

**Comment by Jorys-Paulin** [comment]
I found this example on the internet suggesting video components are there: https://d2jta7o2zej4pf.cloudfront.net/

**Comment by Jorys-Paulin** [comment]
Porting to WebAssembly would also bring support for Official Linux Releases as well as mobile browsers.

**Comment by mzernetsch** [comment]
A WebAssembly could also be wrapped inside a Progressive Web App. This would allow for Offline Access and "Add-to-Homescreen/Desktop" functionality without the need of a setup.

**Comment by Jorys-Paulin** [comment]
@Calcyfer That's exactly what I had in mind. Offline won't be necessary since we're dealing with communications in local lan and even through the Internet

**Comment by mzernetsch** [comment]
Sorry that wasn't really clear, I meant offline in sense of "Not connected to the internet". There can be situations where you don't have access to the internet (to get the WebAssembly from the official website) but still be connected to a LAN where you want to stream a game in.

**Comment by Jorys-Paulin** [comment]
@mzernetsch Yes, of course its what I also thought, you can have the entire app running offline but you can still connect to your computer.

**Comment by njibhu** [comment]
Hi, I am interested as well, and could help since I already did port some code from nacl to emscripten like.. 
But the big main issue here is that the native client api is much broader than what wasm offers. I quickly read the manifest and saw:
`"tcp-connect", 
"resolve-host", 
"udp-bind:*:*", 
"udp-send-to:*:*"`
That's in the permission category.. Raw sockets or just even UDP are not available with wasm or web apis...
That's also how the app manages to send a custom certificate since a browser would never let that happen. I think finding a solution to that is going to be quite difficult.

**Comment by Jorys-Paulin** [comment]
@njibhu I read somewhere that upd/tcp sockets are emulated using WebSockets, but I might be wrong. If we can't port directly, then we'll just create a forwarder that sits between GFE and Moonlight, if need be.

**Comment by njibhu** [comment]
Yes and no, websockets are supposed to be tcp-like, but they are still wrapped up inside their own layer, and they can only connect to websocket compliant servers, not to any socket listener (That was actually a security requirement for the standard to be accepted). 
Then yes, the solution is to create a forwarder between GFE and Moonlight.

**Comment by Jorys-Paulin** [comment]
@njibhu Too bad. I guess I could write a forwarder prototype with the net module from node.js, but in production, it might be better to use C++

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so closing this issue.
