### ISSUE TITLE
Black screen with audio

### ISSUE THREAD

**Issue by Cjacob0827** [moonlight-stream/moonlight-chrome#448]
Hello,

When I launch any game using Moonlight-chrome, the game launches fine on the host PC, and the audio comes through, but the client has a black screen. I have the same issue when I use my phone.

I am running Chrome version 66.0.3359.117 (Official Build) (64-bit) with Intel 4200 graphics on the client and Nvidia Driver 391.35 on the host. Both devices are running Windows 10. I have tried both Moonlight on my PC and on my Samsung Note 3.

**Comment by Jorys-Paulin** [comment]
You may have to reinstall completely GeForce Experience, as it may be the problem. Restart between steps.

**Comment by Cjacob0827** [comment]
I'm still having issues, it doesn't work on my PC and my phone, but it works on the host's PC and phone

**Comment by Jorys-Paulin** [comment]
@Cjacob0827 Try with another game. Some games aren't fully supported by Gamestream.

**Comment by Cjacob0827** [comment]
We know that the game is compatible because the host used his phone off of his home network using Data and it worked fine. It wasn't connected to his home wifi if that helps clarify things. Honestly we've been trying different things for a few weeks know and we're both stumped.

**Comment by Jorys-Paulin** [comment]
@Cjacob0827 Well then let's try reading the logs: https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs

**Comment by Cjacob0827** [comment]
Here's the log, sorry for the long time in between my last reply.


[thisiswhatswrongwithmoonlight.txt](https://github.com/moonlight-stream/moonlight-chrome/files/1962818/thisiswhatswrongwithmoonlight.txt)

**Comment by Cjacob0827** [comment]
Sorry for the delay from your last comment, we were figuring out some more things. Here's my crash log 
[thisismymoonlightcrashlog.txt](https://github.com/moonlight-stream/moonlight-chrome/files/1962825/thisismymoonlightcrashlog.txt)

**Comment by Jorys-Paulin** [comment]
Unfortunately, the logs go directly from this:
`messages.js:35 [messages.js, handleMessage] Message data:  Connection Established` (which is great)
to this:
`messages.js:35 [messages.js, handleMessage] Message data:  streamTerminated` (which is not great)
That's once again the NaCl module not logging enough info about the crash, unfortunately, we can't debug it, as far as I know.
Maybe you haven't opened all ports, including `48010`?

**Comment by cgutman** [comment]
Possibly MTU related and likely fixed.
