### ISSUE TITLE
Webassembly

### ISSUE THREAD

**Issue by Helladen** [moonlight-stream/moonlight-chrome#450]
I contacted a dev who made a custom version of Chromium to work with Linux and hardware acceleration, required for this application. He said to move to Webassembly, because his build of Chromium doesn't have native client enabled. Although, he plans to add it after bringing it up, and Google is going to eventually kill off native client which means you should switch to it asap.

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so the move to web assembly is not in the project
