### ISSUE TITLE
RTSP Error 552 /Analys WireShark

### ISSUE THREAD

**Issue by iLeViiSxL** [moonlight-stream/moonlight-chrome#453]
Hello,

I wanted to install moonlight. So I activated the shield mode on my host computer, I opened the ports of my firewall and my internet box (UDP and TCP). I made myself on the client side to be on. I can see the list of my games but can not connect error RTSP 552,400 ...

I opened wireshark to scan the network and on both machines I see UDP packets and some TCP packet arrive on port 48010. But I still can not play.

If anyone could help me? thank you very much

**Comment by Jorys-Paulin** [comment]
@iLeViiSxL We would kindly help you if someone (apart from the devs) knew what those codes meant...

**Comment by ScaleRunner** [comment]
I had the same issue. I solved it by port forwarding all the required ports. They can be found in the documentation.

**Comment by AngelsEnd** [comment]
I have the same issue :/ and i opend all required ports but still the same Error code. Sometimes i get the following error message "Control stream establishment failed (error -1)"
Really strange, if i select a game on the client machine, this game is opening on the host side but on the client it isn't connect to the game. All i get ist the "Control stream establishment failed (error -1)" error :/

**Comment by Jorys-Paulin** [comment]
@AngelsEnd @iLeViiSxL  I read somewhere that enabling game optimisations can solve the issue

**Comment by Jorys-Paulin** [comment]
Closing this issue for now. Comment or re-open if you need it.
