### ISSUE TITLE
Trying to play Co-op with a friend

### ISSUE THREAD

**Issue by Thehungrydude** [moonlight-stream/moonlight-chrome#456]
Hey, we're trying to play lego Star Wars: the Complete Saga in local co-op over Moonlight. We're both using the chrome extension. Everything works as it should except for that my friend can't get his PS4 controller (using DS4Windows drivers) to work. I am hosting the game, using a PS3 controller (using ScpToolkit drivers) to control, which works fine. 

I have tried a bunch of the fixes I have seen online, like renaming rxgamepadinput.dll like is mentioned in the wiki, which doesn't seem to do much for us. In addition to that, we tried to connect 2 controllers on my end since I figured it might be worth a shot since he can effectively "highjack" the host keyboard and use it as his keyboard. That didn't work either. We also tried connecting our controllers using the same driver (ScpToolkit), which also did not work.

Is there any way to fix this problem or does my friend just have to use the keyboard to play?

**Comment by Jorys-Paulin** [comment]
@Thehungrydude The best case scenario would be to use the same controllers. However, I don't see why it wouldn't work. This might need more investigation.

**Comment by nickwreck** [comment]
Usually the client PC's controller is always primary. I've noticed in some single player games I am able to control the game with the host PC's controller. My girlfriend and I use moonlight long distance to play games together but 99 percent of the time I am just watching her play. 

Games that are local co-op that have that screen thats like "Push A to connect controller" work best. Always have the person on the client side connect their controller first (it should already be primary) then once you get to the part where "player 2 (the host PC)" signs in then connect your controller.

**Comment by Jorys-Paulin** [comment]
@Thehungrydude Does this still happens today? Have you updated since? If so, re-open this issue.
