### ISSUE TITLE
Non-Chrome Version of Moonlight?

### ISSUE THREAD

**Issue by arcadeportal32** [moonlight-stream/moonlight-chrome#457]
I don't know if this is an issue, or a question lol.
I have a computer that I would love to use this on, however Google Chrome runs like crap on it & barely works at all and 95% usually crashes. Steam Stream works and connects for about 10 seconds before that craps out too lol.

Is there an .EXE version of Moonlight I can download, or some sort of JAVA version I can execute?

Something for PC that doesn't use Chrome which literally eats up ALL of its ram & barely works through patches due to the PC's age.

**Comment by Jorys-Paulin** [comment]
There's the native version, but be warned it requires at least some horse power to decide the stream: https://github.com/moonlight-stream/moonlight-pc

**Comment by arcadeportal32** [comment]
How do I download it, I see alot of jars and files. Where is the executable at?

**Comment by Jorys-Paulin** [comment]
Here: https://github.com/moonlight-stream/moonlight-pc/releases/tag/v0.7.5, just select for your platform. Be warned, it might not work with current GFE versions

**Comment by Jorys-Paulin** [comment]
@arcadeportal32 Is it what you were looking for? Again, I would strongly recommend using the chrome version, even if it's laggy just because it will be supported for future releases of GFE. Anyways, if you're done, you can close this issue, otherwise, I'll still be here to help!

**Comment by Jorys-Paulin** [comment]
Hey @arcadeportal32, would you like to test the new PC version? Be warned it's still in early alpha!
In the meantime, closing this issue. re-open if needed.
https://github.com/moonlight-stream/moonlight-qt/releases
