### ISSUE TITLE
Can't access PC from internet when multiple Gamestreams are enabled in the same network

### ISSUE THREAD

**Issue by zarko-b** [moonlight-stream/moonlight-chrome#458]
Hi,
I have two PCs that have gamestream enabled that are on the same LAN. The android moonlight app shows them all fine and dandy when my android device is connected on the same LAN. 

The problem is that I can't access one of them when I try to connect to them from outside of that LAN. I've port forwarded all the ports that are shown in this wiki https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet for both the PCs. 

If I have only one PC port forwarded and streaming, then it shows fine, but when I do the same for both of them only one shows as available.

What could be the cause of this problem?

Thanks.

**Comment by zarko-b** [comment]
sorry wrong section should've made this post in moonlight-android.

**Comment by Jorys-Paulin** [comment]
@zarko-b You can't forward to two PC's, you can only forward to one.

**Comment by zarko-b** [comment]
@Jorys-Paulin I see. So you're saying that there is no other way to access both of those PCs?

**Comment by Jorys-Paulin** [comment]
@zarko-b Not for now. You would be able to if you changed the ports used to communicate with GameStream but Moonlight doesn't have this feature yet.

**Comment by zarko-b** [comment]
@Jorys-Paulin Thank you for clearing this up.
