### ISSUE TITLE
how

### ISSUE THREAD

**Issue by bjornanderson** [moonlight-stream/moonlight-chrome#459]
how do i acctially play games

**Comment by Jorys-Paulin** [comment]
- Pair your computer: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#quick-setup-instructions
- Click on it's card
- Click on the game you want to play

**Comment by Jorys-Paulin** [comment]
@bjornanderson If you still need help feel free to re-open an issue ;)
