### ISSUE TITLE
<1 fps on Samsung Chromebook Plus

### ISSUE THREAD

**Issue by mmmaxwwwell** [moonlight-stream/moonlight-chrome#461]
Hello, I Love the android client, but I am experiencing one frame every several seconds on my Samsung Chromebook Plus. The main reasons I'm looking into the chrome extension version of moonlight is A) 100ms framebuffer using the android app on chromebook and B) Mouse capture does not work using the android app (Until chromeos upgrades the android runtime to oreo). Both issues are specific to my chromebook, and do not appear on another device I have that runs on oreo.

I don't think this is due to hardware limitations. When I start a game, my entire Chromebook locks up. The only thing I can do is press the power button, and select power off. The "start" (lower left) menu is not responsive, I can't close out of the window and none of the taskbar icons respond.

Samsung Chromebook Plus (kevin)

Platform
10663.0.0 (Official Build) dev-channel kevin

Firmware
Google_Kevin.8785.264.0

Channel
Currently on dev

ARC Version
4771340

Blink
537.36 (@ba3555398bfb463aa9a8f2e99c983708cfe845f7)

V8
6.8.198

If there is anything I can do to help, please let me know.

**Comment by Jorys-Paulin** [comment]
@mmmaxwwwell 
- You can quit the app using `Ctrl+Shift+Alt+Q`
- Maybe it is because of the dev channel
- Have you enabled hardware acceleration?

**Comment by Jorys-Paulin** [comment]
@mmmaxwwwell Hey, have you tried it?
