### ISSUE TITLE
Moonlight - Loading Apps

### ISSUE THREAD

**Issue by AttChatuba** [moonlight-stream/moonlight-chrome#466]
I've recently formatted my pc and did all the forward stuff again.
But now, when I try to stream on the same network it works fine, but through the internet
I get stuck on the "Loading Apps" screen right after I click to access my pc (I get asked to insert the code into my nvidia experience).
What could be happening?

**Comment by Jorys-Paulin** [comment]
@AttChatuba Make sure all ports are opened, even the one that ends with 10, see wiki for it. Can you also give us the console output? See wiki

**Comment by AttChatuba** [comment]
@Jorys-Paulin This is the Console output, I don't know how to make it collapsible.
All the ports are opened. 

common.js:331 [updateStatus, common.js] Page loaded.
common.js:56 [browserSupportsNaCl, common.js] is NOT host toolchain for tool: pnacl
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:58 [browserSupportsNaCl, common.js] mimetypes: application/x-pnacl
common.js:331 [updateStatus, common.js] Browser supports NaCl (pnacl)
common.js:331 [updateStatus, common.js] Creating embed: pnacl
common.js:74 [createNaClModule, common.js] name: moonlight-chrome, tool: pnacl, path: pnacl/Release, width: 200, height: 200, attrs: {}
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:94 [createNaClModule, common.js] moduleEl: {}
index.js:835 [index.js] Moonlight's main window loaded
common.js:331 [updateStatus, common.js] RUNNING
utils.js:67 [utils.js, NvHTTP Object] NvHTTP
index.js:236 [index.js] Loaded previously connected hosts
index.js:534 [index.js] Entering "Show apps and hosts" mode
main.js:27 IPv6 address unsupported fe80::f4fb:2d66:2212:4036
main.js:30 Broadcasting to address 192.168.0.5
main.js:27 IPv6 address unsupported 2001:0:5ef5:79fd:341c:32e5:428e:b522
main.js:27 IPv6 address unsupported fe80::341c:32e5:428e:b522
messages.js:35 [messages.js, handleMessage] Message data:  https://138.255.147.193:47984/serverinfo?uniqueid=0f0896ab13496ab4&uuid=70922144-1e19-41c4-bd46-cfae0bb956a4
utils.js:238 [utils.js, _parseServerInfo] Parsing server info: n.fn.init(1)
index.js:159 [index.js, backgroundPolling] Stopping background polling of host 3c9cbb12-6663-4137-a73b-0dcdec125d60
 NvHTTP server address: 138.255.147.193
server UID: 3c9cbb12-6663-4137-a73b-0dcdec125d60
is paired: true
current game: 0
server major version: 7
appversion: 7.1.406.0
GFE version: 3.14.0.139
gpu type: GeForce GTX 1050
number of apps: 0
supported display modes: 
	2160:3840: 60,30
	1080:1920: 60,30
	720:1280: 60,30

index.js:460 [index.js, showApps] Current host object: NvHTTP server address: 138.255.147.193
server UID: 3c9cbb12-6663-4137-a73b-0dcdec125d60
is paired: true
current game: 0
server major version: 7
appversion: 7.1.406.0
GFE version: 3.14.0.139
gpu type: GeForce GTX 1050
number of apps: 0
supported display modes: 
	2160:3840: 60,30
	1080:1920: 60,30
	720:1280: 60,30

index.js:549 [index.js] Entrering "Show apps" mode
index.js:159 [index.js, backgroundPolling] Stopping background polling of host 3c9cbb12-6663-4137-a73b-0dcdec125d60
 NvHTTP server address: 138.255.147.193
server UID: 3c9cbb12-6663-4137-a73b-0dcdec125d60
is paired: true
current game: 0
server major version: 7
appversion: 7.1.406.0
GFE version: 3.14.0.139
gpu type: GeForce GTX 1050
number of apps: 0
supported display modes: 
	2160:3840: 60,30
	1080:1920: 60,30
	720:1280: 60,30

messages.js:35 [messages.js, handleMessage] Message data:  https://138.255.147.193:47984/applist?uniqueid=0f0896ab13496ab4&uuid=7912efc1-7d0f-42ef-b828-468107223367

**Comment by AttChatuba** [comment]
This is what happens right after I click to access my pc
![screenshot_1](https://user-images.githubusercontent.com/36642354/40368609-9430bf2c-5db2-11e8-87d7-aecc29f95c76.png)

**Comment by Jorys-Paulin** [comment]
@AttChatuba I see at least two problems:
- `number of apps: 0` It shouldn't be 0, at least if you have games inside GFE
- The header in the screenshot shouldn't be there.

**Comment by AttChatuba** [comment]
@Jorys-Paulin  I have 20 games showing up in there
About the hearder, do you mean the "<Moonlight"?
What could be happening?

Btw, this is what happens when I click to go back:

![image](https://user-images.githubusercontent.com/36642354/40378152-1ac54d12-5dc9-11e8-96f8-2d2703cc35ca.png)

The Loading continues.

**Comment by Jorys-Paulin** [comment]
@AttChatuba Yes, there's definitely a problem with the JavaScript. Make sure you are running the latest version of chrome and moonlight

**Comment by AttChatuba** [comment]
@Jorys-Paulin I think something is messed up with my geforce experience, I tried connecting through the ios app and got the same problem, loading until I got a "Fetching App List Failed" error.

**Comment by AttChatuba** [comment]
Well, I feel dumb now...
My home ethernet network was set as a public network...
That's why I couldn't see my games. I have no idea why it was like that, but yeah.....

**Comment by Jorys-Paulin** [comment]
@AttChatuba Oh nice ! Well, you can close this issue if there's nothing left to solve :)
