### ISSUE TITLE
PC black screen - mobile phone working - Internet Streaming

### ISSUE THREAD

**Issue by fraxexplicit** [moonlight-stream/moonlight-chrome#468]
Hi all,

i have the following simple setup:
- PC with GFE -> connected via VPN (port forwarding is configured) for streaming over internet.
GFE Version: 3.1.2.31
Ports forwarded: 
UDP 7,9,48010,47999,47992,47998,47989,48000
TCP: 7,9,35043,47991,47995,47996,47989,47984,48010
Debug-Log:
`index.js, showApps] Current host object: NvHTTP {address: "[top_secret_hostname_here]", paired: true, currentGame: 0, serverMajorVersion: 7, appVersion: "7.1.340.0", …} server address: [top_secret_hostname_here]
server UID: 29f14235-441f-4e2c-8364-d02cf899f865
is paired: true
current game: 0
server major version: 7
appversion: 7.1.340.0
GFE version: 3.1.2.31
gpu type: GeForce GTX 970
number of apps: 32
supported display modes: 
	2160:3840: 60,30
	1080:1920: 60,30
	720:1280: 60,30

index.js:549 [index.js] Entrering "Show apps" mode
index.js:159 [index.js, backgroundPolling] Stopping background polling of host 29f14235-441f-4e2c-8364-d02cf899f865
 NvHTTP {address: "[top_secret_hostname_here]", paired: true, currentGame: 0, serverMajorVersion: 7, appVersion: "7.1.340.0", …} server address: [top_secret_hostname_here]
server UID: 29f14235-441f-4e2c-8364-d02cf599f865
is paired: true
current game: 0
server major version: 7
appversion: 7.1.340.0
GFE version: 3.1.2.31
gpu type: GeForce GTX 970
number of apps: 32
supported display modes: 
	2160:3840: 60,30
	1080:1920: 60,30
	720:1280: 60,30

messages.js:35 [messages.js, handleMessage] Message data:  https://[top_secret_hostname_here]:47984/applist?uniqueid=d576d165955202d6&uuid=7b12e0a7-a4dd-4ba4-8f55-6874a06d46e0
utils.js:361 [utils.js, getBoxArt] Returning storage-cached box art for app:  941778600
messages.js:35 [messages.js, handleMessage] Message data:  https://[top_secret_hostname_here]:47984/serverinfo?uniqueid=d576d165955202d6&uuid=32381e55-99c9-4147-95ad-4498e235c3af
utils.js:238 [utils.js, _parseServerInfo] Parsing server info: n.fn.init [root, prevObject: n.fn.init(1), context: document, selector: "root"]
utils.js:343 [utils.js, utils.js] Returning memory-cached apps list
index.js:616 [index.js, startGame] startRequest:[top_secret_hostname_here]:1280:720:30:10000:1
utils.js:54 [utils.js, getConnectedGamepadMask] Detected 0 gamepads
index.js:659 [index.js, playGameMode] Entering play game mode
messages.js:35 [messages.js, handleMessage] Message data:  https://[top_secret_hostname_here]:47984/launch?uniqueid=d576d165955202d6&uuid=79070cfc-911b-4d46-a0e6-19f306b95b2b&appid=110183152&mode=1280x720x30&additionalStates=1&sops=1&rikey=4cdf59a6996f20cca4fb819c2cd3d624&rikeyid=941778600&localAudioPlayMode=0&surroundAudioInfo=196610&remoteControllersBitmap=0&gcmap=0
messages.js:35 [messages.js, handleMessage] Message data:  Setting stream width to: 1280
messages.js:35 [messages.js, handleMessage] Message data:  Setting stream height to: 720
messages.js:35 [messages.js, handleMessage] Message data:  Setting stream fps to: 30
messages.js:35 [messages.js, handleMessage] Message data:  Setting stream host to: [top_secret_hostname_here]
messages.js:35 [messages.js, handleMessage] Message data:  Setting stream bitrate to: 10000
messages.js:35 [messages.js, handleMessage] Message data:  Setting rikey to: 4cdf59a6996f20cca4fb819c2cd3d624
messages.js:35 [messages.js, handleMessage] Message data:  Setting rikeyid to: 941778600
messages.js:35 [messages.js, handleMessage] Message data:  Setting appversion to: 7.1.340.0
messages.js:35 [messages.js, handleMessage] Message data:  Starting connection to [top_secret_hostname_here]
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting platform initialization...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting name resolution...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting RTSP handshake...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting control stream initialization...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting video stream initialization...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting audio stream initialization...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting input stream initialization...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting control stream establishment...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting video stream establishment...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting audio stream establishment...
messages.js:35 [messages.js, handleMessage] Message data:  ProgressMsg: Starting input stream establishment...
messages.js:35 [messages.js, handleMessage] Message data:  Connection Established`

- mobile phone and PC at my friends place. 

On both devices i can pair and connect with GFE. I have no problem to start a game with my mobile phone, i get sound and video, no lagging, etc. Everything is fine and working.
With the pc i can start the game, get sound, but no video. Moonlight just keeps black. There are no errors in the debug log, RTSP handshake is working, hardware acc is available, ports are double checked.
Actually the game starts on the other PC, but thats it.
Both devices are in the exact same network, i dont get it why the mobile device is working but the pc isnt. 

Thanks!

**Comment by Jorys-Paulin** [comment]
@fraxexplicit I think it is related to the NaCL module, which handles the video output. However, it can't be debugged as far as I know. This caused many problems not to be solved before. Just double-check you got all ports opened with both udp and tcp

**Comment by fraxexplicit** [comment]
Thanks, i already checked the ports. As far as i can see there are all needed ports open. I also tried to stream with my laptop a few minutes ago, same problem. The screen keeps black. Within a local network there are no problems. The Java Version has the same problem.

**Comment by Jorys-Paulin** [comment]
> Within a local network there are no problems

Definitely something with the ports. I can't see anything else that could cause this.

**Comment by fraxexplicit** [comment]
Okay, i checked the ports. 

I have the following ports forwarded: 
TCP: 7,9,35043,47991,47995,47996,47989,47984,48010 
UDP: 7,9,5353,48010,47999,47992,47998,47999,47989,48000,48002

I did the following on both pc and laptop:
- netsh advfirewall firewall add rule name="GameStream UDP" dir=in protocol=udp localport=5353,47998-48010 action=allow
- netsh advfirewall firewall add rule name="GameStream TCP" dir=in protocol=tcp localport=47984,47989,48010 action=allow

Again, my mobile phone is working without any problem. So, as far as i understand, there shouldnt be a problem with the ports. I have no other firewall software.

**Comment by Jorys-Paulin** [comment]
@fraxexplicit Well I don't know, maybe @cgutman has the technical answer...

**Comment by fraxexplicit** [comment]
@Jorys-Paulin thank you for your help.

I need to correct one thing, i dont have audio aswell on pc and laptop.

**Comment by Zibbibbo** [comment]
I had the black screen issue when I connected the monitor of the host pc via an AV-Amplifier instead of directly to the computer. 
If the AV-Ampli and the monitor are off I have the black screen issue, audio works correctly.
So, to solve my problem I just need to leave the AV-Ampli on.

Maybe you can try to leave the monitor on and see if something change.

**Comment by fraxexplicit** [comment]
Thanks Zibbibbo, but it was not the solution.

I tested a bit around with SoftEtherVPN. While "Steam InHome Streaming" over SoftEtherVPN works perfectly fine, i still have the black screen with moonlight. There are no port restrictions in SoftEtherVPN, so it could not be a problem. I still have no error in log files.

Maybe someone have an idea...thanks!

**Comment by cgutman** [comment]
Probably already fixed by the MTU changes in v0.9.4
