### ISSUE TITLE
Moonlight Terminates Connection on Starting Steam Game

### ISSUE THREAD

**Issue by nadaso8** [moonlight-stream/moonlight-chrome#470]
It's exactly what it sounds like, whenever I start steam then try to start a game The connection is dropped. Everything works fine up to that point and it works fine if I start a game from moonlight, but not from steam. It happens on my phone and laptop so this is definitely a problem with moonlight at large or the host end.
I'm going to work on a clean install as suggested in the trouble shooting guide

**Comment by nadaso8** [comment]
Update: Clean Install did not fix the problem

**Comment by Jorys-Paulin** [comment]
@nadaso8 And if you launch directly from Moonlight you have no problems? Sounds strange...

**Comment by nadaso8** [comment]
Yeah it was, I'd stress was because it's not doing thins now. I guess a few reboots and some downtime was all it needed.

**Comment by nadaso8** [comment]
Same problem is back, I was hoping that this would be a one time issue but that doesn't seem like it's going to happen.

**Comment by Jorys-Paulin** [comment]
@nadaso8 Try giving us the logs

**Comment by nadaso8** [comment]
How would I get them from the chrome version, it's not exactly like the embedded version where i just add on -verbose.

**Comment by nadaso8** [comment]
Ok so this is what it outputs to the console when I load steam try to run a game and steam is closed 

<img width="1244" alt="screen shot 2018-06-08 at 11 36 11 am" src="https://user-images.githubusercontent.com/30607379/41169980-417bd5bc-6b10-11e8-8b60-562d1f2b9805.png">

**Comment by Jorys-Paulin** [comment]
@nadaso8 Please upload the full log as text, that would help me much more, just blank any IPs if you're concerned.

**Comment by nadaso8** [comment]
![fullsizeoutput_88](https://user-images.githubusercontent.com/30607379/41170623-a64e2920-6b12-11e8-85d9-b289541e5204.jpeg)

**Comment by Jorys-Paulin** [comment]
@nadaso8 Well, it's yet another bug with the NaCL module, which we can't debug unfortunately (as far as I know)

**Comment by Jorys-Paulin** [comment]
@nadaso8 Doesn't a toast shows up when you get kicked from the streaming ?

**Comment by nadaso8** [comment]
Usually there is but when it happened that time id didn't fully kick me to the main menu and instead just sat a screen the color of the background in the main menu, so the discrepancy in the logs is probably because of that.

**Comment by Jorys-Paulin** [comment]
@nadaso8 And the toast don't show any error code? Btw, are you using the latest version of booth Chrome, Moonlight and Geforce Experience?

**Comment by nadaso8** [comment]
I'm on version 0.9 of moonlight Chrome with the most recent chrome browser, and I updated geforce experience to the newest version yesterday while I was troubleshooting. I think the version number was 3.14.0.139. As for the toast It normally shows this in the console after the stream is terminated 
<img width="1252" alt="screen shot 2018-06-09 at 10 53 55 am" src="https://user-images.githubusercontent.com/30607379/41193632-5e4790d6-6bd4-11e8-8151-d9c8ff72b966.png">

**Comment by Jorys-Paulin** [comment]
@nadaso8 Sorry, I meant a snack, something like a notification on the bottom centre:
![untitled](https://user-images.githubusercontent.com/5084309/41193671-d0bfd7b4-6c0f-11e8-9b47-18e129b295b7.png)

**Comment by nadaso8** [comment]
Oh, no there wasn't anything except for on iOS where it popped up an alert reading connection terminated.

**Comment by Jorys-Paulin** [comment]
@nadaso8 So it means your GFE is the problem. When streaming, is the monitor on?

**Comment by nadaso8** [comment]
The monitor is on most of the time and since I've had issues when it's off I usually leave it on now and it should be on right now, though I'll have to check in a day or two since I use moonlight remote most of the time because i'm out of town.

**Comment by Jorys-Paulin** [comment]
@nadaso8 Oh so I might also be a port forwarding issue... Check for all ports to be opened.

**Comment by nadaso8** [comment]
after installing the update to GFE which apparently downloaded but didn't install things are working again I'll reopen the issue if the problem appears again.
