### ISSUE TITLE
[Suggestion] Add an option for Native PC resolution

### ISSUE THREAD

**Issue by pilonull** [moonlight-stream/moonlight-chrome#472]
I've noticed that with Rocket League, for example, if I select 720P@60FPS, my framerate while streaming to my phone is wayyy lower than it is playing at my regular 1440p monitor resolution... When playing/not streaming i get 165+ FPS, but when I'm streaming to my phone I get around 120FPS. I noticed that if I connect to my desktop before launching the game, using the MSTSC.exe workaround, and then launch the game, my FPS will be 165+ again. Any clue what might be causing this? I have a 4790k with a 1080ti with 32gb RAM.

**Comment by Jorys-Paulin** [comment]
@pilonull 
- Try disabling the GeForce optimisations. It's chart icon on the host select page, see if it helps
- Maybe you're just caped at 60FPS, as you've asked with the resolution of 720p60

**Comment by pilonull** [comment]
@Jorys-Paulin

Oh I always disable the GeForce optimizations and run my own settings.. I was under the impression that the fps option in moonlight only affected the encoded video fps that is streamed to moonlight and should have no affect the games actual fps. Like I said, selecting the mstsc to stream the desktop and then launching a game causes it to run at maximum fps but launching the game directly from moonlight causes a dip in fps in-game, not on the moonlight stream but on the PC.

**Comment by Jorys-Paulin** [comment]
@pilonull Even if the game runs at 120fps, you'll only see 60fps. I think you can hack Moonlight to make it stream at 120fps, but I'm not sure if GFE would support it. Plus, you'll need a high refresh rate monitor to benefit from it

**Comment by pilonull** [comment]
I'm an idiot and didn't realize this is the chrome extension section.. I meant to post this in the Android app GitHub..
