### ISSUE TITLE
Control stream establishment failed (error -1) on IPv6

### ISSUE THREAD

**Issue by tsumeone** [moonlight-stream/moonlight-chrome#473]
Hello,

Someone already reported this (but in the documentation project) here: https://github.com/moonlight-stream/moonlight-docs/issues/115

I'm having the same problem as that person; "Control stream establishment failed (error -1)" on every attempt to launch a game while connected with the Chrome app using IPv6.  The game launches on the host machine, so there is at least some functional connection between the two computers.  Windows Firewall is turned off on the host machine so I don't think it's an issue with an inbound connection being blocked.  I tried rebooting after installing the IPv6 forwarder but that didn't help either.  I get 10/10 on the IPv6 test on both of the computers.  Both are on the same network.  The router is an Asus RT-AC68U and this happens whether I use the link local IP or the global IP to connect.  It works totally fine with IPv4 whether I use the LAN IP or Public IP - the problem is only happening when I try to use IPv6.

**Comment by Jorys-Paulin** [comment]
@tsumeone I strongly suggest you only use IPv4 for now, GFE wasn't meant to work with it, and the GFE Port forwarder isn't very stable from what I see.

**Comment by AngelsEnd** [comment]
So streaming over the internet with ipv6 isnt possible?

In my case i can't use ipv4 because i have dual stack and therefor a global ipv6 ip and a private ipv4 ip :/

**Comment by Jorys-Paulin** [comment]
> a global ipv6 ip and a private ipv4 ip

So, you still have an ipv4 or not? If so, you can still use it, at least you should.

**Comment by cgutman** [comment]
Yeah I looked into this a month ago. Unfortunately it looks like there's an issue with the NaCl sockets API in recent versions of Chrome that somehow breaks UDP IPv6 sockets. I don't see any such traffic leaving the host in Wireshark and I see NaCl errors saying the socket is not permitted to send packets IIRC.

**Comment by AngelsEnd** [comment]
Oh man i really hate ipv6 :D thanks dir the tipp with von. Hamachi should Work? Or anything Others vpn ist requests?
One Off topic question. Will there some das Moonlight Work 100% with ipv6?

**Comment by Maas1337** [comment]
Hey i have the same problem, as angelsend, My ISP had only a private ipv4.
Im stuckk on  "control stream establishment failed (error -1).
Will the be available without an vpn? 
Please support us :)

**Comment by cgutman** [comment]
As I said in my earlier comment, this appears to be a bug in Chrome, so it's not something we could fix ourselves

**Comment by Maas1337** [comment]
Thx for the Fast answer, maybe is there an earlier Version of Chrome where it works?

**Comment by Maas1337** [comment]
I got the same error from the moonlight android app. I dont think its  a problem with chrome.

Tested on iOS too -> same error

**Comment by soonshiny** [comment]
Just found this issue thread, I do have the exact same problem.
Is Google aware of the NaCl sockets API problem ?
I can't find a bug report so far.

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt, so it will be a "don't fix" on that one, sorry!
