### ISSUE TITLE
Can't launch unravel two

### ISSUE THREAD

**Issue by AlphaTheater** [moonlight-stream/moonlight-chrome#474]
Was excited to play unravel two with moonlight, but if you have somebody connected to you and they have a controller plugged in, the game doesn't even launch and just crashes instantly.

**Comment by Jorys-Paulin** [comment]
@AlphaTheater Is it already supported by GFE? If not, you won't have much luck for now. If at all, streaming is supported, but maybe not controls.

**Comment by Jorys-Paulin** [comment]
@AlphaTheater Is the bug still happening? If so, please re-open this issue, otherwise I hope you have a great experience!
