### ISSUE TITLE
Moonlight Chrome, Game freeze when using xbox 360 controller

### ISSUE THREAD

**Issue by bsteeve** [moonlight-stream/moonlight-chrome#475]
I'm streaming from my PC (win 10, latest update) onto a macbook pro 2012 i7 2.6ghz 16gb ram (high sierra 10.13.3) with moonlight chrome. 

I haven't streamed in a couple months but my xbox 360 controller (wired) use to work fine with this setup but now as soon as I touch any of the control on the controller when in game it freezes the game on my PC... it freezes on every single games I've got...  

I'm using the latest moonlight 0.9, latest GFE drivers. I've tried uninstalling my xbox 360 driver on my macbook but that didn't fix the issue. When the controller is not connected to my macbook pro, everything works perfectly... so the Xbox controller seems to be the issue where as soon as moonlight transmit controller data it crashes the game. The controller itself works perfectly when connected directly to my PC... I just don't get why all of a sudden I can't use my controller anymore. 

Is it possible that there could be an app on my PC that is causing a conflict? The are only a couple new program that have been installed since the last time i streamed game when it use to work. Those are sharemouse, which I have  I've disabled but that didn't fix the problem and some midi bridge application used to connect my mac and pc midi network together through wifi for syncing my DAW together... I haven't disabled it yet... but maybe that is the issue.  Any help would be greatly appreciated.

**Comment by bsteeve** [comment]
well I've installed "Parsec" and everything is working 100% including my controller.. so i'm gonna have to say goodbye to Moonlight for now. It was great whilst it was working.

**Comment by bsteeve** [comment]
Thanks for your reply. My xbox 360 controller (genuine) work perfectly using the html5gamepad.com on my macbook pro, work fine plugged straight into my PC using  GeForce Experience 3.14.0.139, works perfectly when using Parsec on my macbook pro streaming games from my PC.. It is just freezing the game when I stream through moonlight 0.9. I then have to quit chrome, relaunch moonlight and quit current app for my PC to able to close the game window. It use to work a few months ago but now with the lastest version of windows 10, chrome and moonlight 0.9 my xbox 360 controller is unsuable... I;ve tried to uninstall and re install Geforce experience with no success unfortunately...

**Comment by Jorys-Paulin** [comment]
@bsteeve So it's once again GFE that's causing launch errors. It can happen with every game sometimes. Maybe you should report this to them then...

**Comment by bsteeve** [comment]
right, maybe I should install an older version of GFE see if that works and confirm that this issue is directly related to the newer version of GFE. Thanks for you help. I appreciate it.

**Comment by bsteeve** [comment]
well I can't even install an older version... after logging in GFE forces me install the latest version... So i'll be reporting this to NVidia and in the mean time I'll be using Parsec... :(

**Comment by Jorys-Paulin** [comment]
If you need anything else, feel free to re-open an issue:
