### ISSUE TITLE
Moonlight gets stuck on the "Loading Moonlight plugin" screen on start up

### ISSUE THREAD

**Issue by Darthfett38** [moonlight-stream/moonlight-chrome#479]
Sorry I am very new to this so I have no idea how to find or post logs though if someone could tell me how to I would be happy to. Stupid me, I know. Anyway I am trying to use Moonlight to stream a game with my friend but I can't even get it to go past the loading screen. I've tried uninstalling and reinstalling Moonlight, Chrome, GFE and Nvidia Drivers. I also enabled Native Client. I don't know what to try anymore. Any help would be appreciated. Thanks!

**Comment by Jorys-Paulin** [comment]
@Darthfett38 See here for the logs: https://github.com/moonlight-stream/moonlight-chrome/wiki#reading-the-chrome-app-logs

**Comment by SnekSnak** [comment]
This is the issue I'm facing after the recent Chrome update which has screwed people from being able to run Moonlight correctly after being installed as an unpacked-app.

![image](https://user-images.githubusercontent.com/38109656/41549143-e72eee6a-72f2-11e8-9f86-3655d247d191.png)

**Comment by Jorys-Paulin** [comment]
@SnekSnak You're missing the NaCL module. You can get it from the official build or you can build your own (see readme)

**Comment by SnekSnak** [comment]
@Jorys-Paulin The problem is that non-developers are going to have trouble figuring this out. Up until the last Chrome build update, most users were installing Moonlight via the .crx extension. Now that it's impossible to install apps that way, this is adding another step that isn't clear in the installation instructions.

**Comment by Jorys-Paulin** [comment]
@SnekSnak Yes, the maintainers didn't add that mention, which is why I opened #478.

**Comment by SnekSnak** [comment]
@Jorys-Paulin It's depressing that Chrome is functionally hindering hundreds if not thousands of apps by forcing people to install apps via developer options now which is more time consuming and screws up the streamlining process for the average user. It's disgraceful to developers who have put countless hours into extensions that are seemingly going to become defunct within 1-2 years.

**Comment by Darthfett38** [comment]
Thanks for the comments guys. How exactly do I get a NaCL module? Also here are my logs if there are any other issues.
![capture0](https://user-images.githubusercontent.com/40343019/41561564-e30bfc52-730f-11e8-8a83-f3688e10ba64.png)

**Comment by Jorys-Paulin** [comment]
@Darthfett38 
- Download the `crx`
- Extract it as a folder
- Under `chrome://extensions`, activate developer mode
- Click "Load unpacked extension"
- Select the folder you extracted earlier
- Go to `chrome://apps` to launch the app or add shortcuts (right-click on Moonlight, "Add shorcuts")

**Comment by manpilogov** [comment]
@Jorys-Paulin 
Thank you! It's work!

**Comment by Jorys-Paulin** [comment]
@Darthfett38 Well, I've never seen this error. Can you give us your system details, that might help. I think your system isn't compatible with NaCL

**Comment by fred55co** [comment]
I have(Client PC): 
W8.1
i5-3330S
8GB RAM
Geforce 710A with Intel Graphics

**Comment by fred55co** [comment]
I got it working. The problem was, I had NaCl-related settings changed when I didn't know I should extract from the .crx. Reverting back the changes made it work. I have only these enabled:
![sem titulo2](https://user-images.githubusercontent.com/18707967/41617092-01d3fe70-73d6-11e8-95db-2e4ad30bbd82.png)

**Comment by Jorys-Paulin** [comment]
@fred55co Try searching for NaCL compatibility with your laptop, and make sure it is enabled. Looks like a missing compiler. Maybe your system architecture isn't compatible, Wich is strange

**Comment by Darthfett38** [comment]
@Jorys-Paulin 
Thanks for help but I did the steps you offered and they didn't help. They were actually the steps I took in the first place to install moonlight but I just retried them and got the same result. It says I'm missing the NaCL module. I enabled NaCL so what do I do? Thanks in advance.
![image](https://user-images.githubusercontent.com/40343019/41623746-57dca756-73d9-11e8-9837-895022a59f4a.png)

**Comment by Darthfett38** [comment]
I tried to make the module using the readme but I know very little about programing and have absolutely no idea what I am doing. Instructions for a dummy like me would be very appreciated. Thanks!

**Comment by Jorys-Paulin** [comment]
@Darthfett38 See here, I wrote a more detailed guide, might help you: https://github.com/Jorys-Paulin/moonlight-chrome/wiki/Building

**Comment by Darthfett38** [comment]
![screenshot 2](https://user-images.githubusercontent.com/40343019/41684295-add7d24c-74a2-11e8-9ef9-6f6d41bc5c0c.png)
![screenshot 1](https://user-images.githubusercontent.com/40343019/41684296-adf575f4-74a2-11e8-81a9-2e5e97da7baa.png)

Okay I got like half way through the guide but now I am stuck. When I try to put the "naclsdk list" command I get this... also here are my logs now too.

**Comment by Jorys-Paulin** [comment]
@Darthfett38 That's because Google doesn't want you to download the switch anymore. I'll try to give you the sdk when I get home.

**Comment by Jorys-Paulin** [comment]
@Darthfett38 Unfortunately I can't figure out why it won't download the package. And I can't give you the SDK either, it's too large and I don't think I'm allowed to do that. Sorry :/

**Comment by Darthfett38** [comment]
Well it's all okay because I got it to work with the crx file. Though I have a horrific sound stutter on the host PC that I can't seem to get rid of...

**Comment by Jorys-Paulin** [comment]
@Darthfett38 That I also never encountered... probably your pc being not compatible, which is strange...

**Comment by mike855** [comment]
Same problem here but not the same message : 

[updateStatus, common.js] ERROR [NaCl module load failed: The Portable Native Client (pnacl) component is not installed. Please consult chrome://components for more information.]

I have Nacl enabled

**Comment by mike855** [comment]
I'm on windows 7, Chrome version : 65.0.3325.181 (Build officiel) (32 bits)

**Comment by Jorys-Paulin** [comment]
@mike855 Nacl should work. Can you post the full log? (Blank public IPS)

**Comment by mike855** [comment]
This log or another? 

[updateStatus, common.js] Page loaded.
common.js:56 [browserSupportsNaCl, common.js] is NOT host toolchain for tool: pnacl
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:58 [browserSupportsNaCl, common.js] mimetypes: application/x-pnacl
common.js:331 [updateStatus, common.js] Browser supports NaCl (pnacl)
common.js:331 [updateStatus, common.js] Creating embed: pnacl
common.js:74 [createNaClModule, common.js] name: moonlight-chrome, tool: pnacl, path: pnacl/Release, width: 200, height: 200, attrs: {}
common.js:29 [mimeTypeForTool, common.js] tool: pnacl
common.js:38 [updateStatus, common.js] mimetype: application/x-pnacl
common.js:94 [createNaClModule, common.js] moduleEl: {}
index.js:835 [index.js] Moonlight's main window loaded
index.html:1 NativeClient: The Portable Native Client (pnacl) component is not installed. Please consult chrome://components for more information.
common.js:150 [handleError, common.js] ProgressEvent
common.js:331 [updateStatus, common.js] ERROR [NaCl module load failed: The Portable Native Client (pnacl) component is not installed. Please consult chrome://components for more information.]

**Comment by Jorys-Paulin** [comment]
Hav you tried installing NaCL inside `chrome://components`, as suggested by the logs?

**Comment by mike855** [comment]
pnacl - Version : 0.0.0.0
Nothing appens when I try to update. Maybe the proxy at my work...

**Comment by Jorys-Paulin** [comment]
@mike855 Definitely, version 0.0.0.0 ins't very correct...

**Comment by Jorys-Paulin** [comment]
@mike855 Please open a separate issue with all your logs and information please, that would help us a lot! @Darthfett38 If your issue still appears please open a separate issue
