### ISSUE TITLE
Guests Dualshock 4 controller not detected

### ISSUE THREAD

**Issue by stips12** [moonlight-stream/moonlight-chrome#484]
Me and a friend played a local co-op game together using this with both of us using a Dualshock 4 controller about a month or two ago, recently we wanted to play again and after starting moonlight and the game my friends controller does not work, only thing i remember changing is updating to a new version of geforce experience.

**Comment by stips12** [comment]
We tried HTML 5 Gamepad Tester both on his computer and trough moonlight on my pc, on his pc his controller apeared and trough moonlight it did not.

**Comment by Jorys-Paulin** [comment]
@stips12 Geforce Experience uses a XInput driver, which is meant for the Xbox controller, but the Dualshock 2 should work. Maybe try updating Moonlight, I think there was a fix for controller not that long ago. Make sure you are running the latest version (0.9.0)
