### ISSUE TITLE
Several Input Issues: Primarily My Mouse Keeps Getting Dragged to the Bottom of the Screen

### ISSUE THREAD

**Issue by redlinejoes** [moonlight-stream/moonlight-chrome#486]
Server OS: Windows 10 1803
Server GPU: NVIDIA 1080Ti 11GB
NVIDIA GPU Driver: 398.36
NVIDIA GFE Version: 3.14.1.48

Client Device Hardware: MS Windows Surface Pro 3
Client OS: WIndows 10 1803
Client GPU: Intel HD 4000
Client GPU Driver: 20.19.15.4568 (latest driver has graphical glitches and runs slow)
Client Moonlight Version: Moonlight Chrome v0.9.0

Issue: When using Moonlight Chrome, the mouse will get stuck being dragged diagonally to the bottom left of the screen inside the Moonlight session. If I quit Moonlight and connect to the server using Splashtop Streamer, the Moonlight input issue persists and the mouse cursor can be seen being forced to the lower left of the screen while the Splashtop virtual cursor works correctly and continues to try and reset the mouse cursor correctly. This causes anything I click on in Splashtop to get "force dragged" since the issues is persistent until a system reboot. 

To play a game with Moonlight, I use Moonlight to launch mstsc.exe and then I launch my game from within the RDP session.

**Comment by redlinejoes** [comment]
@Jorys-Paulin Unfortunately the QT version runs very poorly on my Surface Pro 3 compared to the Chrome version of Moonlight. The QT version is unusable at this time. I went back to the Chrome version and it runs way faster. With the QT version, the input and video lag was really bad.

**Comment by cgutman** [comment]
Interesting. This is the first we've heard of someone having worse performance on the Qt client than Chrome. It might be caused by https://github.com/moonlight-stream/moonlight-qt/issues/14

Does forcing H.264 in settings fix it?

**Comment by redlinejoes** [comment]
Forcing H.264 resolved the performance issue with QT and I have cleaned up this issue and created a separate issue for my Android Moonlight input problems.

**Comment by Jorys-Paulin** [comment]
If you need anything else, feel free to open another issue :)
