### ISSUE TITLE
Lag on older laptops in fullscreen

### ISSUE THREAD

**Issue by 19clarnoah** [moonlight-stream/moonlight-chrome#488]
I have native client enabled, and the laptops i have tried have hardware acceleration enabled.
Both have Intel integrated graphics
Both have a screen resolution of 1366x768
Both will stream 1080p60fps @20mbps just fine if in windowed mode
However, when in fullscreen, input has huge latency at 1080p60fps, and video is very jittery.
720p60fps works no problem in fullscreen.
Obviously, h.264 video is not hard to decode, even the crappiest laptops can display it with minimal issues. 
Is this perhaps on the compatibility end? Maybe the fullscreen optimisations or scaling for Chrome doesn't like it, since full screen is 1366x768 and not 1080p?
What can I do? 720p is awful, even downscaled 1080 looks astronomically better

**Comment by Jorys-Paulin** [comment]
@19clarnoah You could try the new native version: https://github.com/moonlight-stream/moonlight-qt/releases. It's still in early alpha tough

**Comment by 19clarnoah** [comment]
@Jorys-Paulin i had no idea that was so far in development already, thank you! And damn you replied fast, that's what I call good support :D

**Comment by Jorys-Paulin** [comment]
@19clarnoah You're welcome. If you get another issue, feel free to open another issue!
