### ISSUE TITLE
Impossible to stream when I use VPN on PC

### ISSUE THREAD

**Issue by whiteorino** [moonlight-stream/moonlight-chrome#490]
Hello, 

**My moonlight stream work properly in normal time.**
But recently I wanted to use VPN on my PC, and when I use VPN on my PC, I can't connect moonlight on the raspberry.

_pi@raspberrypi:~ $ moonlight stream -1080
Searching for server..._

And nothing more than this, I have to CTRL+C to stop.

I think there is a routing issue but I don't know which one.

Can you help me guys ?

**Comment by Jorys-Paulin** [comment]
@whiteorino This better be placed inside moonlight-embeded issues, but try to see if all the required ports are usable. Please not I'm not familiar with the use of vpns and in my experience doesn't work for most users.

**Comment by whiteorino** [comment]
@Jorys-Paulin Thank you, I thank it was the same thing here, but it appear to be not ;)

You can close this post
