### ISSUE TITLE
Controllers not working

### ISSUE THREAD

**Issue by lodesmets** [moonlight-stream/moonlight-chrome#491]
Hello,
Noticed that suddenly my controllers do not work anymore over moonlight stream. It worked in the past.

I have moonlight version 9.0.0 and GFE 3.14.1.48 (the latest version right now).
For my controllers (ds3 and ds4) I usually use scpToolkit, but I tested it with ds4windows also.
The controller input works on my laptop, but my main pc doesn't recognize my controllers.
On both pc I have windows 10 and the latest version of chrome.

Any Ideas?
Thanks in advance,
Lode

**Comment by Jorys-Paulin** [comment]
@lodesmets Can you please try the new version of moonlight? That would help us see if that's chrome related: https://github.com/moonlight-stream/moonlight-qt/releases

**Comment by lodesmets** [comment]
Thank you for the very quick response.
It works with the new version, But it wasn't the problem of chrome. 
Apparently GFE updated (I did not notice) and I had to reboot my pc 3-4 times (I tried switching my pc off and on, but 1 time was not enough)
