### ISSUE TITLE
Moonlight Freezing when using Xbox 360 controller.

### ISSUE THREAD

**Issue by DelegateZero** [moonlight-stream/moonlight-chrome#492]
I'm on a Google Pixelbook, streaming works very well until I pick up my xbox 360 controller and press any button, everything freeze any time I press any button.

**Comment by airdjing** [comment]
Exactly same problem appears to me.

**Comment by LonKeelay** [comment]
The same problem happens to me, with both my Dualshock 4 and my Logitech f310. I'm using a ThinkPad X131e.

**Comment by cgutman** [comment]
@LonKeelay If your're not using a Chromebook, you should use the native PC client instead. The Chrome client is no longer supported for streaming on non-ChromeOS machines.

https://github.com/moonlight-stream/moonlight-qt/releases

**Comment by LonKeelay** [comment]
@cgutman There are 2 versions of the X131e. I'm using the version that is a Chromebook. I tried running the Linux version using Crouton, but that ended up being a glitchy mess.

**Comment by cgutman** [comment]
The bug is fixed in Chrome 72 in Canary now

**Comment by cgutman** [comment]
Chrome 72 is in stable since early this month. Fixed.
