### ISSUE TITLE
Audio crackling in native Mac Client

### ISSUE THREAD

**Issue by mtwomey** [moonlight-stream/moonlight-chrome#493]
I recently switched from the Chrome extension to the Mac native Moonlight client. I experience audio crackling with the native client. I have confirmed that I have all the settings the same between the two, however - when I switch back to the extension version, the crackling disappears. It only appears to happen with the native client.

**Comment by cgutman** [comment]
I experienced that issue too. That was one of the reasons I changed our audio renderer from SDL to PortAudio. However, this change hasn't made it into a new release yet. I expect to release again in the next few days.

As a side note, for bugs in the native PC client, please file them on that project: https://github.com/moonlight-stream/moonlight-qt/issues

I'm going to close this issue as fixed for now. If it still occurs after the next PC release, please open a ticket on the native PC client.

**Comment by mtwomey** [comment]
@cgutman Yep - sorry about opening this in the wrong repo. Will check out the new release once it's out. Thank you.
