### ISSUE TITLE
Black flickering on Pixelbook (Dev 74)

### ISSUE THREAD

**Issue by smiller171** [moonlight-stream/moonlight-chrome#494]
# Read before posting an issue
If you have an issue, please consider the following before:

- Have you tried __updating__:
  - Your operating system: Yes
  - Geforce Experience (mention if in beta): Yes
  - Chrome to the latest version: Yes
  - The Moonlight client: Yes
- Have you tried __pinging__ your host from the client?: Yes
- If streaming __over the internet__:
  - Have you followed the [guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide)?
  - Have you opened all ports to they correct protocols (udp or tcp)
- Have you enabled __hardware acceleration__?
  - Check under `chrome://settings/system` to enable it: yes
  - Check under `chrome://flags/#disable-accelerated-video-decode` for video hardware acceleration: yes
  - Check under `chrome://gpu` for:
    - Video Decode: "Hardware accelerated": yes
    - WebGL: "Hardware accelerated": yes
    - WebGL2: "Hardware accelerated": yes
- Have you __enabled NaCL__?
  - Check under `chrome://flags/#enable-nacl` to enable it (Not available)
  - Are you running Linux? if so, install Chrome from official ppa: No

If you still have problems, post them in the issues section with info, logs and screenshots if possible

On my Google Pixelbook (i5) Moonlight has really bad flickering in Chrome (black frames) This persists in any setting above 720P/30. However using the Moonlight Android app from the same PixelBook works flawlessly (except I can't use a mouse)

**Comment by cgutman** [comment]
I wonder if it's something broken in ChromeOS Dev.

If you manually disable hardware accelerated video decoding with `chrome://flags/#disable-accelerated-video-decode`, does the issue go away?

**Comment by smiller171** [comment]
I'll give it a try. Something related to hardware acceleration makes sense since they are trying to fix it for Linux apps.

**Comment by smiller171** [comment]
Disabling hardware acceleration results in no improvement, and may be slightly worse.
