### ISSUE TITLE
Experiencing Mouse Glitch

### ISSUE THREAD

**Issue by MicroClue** [moonlight-stream/moonlight-chrome#495]
Hi, I was running the latest ChromeOS version (74.0.3729.68) and I seem to be experiencing mouse glitches similar to as described here: https://github.com/moonlight-stream/moonlight-chrome/issues/353 - I don't think the previous beta 74.0.3729.38 experienced this issue, but I can't currently confirm since I'm not aware of a way to move between specific versions.

I can confirm that by moving back to stable (73.0.3683.88) this mouse jerking disappears. I didn't change anything else on either the chromebook side or the desktop side (all the same exact software versions as before).

It seems like this bug was originally fixed (according to https://bugs.chromium.org/p/chromium/issues/detail?id=781182) but I believe it regressed. Is anyone else experiencing this?

Thank you!

**Comment by cgutman** [comment]
Are you able to reproduce the issue using the same steps as listed on the https://bugs.chromium.org/p/chromium/issues/detail?id=781182 bug?

**Comment by MicroClue** [comment]
Sorry for the late reply - I haven't tried to follow the exact steps as my chromebook isn't currently running the OS version with the issue. Once I have some more time, I'll try those steps. Thanks!

**Comment by jamest212** [comment]
I'm experiencing this as well, all of a sudden, on 74.0.3729.68.

I tried the website mentioned in the OP of the referenced bug, and I did see the issue when pointer lock was engaged. I'd be moving the mouse slowly so as to get low double-digit numbers at most then I'd suddenly get a 400+, sometimes paired with the opposite signed number right after (so a -432 followed by a +432, for example).

When I try to use Moonlight, it occurs much more frequently than it did in the mouse tracking website, for whatever reason. It's totally unusable. Mouse just goes insane constantly as its being moved.

Guess I will also roll back to the stable channel. Seems like a ChromeOS problem for sure. This was working fine for me as recently as last Friday.

**Comment by jamest212** [comment]
To follow up - I rolled back to the 73.x stable version, and it works perfectly again.

Something is broken on that beta build which only broke very recently. I've been on the beta channel for months, and using the Moonlight Chrome version consistently for the past few weeks.

**Comment by jamest212** [comment]
One other potentially useful piece of info:

1) I can no longer reproduce the random large jump on that mouse recording website from the bug report OP, neither while streaming or in the native Chrome browser outside of streaming. Previously, I was able to reproduce the issue even when I wasn't streaming, in the native Chrome browser.

2) Now that website only records events when I actually move the mouse, but while I was on the beta channel, it was recording events ALL the time, even when I wasn't moving (so there were massive numbers of 0 movement events being recorded). I initially assumed it was just supposed to work that way. What I'm not sure is whether that happened all the time, or only when I engaged the lock. I think it was only when I engaged the lock.

**Comment by cyphercolt** [comment]
> Are you able to reproduce the issue using the same steps as listed on the https://bugs.chromium.org/p/chromium/issues/detail?id=781182 bug?

Info:
Samsung Chromebook Plus V1
Version 74.0.3729.111 (Official Build) beta (32-bit)

Using the mouse pointer lock page in the steps provided, I enable lock and drag my mouse around slowly. I am seeing the jumps in numbers (positive and negative 400+ - even 200s when the average was about 50-60)

Same issue in Moonlight when using the Chromebook's mouse and keyboard, and a usb mouse and keyboard.

Not sure if related but trying to workaround the issue by mapping the right stick to mouse movement on Steam with my PS4 Controller also failed.

**Comment by cyphercolt** [comment]
> > Are you able to reproduce the issue using the same steps as listed on the https://bugs.chromium.org/p/chromium/issues/detail?id=781182 bug?
> 
> Info:
> Samsung Chromebook Plus V1
> Version 74.0.3729.111 (Official Build) beta (32-bit)
> 
> Using the mouse pointer lock page in the steps provided, I enable lock and drag my mouse around slowly. I am seeing the jumps in numbers (positive and negative 400+ - even 200s when the average was about 50-60)
> 
> Same issue in Moonlight when using the Chromebook's mouse and keyboard, and a usb mouse and keyboard. (Mouse is awkward - boxed out when moving too far up or down, goes back to center when moving up out of the screen and down out of the screen.)
> 
> Not sure if related but trying to workaround the issue by mapping the right stick to mouse movement on Steam with my PS4 Controller also failed.

Issue is no longer occurring on my Chromebook Plus V1 since the last update recently: Version 74.0.3729.125 (Official Build) beta (32-bit)

**Comment by MicroClue** [comment]
Yep, can confirm that it works now!
