### ISSUE TITLE
Mouse offset issues (still an ongoing issue)

### ISSUE THREAD

**Issue by craigread77** [moonlight-stream/moonlight-chrome#498]
This has previously been brought up and closed because "better mouse support will come with Chrome OS update x" We've now had 4 or 5 versions of Chrome OS and this is still an issue for quite a few people.

**Issue**: When connecting from a Chromebook using the moonlight playstore app, the cursor on the host and connecting client are not synced, and reaching the "edge" of the moonlight window puts the cursors even more out of sync. The client and host are both using the same resolution of 1080p

**Comment by cgutman** [comment]
This bug tracker is for the [Chrome Web Store version of Moonlight for ChromeOS](https://chrome.google.com/webstore/detail/moonlight-game-streaming/gemamigbbenahjlfnmlfdjhdnkpbkfjj), not the Android version. I would suggest you try the Chrome Web Store version which should have working pointer capture on ChromeOS.

There's nothing we can do about broken Android platform features on ChromeOS. I would suggest you file a bug on ChromiumOS's issue tracker if you want them to address the broken pointer capture support for Android apps.

**Comment by craigread77** [comment]
Wow now I feel stupid I had no idea those were not the same thing!

I thought that chrome OS apps were installed through the play store.

Thank you so much
On Sep 14, 2019, at 12:37 PM, Cameron Gutman <notifications@github.com<mailto:notifications@github.com>> wrote:

This bug tracker is for the Chrome Web Store version of Moonlight for ChromeOS<https://chrome.google.com/webstore/detail/moonlight-game-streaming/gemamigbbenahjlfnmlfdjhdnkpbkfjj>, not the Android version. I would suggest you try the Chrome Web Store version which should have working pointer capture on ChromeOS.

There's nothing we can do about broken Android platform features on ChromeOS. I would suggest you file a bug on ChromiumOS's issue tracker if you want them to address the broken pointer capture support for Android apps.
