### ISSUE TITLE
Multiple PCs streaming to one Moonlight Client

### ISSUE THREAD

**Issue by SlateDave** [moonlight-stream/moonlight-chrome#499]
Hey!

We've wanted to host a lan-party with at least 10 pepole. We have a strong wifi and setup a projector in the middle. Now the plan is to have all the views of the different gamers on one big screen as overview. Cloud this be possible with the Nvidia Gamestream feature (If everyone had a Nvidia GPU) and cloud therefor be realised with Moonlight?

**Comment by Jorys-Paulin** [comment]
@SlateDave No, GameStream only supports one session at a time. You can only have one client connected to a host at a time
