### ISSUE TITLE
Stale image displayed in plugin when resuming a stream

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#50]
The last frame of the previous session is shown in the plugin when the next stream is started. This should not be the case.

**Comment by cgutman** [comment]
This isn't totally fixed it seems.

**Comment by raidancampbell** [comment]
Is there any reason to display the NaCl plugin before the stream is fully negotiated?  Some CSS trickery could keep the black screen with loading status, then make it "appear" once the stream is fully opened.

**Comment by cgutman** [comment]
No, but that doesn't solve the issue really. Even when we get the connection established callback, it doesn't mean we've necessarily received, decoded, and drawn a new video frame to replace the stale one. We could _maybe_ get away with sending a message telling the JS to show the NaCl plugin, though I'm not sure whether we might have other issues doing that. Generally, blocking in that SubmitDecodeUnit callback is something to avoid.

**Comment by cgutman** [comment]
Fixed by 6c13c9b67d886deff260a3a0c4fc90f97b8cb858
