### ISSUE TITLE
Black screen on ChromeOS 83

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#503]
In the ChromeOS 83 update, Google broke the video decoder that Moonlight relies on to display the video stream. You will just get a black screen when you try to stream.

Please star the Chrome bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1088263

There is no workaround, but the Android app still works.

**Comment by Vegz78** [comment]
I am not sure if this is related directly to the underlying bug that is identified here in this issue, but the symptom with a black screen when trying to stream is the same.

Patrick Baker recently reports on the Chrome web market about a successful workaround, which I can confirm also works most of the time on my two kids' school Chromebooks, most likely updated to recent ChromOS versions, don't know which:

When the black screen appears, just press the minimize button twice(minimize Moonlight window and then maximize), and the game stream video shows.
![Screenshot](https://user-images.githubusercontent.com/49032025/141277048-565bbce7-4a94-4dfc-8f11-e4b8cbbe1428.png)

We normally don't start Steam or any games directly upon launch of Moonlight from the Chromebooks, we mostly just [stream the remote desktop](https://github.com/moonlight-stream/moonlight-android/issues/307) and continue from there.

Might this also be a hint for an opportunity to fix this somehow from the Moonlight's side of the issue?
