### ISSUE TITLE
Feature Request : Port to Samsung Smart TV

### ISSUE THREAD

**Issue by jacky400** [moonlight-stream/moonlight-chrome#505]
Wonder if any moonlight port to Samsung Smart TV ?

**Comment by Jorys-Paulin** [comment]
Hello @jacky400, a port is in the works by a member of the community, but it'll be the most recent QT version: https://github.com/moonlight-stream/moonlight-qt

**Comment by Jorys-Paulin** [comment]
Hello again, if you want there's already a post on our feedback site you can upvote : https://ideas.moonlight-stream.org/posts/38/samsung-tv-app
