### ISSUE TITLE
Run moonlight in a web page with the webrtc technology possible ?

### ISSUE THREAD

**Issue by liujiayu2** [moonlight-stream/moonlight-chrome#510]
Is that possible make the moonlight all function in a webpage with the webrtc technology, but not use chrome plugin, so that the moonlight can run in all web browsers ?

**Comment by cr4ckerj4ck** [comment]
first of all through god all things are possible so jot that down...
secondly, this seems like a bad idea from a security standpoint

**Comment by liujiayu2** [comment]
> first of all through god all things are possible so jot that down...
> secondly, this seems like a bad idea from a security standpoint

First of all, thank you for your answer. I tried to grab the data communication packet through Wireshark, which looks like audio and video transmitted by RTSP. However, I found that it is far from the standard RTSP protocol. Is there any relevant agreement description document? My wish is to run moonlight on the browser (not the Google Chrome extension). Is there any proposal? Thank you.

**Comment by cr4ckerj4ck** [comment]
What OS? Either Linux or ChromeOS should work but it just depends. After all, it was apple who ripped off samsung on their phones so I wouldn't put it past them to botch something in MacOS to be honest... ChromeOS is technically just a browser version of watered down linux. This is really getting into the weeds here 🙄

**Comment by liujiayu2** [comment]
My OS is Linux,in my opinion, once the moonlight can run in a browser, it seems to be cross platform 🙄

**Comment by cgutman** [comment]
This is covered in the Moonlight FAQ: https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#is-there-a-moonlight-web-client

**Comment by liujiayu2** [comment]
> This is covered in the Moonlight FAQ: https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#is-there-a-moonlight-web-client

Yes, i saw that, and read it again and again. It said that there is not a pure web-based Moonlight client because of Network protocol. My boss want me development a pure web-based Moonlight client with the webrtc-streamer technology. like the project [](https://github.com/mpromonet/webrtc-streamer) .  It seems possible to be done, but i dont sure of this,  Can you give some proposal. lots of thanks!!!

**Comment by liujiayu2** [comment]
> This is covered in the Moonlight FAQ: https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#is-there-a-moonlight-web-client

Yes, i saw that, and read it again and again. It said that there is not a pure web-based Moonlight client because of Network protocol. My boss want me development a pure web-based Moonlight client with the webrtc-streamer technology. like the project(https://github.com/mpromonet/webrtc-streamer) . It seems possible to be done, but i dont sure of this, Can you give some proposal. lots of thanks!!!

**Comment by meponderR** [comment]
Would it be possible to do this using a forwarder run on the host computer.
