### ISSUE TITLE
Unable to quit on tablet mode

### ISSUE THREAD

**Issue by CuriousLocky** [moonlight-stream/moonlight-chrome#519]
On Chrome OS tablet mode, after launching the app and selecting a host PC, there is no way to quit the app other than rebooting. 
Swiping up from the bottom edge does not bring the taskbar, swiping right from left edge triggers return gesture animation but does not close or minimize the app.

**Comment by utopiafallen** [comment]
Can confirm. I had to use the keyboard Esc button to get the app out of fullscreen mode.

**Comment by cgutman** [comment]
Fixed in v0.10.22.
