### ISSUE TITLE
Starts up with complete black screen

### ISSUE THREAD

**Issue by william137m** [moonlight-stream/moonlight-chrome#523]
The moonlight in the web store starts up with a complete black screen, Pressing esc or back doesn't get rid of it. Switching to my desktop or a different game doesn't help, and moonlight runs great for me on my IPhone. I know there is one on the play store but i'd like to use this version so any fixes would be greatly appreciated. Also the sound does play on my chromebook and my resolution on my computer changes so it does seem to be connecting

**Comment by cgutman** [comment]
Should be fixed in the v0.10.22 release. Please reopen if that new build didn't solve it.
