### ISSUE TITLE
Previous issue #523, Black screen on chromebook.

### ISSUE THREAD

**Issue by william137m** [moonlight-stream/moonlight-chrome#526]
I'm not fully sure how to reopen an issue so I'm submitting this new one, But I previously posted an issue with a black screen on my chromebook and he said it should be fixed now. I appreciate the help A LOT, But I'm sadly still having this issue. Now tho my mouse does seem to be working compared to before where it also was not getting any mouse input, But I'm still stuck with a black screen. I did try the fixes that were proposed such as turning on hardware acceleration and the other thing in chrome flags but this did not help, Any more help would be greatly appreciated.

**Comment by utopiafallen** [comment]
Has Moonlight ever worked on your Chromebook?

Also, is Moonlight running windowed or fullscreen?

**Comment by william137m** [comment]
Moonlight has never worked on my chromebook before, I've only ever gotten it close to working once. Where I could suddenly see my computer screen for a few seconds and then it went away, Moonlight opens up in fullscreen mode.

**Comment by utopiafallen** [comment]
The latest version should no longer open in fullscreen mode automatically. What happens if you toggle between windowed and fullscreen while at the black screen (your Chromebook has a keyboard button for fullscreen, where F4 would be on a standard keyboard)?

Just to sanity check, do any other Moonlight clients work?

**Comment by william137m** [comment]
That's the weird part, When I press the fullscreen buttom i'm actually locked in fullscreen mode on moonlight. From what I can tell it doesn't switch to windowed it only shows with the little bar on the top, and yes moonlight works great on all of my other devices.

**Comment by utopiafallen** [comment]
How familiar are you with inspecting extensions in Chrome with Developer Mode enabled on your Chromebook? I think you need to be able to pull up the console log for Moonlight to have a better clue as to what's going on. As a bonus, you'll also be able to use the Chrome inspector to look at what the source of the black screen is, if you're familiar at all with web debugging tools.

Also, what Chromebook do you have? Maybe it's too old to have H.264 HW decode support?

**Comment by SoarinFerret** [comment]
@utopiafallen I am having the same issue on an older Lenovo 100E with a Intel Celeron N3350 (which supports Intel QuickSync, so should do both h264 and h265 decoding no problem).

When I connect, its a purely black screen, but I am getting audio

**Comment by jannyg** [comment]
I have the same issue. Black screen, but getting audio sometimes. Does not help to go in and out of full screen.

Chrome OS 108.0.5359.172
Acer CB315-3H-C6XA

See attached debug log from the extension. [gemamigbbenahjlfnmlfdjhdnkpbkfjj-1673867245154.log](https://github.com/moonlight-stream/moonlight-chrome/files/10425201/gemamigbbenahjlfnmlfdjhdnkpbkfjj-1673867245154.log)

**Comment by william137m** [comment]
> How familiar are you with inspecting extensions in Chrome with Developer Mode enabled on your Chromebook? I think you need to be able to pull up the console log for Moonlight to have a better clue as to what's going on. As a bonus, you'll also be able to use the Chrome inspector to look at what the source of the black screen is, if you're familiar at all with web debugging tools.
> 
> Also, what Chromebook do you have? Maybe it's too old to have H.264 HW decode support?

I have a chromebook c722-k4cn, I'm honestly completely unsure on how to pull up the console log or any of that.  I could if you told me the steps, Something to note is that the android version works perfect for me and I would preferably use that. But of course the mouse does not work on me for there and just spins around really quickly, Mouse fix in your discord does not work even at lowest speed.

**Comment by william137m** [comment]
Closing it was a mistake my bad

**Comment by william137m** [comment]
Closing it was a mistake my bad.

**Comment by william137m** [comment]
My bad I did not mean to close it

**Comment by jannyg** [comment]
> My bad I did not mean to close it

Re-open it again then?
