### ISSUE TITLE
Perform routine polling of available PCs in the background

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#53]
We should be polling machines the in background for reachability over the available IP addresses. We should pull new serverinfo roughly every 5 seconds. We should pull a new applist every 30 seconds (when we're viewing the grid of apps).

**Comment by raidancampbell** [comment]
doing server queries on a hard schedule is a bad idea: if I'm trying to start an app, and suddenly a serverinfo query gets thrown at the server, it all breaks down.  I've solved this by not doing the 5-second serverinfo query when you're currently looking at the app list.

However, the 30-second applist query still presents the same problem: if the user is performing some action, and an applist query is fired, the user's action is interrupted and has an undefined result.

How do other clients handle this?
