### ISSUE TITLE
Fix remote input key generation

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#54]
We're using RI keys of all zeros. We should fix this before shipping.

**Comment by raidancampbell** [comment]
How unique does this need to be? per client, per session, etc...

Additionally, are you looking for hex or numerical values in this key?

**Comment by cgutman** [comment]
It should never be reused or persisted in any way. It should be generated any time we hit the code where it is created today.

The rikey value is a 128-bit hexadecimal string in the URL and an unsigned char[16] in NaCl. The rikeyid is a 32-bit decimal string and an 32-bit int coerced into an unsigned char[16] in NaCl.
