### ISSUE TITLE
NaCl help

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-chrome#57]
I'm have this problem when I launch moonlight I get this error "NaCl module load failed : could not load manifest url."  any ideas how to fix this? 

I'm trying to change the resolutions to custom one non of my devices are stander resolutions.

**Comment by cgutman** [comment]
Make sure you've followed the building steps: https://github.com/moonlight-stream/moonlight-chrome#building

**Comment by muffinmannameistaken** [comment]
ok will i was able to rebuild moonlight all i did was download a working copy and used Winrar to unpack then use chrome to repack it, works great!
