### ISSUE TITLE
Unable to stream

### ISSUE THREAD

**Issue by andrew-anguiano** [moonlight-stream/moonlight-chrome#58]
I've been unable to stream while on my LAN. I recently set up my router and no-ip.com so I could stream over the internet. When streaming over the internet, everything works fine. However, when I try to stream from my home network using the server's IP, the app launches on the server but the client crashes with the error `Starting RTSP handshakefailed`.

Does anyone have any ideas? All my firewalls are disabled and obviously I'm able to stream over the internet.

**Comment by cgutman** [comment]
Interesting, can you get a Wireshark packet capture from your client PC running Moonlight Chrome?

Install Wireshark, start a capture on your network adapter, try to stream over LAN to get the error, stop the capture, then save and upload the file here.

**Comment by andrew-anguiano** [comment]
Sure thing. I have it attached. I don't know a whole lot about what I'm looking for so sorry I can't be of much more help.


[Wireshark Capture](https://github.com/moonlight-stream/moonlight-chrome/files/265390/capture.pcapng.zip)

**Comment by cgutman** [comment]
Thanks, looks like the RTSP handshake messages are being sent correctly by Moonlight Chrome but they aren't making it to the streaming server on the PC somehow.

Do you have any anti-virus or firewall installed on your GeForce PC? Were you ever able to stream over LAN?

**Comment by andrew-anguiano** [comment]
@cgutman I didn't used to have any problem streaming over LAN. I also don't have any issues streaming with Steam. Just Moonlight (both Chrome and the Java version).

I had AVG installed, but I removed it to see if it made a difference. Windows Firewall is also disabled.

**Comment by cgutman** [comment]
Can you remember what may have changed in your setup since you were able to stream?

Can you upload a ZIP of the 'C:\ProgramData\NVIDIA Corporation\NvStream' folder? ProgramData is a hidden folder so you may need to enable those to see it.

**Comment by andrew-anguiano** [comment]
Nothing's changed that I'm aware of. I updated GeForce Experience and my GPU drivers but that's about it. Attached is my NvStream folder. Hope it helps!

[NvStream.zip](https://github.com/moonlight-stream/moonlight-chrome/files/271653/NvStream.zip)

**Comment by andrew-anguiano** [comment]
So now I'm seeing similar behavior over LAN. However, it's not throwing the RTSP handshake failed error. Instead, the JS console shows the following:

```
ProgressMsg: Starting video stream establishment...
ProgressMsg: Starting audio stream establishment...
ProgressMsg: Starting input stream establishment...
Connection Established
streamTerminated
```

The game is still launching fine.

Not sure why I'm getting this all of a sudden. I literally haven't played games for the last couple days and got this issue when I went to stream today.

**Comment by cgutman** [comment]
Can you upload a ZIP of that folder again now that you've got different errors?

**Comment by andrew-anguiano** [comment]
Here's the most recent nvStream folder. I accidentally said before that I was now unable to stream over LAN. I meant to say that I can't stream over the internet via my no-ip hostname anymore either (which was the only way I used to be able to stream). Starting to wonder if it may be easier just to wipe my PC (it's probably due for it anyway).

[NvStream - New.zip](https://github.com/moonlight-stream/moonlight-chrome/files/273812/NvStream.-.New.zip)

**Comment by andrew-anguiano** [comment]
So, I ended up wiping my gaming PC and reinstalling Windows on it (it needed to be done a while ago). Now everything works perfectly. I don't know what got all messed up before. Thanks for your help @cgutman.
