### ISSUE TITLE
Mouse 4+5 (and presumably more) don't work

### ISSUE THREAD

**Issue by bmm85** [moonlight-stream/moonlight-chrome#63]
The side buttons on my mouse (mouse 4 and mouse 5) don't appear to work.

**Comment by raidancampbell** [comment]
It doesn't look like the NaCl API provides access to any more than the [default three buttons](https://developer.chrome.com/native-client/pepper_dev/c/group___enums#ga25113f3c8d33e863fd38b3f70f8a5e6e)
