### ISSUE TITLE
Custom or more resolutions to pick from

### ISSUE THREAD

**Issue by drasbeck** [moonlight-stream/moonlight-chrome#64]
Would it be possible to add more resolutions to pick from, or the ability to add custom resolution? Or is it technically limited to the three choices we have now?

I for example have two monitors that doesn't fit the scheme, a 1440p and a 1920x1200.
Technically I could just downscale 4K on the 1440p, but it would impact performance on many games on my current rig.

**Comment by raidancampbell** [comment]
see #44 for why this hasn't happened

**Comment by drasbeck** [comment]
Hi team, @raidancampbell, I've read through the [thread](https://github.com/moonlight-stream/moonlight-chrome/pull/44), and although I wholeheartedly appreciate your efforts to keep the app sleek and user friendly (which I think is paramount in great design). Users who otherwise end up not using the app because of this reason, should at least have a way to make it work?

As I understand GFE will actually allow custom resolutions which the connected monitor supports. So my suggestion is something along the lines of an unremarkable "advanced settings" option, which could let people experiment with resolutions, to make their system work. Could also be some kind of launch options implementation, if Google Apps support this. Just suggesting off the cuff here. =)

**Comment by tbergeron** [comment]
I'd love this issue to be reconsidered. There's more and more 16:10 monitors on the market and I'm stuck in the same case as OP. It is possible and asked for, "keeping it simple" isn't a valid answer here.

**Comment by JustAnotherPU** [comment]
I am very interested in this too could your please consider to update moonlight to support custom resolution and aspect ratio ?

**Comment by buzzcut2k15** [comment]
Just chiming in here, I'm also very very interested in such functionality. Note - I tried to look for 'index.html' in the moonlight application on my mac, but couldn't find it. I have no idea about how I may make the change. It would be great if there were anyone who could point me to a link or detail the steps! Thanks

**Comment by kilka** [comment]
I am currently running a custom resolution on a Samsung Chromebook Plus and it works quite well. If you want to quickly test different resolutions you can try the following. 

1.  Launch Moonlight
2.  On a separate tab goto chrome://extensions and look for the Moonlight extension
3.  Click on "Index.html" under "Inspect  views"
4.  Click on the select an element button on the far left side (cursor in a rectange)
5.  Click on the select resolution dropdown in Moonlight
6.  Back in the window with the code it should jump to the different select options.
7.  Input your own custom resolution in the format shown "1920:1080" etc.

If you want to save these settings you will need to fork the project and make the same changes to the index.html file.

**Comment by iaomw** [comment]
Good idea. @kilka But I found out it was just scaled, not really customized resolution.
In my case. I change it to "2880:1800", but result is only scaled 1080p from 16:9 to 16:10.

**Comment by kamakiri1192** [comment]
@iaomw Hello! I succeeded in streaming to a device with a different resolution and a different aspect.
It is streaming from device with 1080p display to MacBook Pro (2880 * 1800) at native resolution.

It is realized using **DSR**.

When the aspect ratio is the same
1. Open the Nvidia control panel
2. Configure the DSR
3. Change the resolution.
4. Open Moonlight index.html with an editor
5. Add custom resolution menu to line 34 and beyond
example
`<li class="mdl-menu__item" data-value="2880:1620">MBP15mid</li>`
6. enjoy!


When the aspect ratio is different
1. **Edit the registry**
Detailed method is [here](https://www.deadendthrills.com/forum/discussion/504/how-to-custom-aspect-ratios-and-resolutions-via-dsr-nvidia-only)
> 1. Export your Nvidia DSR registry settings (you should only ever need to do this once).
> 2. Use [this](https://web.archive.org/web/20161023054342/http://www.jim2point0.com/tools/dsr_hex/) tool to generate the registry data for up to 10 custom resolutions.
> 3. Swap that into your exported registry file and save. Double click that file to import your registry settings.
> 4. Reboot
2. Configure the DSR
3. Change the resolution.
4. Open Moonlight index.html with an editor
5. Add custom resolution menu to line 34 and beyond
example
`<li class="mdl-menu__item" data-value="2880:1800">MBP15full</li>`
6. enjoy!

**Comment by Yojimbo108** [comment]
Would just like to say thanks to @kamakiri1192 
The solution above worked great for me. Now if I could get it to enable DSR when starting Moonlight and disable it when I'm done I'd be over the moon!

**Comment by retrop7** [comment]
Has something changed? I could not get this to work Moonlight Game Streaming 0.7.3

**Comment by kamakiri1192** [comment]
Hi! @Yojimbo108 

> Now if I could get it to enable DSR when starting Moonlight and disable it when I'm done I'd be over the moon!

It is possible. but some have issue.

With this method,
When you start the game you automatically enable DSR
You can turn off DSR at the end of the game.

**Advance preparation**
- Configuring DSR
- Edit moonlight index.html

**How to**
1. open Geforce Experience
2. select game
![step1-gfe](https://user-images.githubusercontent.com/28837869/29491646-ca2c4866-859b-11e7-886f-8ba81094f0d5.JPG)

3. setting resolution (DSR)
![step2- dsr](https://user-images.githubusercontent.com/28837869/29491647-cd4844d2-859b-11e7-9b36-f963bc79c76e.JPG)

4. enjoy!
![default](https://user-images.githubusercontent.com/28837869/29491707-8ffcbc4a-859e-11e7-81c1-827edda947b3.jpg)


**issue**
- You can not change the screen ratio in GFE
- Some applications can not change the resolution setting with GFE
ex: mstsc.exe,  pso2.exe

Applications that can not automatically change the resolution at game startup can not use this method.

-----
However, applications such as mstsc.exe can stream at native resolutionand custom aspect ratio if you set the resolution manually.
If someone knows how to set up DSR automatically without using GFE, please let me know.
