### ISSUE TITLE
Connection Checker

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#65]
Would it be possible to add a connection checker into Moonlight Chrome? I feel like this would benefit some users as they could see what they will likely encounter when streaming. I know that Shield Hub has this feature and perhaps you could tap into that API as well.

**Comment by raidancampbell** [comment]
Are you referring to some way to test the network quality (e.g. latency, throughput, packet loss) between the host and client?

**Comment by ShadowBullet** [comment]
Yes, that is exactly what I am referring to. Could it be possible to include this?

**Comment by raidancampbell** [comment]
I'm not intimately familiar with Shield Hub, and wouldn't know how to implement this without adding a host-side server (which is not going to happen).  I'm leaning towards not adding this: it's not very useful for the average workflow, is likely nontrivial to implement, and is not currently a priority
