### ISSUE TITLE
No games in "Select a game to run"

### ISSUE THREAD

**Issue by Yanniclord** [moonlight-stream/moonlight-chrome#66]
So when i use the Chrome extension of Moonlight (latest), and connect over the IP to myself (just for testing, works with the Desktop version and Android), i get the PIN request and all that, but in the list of games/programs, there is nothing to pick from, no game, no program, no nothing.

Here a screenshot:
![image](https://cloud.githubusercontent.com/assets/5807595/16365256/187ed29a-3bfb-11e6-900a-db384ddc6f79.png)

Any idea what that could be about?

**Comment by Yanniclord** [comment]
Ping

**Comment by raidancampbell** [comment]
restart moonlight, clear the `IP Address` box if anything was autofilled there, select the proper address from the dropdown menu, and click `CONNECT`

If this does not work, try right clicking, and hitting `inspect`, then opening the javascript console to find any errors.  I'm hoping that packed apps are still capable of being debugged, but I may have forgotten to fix this.

**Comment by raidancampbell** [comment]
@Yanniclord ping

**Comment by Yanniclord** [comment]
@raidancampbell Ye i cannot hit inspect (debug) the packaged app anymore, sorry. I tried clicking forget and type the IP manually, but then in the list of games, nothing.

**Comment by raidancampbell** [comment]
@Yanniclord is GFE updated on your PC?  Double check it's up to date and the PC has been restarted recently

**Comment by Yanniclord** [comment]
GFE couldn't be more up to date than it is, i always use the latest BETA for GFE, and i am not one of those scrubs that leave their PC powered on all the time, i turn it off when i leave it, so it refreshes its resources more than once a day (A reboot a day keeps the bugs away).

**Comment by Yanniclord** [comment]
Again, it works for the Android version and for the Java version for Windows, Chrome is the only one failing.

**Comment by raidancampbell** [comment]
Alright, I'm not sure exactly what went wrong, but I'd like to find out.  To enable debugging of packed apps (like the release .crx for Moonlight), head over to `chrome://flags`, and enable `Debugging for packed apps`

After restarting chrome, you should be able to right click -> `inspect` the moonlight app.  It may be helpful to take moonlight out of fullscreen by clicking somewhere on the app and hitting `esc`.  The Javascript console will appear in the bottom pane, or as a tab along the top.

Before you do anything, take a screenshot of the console.  There may be IP addresses in it, so mask those if you want.

Then, try connecting like you usually do.  Again, screenshot the console and mask IP addresses as you wish.

To completely wipe everything that Moonlight has saved (requiring you to re-pair when you add the PC again), paste the following line into the console:

    chrome.storage.sync.clear()

**Comment by Yanniclord** [comment]
Ok, so screenshot number one:
![image](https://cloud.githubusercontent.com/assets/5807595/16494264/f6675664-3ee8-11e6-940d-e2bb4df87192.png)

And screenshot number two:
![image](https://cloud.githubusercontent.com/assets/5807595/16494287/11f2e5ce-3ee9-11e6-830b-aad049f6d694.png)

And here a third screenshot while it is pairing:
![unbenannt](https://cloud.githubusercontent.com/assets/5807595/16494394/74f55418-3ee9-11e6-94b2-1f3231ea6015.png)

And a fourth after the pairing succeeded and i tried to connect and fetch the app list:
![image](https://cloud.githubusercontent.com/assets/5807595/16494437/9d291b0e-3ee9-11e6-808c-60641c28c571.png)

**Comment by raidancampbell** [comment]
the error `Moved into showApps, but `api` did not initialize properly! Failing.` is most telling.  I'll take a look

**Comment by raidancampbell** [comment]
It looks like I screwed up an async callback during the pairing process: the `api` is being built before the pairing process has finished?  I'd be surprised if that was the case, because this is the first I've heard of it.  

Regardless, I just successfully paired on a [build from master](https://dl.dropboxusercontent.com/u/9034340/moonlight-chrome-Yanniclord.crx).  This is in-progress code, so ignore the rough edges of the UI.  There's two parts to the UI: a grid section for pairing, and the older section for pairing.  Use the grid section.

As a side note, I haven't had a network with a GFE computer on it for a few months, so I have no clue how the autodiscovery will work.

**Comment by Yanniclord** [comment]
@raidancampbell Ok i can try the master build you sent me out, see if it works.

**Comment by raidancampbell** [comment]
The green + is the base for the new grid UI: there will no longer be a text field.  Instead clicking it should result in a pairing process.  If you re-open moonlight, you should see the host appear in a green box: clicking it should open the app selection section.

Unfortunately, I don't have much of an idea on the controller stuff
