### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by fisher51** [moonlight-stream/moonlight-chrome#68]
Hi,

There are lag when i move mouse. It was on Java version as well, but now it make keyboard+mouse really unplayable. I'm playing via internet, but latency less than 10ms, but it seemed like more than 0.6s for input.

**Comment by raidancampbell** [comment]
I've had bad input lag, and just assumed fast-paced games like RPGs and FPSs were not good for remote streaming.

@cgutman anything come to mind?

**Comment by fisher51** [comment]
Yeah, but it seems good on android, not bad on java(not openGL version) and with chrome it's really awful

**Comment by ShadowBullet** [comment]
I can confirm this as well, I thought it was just the way it was but I tested it on my local network and experienced this lag here as well.

**Comment by bmaciag** [comment]
When I first load everything up, Input lag isn't an issue. If I need to alt tab out a few times, then things sometimes get dicey. For example, if I alt tab out of Moonlight Chrome for a few minutes and then alt tab back in, there will be a 250ms+ input delay. Sometimes alt tabbing out and back in immediately after that will resolve the issue. Sometimes it will self correct over time. Sometimes I need to close the client and resume the game to resolve it.

This is very vague and must be a pain to troubleshoot. I'll be happy to help provide any further information I can.

**Comment by raidancampbell** [comment]
@bmaciag can you confirm whether you see this from regular usage, without alt-tabbing?  i.e. if you keep a connection open for a few minutes do you eventually see input delay worsen?

**Comment by bmaciag** [comment]
@raidancampbell Input delay has never been an issue for me unless I alt tab out. I'm playing WoW from work, streaming from my home PC. When I move the mouse cursor around the screen, it is incredibly responsive under normal conditions. Playing at 1080p/60fps 10mbps.

**Comment by fisher51** [comment]
@bmm85 I can confirm that without alt-tab input lag not so horrible.

**Comment by cgutman** [comment]
Partially fixed by 12e34a9f4e7b8211dc4e9cabb061c370dd2bb7f4. The remainder of the fix will be adding an option to force software decoding on hardware with too high decoder latency.

**Comment by ShadowBullet** [comment]
In the current build, it is much much better than previous builds. I would say it's almost local. @raidancampbell may want to close this.

**Comment by bmm85** [comment]
The current public release? I still have the issue under 0.4. Is anyone hosting a compiled version of the latest commits that I can test?

**Comment by raidancampbell** [comment]
@ShadowBullet built his own copy of `master`, There has not been a new github release, and I have not put up a dropbox release.

**Comment by ShadowBullet** [comment]
I'll host a Dropbox build for as soon as I get the chance

**Comment by raidancampbell** [comment]
Please don't, I'd like to keep the releases as simple as possible and in one place.  I'll work on a github release later today

**Comment by ShadowBullet** [comment]
@raidancampbell Alright I won't host one, totally understandable to keep everything aligned.

**Comment by bmm85** [comment]
So I'm still having the issue I reported in this issue thread, though it is hard to tell if it is exactly the same as the original. Essentially, input lag is completely fine for the most part, but often times if I alt tab and come back after a few minutes, input is delayed by at least 500ms+. I have to close Moonlight and reconnect.

**Comment by raidancampbell** [comment]
I'm not hopeful that anything can be done about this: it's not uncommon for video decoders to optimize throughput over latency.  I'll keep the issue open for the time being in case we stumble across something.

**Comment by evildog1** [comment]
i also have input lag problem no matter which quality i select. 720p 30fps and 1080p 30fps and 10 Mbps. input lag still happen

**Comment by hikkikuma1991** [comment]
I met this issue too, moonlight-chrome works well over home ac Wifi if I use a xbox 360 controller, but after I switched to mouse it has input lag(I think this lag is very slight, but it greatly affected my experience. I suppose the controller also has lag but it's hard to be felt). My ping from client to game experience host is 7ms in average.

**Comment by Sawyer007** [comment]
I'm having the same problem here with the chrome app.
My hardware is i7 6700k, 1080GTX. 32GB memory,Win10. Latest official drivers as of today.

When I first login I feel absolute no input mouse lag at all. It is so responsive that you can not tell its streaming at all. After some time the mouse lag starts to appear and it can get as bad as in really bad.

It happens when using it normally. Dont even need to alt tab out. In games like XCom, Mad Max. The screen flashes abit on the edges and the mouse lag kicks in. If it flashes again even more mouse lag. It can happen as much as 5-7 times then its really bad. I can close the game down and the mosue lag will still be on the streamed desktop itself. 
But it will fully be gone and not come back if I start and play Tomb Raider for example. 

Like if it would resets itself.

Steam inhome streaming also has no mouse lag problems in any game as far as I can tell.

**Comment by evildog1** [comment]
@Sawyer007 i'm getting the same issue just now on both my old and new laptop. It's not gaming computer issue.

**Comment by Sawyer007** [comment]
What you mean just now? Since yesterday? I would use Steam inhome streaming but the thing keeps minimizing randomly for what ever reason.

**Comment by evildog1** [comment]
Why would you ask. I have the same excat problem today and i know the bug is client side.

**Comment by Sawyer007** [comment]
sounds just like this. https://github.com/moonlight-stream/moonlight-chrome/issues/116

**Comment by xchannels** [comment]
This issue happen when i play the game for too long time. Quit the game from Moonlight and relaunch does not fix the issue. Moonlight randomly popout my cursor with some lags during gameplay is super annyoing.

**Comment by Sawyer007** [comment]
Today I had no issues with mouse lag on Xcom 1. No screen flashes or anything yet.
Which is damn confusing. The only difference from last time is. I do not have my Logitech web cam enabled and before I left home I made sure that dual monitor is turned off in Windows 10 with windows+P key combination. But dual monitor shouldnt really matter as first I have it plugged into the igpu+1080gtx. Secondly its both on HDMI which theoretically means that when the monitor is off , the dual monitor feature turns off by itself.

The mouse lag can still happen if I remove the mouse focus with ctr+alt+shift and refocus. But it hasnt happened just yet during Xcom gameplay.

**Comment by Sawyer007** [comment]
Alright after abit more testing. I found finally the culprit and its chrome itself. If I open this page https://www.easports.com/fifa/ultimate-team/web-app which is full of flash and have it running in the background. It start to flash inside most games and mouse start getting more and more delay in intervals.

**Comment by Sawyer007** [comment]
Did alot of testing tonight and finally found out why it flashes in xcom and lags the mouse. Has nothing to do with flash player or webcam software.
If I start the stream like I usually do with desktop MSTSC.EXE and lunch the games from there most do work normal. Some dont work very well like Xcom. But If i start the game through steam big picture or directly with the Xcom incon in the chrome app it will work just fine.

So does it maybe use another encoding method this way?

**Comment by kilka** [comment]
I think I've narrowed down this issue.

In Windows 10 if you go to Mouse and Touchpad settings -> Additonal Mouse Options -> Pointer Options -> Uncheck "Enhance pointer precision".

This completely resolves the input lag issues for me. I have noticed however that every time I launch MSTSC.EXE the "Enhance pointer precision" option gets set back to on.

Upon further testing it seems that if you have a game set to "Exclusive fullscreen" then the mouse options don't get reset and you won't notice any input lag. If you have a game set to "Borderless window" or "windowed" then the option seems to check again and you will have input lag until you correct it.

Either way, does not seem to be an issue with Moonlight but with RDP/ MSTSC.EXE. If anyone knows a way to keep MSTSC.EXE from turning Enhance pointer precision on every connection then please let us know.

**Comment by Sawyer007** [comment]
I just have a mouse setting shortcut on my desktop but you could try this. http://jan-glx.github.io/accelSwitch/

I also dont know for sure if it helps. Since a week I use nagle algorithm turned off on my client windows 10 PC. This is a TCP/IP tweak for enhancing faster packet transmission between 2 PCs so client doesnt wait for a full block before it requests another packet. In some games it helps to reduce the lateny.
It is also a recommendet tweak for a cloud gaming computer like LiquidSky, Azure or Amazon EC2.
Impossible to measure in moonlight but iz kind of feels.
