### ISSUE TITLE
Application does not remember how much bandwidth you selected

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#69]
Whenever you adjust the slider to the desired amount of bandwidth you want, it remembers it only until you are done with the app. When you close the app it resets it back to 20 (the default).

**Comment by raidancampbell** [comment]
Describe to me how you use the program, I'm not seeing this behavior at all.

The true default on first load is 10Mbit.  When you select a different resolution or bitrate, the slider will jump to the recommended value: 20Mbit is the default for 1080p@60fps.  So if you continually change the resolution around, it will change the bitrate.

Either way, the resolution, FPS, and bitrate should all be saved and loaded properly every time moonlight is run.

**Comment by ShadowBullet** [comment]
Closing the issue, I am stupid and did not look properly. It is working as intended, I thought that at one point or another it did not remember this but after just trying it myself it did remember it and now feel like a total dumb ass.

**Comment by raidancampbell** [comment]
Thanks for reporting what you thought was an issue: if you do find something in the future please do report it.
