### ISSUE TITLE
Back button should have Material-style hover and click highlights

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#70]
Since the back button isn't declared with MDL styles, it doesn't behave like the other buttons. It should have the same highlights when clicked or hovered over that the other MDL buttons do.

**Comment by abdallahsoliman** [comment]
@cgutman what is the desired hover behavior? do you simply want the hand pointer? also for which buttons do you want said behavior implemented?

**Comment by cgutman** [comment]
I don't care about the hand cursor behavior, I just want the highlight when hovering and clicking that MDL buttons have. Compare the back button when hovered or clicked with the real MDL buttons in our dialogs.

We should also imitate this behavior on our grids too.

**Comment by abdallahsoliman** [comment]
@cgutman  i can add that in, but it may be better if you just decide the exact details of the hover you want like the highlight color, etc and i can manually add a style for them. I will push a sample of the behavior using default hover from material, the colors clash give me a few min

**Comment by abdallahsoliman** [comment]
@cgutman pushed, please take a look at the host buttons (not add new host but the paired ones) and let me know if thats the desired behavior

**Comment by raidancampbell** [comment]
I don't understand what behavior you're expecting. When I hover over the pairing dialog's buttons "CONTINUE" and "CANCEL", I see no difference.  Can you explain or screenshot what you want?

**Comment by raidancampbell** [comment]
Closed due to inactivity
