### ISSUE TITLE
PC tracking and state updating needs a rewrite

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#71]
We're keeping track of PCs via IP address and host name, which means we can have duplicate PCs in the list simply by adding one by IP address and one by DNS name (and other similar problems). GFE gives use a UUID that should be used to track a single PC with multiple IP addresses. We should track the active IP address (local or remote) and poll periodically for updated PC state. We can then display the PC with the actual PC name rather than the IP address in the grid.

**Comment by raidancampbell** [comment]
Heads up: this will likely require building a new set of hosts, meaning repairing will be required

**Comment by raidancampbell** [comment]
Parsed a whole bunch more useful info from the server into `api`.  I think proper behavior may be saving the entire `api` object into `chrome.storage.sync`.  Current behavior only saves the hostname.

**Comment by raidancampbell** [comment]
For personal reference:

```
okay, so here's how the other clients do it
we have code in the background that routinely polls /serverinfo for computers in our list
we keep track of ExternalIP and LocalIP plus the IP address the PC was originally added with
when we poll, we first try LocalIP, then ExternalIP, then the original IP address
we ​_must_​ check the UID matches the expected value though because the ExternalIP may be shared by several computers behind a NAT
mDNS simply tells the polling code that we have a new one to try, if polling fails on that PC, it doesn't get added to the UI
and the polling code is responsible for graying out computers that are offline if they fail to respond to several polls in a row
when we first start, until we get a poll response from a machine, it's in a "refreshing" state where it doesn't do anything when clicked
then it moves from refreshing -> online or offline
and if mDNS finds a PC we already know about, we update the LocalIP entry to match what mDNS says
```

**Comment by raidancampbell** [comment]
Everything except for mDNS handling should have been done by commit 6b8ac65d7f6b4edd118ae3bd5707e6f73d284c06, but I haven't tested the intricacies of NAT situations.  Additionally, nothing has been disabled yet, just visually warned with a red border

**Comment by raidancampbell** [comment]
With the latest updates to mDNS, this should work.  If NAT situations don't work, a new bug should be filed.
