### ISSUE TITLE
Investigate storage mechanism for box art caching

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#74]
We should determine if we can cache locally some way that doesn't require the unlimitedStorage permission.

**Comment by raidancampbell** [comment]
solution for this is the HTML5 filesystem API, but I don't see an issue with using unlimitedStorage.  unlimitedStorage is just more storage on chrome.storage.local past the default ~5MB.  It doesn't sync or anything, and I don't see any reason to avoid it.
