### ISSUE TITLE
Running app highlight not correct when terminating an app from within the stream

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-chrome#75]
The app stays highlighted even though it's no longer running.

**Comment by raidancampbell** [comment]
Personal reference, when I get to it:
https://github.com/moonlight-stream/moonlight-chrome/blob/f88f55e7c9c6b3df819ddf5f265dce45d4f7d267/static/js/index.js#L238

**Comment by raidancampbell** [comment]
fixed in abdallah's fork.  I added him to this repo, so in the future we can ignore this inconvenience
