### ISSUE TITLE
Requesting windowed mode

### ISSUE THREAD

**Issue by minnux** [moonlight-stream/moonlight-chrome#76]
Using two monitors, moonlight takes up both screens when streaming using the chrome app even though it's only playing in one. Are there any plans to implement a windowed mode in the future?

Mac OS X Yosemite 10.10.5
Google Chrome 51.0.2704.106

**Comment by cgutman** [comment]
You should be able to enter windowed mode if you just exit full screen while streaming. Apparently, you can fix the issue with full-screen apps taking all screens if you set an option "Displays have separate Spaces"

https://www.reddit.com/r/osx/comments/2kkwb9/yosemite_multi_monitor_fullscreen_mode_all_other/

**Comment by minnux** [comment]
Good suggestions. I will try these tonight and reply back in case someone else is having the same issue. BTW, what is the key combination to exit full screen while streaming? Thanks.

**Comment by minnux** [comment]
So I couldn't find it in the wiki, but to exit full screen while streaming into windowed mode is just the ESC key. And the fix in the link you posted about both displays worked. Thanks for the help.
