### ISSUE TITLE
no hardware decoding with ubuntu 16.04

### ISSUE THREAD

**Issue by medom** [moonlight-stream/moonlight-chrome#81]
hello,

i am having some issues with moonlight-chrome under chrome 52 in ubuntu 16.04. every time the stream starts on the client, I would get a message saying "Hardware decoding unavailable, falling back to CPU decoding". I have Intel Graphics HD 4000, when I stream through chrome on windows 10, there seems to be no problem.
I already tinkered with a lot of flags & settings like enabling "override software rendering list", updating drivers etc, however that did not help. 

Any ideas?

edit: nvm, this seems to be a deeper issue with linux & chrome itself. can be closed..

**Comment by raidancampbell** [comment]
The main reason we pursued the Chrome plugin was the abstraction of hardware accelerated video decoding, if Chrome doesn't provide it for a client, there's nothing we can do to fix that.
