### ISSUE TITLE
Add support for Steam Controller

### ISSUE THREAD

**Issue by Marioheld** [moonlight-stream/moonlight-chrome#82]
Hello there, 

I am tried today to stream over the internet with Chrome 52.0.2743.82 on macOS Sierra [10.12 Beta (16A254g)] to a Windows 10 PC. I have only a 2,2 Mbps upstream at my home network and streaming with 1 Mbps and must say it works really well! It is even possible to play Rocket League which is incredible! Great work guys! But I missing support for the Steam Controller. Steam recognizes the Xinput Device but the controller is mapped like a mouse. Left touchpad for mouse movement, LT and RT for mouse buttons. which will not properly work for most games. It seems that the local Steam (macOS Version) controller configuration only takes affect in steam itself and not systemwidley. Can anyone recommend a third party app for simulating a xbox 360 controller until moonlight does support the Steam Controller itself nativly?

**Comment by claymullis** [comment]
I'm in the same boat here. Would love steam controller support.

**Comment by kriekprinsloo** [comment]
Yes same here.  I'm bumping this since this is still open.

**Comment by retrop7** [comment]
A work around I have found is to use my android phone as a virtualhere server. I use the computer which is hosting the game as my virtualhere client. It is just like the controller was plugged directly into the computer. I haven't done too much testing but everything seems to be working, I can fully configure my steam controller when I stream (with moonlight) Steam.
