### ISSUE TITLE
What now that Chrome Apps are being discontinued?

### ISSUE THREAD

**Issue by mirh** [moonlight-stream/moonlight-chrome#89]
http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by raidancampbell** [comment]
Development will continue, the changes are a while away

**Comment by mirh** [comment]
Yes, I mean.. It's still nice for chrome OS users to have a choice and all
But I was under the impression that this was supposed to be the "main", "prime" client for desktops after the deprecation of moonlight-pc.  

And it seems pretty lame in a year to have to rely on that then.

**Comment by raidancampbell** [comment]
We will have a solid year of a good cross-platform client.  We'll evaluate our migration choices in a few months.  Several other developers are in the same situation: I'm sure some handy migration paths will pop up and mature.  As of now, I'm not aware of any simple approaches to this issue.

**Comment by viljoviitanen** [comment]
Here's a potential future solution, a high profile android developer has ported his chrome app to http://electron.atom.io/ . https://plus.google.com/110558071969009568835/posts/1b7thJXHqcd - says he'll open source the porting bits.

**Comment by raidancampbell** [comment]
I have a lot of respect for Koush, but the nature of our plugin is a bit different.  Moonlight-Chrome is a Native Client (NaCl) plugin in a Chrome app.  This means we were able to compile straight C and target NaCl, which runs inside Chrome on the individual platforms.  

Deprecation of Chrome apps isn't as much of a problem as losing our NaCl base.  It's possible we could port the app to an extension and still retain the NaCl code, but last I checked several APIs we used weren't available to extensions

**Comment by dead** [comment]
Related: http://nwjs.io/blog/chrome-apps-support/

**Comment by raidancampbell** [comment]
thanks @dead, you seem to have a habit of swooping in with helpful information and solutions :).  Looks like [NW.js supports NaCl](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20NaCl%20in%20NW.js/).  Full disclosure: I only lightly skimmed the relevant NaCl section.

I'm going to continue development with the Chrome App platform until Moonlight-Chrome is more mature, then worry about the transition

**Comment by eligrey** [comment]
This issue is still unfixed and should stay open.

**Comment by Jorys-Paulin** [comment]
Hello! Unfortunately, the chrome version is now deprecated in favour of moonlight-qt.

**Comment by eligrey** [comment]
This issue should still be open.

**Comment by Jorys-Paulin** [comment]
@eligrey Have you tried the QT version?

**Comment by eligrey** [comment]
@Jorys-Paulin Not on Chrome OS.
