### ISSUE TITLE
App will not display any games from dropdown

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#90]
Totally reinstalled moonlight and forgot the PC multiple times, the dropdown menu for games will not show any of the available games. Just to check my sanity, I loaded up the iOS app and it is able to see all of my games and launch all of them just fine. A reboot of the PC also did not work. I am using the latest release (the one that is already compiled) any logs you need please let me know.

**Comment by raidancampbell** [comment]
Please follow the instructions [here](https://github.com/moonlight-stream/moonlight-chrome/issues/66#issuecomment-229672882), and send me the results

**Comment by ShadowBullet** [comment]
Here are the results 
![screen shot 2016-08-23 at 3 12 01 pm](https://cloud.githubusercontent.com/assets/6118102/17908079/8588fe44-6944-11e6-8343-07eb79de7f9d.png)
![screen shot 2016-08-23 at 3 10 02 pm](https://cloud.githubusercontent.com/assets/6118102/17908083/8762d906-6944-11e6-9e81-9d1fba95d2d2.png)

**Comment by raidancampbell** [comment]
So I remember you were using my dropbox-hosted build from your comments on #78, this issue seems like the same one as #66, and sometimes pops up in the current official "pre-release" build.  Can you replicate this on the same build you used in #78?

**Comment by ShadowBullet** [comment]
Sorry for the long reply, I am using the pre-release version, I am testing at my house connecting to public IP and no tLAN address, same issue happens. I thought I would just try spam clicking connect, surprisingly that actually worked. But only if I spam click it until it shows up, other than that it still persists. I will try the build in that I used #78 and see if the issue is there.

**Comment by ShadowBullet** [comment]
Just tested the build from #66 and it seemed to work first try

**Comment by ShadowBullet** [comment]
I'm going to keep using the build from #66 instead of the pre-release. I would use the one with the game posters but unfortunately, there is no option to quit the game. I will aggressively test #66 build, it seems stable (enough).
