### ISSUE TITLE
[Q] Time for a new release?

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#93]
Is it almost time to compile a new build and put it in the release section? The app has changed dramatically since the first compiled release.

**Comment by raidancampbell** [comment]
Patience, we still have internal testing and cleaning before anything gets released

**Comment by ShadowBullet** [comment]
If you're willing to compile this build I would be more than happy to test some of the new features

Sent from my iPhone 6
-Max Herman

**Comment by ShadowBullet** [comment]
Because now it has the ability to functionally quit an app, which means that I can now test it with full functionality even if it's a little buggy. But all it needs is some ironing out

Sent from my iPhone 6
-Max Herman

**Comment by ShadowBullet** [comment]
@raidancampbell I compiled it myself, it took a while to figure out to but overall a fun learning experience. So far it is looking great, and I will test it and let you know if any bugs pop up.
